### ISSUE TITLE
[Bug]: Required named parameter 'userName' must be provided AND Found this candidate, but the arguments don't match

### ISSUE THREAD

**Issue by erperejildo** [fluttercommunity/plus_plugins#1003]
### Platform

Android 10

### Plugin

device_info_plus

### Version

4.0.0

### Flutter SDK

3.0.5

### Steps to reproduce

Error occurs on build process

### Logs

```shell
/opt/homebrew/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_windows-2.1.1/lib/src/device_info_plus_windows.dart:24:35: Error: Required named parameter 'userName' must be provided.
    final data = WindowsDeviceInfo(
                      
And there is this other error:
/opt/homebrew/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_platform_interface-2.4.0/lib/model/windows_device_info.dart:12:3: Context: Found this candidate, but the arguments don't match.
  WindowsDeviceInfo({
  ^^^^^^^^^^^^^^^^^
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-ES)
    • Flutter version 3.0.5 at /opt/homebrew/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dani/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Users/dani/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by jenilDT** [comment]
Same issue

**Comment by dab246** [comment]
Using `device_info_plus `version `4.0.2` will solve this problem.

**Comment by erperejildo** [comment]
> Using `device_info_plus `version `4.0.2` will solve this problem.

I tried that but I got this problem instead:

```
Because no versions of open_file match >3.2.1 <4.0.0 and open_file 3.2.1 depends on ffi ^1.0.0, open_file ^3.2.1 requires ffi ^1.0.0.
And because device_info_plus >=4.0.2 depends on device_info_plus_windows ^3.0.2 which depends on ffi ^2.0.1, open_file ^3.2.1 is incompatible with device_info_plus >=4.0.2.
So, because my_rents depends on both device_info_plus ^4.0.2 and open_file ^3.2.1, version solving failed.
pub get failed (1; So, because my_rents depends on both device_info_plus ^4.0.2 and open_file ^3.2.1, version solving failed.)
```

**Comment by dab246** [comment]
You can use [better_open_file](https://pub.dev/packages/better_open_file) instead of `open_file`

**Comment by erperejildo** [comment]
> You can use [better_open_file](https://pub.dev/packages/better_open_file) instead of `open_file`

Maybe, but I could have other issues. I prefer to have the fix here

**Comment by dab246** [comment]
> > You can use [better_open_file](https://pub.dev/packages/better_open_file) instead of `open_file`
> 
> Maybe, but I could have other issues. I prefer to have this fixed if it's possible

Or you can fix it this way. https://github.com/fluttercommunity/plus_plugins/issues/1002#issuecomment-1207881999

**Comment by erperejildo** [comment]
> > > You can use [better_open_file](https://pub.dev/packages/better_open_file) instead of `open_file`
> > 
> > 
> > Maybe, but I could have other issues. I prefer to have this fixed if it's possible
> 
> Or you can fix it this way. [#1002 (comment)](https://github.com/fluttercommunity/plus_plugins/issues/1002#issuecomment-1207881999)

I added this as they suggested but the issue is still there:
```
dependency_overrides:
  device_info_plus: ^4.0.2
  device_info_plus_platform_interface: ^2.4.0
```

**Comment by gaurav-girase** [comment]
it's resolved when i added the 
  `device_info_plus_platform_interface: '2.3.0+1'`
in pubspec.lock

**Comment by erperejildo** [comment]
> it's resolved when i added the `device_info_plus_platform_interface: '2.3.0+1'` in pubspec.lock

why would you modify .lock?

**Comment by LaoitdevOpen** [comment]
same issue!
 if you cannot  update to new version of the plugin you can fixed it  by add `device_info_plus_platform_interface: '2.3.0+1'` to `pubspec.yaml`

```yaml
  device_info_plus: 3.2.4
  package_info_plus: 1.4.2
  device_info_plus_platform_interface: 2.3.0+1
```

**Comment by xang555** [comment]
same issue!
if you cannot update to new version of the plugin you can fixed it by add `device_info_plus_platform_interface: '2.3.0+1' `to `pubspec.yaml`

```yaml
  device_info_plus: 3.2.4
  package_info_plus: 1.4.2
  device_info_plus_platform_interface: 2.3.0+1
```

**Comment by bayunugroho2022** [comment]
i solved this issue, by adding dependency_overrides for device_info_plus

  device_info_plus: ^3.2.4

dependency_overrides:
  device_info_plus_windows: ^2.1.1
  device_info_plus_platform_interface: ^2.3.0

**Comment by erperejildo** [comment]
> dependency_overrides:
> device_info_plus_platform_interface: '2.3.0+1'

I get other issues with this:

`flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/intl_phone_number_input-0.7.0+2/lib/src/widgets/input_widget.dart:321:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.`

These fixes really depend on the packages we have installed. Better to try to fix this on this one

**Comment by BoLindJensen** [comment]
> Using `device_info_plus `version `4.0.2` will solve this problem.

This does solve the issue, but why does the error suddendly happen for older versions?

**Comment by Stachuu87** [comment]
Same issue here. I'm not using the package itself, but its a dependenxecy for native_pdf_viewer, which i use.

I've made No changes to my project, it was working fine until yesterday. 

Any ideas? I don't like the dependecy_overrides solution. Its more walkaround, not a solution.

**Comment by miquelbeltran** [comment]
Could you provide exact steps to reproduce the issue?

If I do the following, I can compile the app without issues:

1. Create a flutter project
2. add the device_info_plus dependency with `flutter pub add device_info_plus`
3. Run the project on Android

All of that works.

**Comment by miquelbeltran** [comment]
> > Using `device_info_plus `version `4.0.2` will solve this problem.
> 
> I tried that but I got this problem instead:
> 
> ```
> Because no versions of open_file match >3.2.1 <4.0.0 and open_file 3.2.1 depends on ffi ^1.0.0, open_file ^3.2.1 requires ffi ^1.0.0.
> And because device_info_plus >=4.0.2 depends on device_info_plus_windows ^3.0.2 which depends on ffi ^2.0.1, open_file ^3.2.1 is incompatible with device_info_plus >=4.0.2.
> So, because my_rents depends on both device_info_plus ^4.0.2 and open_file ^3.2.1, version solving failed.
> pub get failed (1; So, because my_rents depends on both device_info_plus ^4.0.2 and open_file ^3.2.1, version solving failed.)
> ```

The problem there is that `open_file` still uses ffi 1.0.0

**Comment by miquelbeltran** [comment]
Potentially duplicated of #1000

**Comment by miquelbeltran** [comment]
Please move the conversation to #1000
