### ISSUE TITLE
[Bug]: device_info_plus: ^4.0.2 ERROR

### ISSUE THREAD

**Issue by andim27** [fluttercommunity/plus_plugins#1009]
### Platform

android 12

### Plugin

device_info_plus

### Version

4.0.2

### Flutter SDK

3.0.5

### Steps to reproduce

1. add into pubspec.yaml 
2. flutter run
3.ERRORS: And because device_info_plus >=4.0.2 depends on device_info_plus_windows ^3.0.2

!!! I don't need device_info_plus_windows  I added device_info_plus !!!

ERRORS:
flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_windows-2.1.1/lib/src/device_info_plus_windows.dart:24:35: Error: Required named parameter 'userName' must be provided.
    final data = WindowsDeviceInfo(
                                  ^
/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_platform_interface-2.4.0/lib/model/windows_device_info.dart:12:3: Context: Found this candidate, but the arguments don't match.
  WindowsDeviceInfo({

### Logs

```shell
flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_windows-2.1.1/lib/src/device_info_plus_windows.dart:24:35: Error: Required named parameter 'userName' must be provided.
    final data = WindowsDeviceInfo(
                                  ^
../../../../Progs/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_platform_interface-2.4.0/lib/model/windows_device_info.dart:12:3: Context: Found this candidate, but the arguments don't match.
  WindowsDeviceInfo({
```

### Flutter Doctor

```shell
ok
```

**Comment by albatrosify** [comment]
Same Problem. Cant build my app any longer.

**Comment by jttuboi** [comment]
The same happens in package which uses it, like as Upgrader. And my project is in the 2.10.5 version. So, it's not impact only the last version, but I think impact all projects who use it. Please, fix ASAP.

**Comment by Stachuu87** [comment]
Related to [#1003](https://github.com/fluttercommunity/plus_plugins/issues/1003) issue

**Comment by miquelbeltran** [comment]
Will revert the last changes.

Please set the version to 4.0.1 (without the ^) meanwhile

**Comment by miquelbeltran** [comment]
Actually it works for me, I had to do a `flutter pub upgrade` to pull the latest dependencies.

**Comment by miquelbeltran** [comment]
Potentially a duplicated of #1003

**Comment by miquelbeltran** [comment]
Please move the conversation to #1000
