### ISSUE TITLE
[Bug]: Text is not displayed in iOS Messages app when sharing file with text.

### ISSUE THREAD

**Issue by Remskei** [fluttercommunity/plus_plugins#1015]
### Platform

iOS 15.6

### Plugin

share_plus

### Version

4.0.10+1

### Flutter SDK

3.0.5

### Steps to reproduce

1. Share file with text
2. Select the Messages app

The text is not displayed, only the file.
When I share with the Mail app, the file and the text are visible.

### Logs

```shell
No log needed.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale fr-FR)
    • Flutter version 3.0.5 at /Users/user/Documents/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (il y a 4 semaines), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by iamakhileshmishra** [comment]
@mhadaily please assign this to me so that i can work upon it

**Comment by Coronon** [comment]
@Remskei Isn't that expected behavior? Some apps allow you to directly inspect a file, while others do not. As long as we always attach the actual text file, I wouldn't call that a bug. Please correct me if I understood you wrong :)

**Comment by Remskei** [comment]
> @Remskei Isn't that expected behavior? Some apps allow you to directly inspect a file, while others do not. As long as we always attach the actual text file, I wouldn't call that a bug. Please correct me if I understood you wrong :)
> 
> PS: Screenshots/videos would be extremely helpful.

Maybe for some applications and some types of files.

In my case, I've just tried to share a photo with a text. 
On Android, it is working, I can share the photo and the text in Messages app. On iOS only the text is shared in Message app. So I think it not the expecting behavior.
