### ISSUE TITLE
[Bug]: [IOS][Share_Plus] Instagram App Icon is not shown on share dialog

### ISSUE THREAD

**Issue by dqcuong2** [fluttercommunity/plus_plugins#1026]
### Platform

iOS 

### Plugin

share_plus

### Version

4.0.10

### Flutter SDK

3.0.2

### Steps to reproduce

1. Open share dialog
2. Find Instagram App Icon to share
3. It doesn't not have Instagram App to share

### Logs

```shell
.
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by dqcuong2** [comment]
[Skype_Video.mp4.zip](https://github.com/fluttercommunity/plus_plugins/files/9349336/Skype_Video.mp4.zip)

**Comment by dqcuong2** [comment]
Although I have instagram app on my phone, but it's not available on the share dialog

**Comment by dqcuong2** [comment]
Does anyone face this issue?

**Comment by miquelbeltran** [comment]
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/share_plus/README.md#facebook-limitations-whatsapp-instagram-facebook-messenger
