### ISSUE TITLE
[Question]: I'm using share_plus to share on Android and the UI is inconsistent with other apps.

### ISSUE THREAD

**Issue by Leheih** [fluttercommunity/plus_plugins#1030]
### What is your question?

The following is my UI using share_plus：
<img width="395" alt="image" src="https://user-images.githubusercontent.com/17791894/185590046-63044a2d-9026-400c-83c5-e32a7a6b658d.png">

Below is the sharing UI for another app on the same phone
<img width="414" alt="image" src="https://user-images.githubusercontent.com/17791894/185590505-a4fd4a7c-ee2e-4d26-86c9-f6c7e30ba00a.png">

**Comment by miquelbeltran** [comment]
share_plus uses `Intent.createChooser` from Android internally, which is what is being used in the official Android docs: https://developer.android.com/training/sharing/send

tbh I am not sure what other apps may be doing. Any ideas?

**Comment by LuisMiguelSS** [comment]
Perhaps the other apps include more intents, which add up the amount of results shown in the intent, thus having different results. Intent choosers should always be the same under the same circunstamces.

**Comment by ueman** [comment]
I guess this is because `share_plus` doesn't make use of [`Rich content previews`](https://developer.android.com/training/sharing/send#adding-rich-content-previews) on Android.

**Comment by SirusCodes** [comment]
Some other apps create their own chooser and use intents to directly target those apps.

Found [this](https://medium.com/@amirdes021_73588/android-custom-chooser-for-intent-share-send-358ee8cbc152) medium article to do so.

**Comment by SirusCodes** [comment]
> I guess this is because `share_plus` doesn't make use of [`Rich content previews`](https://developer.android.com/training/sharing/send#adding-rich-content-previews) on Android.

It's not because of that but it would be a good idea to have support for Rich content previews 🤔

I would love to contribute that for hacktoberfest

**Comment by Coronon** [comment]
@SirusCodes I would refrain from such a change at the moment as there was an announcement that a large portion of the plus plugins may be refactored. When we do add this, we should also add it to other platforms.

See #1221

**Comment by miquelbeltran** [comment]
> I would refrain from such a change at the moment as there was an announcement that a large portion of the plus plugins may be refactored. When we do add this, we should also add it to other platforms.

There's nothing going on at the moment.

**Comment by ipcjs** [comment]
you can use [huawei_share](https://pub.dev/packages/huawei_share) 😅

**Comment by ipcjs** [comment]
👀
