### ISSUE TITLE
[Question]  How can I use [share_plus] functionality outside its native dialog? 

### ISSUE THREAD

**Issue by callmephil** [fluttercommunity/plus_plugins#1031]
### What is your question?

I would like to use share_plus options to restrict to certain apps only. Is there a way to do that?

e.g: I would like to only use the Instagram button for stories in a custom container as a stand-alone.

![image](https://user-images.githubusercontent.com/2213079/170664259-98be845e-7df3-498d-8946-43c35c6df347.png)

**Comment by SirusCodes** [comment]
I don't know how you can handle this on other devices but on Android you need to create your own UI for this functionality and send intents to those apps directly.

To send intents you can use [android_intent_plus](https://pub.dev/packages/android_intent_plus) plugin.

**Comment by Coronon** [comment]
I don't think this is possible on iOS. The only thing you could use to directly share something are Deeplink URL's. Even an App like Snapchat can't provide that feature :/
