### ISSUE TITLE
[Request]: share_plus Disable touch input on share screen open

### ISSUE THREAD

**Issue by Shawn-sudo** [fluttercommunity/plus_plugins#1053]
### Plugin

share_plus

### Use case

Disable touch inputs when share screen is opened

Currently looks like: https://vimeo.com/746740170
In the video, "Invite Friend" button calls `Share.share("You can get ...")`
I was tapping the "Invite Friend" button area above the share panel on iOS.

#### Alternative Solution I've considered
I could wrap the whole widgets with `AbsorbPointer(absorbing: true/false, child: childhere)`, but this makes the widget tree a little bit messy

### Proposal

Disable touch input when the share panel is opened

**Comment by miquelbeltran** [comment]
This doesn't have anything to do with the plugin. You could try to disable the button and wait for a response on shareWithResult which returns after the user selected an option.

**Comment by Shawn-sudo** [comment]
@miquelbeltran ye i can definitely write some codes to block touch inputs by myself, but I just hope it is provided by default. The behavior shown in the video is definitely unexpected.

**Comment by mkobuolys** [comment]
I would love to contribute to this 💙

**Comment by SirusCodes** [comment]
I'm not sure how we can handle this in the plugin but it definitely that you should handle by yourself and not the plugin.

**Comment by Shawn-sudo** [comment]
Oh ok then I'll close this issue
