### ISSUE TITLE
[Bug]: Subject is not set when sharing text + subject on iOS to Gmail app

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#1056]
### Platform

iOS 15

### Plugin

share_plus

### Version

>4.0.0 (unreleased changes)

### Flutter SDK

3.3.0

### Steps to reproduce

1. Use share_plus example
2. share text and subject
3. Select GMAIL app on iPhone

The text appears both on the subject and body.

### Logs

```shell
not necessary
```

### Flutter Doctor

```shell
not necessary
```

**Comment by miquelbeltran** [comment]
This issue seems to be present on Gmail, not on the Mail app of iOS, which works. So closing this.

**Comment by gbaccetta** [comment]
Gmail is still not working properly with this. If you need to have a subject set in Gmail, you can have your body string as this one: `'${SUBJECT}\n${BODY}'`. Gmail will use only the first line till the new line as subject.
