### ISSUE TITLE
When in iOS we are sharing Post to Facebook it is not redirected back to our app.

### ISSUE THREAD

**Issue by expertdev-designer** [fluttercommunity/plus_plugins#1066]
### What is your question?

When in iOS we are sharing posts to Facebook it is not redirected back to our app. 
On Android after successfully sharing to Facebook, it is redirecting to our app. But in the case of Facebook Sharing only in iOS, it is stuck on the done screen to go back we have to kill the app and reopen it. We added Facebook SDK also.
Any solution Please?

**Comment by miquelbeltran** [comment]
The questions should be asked on StackOverflow, doesn't seem related to the share_plus plugin.
