### ISSUE TITLE
[Request]: share_plus android remove url_launcher

### ISSUE THREAD

**Issue by git-xiaocao** [fluttercommunity/plus_plugins#1070]
### Plugin

share_plus

### Use case

url_launcher is not required when compiling android but it will also be loaded into the app's gradle project

### Proposal

Remove url_launcher when compiling android

**Comment by miquelbeltran** [comment]
makes sense, feel free to submit a PR if you think you can do it!

**Comment by aakash-pamnani** [comment]
url_launcher is in other platforms pubspec.yaml dependency, How to remove, Can any one guide me.

**Comment by aakash-pamnani** [comment]
url_launcher is in dependency of share_plus_linux and share_plus_web how can we stop it from being importing in android build, Can anybody guid me?

**Comment by SirusCodes** [comment]
I feel it's only possible if we have federated plugins.

**Comment by miquelbeltran** [comment]
> I feel it's only possible if we have federated plugins.
> 
>   

Nope, the dependency would still be there through the other platform dependency unfortunately

**Comment by SirusCodes** [comment]
> Nope, the dependency would still be there through the other platform dependency unfortunately 

Then only way is to have platform channels for each😕

**Comment by stuartmorgan** [comment]
Since `url_launcher` is fully federated, you could in theory depend directly on `url_launcher_linux` and `url_launcher_web` instead of `url_launcher`. You'd have to code against the platform interface directly instead of the app-facing API though.

**Comment by SirusCodes** [comment]
Would make a PR for it then thanks @stuartmorgan for the idea
