### ISSUE TITLE
[Request]: Battery Charging Threshold 

### ISSUE THREAD

**Issue by marwenbk** [fluttercommunity/plus_plugins#1071]
### Plugin

battery_plus

### Use case

When the device is plugged-in all day long (example: in case of POS app ) the battery may get damaged by holding 100%. 
in modern devices (in my case my laptop) you can set the threshold to 60-80% to avoid damaging the battery

### Proposal

Setting Charging threshold for android and ios devices

**Comment by miquelbeltran** [comment]
I am not sure what this has to do with the plugin. The plugin just exposes the status from the OS, it does not control how the device charges.

**Comment by marwenbk** [comment]
Yes, it doesn't that's why i have suggest that

**Comment by miquelbeltran** [comment]
Again, you need to understand that the plugin has nothing to do with how the device charges.

I'm going to close to this issue since this is unrelated to the plugin itself.
