### ISSUE TITLE
[Request]: You should provide a way to share text as a URL

### ISSUE THREAD

**Issue by xiaocode337317439** [fluttercommunity/plus_plugins#1072]
### Plugin

share_plus: ^4.1.0

### Use case

You should provide a way to share text as a URL

### Proposal

You should provide a way to share text as a URL

**Comment by miquelbeltran** [comment]
Agreed, the problem we had before is that the parameter for text was used also for URLs and this caused parsing issues, having a different method for URLs would be good

**Comment by miquelbeltran** [comment]
Just to clarify, sharing a url is a pure iOS thing right? The share_plus plugin never did anything different for sharing urls on Android

**Comment by xiaocode337317439** [comment]
> Just to clarify, sharing a url is a pure iOS thing right? The share_plus plugin never did anything different for sharing urls on Android

Yes, I think we can provide a new shareURL method

**Comment by miquelbeltran** [comment]
A fix to share text as URL on iOS was published today in 4.2.0 :tada:
