### ISSUE TITLE
[Request]: Please upgrade device_info_plus_windows to ffi ^2.0.1

### ISSUE THREAD

**Issue by Mmisiek** [fluttercommunity/plus_plugins#1075]
### Plugin

device_plus_info_windows

### Use case

The use of old ffi blocks adding new plugins like catcher:

Because device_info_plus >=2.1.0 <3.2.1 depends on device_info_plus_windows ^2.1.0 and device_info_plus >=3.2.1 <4.0.1 depends on device_info_plus_windows ^2.1.1, device_info_plus >=2.1.0 <4.0.1 requires device_info_plus_windows ^2.1.0.
And because catcher >=0.6.9 depends on device_info_plus ^3.1.1, catcher >=0.6.9 requires device_info_plus_windows ^2.1.0.
And because device_info_plus_windows >=1.0.0-nullsafety.0 <3.0.0 depends on ffi ^1.0.0 and file_picker >=5.0.0 depends on ffi ^2.0.1, catcher >=0.6.9 is incompatible with file_picker >=5.0.0.
So, because trader_view_app depends on both file_picker ^5.0.1 and catcher ^0.6.9, version solving failed.
pub get failed (1; So, because trader_view_app depends on both file_picker ^5.0.1 and catcher ^0.6.9, version solving failed.)

### Proposal

Upgrade dependency to ffi 2.0.1

**Comment by miquelbeltran** [comment]
I think there were a couple of PRs already upgrading ffi for win on other plugins in this repo.

I'll try to do this during this week, but if you can take a look at those changes and submit a similar pr, the patch should be easy to do.

**Comment by miquelbeltran** [comment]
Actually, ffi is already at 2.0.1 for package_info_plus_windows 3.0.0, and you are using an old version of device_info_plus. Upgrade to the latest device_info_plus.

**Comment by miquelbeltran** [comment]
Closing because using outdated version

**Comment by Mmisiek** [comment]
Thanks
