### ISSUE TITLE
[Bug]: IOS 16 iPad 9th gen crash

### ISSUE THREAD

**Issue by Mohdx** [fluttercommunity/plus_plugins#1083]
### Platform

IOS 16

### Plugin

share_plus

### Version

4.3.0

### Flutter SDK

3.3.2

### Steps to reproduce

I've tried the readme solution for iPad issue. but it's not working 
After calling ``Share.share``, the UI is not frozen, still can scroll and everything... wait few seconds then crash

### Code Sample

```dart
IconButton(
     onPressed: () {
       final box = context.findRenderObject() as RenderBox?;
       Share.share('${Configs.baseUrl}product/${prod.id}',
         sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size);
       },
       icon: const Icon(Icons.share_outlined),
     )
```

### Logs

```shell
Unfortunately this is so confusing that the only log I get is:

Lost connection to device.
Exited
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    • Flutter version 3.3.2 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (7 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mohdarab/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • iPad (9th generation) (mobile) • 045B05D9-7579-4A5A-A778-02C51BEE037F • ios        •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                • macos                                • darwin-x64 • macOS 12.6 21G115 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by miquelbeltran** [comment]
See #1082 and #1081, using 4.1.0 may help

**Comment by miquelbeltran** [comment]
There's also a new code on 4.3.0 that gives better error logs if the provided `sharePositionOrigin` is incorrect.

I'd recommend checking the example in share_plus/example and try to run on the same device, see if you run into the same issue.

**Comment by mohd-afid** [comment]
@miquelbeltran I tried the same code as in the example, but I'm having the same problem on the iPad. 



log
[default] LaunchServices: store (null) or url (null) was nil: Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=66, _LSFunction=_LSServer_GetServerStoreForConnectionWithCompletionHandler}
[default] Attempt to map database failed: permission was denied. This attempt will not be retried.
[db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=66, _LSFunction=_LSServer_GetServerStoreForConnectionWithCompletionHandler}
[LayoutConstraints] Unable to simultaneously satisfy constraints.
        Probably at least one of the constraints in the following list is one you don't want. 
        Try this: 
                (1) look at each constraint and try to figure out which you don't expect; 
                (2) find the code that added the unwanted constraint or constraints and fix it. 
        (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x2834ae5d0 h=-&- v=--& _UIActivityContentNavigationBar:0x1296ec2e0.minY == 0   (active, names: '|':UILayoutContainerView:0x125508280 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x2834a9d60 h=-&- v=--& _UIActivityContentNavigationBar:0x1296ec2e0.height == 50   (active)>",
    "<NSLayoutConstraint:0x28344bb60 V:[_UIActivityContentNavigationBar:0x1296ec2e0]-(0)-[UIFocusContainerGuide:0x2828c1ef0'UINavigationControllerContentFocusContainerGuide']   (active)>",
    "<NSLayoutConstraint:0x28344ac60 UIFocusContainerGuide:0x2828c1ef0'UINavigationControllerContentFocusContainerGuide'.bottom == UILayoutContainerView:0x125508280.bottom   (active)>",
    "<NSLayoutConstraint:0x28344ab70 V:|-(0)-[UILayoutContainerView:0x125508280]   (active, names: '|':UIView:0x129691580 )>",
    "<NSLayoutConstraint:0x28344aa30 UILayoutContainerView:0x125508280.bottom == UIView:0x129691580.bottom   (active)>",
    "<NSLayoutConstraint:0x2834a0f00 'UIView-Encapsulated-Layout-Height' UIView:0x129691580.height == 0   (active)>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x28344bb60 V:[_UIActivityContentNavigationBar:0x1296ec2e0]-(0)-[UIFocusContainerGuide:0x2828c1ef0'UINavigationControllerContentFocusContainerGuide']   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[LayoutConstraints] Unable to simultaneously satisfy constraints.
        Probably at least one of the constraints in the following list is one you don't want. 
        Try this: 
                (1) look at each constraint and try to figure out which you don't expect; 
                (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x28344a6c0 UILayoutGuide:0x282ef56c0'TitleViewGuide(0x128b4b6c0)'.leading >= UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x28344b7a0 UILayoutGuide:0x282ef56c0'TitleViewGuide(0x128b4b6c0)'.trailing <= UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide'.trailing   (active)>",
    "<NSLayoutConstraint:0x28344f2a0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x128b279d0'InviatonLink'.width == 0   (active)>",
    "<NSLayoutConstraint:0x2834485f0 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UINavigationBarContentView:0x128b279d0'InviatonLink' )>",
    "<NSLayoutConstraint:0x28344a350 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide']-(16)-|(LTR)   (active, names: '|':_UINavigationBarContentView:0x128b279d0'InviatonLink' )>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x28344b7a0 UILayoutGuide:0x282ef56c0'TitleViewGuide(0x128b4b6c0)'.trailing <= UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide'.trailing   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[LayoutConstraints] Unable to simultaneously satisfy constraints.
        Probably at least one of the constraints in the following list is one you don't want. 
        Try this: 
                (1) look at each constraint and try to figure out which you don't expect; 
                (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x28345eda0 H:|-(0)-[_UIActivityContentTitleView:0x128b84220]   (active, names: '|':_UINavigationBarContentView:0x128b279d0'InviatonLink' )>",
    "<NSLayoutConstraint:0x28345c5a0 _UIActivityContentTitleView:0x128b84220.trailing == _UINavigationBarContentView:0x128b279d0'InviatonLink'.trailing   (active)>",
    "<NSLayoutConstraint:0x2834a3de0 LPLinkView:0x128b84440.leading == UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x2834a3480 LPLinkView:0x128b84440.trailing == UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide'.trailing   (active)>",
    "<NSLayoutConstraint:0x28344f2a0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x128b279d0'InviatonLink'.width == 0   (active)>",
    "<NSLayoutConstraint:0x2834a3e30 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIActivityContentTitleView:0x128b84220 )>",
    "<NSLayoutConstraint:0x2834a2530 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide']-(8)-|(LTR)   (active, names: '|':_UIActivityContentTitleView:0x128b84220 )>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2834a3480 LPLinkView:0x128b84440.trailing == UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide'.trailing   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by kaushikgodhani** [comment]
> @miquelbeltran I tried the same code as in the example, but I'm having the same problem on the iPad. 
> 
> log [default] LaunchServices: store (null) or url (null) was nil: Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=66, _LSFunction=_LSServer_GetServerStoreForConnectionWithCompletionHandler} [default] Attempt to map database failed: permission was denied. This attempt will not be retried. [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=66, _LSFunction=_LSServer_GetServerStoreForConnectionWithCompletionHandler} [LayoutConstraints] Unable to simultaneously satisfy constraints. Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) ( "<NSAutoresizingMaskLayoutConstraint:0x2834ae5d0 h=-&- v=--& _UIActivityContentNavigationBar:0x1296ec2e0.minY == 0 (active, names: '|':UILayoutContainerView:0x125508280 )>", "<NSAutoresizingMaskLayoutConstraint:0x2834a9d60 h=-&- v=--& _UIActivityContentNavigationBar:0x1296ec2e0.height == 50 (active)>", "<NSLayoutConstraint:0x28344bb60 V:[_UIActivityContentNavigationBar:0x1296ec2e0]-(0)-[UIFocusContainerGuide:0x2828c1ef0'UINavigationControllerContentFocusContainerGuide'] (active)>", "<NSLayoutConstraint:0x28344ac60 UIFocusContainerGuide:0x2828c1ef0'UINavigationControllerContentFocusContainerGuide'.bottom == UILayoutContainerView:0x125508280.bottom (active)>", "<NSLayoutConstraint:0x28344ab70 V:|-(0)-[UILayoutContainerView:0x125508280] (active, names: '|':UIView:0x129691580 )>", "<NSLayoutConstraint:0x28344aa30 UILayoutContainerView:0x125508280.bottom == UIView:0x129691580.bottom (active)>", "<NSLayoutConstraint:0x2834a0f00 'UIView-Encapsulated-Layout-Height' UIView:0x129691580.height == 0 (active)>" )
> 
> Will attempt to recover by breaking constraint <NSLayoutConstraint:0x28344bb60 V:[_UIActivityContentNavigationBar:0x1296ec2e0]-(0)-[UIFocusContainerGuide:0x2828c1ef0'UINavigationControllerContentFocusContainerGuide'] (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger. The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful. [LayoutConstraints] Unable to simultaneously satisfy constraints. Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. ( "<NSLayoutConstraint:0x28344a6c0 UILayoutGuide:0x282ef56c0'TitleViewGuide(0x128b4b6c0)'.leading >= UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide'.leading (active)>", "<NSLayoutConstraint:0x28344b7a0 UILayoutGuide:0x282ef56c0'TitleViewGuide(0x128b4b6c0)'.trailing <= UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide'.trailing (active)>", "<NSLayoutConstraint:0x28344f2a0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x128b279d0'InviatonLink'.width == 0 (active)>", "<NSLayoutConstraint:0x2834485f0 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide'](LTR) (active, names: '|':_UINavigationBarContentView:0x128b279d0'InviatonLink' )>", "<NSLayoutConstraint:0x28344a350 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide']-(16)-|(LTR) (active, names: '|':_UINavigationBarContentView:0x128b279d0'InviatonLink' )>" )
> 
> Will attempt to recover by breaking constraint <NSLayoutConstraint:0x28344b7a0 UILayoutGuide:0x282ef56c0'TitleViewGuide(0x128b4b6c0)'.trailing <= UILayoutGuide:0x282ef5500'UIViewLayoutMarginsGuide'.trailing (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger. The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful. [LayoutConstraints] Unable to simultaneously satisfy constraints. Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. ( "<NSLayoutConstraint:0x28345eda0 H:|-(0)-[_UIActivityContentTitleView:0x128b84220] (active, names: '|':_UINavigationBarContentView:0x128b279d0'InviatonLink' )>", "<NSLayoutConstraint:0x28345c5a0 _UIActivityContentTitleView:0x128b84220.trailing == _UINavigationBarContentView:0x128b279d0'InviatonLink'.trailing (active)>", "<NSLayoutConstraint:0x2834a3de0 LPLinkView:0x128b84440.leading == UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide'.leading (active)>", "<NSLayoutConstraint:0x2834a3480 LPLinkView:0x128b84440.trailing == UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide'.trailing (active)>", "<NSLayoutConstraint:0x28344f2a0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x128b279d0'InviatonLink'.width == 0 (active)>", "<NSLayoutConstraint:0x2834a3e30 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide'](LTR) (active, names: '|':_UIActivityContentTitleView:0x128b84220 )>", "<NSLayoutConstraint:0x2834a2530 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide']-(8)-|(LTR) (active, names: '|':_UIActivityContentTitleView:0x128b84220 )>" )
> 
> Will attempt to recover by breaking constraint <NSLayoutConstraint:0x2834a3480 LPLinkView:0x128b84440.trailing == UILayoutGuide:0x282ef5b20'UIViewLayoutMarginsGuide'.trailing (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger. The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

same issue I have
