### ISSUE TITLE
[Bug] Crash on startup on platform windows

### ISSUE THREAD

**Issue by jdebou** [fluttercommunity/plus_plugins#1086]
### Platform

Windows

### Plugin

battery_plus_windows

### Version

1.1.2

### Flutter SDK

3.3.0

### Steps to reproduce

The crash in battery_plus initially described in #734 is back since #881 was fixed. This is because the changes that fixed it were reverted.

I apologize about the connectivity_plus issues that my commit caused, but can we please get the changes to battery_plus back ? 

### Logs

```shell
(see #734)
```

### Flutter Doctor

```shell
(see #734)
```

**Comment by miquelbeltran** [comment]
Hi! Is there a chance you can resubmit the PR?

Unfortunately I don't have enough Win dev knowledge to touch that part of the code.

**Comment by jdebou** [comment]
@miquelbeltran done !

As for connectivity_plus, it would be quite simple to fix the compilation issue and implement the same keepalive behavior. While I do not use connectivity_plus myself, I believe that #404 could be caused by the same programming mistake that affected me on battery_plus, which is why I initually tried to implement the same fix.

I am quite surprised that the test suite doesn't try to compile the code for windows platforms. I trusted it too much and did not compile connectivity_plus myself (I should have anyways). Is there a plan on including stronger coverage for desktop platforms ?

cheers

**Comment by miquelbeltran** [comment]
>  Is there a plan on including stronger coverage for desktop platforms ?

It is the idea. We have integration tests running just on Android but the other 5 platforms would be possible, depends on the tooling available on GitHub Actions tho. Any help on that matter is more than welcome!
