### ISSUE TITLE
[Bug]: canShareURLThroughMail returning NO. Reason: Failed to issue sandbox

### ISSUE THREAD

**Issue by bagoelz** [fluttercommunity/plus_plugins#1088]
### Platform

IOS 12

### Plugin

share_plus

### Version

4.4.0

### Flutter SDK

>=2.17.5

### Steps to reproduce

running on ios and then star sharing, then come the error,
[ShareSheet] canShareURLThroughMail returning NO. Reason: Failed to issue sandbox extension for /var/mobile/Media/DCIM/101APPLE/IMG_1532.JPG with error 1.

### Logs

```shell
2022-09-23 12:31:18.925402+0700 Runner[1438:541402] [ShareSheet] canShareURLThroughMail returning NO. Reason: Failed to issue sandbox extension for /var/mobile/Media/DCIM/101APPLE/IMG_1532.JPG with error 1.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.3, on macOS 11.6.3 20G415 darwin-x64, locale en-US)
    • Flutter version 3.0.3 at /Users/mahesaputra/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (3 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesaputra/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Boemi (mobile)  • 0e1b00fe04edebc61808b97c88c0ccd89f6c7e71 • ios            • iOS 14.6 18F72
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 11.6.3 20G415 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
mahesaputra@Mahesas-MacBook-Pro-8 ios %
```

**Comment by miquelbeltran** [comment]
Would it be possible to add a code sample to your bug report?

**Comment by bagoelz** [comment]
Future<File?> getImageToLocal(url, msg) async {
    try {
      final Directory? dir;
      String imagePath;
      var imageId;
      if (GetPlatform.isIOS) {
        imageId = await ImageDownloader.downloadImage(
          selectedImageSLide.value.img!,
        );
      } 
      if (imageId != null) {
        var path = await ImageDownloader.findPath(imageId);
        return File(path!);
      }
    } on PlatformException catch (error) {
      sendSnackbar(title: "error", message: "download image error", durasi: 3);
    }
    return null;
  }

  

  Future<void> shareTo(context, {msg}) async {
    final box = context.findRenderObject() as RenderBox?;
      File? file = await getImageToLocal(selectedImageSLide.value.img, msg);
      if (GetPlatform.isIOS) {
        await Share.shareFiles([file!.path],
            text: msg,
            subject: "Sharing FIle",
            sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size);
      }
  }



this is the code that i used
