### ISSUE TITLE
[Question][share_plus]: Social Meta(st, sd, si) doesn't work on Android preview share sheet 

### ISSUE THREAD

**Issue by krim45** [fluttercommunity/plus_plugins#1091]
### What is your question?

I made Dynamic Link in Firebase and set Social Meta Data(st, sd, si) ex) preview title, image, description.

When I press share button, there is share sheet and preview title, image, description.

When I press share button and check preview sheet on IOS, it works well. I can see everything what I set on Firebase. But not working on Android.

What should I do?

```dart
import 'package:share_plus/share_plus.dart';

~
onTap: () async {
                  await Share.share('https://earnion.page.link/guide');
                },
~
```

**Comment by miquelbeltran** [comment]
Does that even work when sharing the firebase link in native code?

You could create a small native Android project and check it out.
