### ISSUE TITLE
[Request] Setup Windows CI process

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#1094]
### Proposal

Setup the CI build process on Windows:

- Build example projects for Windows.
- Run integration_test on Windows.

Since this works very differently to how things are done in Linux/MacOS, help is welcome from anyone familiar working on that environment with GitHub Actions and Windows.

**Comment by Hirdey-1999** [comment]
I Am Ready To Work With this issue but i need help for this.
Please Can you explain the issue

**Comment by miquelbeltran** [comment]
What question do you have?

**Comment by Hirdey-1999** [comment]
How To Start Working on this issue.

**Comment by miquelbeltran** [comment]
I don't understand what you mean. Either ask specific questions or submit a PR with the work.

**Comment by krshkodes** [comment]
Hi @miquelbeltran can I work on this?

**Comment by miquelbeltran** [comment]
See the pinned issue for more info: https://github.com/fluttercommunity/plus_plugins/issues/1108

Anyone can work on the issues, and first quality PR approved gets it

**Comment by miquelbeltran** [comment]
fixed in https://github.com/fluttercommunity/plus_plugins/pull/1133
