### ISSUE TITLE
[Question]: [android_alarm_manager_plus] Does this plugin support to trigger method after reboot?

### ISSUE THREAD

**Issue by haizadvnet** [fluttercommunity/plus_plugins#1097]
### What is your question?

Hi,

Objective : To invoke a method whenever device reboot.

I have went through other sources on how to trigger method once the device has been reboot. I am looking for a simple solution by using plugin to achieve the objective. Then I came across android_alarm_manager_plus and I thought maybe I can use it.

Question : Does this plugin support to invoke a method after reboot?

Sources that I went through:
https://stackoverflow.com/questions/63419221/invoke-a-method-in-flutter-after-restarting-the-device
https://stackoverflow.com/questions/66442315/flutter-start-foreground-service-on-boot
https://medium.com/software-engineers-toolbox/call-flutter-from-native-android-via-platform-channel-in-4-steps-3151f6535d2f

**Comment by miquelbeltran** [comment]
The plugin does what the Android OS does, with the added problem that the alarm has to be able to call into Dart code once it triggers.

https://developer.android.com/reference/android/app/AlarmManager

> Registered alarms are retained while the device is asleep (and can optionally wake the device up if they go off during that time), but will be cleared if it is turned off and rebooted. 

I'd add, Alarms are also removed when the app is force-killed by the user.

I think this already answers your question :sweat_smile:

**Comment by haizadvnet** [comment]
Yup ,you have answered my question. Thank you sir 😄  Seems like I need to find another way to do it...
