### ISSUE TITLE
[Request]: android_alarm_manager_plus Integration test

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#1103]
### Plugin

android_alarm_manager_plus

### Use case

Current test implementation in packages/android_alarm_manager_plus/example/integration_test/android_alarm_manager_plus_test.dart does nothing.

### Proposal

Write working integration_test for android_alarm_manager_plus and enable the CI job to run it on an Android emulator

**Comment by Hadi-Alsinan** [comment]
Hello, do I need to assign myself to the issue or do I start working on it right away?

**Comment by miquelbeltran** [comment]
There's no ticket "reservation". Whoever gets the PR approved gets it.
