### ISSUE TITLE
[Request]: Integration tests for macOs

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#1105]
### Plugin

all

### Use case

At the moment integration_test run on Android and iOS emulator/simulator but not on desktop

### Proposal

Enable the integration_test to run and pass on a macOs "macos-latest" machine.

Also, the tests will need to be adapted to macOs.

**Comment by abd99** [comment]
I would like to work on this issue for Hacktoberfest.

**Comment by miquelbeltran** [comment]
There's no ticket "reservation". Whoever gets the PR approved gets it.

**Comment by abd99** [comment]
Okay. Thanks for clarifying that, @miquelbeltran.
