### ISSUE TITLE
🎁 Hacktoberfest 2022 Announcement 🎁

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#1108]
Hacktoberfest is back this year with more prizes than ever!

~~Visit https://invertase.io/community/hacktoberfest for more information on how to parcitipate.~~

Update: You can see your contributions here: https://archive.invertase.io/community/hacktoberfest

**Comment by miquelbeltran** [comment]
Note: There's no ticket "reservation". Whoever gets the PR approved, gets the prize.

Please try to be fair, and if you see someone working on something (e.g. PR in review) work on something else meanwhile.

**Comment by vbuberen** [comment]
We would also appreciate if you don't open draft PRs, but work on your own fork till the code is ready for review. Having multiple drafts introduces a lot of noise and distraction for maintainers and intensively uses Github Actions runners, so PRs that are ready for review can't run required check.
