### ISSUE TITLE
[Question]: does the stream only emit values if the ConnectionState changes?

### ISSUE THREAD

**Issue by davoutuk** [fluttercommunity/plus_plugins#1115]
### What is your question?

This might be a bug in my code, but I'm getting a situation where the Connectivity_plus stream is emitting the same ConnectivityResult value twice in a row.  Is that expected?

If so, how can I fix this so that the stream only emits an event if the value is different to the previously emitted value?

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
AFAIK, it depends on the platform.

You can filter out events in Streams using Dart's `distinct`: https://api.flutter.dev/flutter/dart-async/Stream/distinct.html
