### ISSUE TITLE
[Bug]: Admonitions don't appear on a website anymore

### ISSUE THREAD

**Issue by vbuberen** [fluttercommunity/plus_plugins#1117]
After recent fix for website deployment and dependencies updates admonitions like `:::note` stopped working and don't appear on Plus plugins website anymore.

Here is a screenshot of how it was in old version of website:
<img width="1322" alt="Screenshot 2022-09-30 at 18 02 57" src="https://user-images.githubusercontent.com/13467769/193300822-085a6558-4082-4707-9ccb-c279ab57ec8e.png">

And here is current version (text `PlusPlugins are all...` isn't highlighted with a separate note block anymore):
<img width="788" alt="Screenshot 2022-09-30 at 18 11 17" src="https://user-images.githubusercontent.com/13467769/193301085-93ee969b-25d5-4b62-ba44-c22ff76f4df3.png">

Might be something related to Docusaurus configs.

**Comment by NiranjanMeghwal** [comment]
Hello! I would like to try to work on this issue, could you please assign this to me.

**Comment by miquelbeltran** [comment]
There's no ticket assignment, just submit the PR when ready.

**Comment by vbuberen** [comment]
Completed via #1128
