### ISSUE TITLE
[Bug]: Unreliability of plugin callback execution

### ISSUE THREAD

**Issue by Rackor** [fluttercommunity/plus_plugins#1149]
### Platform

8+

### Plugin

android_alarm_manager_plus

### Version

2.0.7+1

### Flutter SDK

3.3.2

### Steps to reproduce

Calling `oneShotAt` with `alarmClock: true`.

The context is a reminder like application, where reminders (possible recurrent) must trigger at specific times.

I sadly encountered irregularities in the trigger times and often the callback does not get executed at all, breaking possible rescheduling policies done via the passed callback.

Detailed debugging showed, that the alarms, however, fire correctly and get caught by the `BroadcastReceiver ` as they should, but the dart-callback often gets executed delayed or not even executed at all.
After digging into the android documentation and the plugin code, I would guess, that the plugins callback execution is just unreliable on Android O+ due to its usage of `JobIntentService`, which is also deprecated. This issue was already mentioned once in #58263. 

I would suggest migrating to `WorkManager`, which should at least ensure execution according its documentation. 
Furthermore, does something speak against calling `executeDartCallbackInBackgroundIsolate` directly in the `BroadcastReceiver` when using `alarmClock: true`? This is of course not battery optimal, but neither is using `alarmClock: true` in the first place, and it seems like this is the only way, maybe besides using a ForegroundService, to ensure immediate execution of the callback.

### Code Sample

```dart
AndroidAlarmManager.oneShotAt(
        time,
        id,
       callback,
        wakeup: true,
        rescheduleOnReboot: true,
        exact: true,
        allowWhileIdle: true,
        alarmClock: true
);
```

### Logs

```shell
-
```

### Flutter Doctor

```shell
-
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
There's already a plugin for WorkManager by the flutter community: https://pub.dev/packages/workmanager We don't plan to migrate this plugin to WorkManager, the idea is to expose the Android Alarm Manager functionality to Flutter (somehow), if WorkManager works better for your usecase, I highly suggest you to use the other plugin.

As far as I know, there have been changes in Flutter 3 that lead to the plugin not working correctly, and has been mentioned on other issues, e.g. here: https://github.com/fluttercommunity/plus_plugins/issues/1077

> does something speak against calling executeDartCallbackInBackgroundIsolate directly in the BroadcastReceiver when using alarmClock: true? 

I don't know enough about this to have an opinion, sorry.

**Comment by vbuberen** [comment]
As @miquelbeltran already replied about WorkManager package existence from my side I can add info about recent updates that might help with `oneShot()` not working (note, it has nothing to do with issues with trigger time): https://github.com/fluttercommunity/plus_plugins/pull/1229

I think we can close it for now as `oneShot` works.

**Comment by Rackor** [comment]
Reopen this issue. `oneShot` seems not to work reliable with specific options as it should like the corresponding method from the `AlarmManager` API.
The description was updated and steps for reproduction added.

No, this issues is not related to #1077.

@miquelbeltran The section `Solution Proposals` should clearify what I meant with "migrating to WorkManager API".

**Comment by miquelbeltran** [comment]
I am not sure what you mean with the WorkManager API, feel free to submit a PR with the proposed solution.

**Comment by feduke-nukem** [comment]
same 

```allowWhileIdle: true``` does nothing to fire in doze mode

**Comment by ShruAlekha** [comment]
Same issue. The callback is delayed.
