### ISSUE TITLE
[Bug]: device_info_plus: ^ 5.0.0 conflicts with device_info_plus_web ^ 3.0.0 for version device_info_plus_plus_interface

### ISSUE THREAD

**Issue by tomk9** [fluttercommunity/plus_plugins#1162]
### Platform

Android, iOS

### Plugin

device_info_plus_web

### Version

3.0.0

### Flutter SDK

3.3.3

### Steps to reproduce

`pubspec.yaml`:
```yaml
dependencies:
  device_info_plus: ^5.0.0
```
```shell
flutter pub get
```

### Logs

```shell
Because device_info_plus_web 3.0.0 depends on device_info_plus_platform_interface ^3.0.0 and no versions of device_info_plus_web match >3.0.0 <4.0.0, device_info_plus_web ^3.0.0 requires device_info_plus_platform_interface ^3.0.0.
And because device_info_plus 5.0.0 depends on both device_info_plus_platform_interface ^4.0.0 and device_info_plus_web ^3.0.0, device_info_plus 5.0.0 is forbidden.
So, because no versions of device_info_plus match >5.0.0 <6.0.0 and flutter_app depends on device_info_plus ^5.0.0, version solving failed.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale
    en-PL)
    • Flutter version 3.3.3 on channel stable at
      /Users/tomasz/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (7 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Looks like https://github.com/fluttercommunity/plus_plugins/pull/1156 did not have all dependencies correctly sorted.

Please use 4.1.3 meanwhile.

**Comment by miquelbeltran** [comment]
Should work now for 5.0.1

**Comment by alexmercerind** [comment]
Thanks a lot for taking care of it. 🙏
Federated plugin versioning is a challenge.
