### ISSUE TITLE
[Bug]: device_info_plus_windows ^5.1.0 doesn't exist

### ISSUE THREAD

**Issue by naamapps** [fluttercommunity/plus_plugins#1175]
### Platform

Android 12

### Plugin

device_info_plus

### Version

5.0.2

### Flutter SDK

3.3.3

### Steps to reproduce

Depend on device_info_plus >=5.0.2.

### Logs

```shell
Because device_info_plus >=5.0.2 depends on device_info_plus_windows ^5.1.0 which doesn't match any versions, device_info_plus >=5.0.2 is forbidden.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.5.1 21G83 darwin-arm, locale
    en-IL)
    • Flutter version 3.3.3 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.0.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (9 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/naamapps/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Fixed in 5.0.3, sorry for the inconvenience.

**Comment by naamapps** [comment]
Thanks.

**Comment by naamapps** [comment]
@miquelbeltran Same problem with device_info_plus_platform_interface.

The latest is 4.0.1 and not 4.1.0.

**Comment by miquelbeltran** [comment]
Hopefully 5.0.4 is the good one

**Comment by naamapps** [comment]
Unfortunately I see now that also in every platform package there is a dependency of device_info_plus_platform_interface 4.1.0.

In device_info_plus_windows, device_info_plus_web, device_info_plus_macos, device_info_plus_linux

**Comment by miquelbeltran** [comment]
Thanks for letting me know. We switched to a new way of managing versions, so I messed up when doing some changes by hand :disappointed: New versions for device_info_plus and dependencies have been released

**Comment by miquelbeltran** [comment]
I just checked with a new project doing a `flutter pub add device_info_plus` and didn't see any errors with 5.0.5.

**Comment by naamapps** [comment]
Works great, thanks @miquelbeltran 👍
