### ISSUE TITLE
[Request]: Show NSSharingServicePicker asynchronously on main thread

### ISSUE THREAD

**Issue by leonx98** [fluttercommunity/plus_plugins#1177]
### Plugin

share_plus

### Use case

We're using the `share_plus` plugin to share one or multiple files after it has been downloaded. After the download of the files we still need to update the UI. But since the `NSSharingServicePicker` is presented synchronously on the main thread the UI hangs.

### Proposal

Show the `NSSharingServicePicker`asynchronously on the main thread, so that the UI can continue to update.

    let picker = NSSharingServicePicker(items: items)
    DispatchQueue.main.async {
        picker.show(relativeTo: origin, of: view, preferredEdge: NSRectEdge.maxY)
    }

**Comment by miquelbeltran** [comment]
@leonx98 is this request for iOS or for MacOS? You did not specify.

**Comment by miquelbeltran** [comment]
Thanks! Thats fixed with the linked PR
