### ISSUE TITLE
[Bug]: getWifiName() return null on Android 13

### ISSUE THREAD

**Issue by Allen-Guof** [fluttercommunity/plus_plugins#1181]
### Platform

Android 13

### Plugin

network_info_plus

### Version

2.3.1

### Flutter SDK

3.3.0

### Steps to reproduce

Run Example code. The all permissions is granted.
```
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
![image](https://user-images.githubusercontent.com/17547942/194741276-f736b131-220d-411e-bcb9-4ff4f22d2f58.png)

### Logs

```shell
Launching lib/main.dart on Pixel 4 XL in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:53501/OuDXJWYYd0E=/ws
Syncing files to device Pixel 4 XL...
E/SurfaceSyncer(24564): Failed to find sync for id=0
W/Parcel  (24564): Expecting binder but got null!
```

### Flutter Doctor

```shell
guof@admindeMac-mini flutter_test11 % flutter doctor -v                                                                                          
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.0 on channel stable at /Users/guof/fvm/versions/3.3.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 周前), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/guof/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/guof/Library/Android/sdk
    • Java binary at: /Users/guof/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/guof/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/guof/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • Pixel 4 XL (mobile)       • 9A291FFBA0061Y            • android-arm64  • Android 13 (API 33)
    • paidaxing iphone (mobile) • 00008110-0004654C2E12801E • ios            • iOS 16.0 20A362
    • macOS (desktop)           • macos                     • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
There's a related PR that can maybe clarify this issue: https://github.com/fluttercommunity/plus_plugins/pull/1155

I believe you need to actually request user permission, it is not enough with just declaring it in the Android Manifest.

**Comment by kostadin24** [comment]
Hello
Same issue for me:

I have Android 13 (Pixel 5).
Just updated my app to use 2.3.1
No more SSID. Location permission is granted, location service is ON, ACCESS_NETWORK_STATE is in manifest.
Also no BSSID.
It was OK with plugin version 2.2.0

Just tried with Android 9 and SSID is OK.

Example in plugin project also shows me SSID: null

**Comment by Allen-Guof** [comment]
@miquelbeltran Hi, I have turned on the location permission in the Settings. This has the same effect as using code to request permissions. Still can't get wifiName.

**Comment by miquelbeltran** [comment]
So since 2.3.0, where we changed the following: "Android: Use new APIs to get network info on devices with with Android 12 (SDK 31) and newer" it has not been working, correct?

Pinging @vbuberen as he did that, hopefully you know about this issue.

**Comment by vbuberen** [comment]
I will investigate the issue.

**Comment by Kajikoslav** [comment]
same issue - Android 12 with ACCESS_NETWORK_STATE in manifest, network_info_plus: ^2.3.2 -> info.getWifiName() is null

**Comment by codercengiz** [comment]
I also have this problem on Android 12. 

> "Android: Use new APIs to get network info on devices with with Android 12 (SDK 31) and newer" 
it has not been working.

**Comment by DaYang816** [comment]
Why is wifi name still null

**Comment by msilotto** [comment]
Ssid is still null with network_info_plus 3.0.1 and Android 12

**Comment by vbuberen** [comment]
Read https://github.com/fluttercommunity/plus_plugins/tree/main/packages/network_info_plus/network_info_plus#device-permissions 

If one of conditions is not met you won't get SSID.

> Why is wifi name still null

This is the least helpful message about the issue. If you believe that you have all conditions met and still not getting info - open a new issue and provide a sample project. Otherwise such questions won't be answered.
