### ISSUE TITLE
[Bug]: Cannot compile since update to Flutter 3.3.3

### ISSUE THREAD

**Issue by And96** [fluttercommunity/plus_plugins#1183]
### Platform

Android 11

### Plugin

share_plus

### Version

latest

### Flutter SDK

3.3.3

### Steps to reproduce

Cannot compile Android app since upgrade to flutter 3.3.3

### Code Sample

```dart
Tried to remove package and add again but didnt solve
Tried flutter clean
Tried to clean and rebluild gradle with ./gradlew in android directory
Tried adding 
lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }

Actually cannot compile the project. No problem on prevoius flutter SDK on 3.3.2
```

### Logs

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':share_plus:lintDebug'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or create a baseline to see only new errors:
  
  android {
      lint {
          baseline = file("lint-baseline.xml")
      }
  }
  ```

  For more details, see https://developer.android.com/studio/write/lint#snapshot
```


### Flutter Doctor

```shell
.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by And96** [comment]
Sorry. Solved.

**Comment by kamlesh9070** [comment]
How you solved this issue?

I am facing same issue.
Flutter: 3.3.1
android_alarm_manager_plus : 2.1.0

**Comment by And96** [comment]
Ohh I cannot remember sorry. I didnt wrote anything about this issue. Actually it works. But I cannot say what dis I changed.
Sorry

**Comment by erperejildo** [comment]
I'm having exactly the same issue
