### ISSUE TITLE
[Question]: Can you upgrade the kotlin version?

### ISSUE THREAD

**Issue by eggysudianto** [fluttercommunity/plus_plugins#1222]
### What is your question?

because my kotlin version use ^1.7.0 and when I lower it to 1.6.10 like your kotlin version, then my app show many deprecated api from other library. Thanks

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Feel free to submit a PR with the change as well!

**Comment by vbuberen** [comment]
> because my kotlin version use ^1.7.0 and when I lower it to 1.6.10 like your kotlin version, then my app show many deprecated api from other library. Thanks

Why do you lower the version? You can use new Kotlin version in your project without looking at which version is used by plugins.

**Comment by eggysudianto** [comment]
> > because my kotlin version use ^1.7.0 and when I lower it to 1.6.10 like your kotlin version, then my app show many deprecated api from other library. Thanks
> 
> Why do you lower the version? You can use new Kotlin version in your project without looking at which version is used by plugins.

no I can't, error when I tried build apk, after I lower my kotlin version, then it's success

**Comment by vbuberen** [comment]
Would be better to discuss with info on which plugin it is and which errors you have.

**Comment by vbuberen** [comment]
After a series of updates linked above we can close this issue
Next release of plugins will have latest Kotlin and Gradle versions
