### ISSUE TITLE
[Request]: Refactor plugins to a two package architecture

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#1226]
### Plugin

all

### Use case

As discussed internally by the maintainer team, the packages should be refactored, so all platform implementations must be moved into the same package.

e.g. before:

- `connectivity_plus` (Contains Android and iOS implementations)
- `connectivity_plus_platform_inteface`
- `connectivity_plus_macos`
- `connectivity_plus_linux`
- `connectivity_plus_web`
- `connectivity_plus_windows`

e.g. after:

- `connectivity_plus` (Contains Android, iOS, Windows, Linux, macOS, and web implementations)
- `connectivity_plus_platform_inteface`

There are two main reasons to do this:

1. Easier to maintain and collaborate.
2. Avoid dependency issues (diamond dependency problem)

Leaving the platform interface package for each one of them helps with extendability in the future.

### Proposal

Refactor the following packages:

- [x] `connectivity_plus`
- [x] `device_info_plus`
- [x] `network_info_plus`
- [x] `package_info_plus`
- [x] `sensors_plus`
- [x] `share_plus`

Note: This refactors should be done by the maintainers and not by external collaborators.

**Comment by miquelbeltran** [comment]
Currently working on `connectivity_plus`

**Comment by nohli** [comment]
Working on `device_info_plus`

**Comment by nohli** [comment]
Now working on `network_info_plus`

**Comment by nohli** [comment]
Now on `package_info_plus`

**Comment by nohli** [comment]
Now on `sensors_plus`

**Comment by nohli** [comment]
Last one, `share_plus`.

**Comment by nohli** [comment]
Looks like we've done the refactoring 🤝

**Comment by stuartmorgan** [comment]
> 2\. Avoid dependency issues (diamond dependency problem)

Out of curiosity (since we plan to add more documentation about the process of maintaining federated plugins in general), what issues were you having with the diamond dependency?

**Comment by miquelbeltran** [comment]
> > 2. Avoid dependency issues (diamond dependency problem)
> 
> Out of curiosity (since we plan to add more documentation about the process of maintaining federated plugins in general), what issues were you having with the diamond dependency?

Hi @stuartmorgan So a problem we faced is as follows (package names and versions as example)

- battery_plus 2.0.0 depends on battery_plus_platform_interface 2.0.0
- battery_plus 2.0.0 also depends on battery_plus_windows 1.0.0
- battery_plus_windows 1.0.0 depends on battery_plus_platform_interface 1.0.0

This would cause a problem for users when compiling, as battery_plus_platform_interface 1.0.0 and 2.0.0 can't coexist.

The error is not obvious locally because packages are referenced directly by path, so CI didn't detect the error. But also, Melos, the package managing tool we use, didn't solve this problem either. We had to solve these types of errors by making sure all platform packages are also updated with a major update to match the main package. (e.g. bump battery_plus_windows, battery_plus_macos, etc. to 2.0.0 so they also depend on battery_plus_platform_interface 2.0.0)

By incorporating the Windows code into the battery_plus package, we eliminate this diamond dependency problem.

I hope the example is clear.

**Comment by nohli** [comment]
@stuartmorgan I see that you maintain `path_provider`.
Since our refactoring, the tests from [appwrite](https://github.com/appwrite/sdk-generator/pull/572) fail (for `package_info_plus` and `path_provider`).
The (same) error (see failing Flutter stable [logs](https://app.travis-ci.com/github/appwrite/sdk-generator/jobs/585998670)) was fixed for `package_info_plus` with the [increase of Flutter sdk](https://github.com/fluttercommunity/plus_plugins/pull/1275/files) to `>=2.11.0`.
The [test](https://app.travis-ci.com/github/appwrite/sdk-generator/jobs/585998670) for Flutter beta is still failing for `path_provider`. Would increasing the min sdk constraint from `2.10.0` to `2.11.0` resolve this issue?
I'm writing it here, because it happened after the change of our plugins - maybe they affect each other and our change broke `path_provider` somehow.

**Comment by stuartmorgan** [comment]
You should not be relying on plugin registration to be run in unit tests (or in general [using plugins at all in unit tests](https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests)).

> Would increasing the min sdk constraint from `2.10.0` to `2.11.0` resolve this issue?

`path_provider` doesn't use an inline (as in, in the app-facing package) implementation, so there's no SDK check performed for it. See https://github.com/flutter/flutter/issues/87862 for details.
