### ISSUE TITLE
[Question]: Uniqe device ID redistributable?

### ISSUE THREAD

**Issue by thePlayer094** [fluttercommunity/plus_plugins#1244]
### What is your question?

I realized, that after i generate the deviceId on iOS got a good one, but after deleted the application and reinstall i've got another one. So it means this is not uniqe. I am wondering, that if i've got device **'A'** with **XYZ123** uniqe device id. And someone has device **'B'** is there any chance that device **'B'** got **XYZ123** (same) device id, after i've deleted the application on device **'A'**.

ios:  'identifierForVendor': data.identifierForVendor -> I'm talking about this id. 

Thank you!

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by swapnilgaikwad1507** [comment]
Same thing happening for me too. Once I am uninstalling the application, I am getting the new id. Is there any workaround for this?
