### ISSUE TITLE
[Bug]: Update Kotlin version

### ISSUE THREAD

**Issue by tomk9** [fluttercommunity/plus_plugins#1248]
### Platform

Android

### Plugin

package_info_plus

### Version

2.0.0

### Flutter SDK

3.3.4

### Steps to reproduce

Update Gradle to 7.5.1 in `android/gradle/wrapper/gradle-wrapper.properties`
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip
```
Update Kotlin to 1.7.20 and Gradle to 7.3.1 in `android/build.gradle`
```
ext.kotlin_version = '1.7.20'
```
```
classpath 'com.android.tools.build:gradle:7.3.1'
```
Please update the Kotlin version to meet the newest Gradle compatibility
https://docs.gradle.org/7.5/userguide/compatibility.html#kotlin

### Logs

```shell
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':package_info_plus' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale
    en-PL)
    • Flutter version 3.3.4 on channel stable at
      /Users/tomasz/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (12 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tomasz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/tomasz/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Closing this one as all plugins that use Kotlin were updated and next release of updates will have the latest Kotlin version.
