### ISSUE TITLE
[Question]: the class XFILE doesn't exist.

### ISSUE THREAD

**Issue by juliuskopp** [fluttercommunity/plus_plugins#1271]
### What is your question?

1. I create a class and wanted to use "Share.shareXFiles".
2. I add "import 'package:share_plus/share_plus.dart';"
3. When writting this line : await Share.shareXFiles([XFile(filename)],     I have this message : The method 'XFile' isn't defined for the type 'DataShareService'.
4. So I have to add this import "import 'package:cross_file/cross_file.dart';"
5. But now I have this message "package:cross_file/cross_file.dart Depend on referenced packages.dart[depend_on_referenced_packages](https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html)"

In your example, you don't have the problem because XFile is referenced by this import : 'package:image_picker/image_picker.dart'

In the example below, I have commented the line of the import 'package:cross_file/cross_file.dart' so you can see the problem. If you uncomment the import 'package:cross_file/cross_file.dart'; you'll see the other message.
Thanks.

Code sample :

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
// TODO : uncomment the line below to refrence XFile
//import 'package:cross_file/cross_file.dart';

class DataShareService {
  void sharingFile({
    required String filename,
    required BuildContext context,
    required String subject,
  }) async {

    final box = context.findRenderObject() as RenderBox?;

    await Share.shareXFiles([XFile(filename)],
        subject: subject,
        sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size);
  }
}

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
> But now I have this message "package:cross_file/cross_file.dart Depend on referenced packages.dart[depend_on_referenced_packages](https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html)"

Do what the warning suggests and add the dependency to cross_file, which is an official package from the Flutter team.

**Comment by werainkhatri** [comment]
> Do what the warning suggests and add the dependency to cross_file, which is an official package from the Flutter team.

maybe we should export the package? same as what `image_picker` does?

https://github.com/flutter/plugins/blob/f55c7ffc6984c75e6b2b6a72a02b48064e0b5bc1/packages/image_picker/image_picker_platform_interface/lib/image_picker_platform_interface.dart#L5

**Comment by miquelbeltran** [comment]
Good point @werainkhatri a PR with the fix is more than welcome ;)

**Comment by werainkhatri** [comment]
> a PR with the fix is more than welcome

you got it!

**Comment by jingluoguo** [comment]
you can write import 'package:cross_file/cross_file.dart';
