### ISSUE TITLE
[Question]: Is generated_plugin_registrant.dart necessary for web for device_info_plus and package_info_plus?

### ISSUE THREAD

**Issue by naamapps** [fluttercommunity/plus_plugins#1274]
### What is your question?

Hey, 
After upgrading `device_info_plus` and `package_info_plus` to latest versions,
the `generated_plugin_registrant.dart` file does not generate the `PackageInfoPlugin.registerWith(registrar);` and `DeviceInfoPlusPlugin.registerWith(registrar);` lines anymore (It used to generate those lines, so after upgrading I had this error
```
Undefined name 'PackageInfoPlugin'.
Try correcting the name to one that is defined, or defining the name
```

Is this the right behaviour?

Thanks.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Looks related to https://github.com/fluttercommunity/plus_plugins/issues/1270

**Comment by miquelbeltran** [comment]
Please check if with the latest release of the package(s) still happens

**Comment by naamapps** [comment]
Hey @miquelbeltran,
Still won't generate for me.

I think this line is the culprit
https://github.com/fluttercommunity/plus_plugins/blob/37abbf7b05a32bc1e7b440c19540b277e301fe5a/packages/device_info_plus/device_info_plus/lib/device_info_plus.dart#L26 

If I try to write `DeviceInfoPlusWebPlugin` manually inside the `generated_plugin_registrant` file, it won't recognize this class.

**Comment by naamapps** [comment]
Same for PackageInfo.

**Comment by miquelbeltran** [comment]
mhh, so adding the export for the web plugin implementation causes the generated_plugin_registrant not to work properly? If you can checkout the project locally, reference by path, and then find what causes it, it will be super helpful (also feel free to submit a PR if you find the solution).

**Comment by naamapps** [comment]
Is the file web_plugin_registrant the same as generated_plugin_registrant?
I can't find it in my project at all..

I tried deleting the generated_plugin_registrant file and it didn't even regenerate itself.

**Comment by miquelbeltran** [comment]
It is in  `.dart_tool/dartpad/web_plugin_registrant.dart` it appears for me when running the project

**Comment by naamapps** [comment]
Found it! And it does generate correctly for all packages.
So what is the `generated_plugin_registrant` file that was in my project? Is it not relevant anymore?

**Comment by miquelbeltran** [comment]
I remember that the generated_plugin_registrant.dart is generated when running on web, but I guess this was changed eventually.

Do you still have problems running the project on web with the latest release?

**Comment by naamapps** [comment]
Nope, all good.
Thanks.

**Comment by MrCsabaToth** [comment]
Wait, that whole file `generated_plugin_registrant.dart` in my app's lib folder is not needed any more?

**Comment by gizemgizg** [comment]
Hello, PackageInfoPlugin and  that whole file generated_plugin_registrant.dart in my app's lib folder is not needed any more?

**Comment by anushka-mim** [comment]
I have two files `generated_plugin_registrant.cc` and `generated_plugins.cmake` in both windows and linux folders when I build my project for the web. And they keep showing under git changes. How do I stop these files from regenerating?
