### ISSUE TITLE
Generate code coverage and push to codecov

### ISSUE THREAD

**Issue by bruno-garcia** [fluttercommunity/plus_plugins#128]
Currently PRs don't have an indication of how it affects code coverage.
We need CI to generate a coverage file, and upload the result to code a service such as codecov.

**Comment by bruno-garcia** [comment]
I might be able to take this on the weekend if no one beats me to it.

**Comment by bruno-garcia** [comment]
Unassigned myself while I can since I keep postponing this. Hopefully someone has more time to jump in.

**Comment by jpnurmi** [comment]
codecov integrated in #178: https://codecov.io/gh/fluttercommunity/plus_plugins
