### ISSUE TITLE
how to detect system windows version if on windows?

### ISSUE THREAD

**Issue by jinfagang** [fluttercommunity/plus_plugins#1281]
### Plugin

device_info_plugin

### Use case

Does there any instructions to do with it?

### Proposal

Does there any instructions to do with it?

**Comment by alexmercerind** [comment]
What do you expect?

There's a ton of information present like `productName` or `buildNumber`. My recommendation will be to use `buildNumber`.

![](https://user-images.githubusercontent.com/28951144/161233030-9f732dbe-1760-4c1f-9e1f-27b7d50876be.png)

**Comment by jinfagang** [comment]
@alexmercerind thank u so much, just realised you are author of arcrylic plugin. very nice work. I just wanna judege the platform to avoid win10 bug you have mentioned in: https://github.com/alexmercerind/flutter_acrylic/issues/6

**Comment by vbuberen** [comment]
It seems there is enough info provided to you in `device_info_plus` check fields as shared on screenshot provided above. 

Also check API docs for Windows part to get more info about fields and pick the one you need for your purposes: https://pub.dev/documentation/device_info_plus/latest/device_info_plus/WindowsDeviceInfo-class.html
