### ISSUE TITLE
[Question]: Error build android since package_info_plus 3.0.1

### ISSUE THREAD

**Issue by AlexRich16** [fluttercommunity/plus_plugins#1290]
### What is your question?

I've a build error on android since I've upgrade package_info_plus 3.0.0 -> 3.0.1

```
A problem occurred configuring project ':package_info_plus'.
> Could not resolve all artifacts for configuration ':package_info_plus:classpath'.
> Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20.
```

build.gradle
```
ext.kotlin_version = '1.6.10'

classpath 'com.android.tools.build:gradle:3.4.2'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
```

If i downgrade on package_info_plus 3.0.0 , it's ok ✅ 

Can you help me to upgrade my dependency and solve my problem ?
Thanks

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by xrusu** [comment]
you need to upgrade your gradle version, your andoid\build.gradle file should look something like this:

`buildscript {
    ext.kotlin_version = '1.7.20'
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.14'
    }
}`

**Comment by vbuberen** [comment]
Closing as the solution was provided and no further messages from the issue reporter.

**Comment by martin-braun** [comment]
@vbuberen Which makes it incompatible with Flutter 2. I would love if the plugin would be a little bit longer compatible with an older gradle version. Version 2 was still compatible with Gradle 3 and now it requires Gradle 7. The last release of Flutter 2 is not even one year old.
