### ISSUE TITLE
[Question]: share_plus how to localize and how to share text in instagram

### ISSUE THREAD

**Issue by ziqq** [fluttercommunity/plus_plugins#1294]
### What is your question?

I try to share text in instagram but in don't find the button instagram share. And how i can localize the package.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
You definitely didn't read the README.md because in it there's a section about Instagram and other Facebook apps

**Comment by ziqq** [comment]
> You definitely didn't read the README.md because in it there's a section about Instagram and other Facebook apps

OK, this only applies to sharing on Instagram, but what about localization?

**Comment by miquelbeltran** [comment]
I am not sure what you mean, is there any English text in the plugin? I wasn't aware of that, can you point where?

**Comment by ziqq** [comment]
> I am not sure what you mean, is there any English text in the plugin? I wasn't aware of that, can you point where?

No. I want localize to Russia text.

**Comment by miquelbeltran** [comment]
I don't understand your question, what do you want to localize exactly?
