### ISSUE TITLE
[Question]: Connectivity_plus doesn't recognize connected wifi network as wifi connected, is this expected?

### ISSUE THREAD

**Issue by ElegantCrab** [fluttercommunity/plus_plugins#1297]
### What is your question?

I'm using the package https://pub.dev/packages/wifi_iot to connect to a wifi network through flutter

However, I use the function **forceWifiUsage** to have connection to an API on my local network (that has no internet by the way) 

Whenever I connect to a network using this package **(WiFi_IoT)** and execute this function **forceWifiUsage**, I get ping and make requests to my local API without problems but connectivity_plus says there's no wifi connection.

On the Wi-Fi connected list on the phone, it says ''Connected through XXXX app''

Is this expected behaviour? Haven't found anything like it.

### Checklist before submitting a question

- [x] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [x] I tried running the example project

**Comment by miquelbeltran** [comment]
Which platform?

**Comment by ElegantCrab** [comment]
Android 11

**Comment by ElegantCrab** [comment]
I just noticed that whenever I connect to a Wi-Fi connection I get a prompt that talks about a temporary Wi-Fi connection

**Comment by miquelbeltran** [comment]
Not sure what you mean by a prompt.

Take a look at the Android implementation: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java#L26

The plugin uses the NetworkCapabilities from the Android ConnectivityManager and then returns the appropriate value up. There's not much more that the plugin does. If the Android OS is not reporting this connection as WiFi, then there isn't much we can do either.

**Comment by Debakripa** [comment]
@ElegantCrab @miquelbeltran how did you solve this issue? Thanks in advance

**Comment by JooYoo** [comment]
Any suggestion to detect iot-wifi connection?
