### ISSUE TITLE
[share_plus] temporary XFiles directory not cleaned

### ISSUE THREAD

**Issue by Coronon** [fluttercommunity/plus_plugins#1299]
### Platform

All

### Plugin

share_plus

### Version

`>= 4.50`

### Flutter SDK

Any

### Steps to reproduce

This is not really a ‘bug’ as in something is not working for the user, but as in undesirable behaviour.

Simply use `shareXFiles` without the files already having a path e.g. using `XFile.fromData` and experience your apps needed storage to increase by the filesize. While not having experienced this with share_plus, I used a similar approach for one of my apps lately. One would  expect that the OS cleans up temporary storage - but it really does not until absolutely necessary, easily getting an app to a few GB. 

The offending code lives in `Future<List<XFile>> _getFiles(List<XFile> files)`, which is also why we refrained from providing the user with a way to pass raw bytes instead of handling a file himself before version 4.5.0.

### Logs

```shell
n.a.
```

### Flutter Doctor

```shell
n.a.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Yeah, I pointed that up when the PR was submitted, but as far as I understand, the use of the cache/temp directory is correct:

https://pub.dev/documentation/path_provider/latest/path_provider/getTemporaryDirectory.html

I think documenting this and reminding devs to clean this directory up once in a while when using shareXFile without paths would be enough.
