### ISSUE TITLE
[Bug]: js package had updated to 0.6.5, but package_info_plus require 0.6.4

### ISSUE THREAD

**Issue by Riadloc** [fluttercommunity/plus_plugins#1312]
### Platform

Web

### Plugin

package_info_plus

### Version

3.0.1

### Flutter SDK

3.3.5

### Steps to reproduce

```
package_info_plus ^3.0.1 requires js 0.6.4.
So, because h2verse_app depends on both js ^0.6.5 and package_info_plus ^3.0.1, version solving failed.
```

### Logs

```shell
．．．
```

### Flutter Doctor

```shell
．．．
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
As suggested above you should override `js` dependency in your project. Read more here: https://docs.flutter.dev/development/packages-and-plugins/using-packages#conflict-resolution

The reported issue is not a bug.
