### ISSUE TITLE
[share_plus] Share in message with a file in any medium(Skype, WhatsApp,Slack, etc...)  Only the first time file does not attach after that file attached properly but again when restarting the app again the same first time not works then further it works.[Bug]: 

### ISSUE THREAD

**Issue by wrteam-vimal** [fluttercommunity/plus_plugins#1317]
### Platform

Android 12

### Plugin

share_plus

### Version

4.4.0

### Flutter SDK

Flutter 3.3.6 • channel stable • https://github.com/flutter/flutter.git Framework • revision 6928314d50 • 2022-10-25 16:34:41 -0400 Engine • revision 3ad69d7be3 Tools • Dart 2.18.2 • DevTools 2.15.0

### Steps to reproduce

Share in message with a file in any medium(Skype, WhatsApp,Slack, etc...)

Only the first time file does not attach after that file attached properly but again when restarting the app again the same first time not works then further it works.

### Code Sample

```dart
//Using XFile and shareXFile because shareFile deprecated in latest version 
XFile file = XFile(value);

await Share.shareXFiles([file],text: "${product.name}\n\n$shareMessage",subject: "Product share from app");
```

### Logs

```shell
[+1817 ms] D/CompatibilityChangeReporter(27348): Compat change id reported: 160794467; UID 10283; state: ENABLED
[ +138 ms] D/DecorView[](27348): onWindowFocusChanged hasWindowFocus false
[+7109 ms] D/DecorView[](27348): onWindowFocusChanged hasWindowFocus true
[+2023 ms] D/DecorView[](27348): onWindowFocusChanged hasWindowFocus false
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.6, on Ubuntu 22.04.1 LTS 5.15.0-52-generic,
    locale en_IN)
    • Flutter version 3.3.6 on channel stable at
      /home/ubuntu/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (7 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/ubuntu/Android/Sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • Java binary at: /snap/android-studio/124/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/124/android-studio
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • M2101K7BI (mobile) • adb-SWB6A6DUSKIR49NR-NBlbgn._adb-tls-connect._tcp • android-arm64  • Android 12 (API 31)
    • Linux (desktop)    • linux                                             • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-52-generic
    • Chrome (web)       • chrome                                            • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [x] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
> Only the first time file does not attach after that file attached properly but again when restarting the app again the same first time not works then further it works.

I don't understand what you mean. Can you write a step by step description of the bug?

**Comment by wrteam-vimal** [comment]
Only the first time file does not attach after that file attached properly but again when restarting the app again the same first time not works then further it works.

//Using XFile and shareXFile because shareFile deprecated in latest version 
XFile file = XFile(value);

await Share.shareXFiles([file],text: "${product.name}\n\n$shareMessage",subject: "Product share from app");


Reference Video - https://drive.google.com/file/d/11EIrd1qu-M4_mQfMQ2yjxczBqaUz-E-7/view?usp=share_link

**Comment by miquelbeltran** [comment]
I still can't understand you, can you do a step-by-step, like 1. Start app, 2. Select image. etc.

**Comment by wrteam-vimal** [comment]
1. 

> I still can't understand you, can you do a step-by-step, like 1. Start app, 2. Select image. etc.

1. Start app
2. Image file is in the server live
3. In the background download the image file using the image link
4. Set file in XFile 
5. initiate Share.shareXFile method
6. Trying to share on whatsapp 
7. Unable to fetch image only first time
8. Then go back again
9. repeat Steps number 3,4,5,6 in sequence 
10. Working (But only first time share not working)

Hope you get the proper steps that you required 

Thank you!

**Comment by miquelbeltran** [comment]
Thanks, that's better.

Many things could be failing here, for example, the downloaded file didn't finish downloading when you first shared the file, the App did not have permission to open the file, or maybe sharing with Whatsapp didn't work (this is explained in the README.md).

The logs you provided don't show any relevant error, so we cannot figure out the error you have. I would be good if you can plug your device to ADB and provide complete device logs showing the actual error.

**Comment by VocsyJay** [comment]
Hello brother can you share image in whatsApp in ios ?
