### ISSUE TITLE
[Request]: Sample rate for accelerometer and gyroscope

### ISSUE THREAD

**Issue by sikandernoori** [fluttercommunity/plus_plugins#1318]
### Plugin

sensors_plus

### Use case

Listening to accelerometer and gyroscope starts bombarding app with realtime data, there should be an option to limit sample rate per second.

### Proposal

I think it would be better if it's done on the native side, rather limiting event in dart side to get optimal performance.

**Comment by sikandernoori** [comment]
This would still cause performance degradation, native side will still be sending events through event channel, which in itself is computation overload. with debounce I will only be filtering / limiting source stream in dart side.

If we do it in the native side then we can avoid sending unwanted data from native side to dart side.

**Comment by miquelbeltran** [comment]
btw, which platform are you referring to exactly?

**Comment by sikandernoori** [comment]
IOS.

**Comment by miquelbeltran** [comment]
Do you have performance data that supports the idea of the degradation? I'd like to know how bad of an impact it actually does before approving any drastic changes. If you have made any measurements, please share them with us.

Another thing to keep in mind is that supporting a sample rate should also be back-ported to Android and Web, e.g. if we make it as an optional parameter or some sort of setting value. Luckily, this plugin does not have desktop support yet, so it is fewer platforms to support.
