### ISSUE TITLE
Add getSubnet() method to network_info_plus

### ISSUE THREAD

**Issue by myxiplx** [fluttercommunity/plus_plugins#132]
Would it be possible to add a getSubnet() feature please.  I'm using Flutter as the GUI to manage IOT devices and I really expected a network_info package to be able to provide both the IP address and subnet details.

This looks like a great set of packages, that's well thought out, and well maintained.  I'd really like to standardise on these, so if you could add this functionality sometime it would be very much appreciated :-)

**Comment by mhadaily** [comment]
check version ## 1.1.0

- Android, IOS: Adding IPv6 information
- Android, IOS: Adding gateway ip address information
- Android, IOS: Adding broadcast information
- Android, IOS: Adding subnet mask information
