### ISSUE TITLE
Suggestion to change from sha1 to sha2 or sha3, in the PackageInfoPlugin class.

### ISSUE THREAD

**Issue by ricardonostrum** [fluttercommunity/plus_plugins#1329]
### Plugin

package_info_plus

### Use case

Suggestion to change from sha1 to sha2 or sha3, in the PackageInfoPlugin class.

### Proposal

SHA-1 (Secure Hash Algorithm 1) is a cryptographic hash function that takes an input and produces a 160-bit hash value. As of 2005, SHA-1 was considered insecure, being formally banned by the NIST (National Institute of Standards and Technology) in 2011. Currently, attacks against SHA-1 hashes are considered trivial for adversaries with collection and processing power. of collision attacks. As such, NIST recommends removing the use of SHA-1 from products, replacing its use with hashes from the SHA-2 or SHA-3 families, which still
are considered cryptographically secure. It was identified that the informed application makes use of SHA-1 hashes, being susceptible to breach of confidentiality and data integrity.

References
• CWE
– CWE-327: Use of a Broken or Risky Cryptographic Algorithm

Recommendation
It is recommended that you change and implement a secure cryptographic hash algorithm, such as the SHA-2 and SHA-3 families.

More information
• OWASP - Testing for Weak Encryption
• What is a collision attack?

I look forward to hearing from you about the possibility of the change.

Ricardo Magno da Silva
Nostrum Consultoria e Projetos.

**Comment by miquelbeltran** [comment]
Where do we even use encryption?

**Comment by ricardonostrum** [comment]
Good Morning. Well, thank you very much for the extremely quick response from you.
This alert was generated by MobSF and I thought it prudent to inform them, I didn't do a deeper code analysis of the plugin, so I didn't come to that same conclusion, looking better at the class, I fully agree and we will put it on the false positive list.

Ricardo Magno da Silva
Nostrum Consulting and projects.
