### ISSUE TITLE
[Question]: Where is androidId on the latest version? [device_info_plus]

### ISSUE THREAD

**Issue by memishood** [fluttercommunity/plus_plugins#1341]
### What is your question?

I was able to get ```androidInfo.androidId``` in 3.2.3 version, it has been removed as I investigated. How can I get it in latest version?

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by ahmad-mukhlish** [comment]
I need the `androidId` too actually.. For the sake of UUID.. but when I see their changelogs.. I see this

![image](https://user-images.githubusercontent.com/26080886/203146310-1e28de6c-ef0b-4fe5-90e9-381142e6bc59.png)

**Comment by vbuberen** [comment]
It is moved to separate plugin for quite some time already and it is explicitly mentioned in changelogs: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/CHANGELOG.md#410
