### ISSUE TITLE
[Bug]: device_info_plus - iOS 16+ UIDevice.name api changed

### ISSUE THREAD

**Issue by codingiran** [fluttercommunity/plus_plugins#1342]
### Platform

iOS 16

### Plugin

device_info_plus

### Version

8.0.0

### Flutter SDK

3.3.8

### Steps to reproduce

After iOS16, Apple change UIDevice.name API, see https://developer.apple.com/documentation/uikit/uidevice/1620015-name
<img width="835" alt="image" src="https://user-images.githubusercontent.com/11780294/202960234-ff883585-5413-4b20-a493-768cd52a5c13.png">
iOS 16+, Apple enhances privacy control, UIDevice.name always return "iPhone", If need to fetch  user-assigned device name, please check this:https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_device-information_user-assigned-device-name

### Logs

```shell
ignore
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.3.8 on channel stable at
      /Users/codingiran/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (12 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/codingiran/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/codingiran/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode 14.1.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • Iran’s iPhone 14 Pro (mobile) • 00008120-0009648C023B401E • ios
      • iOS 16.1.1 20B101
    • macOS (desktop)               • macos                     • darwin-arm64
      • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)                  • chrome                    • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [x] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by noskova** [comment]
Looks like the issue is gone on Flutter SDK 3.3.9

**Comment by vbuberen** [comment]
> iOS 16+, Apple enhances privacy control, UIDevice.name always return "iPhone", If need to fetch user-assigned device name, please check https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_device-information_user-assigned-device-name

According to the doc provided in the link your project needs to have a proper entitlement added. It is not a bug of `device_info_plus`, but something to configure in the iOS part of the project.
