### ISSUE TITLE
[Question]: How to uniquely identify the mobile , i.e fingerprint for the mobile

### ISSUE THREAD

**Issue by mazen930** [fluttercommunity/plus_plugins#1344]
### What is your question?

 Does device info plus support getting IMEI or any thing that uniquely identify the mobile like serial number or so  

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
No, device info plus doesn't support such features. Both Google and Apple introduce some new privacy enhancements that close access to one of another value that might be used for unique identification of a user or device.

Here is an example of changes introduced in Android 10 to restrict access to serial, email, etc.: https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids

Here is another doc about best practises for Android identifiers to use: https://developer.android.com/training/articles/user-data-ids
