### ISSUE TITLE
[Bug]: Screenshot share to flutter app fails

### ISSUE THREAD

**Issue by rbarzel** [fluttercommunity/plus_plugins#1347]
### Platform

iOS 16.1.1

### Plugin

share_plus

### Version

6.3.0

### Flutter SDK

3.3.9

### Steps to reproduce

share_plus is working fine in my flutter app for images shared from Photos, Google Photos etc. It works both when the app is running, and when it's not. However, on iOS sharing from the screenshot-editing flow fails like this.

1. Take a screenshot
2. Click the thumbnail that pops up to edit the screenshot.
3. Click the share icon in the upper right corner.
4. Select your share_plus enabled flutter app.

**Expected**: Screenshot is sent to my flutter app.
**Actual**: A small dialog appears for a split second and then disappears. (see attached screen shot) Then you're back in the screenshot editing flow. My flutter app does not receive the screenshot image.

<img width="549" alt="Screenshot 2022-11-24 at 11 13 26 AM" src="https://user-images.githubusercontent.com/1355649/203852538-1ecbb250-f247-436d-b85d-a416bedbaf1f.png">

### Logs

```shell
no log output as the app is never opened in this sharing scenario
```

### Flutter Doctor

```shell
ronbarzel@POMac flutt_mpom_3 % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm (Rosetta), locale en-US)
    • Flutter version 3.3.9 on channel stable at /Users/ronbarzel/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ronbarzel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (1 available)
    • Ron’s iPhone X (mobile) • 00008020-001449022ED8002E • ios • iOS 16.1.1 20B101
    ! Error: Ron’s iPhone X is busy: Fetching debug symbols for Ron’s iPhone X. Xcode will continue when Ron’s iPhone X is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
It seems you are confusing the purpose of Share plus plugin. It allows your app to share files, not other apps share files with your app. So this issue isn' about Shape plus plugin.

**Comment by rbarzel** [comment]
Whoops, you're right, meant to file this issue for receive_sharing_intent.
