### ISSUE TITLE
[Question]: how to get gravity only of sensors?

### ISSUE THREAD

**Issue by onemission** [fluttercommunity/plus_plugins#1384]
### What is your question?

how to get gravity only of sensors?

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Didn't get what is your question is about. Could you explain it better?

If you need just one sensor data you can listen just one sensor data and check values only on the axis that you need.
