### ISSUE TITLE
[Bug]: onConnectivityChanged listener not detecting when changed wifi and debug on iOS Simulator

### ISSUE THREAD

**Issue by tour4x** [fluttercommunity/plus_plugins#1385]
### Platform

iOS 16.1

### Plugin

connectivity_plus

### Version

3.0.2

### Flutter SDK

3.3.2

### Steps to reproduce

1.Debug the app
3.change to another wifi
4.Debug the app > Connectivity().checkConnectivity() return ConnectivityResult.none

### Code Sample

```dart
var connectivityResult = await (Connectivity().checkConnectivity());
      if (connectivityResult == ConnectivityResult.none) {
        return;
      }
```

### Logs

```shell
No backticks or errors detected.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.2, on macOS 13.0.1 22A400 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Debakripa** [comment]
@tour4x please tell me how you solved this issue
