### ISSUE TITLE
[Question]: Why is asking for android.permission.REQUEST_INSTALL_PACKAGES

### ISSUE THREAD

**Issue by Idika-alph-atec-concept-limited** [fluttercommunity/plus_plugins#1410]
### What is your question?

Why is asking for android.permission.REQUEST_INSTALL_PACKAGES, below is the log from build/app/outputs/logs/manifest-merger-release-report.txt showing connectivity_plus is asking?

ADDED from [:connectivity_plus] C:\Users\idiknd\Desktop\ppk\prod\ppk\build\connectivity_plus\intermediates\merged_manifest\release\AndroidManifest.xml:9:5-79
MERGED from [com.google.android.gms:play-services-maps:18.0.2] C:\Users\idiknd\.gradle\caches\transforms-3\42e8e193afdde6a89d257fba9624cf99\transformed\jetified-play-services-maps-18.0.2\AndroidManifest.xml:23:5-79
MERGED from [com.google.android.gms:play-services-maps:18.0.2] C:\Users\idiknd\.gradle\caches\transforms-3\42e8e193afdde6a89d257fba9624cf99\transformed\jetified-play-services-maps-18.0.2\AndroidManifest.xml:23:5-79
	android:name
		ADDED from [:connectivity_plus] C:\Users\idiknd\Desktop\ppk\prod\ppk\build\connectivity_plus\intermediates\merged_manifest\release\AndroidManifest.xml:9:22-76
uses-permission#android.permission.REQUEST_INSTALL_PACKAGES

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
`connectivity_plus` doesn't use this permission as well as doesn't ask for such. The only permission package uses is `ACCESS_NETWORK_STATE`.

Logs you provided show that this permission is in `merged_manifest` - it means that this manifest is combined from dependencies that your project uses. It is one of other dependencies you have that have `REQUEST_INSTALL_PACKAGES` declared in its manifest.
