### ISSUE TITLE
[Bug]: connectivity_plus : Runner unexpectedly quit - DYLD 4 Symbol missing

### ISSUE THREAD

**Issue by mdmota** [fluttercommunity/plus_plugins#1411]
### Platform

iPhone 14 pro max simulator

### Plugin

connectivity_plus

### Version

3.0.2

### Flutter SDK

3.3.8

### Steps to reproduce

Whe run app:
Dialog report error shows:
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: AD92F83F-306A-4222-A478-EC9EC73C1CB3
CrashReporter Key:   A230AE61-5A6C-9636-564E-8F625792895C
Hardware Model:      Macmini7,1
Process:             Runner [47977]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/54B538A3-54F5-4C3C-BE56-221EF222F91D/data/Containers/Bundle/Application/53D1367E-8BB6-478C-945E-E0F0356DE7F5/Runner.app/Runner
Identifier:          xxxxxxxx
Version:             1.0.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [38314]
Coalition:           com.apple.CoreSimulator.SimDevice.54B538A3-54F5-4C3C-BE56-221EF222F91D [2517]
Responsible Process: SimulatorTrampoline [829]

Date/Time:           2022-12-19 14:19:19.1110 -0300
Launch Time:         2022-12-19 14:19:17.8771 -0300
OS Version:          macOS 12.6.2 (21G320)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: **DYLD 4 Symbol missing**
Symbol not found: **_OBJC_CLASS_$_Reachability**
Referenced from: <A11EFB57-9C39-37AF-AD54-B36736AABBBD> /Users/USER/Library/Developer/CoreSimulator/Devices/54B538A3-54F5-4C3C-BE56-221EF222F91D/data/Containers/Bundle/Application/53D1367E-8BB6-478C-945E-E0F0356DE7F5/Runner.app/Frameworks/connectivity.framework/connectivity
Expected in:     <863548CB-0CDF-30BB-B5E1-314783DFCC4A> /Users/USER/Library/Developer/CoreSimulator/Devices/54B538A3-54F5-4C3C-BE56-221EF222F91D/data/Containers/Bundle/Application/53D1367E-8BB6-478C-945E-E0F0356DE7F5/Runner.app/Frameworks/Reachability.framework/Reachability
(terminated at launch; ignore backtrace)

### Logs

```shell
Incident Identifier: AD92F83F-306A-4222-A478-EC9EC73C1CB3
CrashReporter Key:   A230AE61-5A6C-9636-564E-8F625792895C
Hardware Model:      Macmini7,1
Process:             Runner [47977]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/54B538A3-54F5-4C3C-BE56-221EF222F91D/data/Containers/Bundle/Application/53D1367E-8BB6-478C-945E-E0F0356DE7F5/Runner.app/Runner
Identifier:          xxxxxxxx
Version:             1.0.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [38314]
Coalition:           com.apple.CoreSimulator.SimDevice.54B538A3-54F5-4C3C-BE56-221EF222F91D [2517]
Responsible Process: SimulatorTrampoline [829]

Date/Time:           2022-12-19 14:19:19.1110 -0300
Launch Time:         2022-12-19 14:19:17.8771 -0300
OS Version:          macOS 12.6.2 (21G320)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: **DYLD 4 Symbol missing**
Symbol not found: **_OBJC_CLASS_$_Reachability**
Referenced from: <A11EFB57-9C39-37AF-AD54-B36736AABBBD> /Users/USER/Library/Developer/CoreSimulator/Devices/54B538A3-54F5-4C3C-BE56-221EF222F91D/data/Containers/Bundle/Application/53D1367E-8BB6-478C-945E-E0F0356DE7F5/Runner.app/Frameworks/connectivity.framework/connectivity
Expected in:     <863548CB-0CDF-30BB-B5E1-314783DFCC4A> /Users/USER/Library/Developer/CoreSimulator/Devices/54B538A3-54F5-4C3C-BE56-221EF222F91D/data/Containers/Bundle/Application/53D1367E-8BB6-478C-945E-E0F0356DE7F5/Runner.app/Frameworks/Reachability.framework/Reachability
(terminated at launch; ignore backtrace)
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6.2 21G320 darwin-x64, locale
    pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by 1076815296** [comment]
I also encounter this problem on all SDK versions

**Comment by 1076815296** [comment]
我找到原因了 将你项目的语言改为 swift 就可以解决这个问题

**Comment by it-hienvv** [comment]
> 1076815296

How to fix. Plz help me!

**Comment by mdmota** [comment]
I stopped using this plugin and handle the error by try catch in the service call
