### ISSUE TITLE
[Request]: add `flutter_blue_plus` to the list of community plugins

### ISSUE THREAD

**Issue by navaronbracke** [fluttercommunity/plus_plugins#1427]
### Plugin

flutter_blue_plus

### Use case

When working with Bluetooth Low Energy devices, someone will probably stumble upon either `flutter_blue` or `flutter_blue_plus`.

The original `flutter_blue` plugin is no longer actively maintained by the author, which led to the creation of `flutter_blue_plus`, which did get some updates over time.

However, that plugin is also leaning towards not being actively maintained anymore (unless the owner of flutter_blue_plus can prove me wrong).

### Proposal

I propose that someone contacts [boskokg](https://github.com/boskokg) so that `flutter_blue_plus` can be moved over to the community plugins.

This would enable more people to contribute to the plugin and avoids the problem where only one person would approve pull requests (which both flutter_blue and flutter_blue_plus are affected by)

@miquelbeltran wdyt?

**Comment by vbuberen** [comment]
Hi there. Thanks for you suggestion, but more correct request would be to add this plugin to `fluttercommunity` organisation. You can find the guide on how to do it here: https://github.com/fluttercommunity/transfer-guide

This repo is formed of plugins that were previously maintained by Google and were transferred to Flutter Community. 
Currently, we don't have plans to add more projects into this repo as it is solely for this specific set of packages.

**Comment by navaronbracke** [comment]
@vbuberen Thanks, I'll close this issue in favor of doing that instead.
