### ISSUE TITLE
[Question]: How can i check internet speed ?

### ISSUE THREAD

**Issue by RahulEncodework** [fluttercommunity/plus_plugins#1443]
### What is your question?

How can i check internet speed ?
* when my device connect with mobile network or wifi network but internet speed is low at this case i show toast internet 
 speed is low in my app but i not found internet speed.. 

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by RahulEncodework** [comment]
if our wifi not connected to device we manage to dialogbox for no internet connection but, when  wifi connected to device but internet speed is very low in this case how to message for user to low internet connection, please switch internet connectivity

**Comment by RahulEncodework** [comment]
Or can it possible to show internet speed (percentage) in our app..

**Comment by RahulEncodework** [comment]
>  What's is the situation ?
if our wifi not connected to device we manage to dialogbox for no internet connection but, when wifi connected to device but internet speed is very low in this case how to message for user to low internet connection, please switch internet connectivity

**Comment by vbuberen** [comment]
There is no such feature in Plus plugins, so can't help here
