### ISSUE TITLE
[Bug]: web plugin throws exception NoSuchMethodError: tried to call a non-function, such as null: 'this.share'

### ISSUE THREAD

**Issue by Sam-Guru-In-Training** [fluttercommunity/plus_plugins#1453]
### Platform

Chrome Web

### Plugin

share_plus

### Version

6.3.0

### Flutter SDK

 3.3.10

### Steps to reproduce

It doesn't want to share a picture from a specified directory on web. Additionally, the landing page for the plugin appears to give examples for deprecated Share.shareFiles. 

I couldn't get shareXFiles to share on Android from a specified directory and had to write the picture down to a temporary file first. That does not work on web, path provider isn't supported. The example given on the landing page of [pub.dev](https://pub.dev/packages/share_plus) claims you can just specify a directory for the image as I have done.

1. It would be great to have a full working example of how to share an image on Flutter web.
2. It would also be great to have an example of a fallback if the particular browser the op employs doesn't support sharing pictures. Or better have this done automatically - it just falls back to subject and text. I'm not sure falling back to downloading an image is that useful or intuitive.

I'm aware there was some chat about 'Well of course sharing static images doesn't work'. But so far as I can see that's what's proposed on pub.dev's landing page.

Apologies if this is entirely my ineptitude.

### Code Sample

```dart
try {
                        var path;
                        path = 'assets/slideshow/${presentLocation.pictureList[0]}';

                        await Share.shareXFiles([
                          XFile(path,
                              mimeType:
                                  "image/${presentLocation.pictureList[0].split(".")[1]}",
                              name: presentLocation.name)
                        ],
                                subject: presentLocation.name +
                                    presentLocation.emoji,
                                text: shareStr,
                                sharePositionOrigin:
                                    box!.localToGlobal(Offset.zero) & box.size)
                            .then((shareResult) async => {
                                  if (shareResult.status ==
                                      ShareResultStatus.success)
                                    {
                                      await MyApp.analytics.logShare(
                                          contentType: "URL shared",
                                          itemId: presentLocation.name,
                                          method: "with image")
                                    }
                                });
                      } catch (exception) {
                        print(
                            "Tried to share with image, hit exception: $exception");
}
```

### Logs

```shell
Tried to share with image, hit exception: NoSuchMethodError: tried to call a non-function, such as null: 'this.share'
```

### Flutter Doctor

```shell
Tried to share with image, hit exception: NoSuchMethodError: tried to call a non-function, such as null: 'this.share'
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by dev-weenit** [comment]
I am facing a similar issue on web platform.

`share_plus: 7.2.1` 

I am creating Xfile from data
```
return XFile.fromData(
                  fileEntity.bytes!,
                  mimeType: fileEntity.mimeType,
                  length: fileEntity.length,
                  lastModified: fileEntity.lastModifiedDate,
                  name: fileEntity.fileName,
                );
```

`Future<ShareResult> shareXFiles` from `share_plus_web.dart` is called. Here there the file is not empty as bytes length of 386353. The execution fails on `await _navigator.share`
