### ISSUE TITLE
[Bug]: iPad 7th, 8th, 9th generation - not open share window properly

### ISSUE THREAD

**Issue by Aljnk** [fluttercommunity/plus_plugins#1466]
### Platform

iPad 7th, 8th, 9th generation

### Plugin

share_plus

### Version

6.3.0

### Flutter SDK

3.3.10

### Steps to reproduce

Full code is here: [share.zip](https://github.com/fluttercommunity/plus_plugins/files/10456440/share.zip)

Tests:

![1](https://user-images.githubusercontent.com/11256478/213444108-aefdcc6a-0481-4e75-ab66-61621a1f857e.jpg)
![2](https://user-images.githubusercontent.com/11256478/213444116-70fcc69b-0271-4fa0-952f-aa40e4d62181.png)
![3](https://user-images.githubusercontent.com/11256478/213444118-03169224-59b6-4bce-a6cf-57b5e69bfd65.jpg)
![4](https://user-images.githubusercontent.com/11256478/213444122-57a86527-0e82-4582-bedf-70e122831316.jpg)

### Code Sample

```dart
Full code see above.
```

### Logs

```shell
Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/avk/Documents/App/share/.dart_tool/flutter_build/dart_plugin_registrant.dart}
[  +49 ms] Found plugin path_provider at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.11/
[   +1 ms] Found plugin path_provider_android at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.22/
[   +1 ms] Found plugin path_provider_ios at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.11/
[   +1 ms] Found plugin path_provider_linux at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.7/
[   +2 ms] Found plugin path_provider_macos at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.7/
[   +2 ms] Found plugin path_provider_windows at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.3/
[   +6 ms] Found plugin share_plus at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-6.3.0/
[  +12 ms] Found plugin url_launcher_linux at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[   +3 ms] Found plugin url_launcher_web at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.13/
[   +1 ms] Found plugin url_launcher_windows at /Users/avk/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +18 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[        ] complete
[        ] Performing hot reload...
[  +24 ms] Scanned through 541 files in 12ms
[        ] Syncing files to device iPad (9th generation)...
[        ] Compiling dart to kernel with 1 updated files
[        ] Processing bundle.
[        ] <- recompile package:share/main.dart d4a49153-7e64-419d-ac1e-d21af1e8e9ac
[        ] file:///Users/avk/Documents/App/share/.dart_tool/flutter_build/dart_plugin_registrant.dart
[        ] <- d4a49153-7e64-419d-ac1e-d21af1e8e9ac
[        ] Bundle processing done.
[  +81 ms] Updating files.
[   +3 ms] DevFS: Sync finished
[        ] Syncing files to device iPad (9th generation)... (completed in 88ms)
[        ] Synced 0.0MB.
[ +107 ms] <- accept
[   +1 ms] reloaded 1 of 878 libraries
[  +21 ms] Reassembling application
[ +102 ms] Hot reload performed in 333ms.
[        ] Performing hot reload... (completed in 347ms)
[        ] Reloaded 1 of 878 libraries in 464ms (compile: 82 ms, reload: 108 ms, reassemble: 121 ms).
[+18982 ms] flutter: Offset(0.0, 0.0)
[   +1 ms] flutter: Size(810.0, 1080.0)
```

### Flutter Doctor

```shell
flutter doctor -v    
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.4 21F79 darwin-x64, locale en-LT)
    • Flutter version 3.3.10 on channel stable at /Users/avk/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/avk/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (4 available)
    • iPad (Alexander) (mobile)      • 71fdbe125931800ceb466abd5d4f07d70b2c8879 • ios            • iOS 12.5.6 16H71
    • iPad (9th generation) (mobile) • FF2F7127-D88B-4DD6-A568-07314D6499DF     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (simulator)
    • macOS (desktop)                • macos                                    • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)                   • chrome                                   • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Aljnk** [comment]
Try:
sharePositionOrigin: const Rect.fromLTRB(0.0, 0.0, 810.0, 1080.0),
-> same result.

But
sharePositionOrigin: const Rect.fromLTRB(0.0, 0.0, 700.0, 970.0),
-> work.
![1](https://user-images.githubusercontent.com/11256478/213470985-68da6328-e161-480d-baea-b9c30cac86c2.jpg)


Or this one:
sharePositionOrigin:Rect.fromLTRB(0,0,box.size.width/2,box.size.height/2),
-> works too.
![2](https://user-images.githubusercontent.com/11256478/213470969-e7b71fd1-3f39-4581-9ff4-7034d706a29f.jpg)

**Comment by Aljnk** [comment]
Try this:
`sharePositionOrigin: const Rect.fromLTRB(0.0, 0.0,box.size.width*0.9,box.size.height*0.9),`
-> result:
![3](https://user-images.githubusercontent.com/11256478/213473487-493d302e-97bc-41d8-8a5a-29ca8e0a388d.jpg)

**Comment by nimeacuerdo** [comment]
> Try this: `sharePositionOrigin: const Rect.fromLTRB(0.0, 0.0,box.size.width*0.9,box.size.height*0.9),` -> result: ![3](https://user-images.githubusercontent.com/11256478/213473487-493d302e-97bc-41d8-8a5a-29ca8e0a388d.jpg)

This saved the day for me, thanks!

**Comment by TheFabbiusCorp** [comment]
I'm using this workaround to avoid hardcoding many values since one can have several iPad screen sizes.

```Dart
final Rect position;
if (box.size.width > 442.0) {
  position = Rect.fromLTRB(0, box.size.height - 1, box.size.width, box.size.height);
} else {
  position = box.localToGlobal(Offset.zero) & box.size;
}

await Share.share(..., sharePositionOrigin: position);
```

The `442.0` is the only hardcoded value in this code block. It refers to the largest size for which the dialog can pop up from the bottom (as it happens on iPhones - note that the current maximum iPhone width is less than 422 pts, so, as of today, this workaround will have no drawsides on iPhones).

**Explanation**
The `if` condition separates the `box.localToGlobal(Offset.zero) & box.size` solution, which shows a dialog (modal sheet) from the bottom and it works fine on iPhones, from `Rect.fromLTRB(0, box.size.height - 1, box.size.width, box.size.height)`, which shows the popup (not a dialog) on the bottom center of the screen and works on devices whose screen width is greater than 442 (this also includes resizing the app window while using the iPad State Manager feature).

**Side notes**
I've noticed that if `Rect.fromLTRB(0, box.size.height, box.size.width, box.size.height);` an exception is thrown, while if `Rect.fromLTRB(0, 0, box.size.width, box.size.height);` there is the same behavior of `box.size` (as shown by @Aljnk).

**Comment by lcw99** [comment]
sharePositionOrigin need bounding box of object to be shared in global position. itemKeyList[index] in following code is global key of list item.
```
var box = itemKeyList[index].currentContext!.findRenderObject()!;
Share.share(message['content'], sharePositionOrigin: box!.localToGlobal(box.paintBounds.topLeft) & box.size);
```

**Comment by v-pavlovskyi** [comment]
How can I remove tail at the bottom of dialog?![image](https://github.com/fluttercommunity/plus_plugins/assets/87654623/07dc337f-3da0-425c-97c8-85073ea3ac7c)
