### ISSUE TITLE
[Request]: Support ARM Simulator

### ISSUE THREAD

**Issue by spkersten** [fluttercommunity/plus_plugins#1467]
### Plugin

connectivity_plus, device_info_plus, share_plus

### Use case

Currently, apps using `connectivity_plus` (or any other plugin from this repo) can't be build for ARM Simulators (on ARM Macs) because it explicitly requires only x86_64. For example:
https://github.com/fluttercommunity/plus_plugins/blob/f0158c7a167c329e0e454fd086c2d6af8f26ea34/packages/connectivity_plus/connectivity_plus/ios/connectivity_plus.podspec#L23

So Simulator has to run under Rosetta which is slower can running natively. `VALID_ARCHS` seems to be deprecated in favour of `EXCLUDED_ARCHS` (e.g., to exclude i863).

### Proposal

Support ARM Simulators by using `EXCLUDED_ARCHS`.

**Comment by vbuberen** [comment]
Thanks for reporting. 

Opened PRs to fix it. Unfortunately, I don't know the historical reasons why the set of architectures was limited, but don't think that it still needed.

**Comment by nohli** [comment]
@spkersten I can't reproduce it with the latest Flutter version, seems to build fine on Apple silicon.

Do you still encounter this issue?
If yes, or if you use an older Flutter version where you encounter this issue -> is the error fixed with the PR branch?

**Comment by spkersten** [comment]
Judging from the linked PRs the issue should be fixed.
