### ISSUE TITLE
[Question]: Configuring sampling rate and events sync

### ISSUE THREAD

**Issue by adrianAzoitei** [fluttercommunity/plus_plugins#1473]
### What is your question?

1. Sampling rate.
I saw a few issues from the community about sampling rate, but didn't reach a definitive answer on how to _control_ sampling rate. Can you shed a bit of light on that? I'm happy to contribute in any documentation based on your answer!

2. Events sync
I see we get different events for accelerometer, magnetometer etc. Does that mean the events are off-sync? In other words, this record would be considered invalid, right?

| timestamp | acc_x | acc_y | acc_z | mag_x | mag_y | mag_z | ... |
|-----------|-------|-------|-------|-------|-------|-------|-----|
| 1      | ...   | ...   | ...   | ...   | ...   | ...   | ... |
| 2      | ...   | ...   | ...   | ...   | ...   | ...   | ... |
| 3      | ...   | ...   | ...   | ...   | ...   | ...   | ... |

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by itdevwu** [comment]
I currently apply interpolation to data of those sensors.

Allowing configure sampling rate will help a lot.

**Comment by athenawisdoms** [comment]
Did you manage to solve the problem?
