### ISSUE TITLE
[Question]: share_plus plugin not showing app icon when pops up

### ISSUE THREAD

**Issue by MerNat** [fluttercommunity/plus_plugins#1475]
### What is your question?

I'm using share_plus plugin for Flutter and I've noticed it's not showing the app icon (with name) when it pops up the dialog for sharing.

It doesn't also mention about the icon with the name in the documentation.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by inc16sec** [comment]
Here also. Not showing the Icon nor the name on both Android and iOS.

**Comment by MerNat** [comment]
Commenting for this issue not to be closed.

**Comment by ramakrishna-chimp** [comment]
I'm also fasing the same. There is no options set custom Icon.

**Comment by 020996** [comment]
I also have the same problem, have you found a solution?

**Comment by postflow** [comment]
Same issue on IOS. Is there any update?

**Comment by miquelbeltran** [comment]
Please create a proper bug report with the necessary information (detailed step by step, code example, logs, etc.), otherwise it is impossible to answer this question.

**Comment by MilkBiscuit** [comment]
If you guys are talking about this App icon not showing correctly.
The issue only exists on the simulator, I tried to release an internal version and worked fine on the real device.

![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-01 at 21 35 44](https://github.com/user-attachments/assets/91432d96-8c06-45a2-bd53-f78fd7fb9651)

**Comment by MerNat** [comment]
> If you guys are talking about this App icon not showing correctly. The issue only exists **on the simulator**, I tried releasing an internal version and it worked fine on the real device.
> 
> ![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-01 at 21 35 44](https://private-user-images.githubusercontent.com/20746964/372386601-719554e4-e070-4562-8c26-3f8a90f253b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDcxMjMsIm5iZiI6MTcyODMwNjgyMywicGF0aCI6Ii8yMDc0Njk2NC8zNzIzODY2MDEtNzE5NTU0ZTQtZTA3MC00NTYyLThjMjYtM2Y4YTkwZjI1M2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEzMTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NmQ0NDU1ZjA4YjVmNDU3M2UzNDZlMGY4NTljMzRhM2ExOWM2ZjZiZTcxOGI5Zjc5YzVmZmE2MGFhZmNlZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2C7KVEO0wMTRkRPuBmT9KNspqRHWTSb3HxP9vhgsrN4)

It's still empty icon on a real app in the phone as well. Strangely it's only in android but not in ios.
