### ISSUE TITLE
[Bug]: share_plus.dart file doesn't import

### ISSUE THREAD

**Issue by Digital-Assist** [fluttercommunity/plus_plugins#1476]
### Platform

10

### Plugin

share_plus

### Version

6.3.0

### Flutter SDK

3.3.3

### Steps to reproduce

import 'package:share_plus/share_plus.dart';

whenever I try to import the package, it shows an error saying the **PACKAGE FILE DOESN'T EXIST**. 

### Logs

```shell
no significant error found in logs
```

### Flutter Doctor

```shell
no significant error found here
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by tolly765** [comment]
Same issue on my end. Trying to import the share_plus package after running `flutter pub add share_plus` and then adding `import 'package:share_plus/share_plus.dart';` to the top of my dart file results in this appearing in VScode:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/9297773/217601749-78c8f421-4908-4762-82f9-f7f9f99f79f8.png">

Part of pubspec.yaml:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/9297773/217602107-84bd4af5-0ba9-4b1d-b4af-9889d20e769d.png">

Plugin
share_plus

Version
6.3.0

Flutter SDK
3.7.1
