### ISSUE TITLE
[Bug]: Nullable struct fields in code

### ISSUE THREAD

**Issue by dcharkes** [fluttercommunity/plus_plugins#1525]
### Platform

all

### Plugin

package_info_plus, possibly more

### Version

latest

### Flutter SDK

master

### Steps to reproduce

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20new_gallery__crane_perf/6462/overview

### Code Sample

```dart
class _LANGANDCODEPAGE extends Struct {
  @Uint16()
  external int? wLanguage;

  @Uint16()
  external int? wCodePage;
}
```

should be

```dart
class _LANGANDCODEPAGE extends Struct {
  @Uint16()
  external int wLanguage;

  @Uint16()
  external int wCodePage;
}
```

### Logs

```shell
-
```

### Flutter Doctor

```shell
-
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by mhadaily** [comment]
Fixed https://pub.dev/packages/package_info_plus/versions/3.0.3
