### ISSUE TITLE
[Question]: Converting Java codes to Kotlin

### ISSUE THREAD

**Issue by TheFinestArtist** [fluttercommunity/plus_plugins#1528]
### What is your question?

Hi community folks and managers,

Would you accept pull request if I convert Java codes into Kotlin? I am thinking of doing this gradually file by file or sometimes the whole package.

Thank you.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by TheFinestArtist** [comment]
I wanted to check this with you before I start the contribution.

**Comment by vbuberen** [comment]
Hello there. Such migration is something that I am personally working on when have time. I would like to finish it for all plugins myself. Thanks for suggestion, though.

**Comment by TheFinestArtist** [comment]
Hi @vbuberen 

I wonder if you still would like to work on the conversion?
I can do this real quick but safely if you let me.

Thanks.

**Comment by vbuberen** [comment]
Thanks for reaching out.

Sure, would be great. It felt so low in my priority list that I forgot about plans to migrate completely. Feel free to grab it. The only request is to not put both conversions into one PR, but separate, so it is easier to review and generate changelogs.

**Comment by TheFinestArtist** [comment]
@vbuberen I just created the first pull request. 

Please let me know whether this looks good start and what is missing.

I think it would be safer if you create a branch for this conversion. Would you be possible to create a branch?
