### ISSUE TITLE
[Request]: How i can send pdf with AndroidIntent?

### ISSUE THREAD

**Issue by hopheylalaley84** [fluttercommunity/plus_plugins#1539]
### Plugin

 AndroidIntent

### Use case

How i can send pdf with AndroidIntent?

### Proposal

How i can send pdf with AndroidIntent?

**Comment by vbuberen** [comment]
You need share_plus for this purpose.
https://stackoverflow.com/questions/71509815/flutter-how-to-share-pdf-files
