### ISSUE TITLE
[Request]: Use the `XFile.name` as the shared file name

### ISSUE THREAD

**Issue by josephelliot-wk** [fluttercommunity/plus_plugins#1548]
### Plugin

share_plus

### Use case

Our app lets users open files (usually PDFs), and some of these files have special characters that don't play nicely with temp-file paths.

For example, `My First / Last File.pdf` causes an error when writing to temp storage.

To combat this, you need to sanitize the file name to play nicely with the native file system. But, when `share_plus` shares this file (via [Share.shareXFiles](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart#L142)), it uses the file name from the path instead of the `XFile`'s `name` property.

According to the [XFile documentation](https://github.com/flutter/packages/blob/main/packages/cross_file/lib/src/types/interface.dart#L21), `name` is intended to be used for this exact scenario.

### Proposal

I propose that the function `Share.shareXFiles` utilizes `XFile.name` for the file name, if available. If not available, then default to the path file name.

**Comment by lukasnevosad** [comment]
I second to this. I am creating the file with `XFile.fromData()` and this is the only option for me to have a user friendly file name.

**Comment by intraector** [comment]
Same here. Getting image from web without any file extension causes the share with .BIN

**Comment by Boucaa** [comment]
Is there at least any workaround for this currently?

**Comment by wildsurfer** [comment]
same issue

**Comment by DieGlueckswurst** [comment]
Any updates on this ?

**Comment by IshanBaliyan** [comment]
Same here, seems like the bug still isnt fixed

**Comment by intraector** [comment]
Please fix this

**Comment by adimshev** [comment]
any updates?

**Comment by erighet** [comment]
Same request from me, now Share.shareXFiles causes files to have uuid like file name

**Comment by bytepoets-jhe** [comment]
Same problem here

**Comment by nidalshehab** [comment]
it  would be better to use file instead of XFile.fromData, this way you can name the file and delete it after sharing to keep the temporary directory clean, here is a work around:

```
Future<File> writeFile(List<int>? excel, String fileName) async {
    final directory = await getApplicationDocumentsDirectory();
    final path = directory.path;
    final file = File('$path/$fileName');
    return file.writeAsBytes(excel!);
  }
```
  if it's an exported excel file:
 ```
 List<int>? excel =  exportToExcel(); 
  String fileName = 'example.xlsx'; // Desired file name
  File file = await writeFile(excel, fileName);
  await Share.shareXFiles([XFile(file.path)]);
```

**Comment by LBYPatrick** [comment]
Same here! And I don't like the idea of writing file into persistent storage then read from it...Why bother the round trip? BTW ``XFile`` works flawlessly on macOS and iPhone for some reason but not on Android and Chrome?! Come on Google u need to take care of your own children as well!

**Comment by miquelbeltran** [comment]
> Come on Google u need to take care of your own children as well!

Not sure who is that referring to, but this is a project run by volunteers, and doesn't belong to Google.

Anyway, these types of comments are unprofessional and go against of code of conduct, so please do not use them in this project.

**Comment by LBYPatrick** [comment]
OK, I have removed that piece of the comment. With that said, I believe the Android implementation for ``XFile.fromData`` should also respect the filename and extension supplied by the user instead of generating a UUID-like filename along with a "reconstructed" filename that, If I have to guess, is based on the interpreted result of the MIME type of the real filename. This is technically fine, but ``xxxxx.jpeg`` will be matched to ``image/jpe`` by the ``mime`` package and the generated filename might have an extension of ``.jpe``, which has all kinds of compatibility issues with the platforms that were designed to handle ``.jpeg`` and ``.jpg``. 

In this case, if the shared file on Android is of extension ``.jpe``, then in some Android Distributions (not sure about Google Pixel, but did run into this issue on Xiaomi's MIUI), image / SMS apps might fail to recognize that it's an image and thus will not show up in the share menu. 

When I got time, I will definitely open a PR to address this issue!

**Comment by miquelbeltran** [comment]
> `xxxxx.jpeg` will be matched to `image/jpe` by the `mime` package 

I see, this is reported here: https://github.com/dart-lang/mime/issues/55 at least the PR is getting some movement, I have subscribed to updates. 

If anyone tries to do a `dependency_override` to the fixed branch, let me know how it went!

Once `mime` is updated, we will update the dependency too.

**Comment by LBYPatrick** [comment]
Ah, I mean I came up with a workaround that respects the extension from user's filename and then fallback to the MIME way in case it fails.

By the way, may I ask why was the filename discarded and UUID was used instead？Is it for collision prevention or ASCII-compliance for some legacy issues?

**Comment by miquelbeltran** [comment]
> By the way, may I ask why was the filename discarded and UUID was used instead？Is it for collision prevention or ASCII-compliance because of some legacy issues that I am not aware of?

I don't remember, sorry. Maybe the git log or the original pr have a clue.

**Comment by miquelbeltran** [comment]
Should be closed by #2713 pending to be released.

Thanks a lot @LBYPatrick for the contribution!

**Comment by LBYPatrick** [comment]
...Haha you are welcome! Though, I have noticed that our test cases do not contain proper tests for simulating the case where we intentionally tamper the path but set ``XFile.name`` and ``XFile.mimeType`` properly. In other words, my code might not be well covered by the test cases...I will follow up with another PR to see if I can pull it off!

**Comment by LBYPatrick** [comment]
Unfortunately I am not familiar with the testing pipeline so I am having a hard time writing such test. With that said, I noticed that ``getTemporaryDirectory()`` is not available at all under the test environment, so we cannot direct test it anyway:

<img width="1203" alt="image" src="https://github.com/fluttercommunity/plus_plugins/assets/23201539/fc508223-2696-4563-91f8-980730133bcb">

I thought about exposing the ``tempRoot`` variable for us to dictate where temporary files should go solely for testing purposes, but doing so will also expose this variable to the users, which I don't know if this will confuse the users or allow them to do things we do not expect to (i.e. saving temporary files to some invalid path). Or do you think there's another way we can simulate this case and somehow extract the intermediate outputs of ``_getFile`` or ``_getFiles``? They are package private methods and are guarded behind the user-facing share methods, and I am just...not sure about it.

**Comment by ibrahimtelman** [comment]
There is an issue with the raw data usage. The Cross file package doesn't return the name parameter when using 'XFile.fromData'. Because of that, this issue should be open.

**Comment by Core121** [comment]
Agreed with @ibrahimtelman that raw data names do not work still

**Comment by Nico04** [comment]
Same issue here, name parameter is ignored when using 'XFile.fromData'

**Comment by frieder-audriga** [comment]
cross_file ignores filename and has documented it as such, see [cross_file/lib/src/types/io.dart:21](https://github.com/andreacioni/packages/blob/85aa45c5230893e769232d1ab07854cb5e6a741b/packages/cross_file/lib/src/types/io.dart#L21)

See also https://github.com/flutter/flutter/issues/147361#issuecomment-2076724612 and https://github.com/flutter/packages/pull/4416

**Comment by frieder-audriga** [comment]
I have created an issue to document this better: https://github.com/fluttercommunity/plus_plugins/issues/3032

In the mean time you can share a file with your custom filename by doing something like this
```dart
         var filename = 'myFileName.extension';
         String content = 'Hello Share';


          var tempRoot = (await getTemporaryDirectory()).path;
          final tempSubfolderPath = "$tempRoot/${const Uuid().v4()}";
          await Directory(tempSubfolderPath).create(recursive: true);

          final path = "$tempSubfolderPath/$filename";

          await File(path).writeAsString(content);  // alternatively use writeAsBytes to write bytes

          var xFile =  XFile(path);
          Share.shareXFiles([xFile]);
```

**Comment by andrescastane** [comment]
For all those who are asking why the name parameter does not work, for it to work and be integrated into the file there is a path parameter in which you must put the route and it is already set in name and path. It happens that putting only the name in the constructor does not create the name in the xfile, but doing it in the path does.

// Instead of putting the name  
`final XFile myFile = XFile.fromData(bytes, name: "tempfile-1.png");`

// Put the path 
`final XFile myFile = XFile.fromData(bytes, path: "tempfile-1.png");`
