### ISSUE TITLE
Is share_plus available for win32 ^4.1.1in the latest master flutter?

### ISSUE THREAD

**Issue by andromeda-center** [fluttercommunity/plus_plugins#1549]
### What is your question?

After building the project it fails and says:
Because it depends on share_plus ^6.3.1 which depends on win32 ^3.0.0, so win32 ^3.0.0 is required.
So, because Project depends on win32 ^4.1.1, version solving failed.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
`6.3.1` has older win32 in dependencies, but nothing blocks you from using [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) to make your project work with latest win32

**Comment by asaarnak** [comment]
@vbuberen file_picker update is blocked when using share_plus
```
Because file_picker >=5.2.11 depends on win32 ^4.1.3 and share_plus 6.3.2 depends on win32 ^3.0.0, file_picker >=5.2.11 is incompatible with share_plus 6.3.2.
```

**Comment by vbuberen** [comment]
Read my comment above and use dependency overrides till share_plus updates to latest dependencies as well.
