### ISSUE TITLE
[Bug]: {WifiIPv4: 172.19.0.1, WifiBroadcast: null}

### ISSUE THREAD

**Issue by jijkbird** [fluttercommunity/plus_plugins#1553]
### Platform

android 12

### Plugin

network_info_plus: ^3.0.2

### Version

network_info_plus: ^3.0.2

### Flutter SDK

3.7

### Steps to reproduce

 try {
      wifiIPv4 = await _networkInfo.getWifiIP();
    } on PlatformException catch (e) {
      print('Failed to get Wifi IPv4');
      wifiIPv4 = 'Failed to get Wifi IPv4';
    }

    try {
      if (!Platform.isWindows) {
        wifiBroadcast = await _networkInfo.getWifiBroadcast();
      }
    } on PlatformException catch (e) {
      print('Failed to get Wifi broadcast');
      wifiBroadcast = 'Failed to get Wifi broadcast';
    }

    connectionStatus = {
      'WifiIPv4': wifiIPv4,
      'WifiBroadcast': wifiBroadcast,
    };

### Logs

```shell
I/flutter ( 4308): {WifiIPv4: 172.19.0.1, WifiBroadcast: null}
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by jijkbird** [comment]
only android is err,ios is ok

**Comment by jijkbird** [comment]
My mobile phone turned on the agent and turned it off

**Comment by jasaw** [comment]
I'm seeing null broadcast address on Android 14, Samsung A05S, model SM-A057F.

**Comment by miquelbeltran** [comment]
My only idea for you to test is to run the example project from Android Studio and set a breakpoint at the `getBroadcastIp` method, and see what fails.

The plugin is also ignoring exceptions instead of returning the error, so that is something that should be addressed nevertheless.

**Comment by jasaw** [comment]
This is on a customer phone, so unfortunately I can't debug on that phone. I can't reproduce the problem on my Android 14 phone.
