### ISSUE TITLE
[Bug]: connectivity_plus ^3.0.3 and device_info_plus ^8.1.0, version solving failed.

### ISSUE THREAD

**Issue by adem74** [fluttercommunity/plus_plugins#1566]
### Platform

--

### Plugin

connectivity_plus

### Version

3.0.3

### Flutter SDK

3.3.10

### Steps to reproduce

Running "flutter pub get" in ss...                    
Because no versions of device_info_plus match >8.1.0 <9.0.0 and device_info_plus 8.1.0 depends on ffi ^2.0.1, device_info_plus ^8.1.0 requires ffi ^2.0.1.
Because nm >=0.5.0 depends on dbus ^0.7.0 and dbus >=0.5.5 <0.7.5 depends on ffi ^1.1.2, nm >=0.5.0 requires ffi ^1.1.2 or dbus ^0.7.5.
Thus, if device_info_plus ^8.1.0 and nm >=0.5.0 then dbus ^0.7.5.
And because connectivity_plus >=3.0.0 depends on nm ^0.5.0 and dbus >=0.7.4 depends on xml ^6.1.0, if device_info_plus ^8.1.0 and connectivity_plus >=3.0.0 then xml ^6.1.0.
And because flutter_html 2.2.1 depends on flutter_svg >=0.22.0 <1.0.0 which depends on xml ^5.0.0, one of device_info_plus ^8.1.0 or connectivity_plus >=3.0.0 or flutter_html 2.2.1 must be false.
And because no versions of flutter_html match >2.2.1 <3.0.0 and ss depends on flutter_html ^2.2.1, device_info_plus ^8.1.0 is incompatible with connectivity_plus >=3.0.0.
So, because ss depends on both connectivity_plus ^3.0.3 and device_info_plus ^8.1.0, version solving failed.
pub get failed (1; So, because ss depends on both connectivity_plus ^3.0.3 and device_info_plus ^8.1.0, version solving failed.)

### Logs

```shell
--
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1265], locale en-GB)
    • Flutter version 3.3.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\adam\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.75.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
     

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
You also have issues with version resolution for `flutter_html`.

Till all 3 plugins have same dependencies requirements you can override problematic dependencies: 
https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by adem74** [comment]
If someone faced with this issue, All i needed was update flutter version.

**Comment by vbuberen** [comment]
> All i needed was update flutter version.

It can't be the solution for the log that you shared. If it helped you it means that there were some pub cache issues there and it occasionally solved the issue.

**Comment by adem74** [comment]
I do not know, I have tried "flutter clean" "flutter pub get" many times before I posted here. Is there a command for clean cache of pub? It would be nice to know for solving up coming problems. 
Thank you.
