### ISSUE TITLE
[share_plus] Sheet does not appear on iPadOS devices

### ISSUE THREAD

**Issue by JagandeepBrar** [fluttercommunity/plus_plugins#158]
## System info

Issue occurs on: iOS (specifically iPadOS)
Plugin name: share_plus
Plugin version: 1.2.0
Flutter doctor output: 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on macOS 11.3 20E5172i darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)
```

## Steps to Reproduce

Attempt to share a file or string using `share.shareFiles([path]` or `share.share('text')` respectively. Nothing occurs on an iPadOS device. Tested on both a simulator and a physical device, both using Flutter stable and beta channels.

The same code executes and functions perfectly on both iPhone and Android devices, it is specifically for iPadOS devices that it does not work.

## Logs

There are no logs or errors that occur. Attached a `.catch((error, stack) {})` never executes, and attaching a `.then((_) {})` does, which means it believes it executed correctly.

## Example Code Snippet

```dart
if(file.existsSync()) await Share.shareFiles([file.path]);
```

With the above getting a file from the temporary directory. A more complete one that dumps a string to the temp directory then shares that file:

```dart
Future<void> exportStringToShareSheet(String name, String data) async {
        Directory tempDirectory = await getTemporaryDirectory();
        File file = File('${tempDirectory.path}/$name');
        file?.writeAsStringSync(data);
        if(file?.existsSync() ?? false) await Share.shareFiles([file.path]).catchError((error) => print(error));
}
```

**Comment by philiplindberg** [comment]
I'm seeing the same thing in my app. Share sheet works fine on iOS devices but not on iPadOS.

**Comment by JagandeepBrar** [comment]
I was able to solve this problem by ensuring I set `sharePositionOrigin` in the share call.

```dart
final RenderBox box = context.findRenderObject();
File file = File(path);
if(file.existsSync()) await Share.shareFiles(
    [path],
    sharePositionOrigin: box.localToGlobal(Offset.zero) & box.size,
);
```
