### ISSUE TITLE
分享pdf文件

### ISSUE THREAD

**Issue by qjb2404** [fluttercommunity/plus_plugins#1588]
### What is your question?

华为鸿蒙系统分享不了图片，文件，有对应的解决办法没

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Would ask you to use English language for your question

**Comment by qjb2404** [comment]
Huawei HarmonyOS2.0 cannot share pictures and files. Is there any solution? "The direct share function cannot be used" is displayed.
