### ISSUE TITLE
Go though all published packages and see what we need to do to up score to 110.

### ISSUE THREAD

**Issue by slightfoot** [fluttercommunity/plus_plugins#16]
Packages:
- [x] battery_plus 100
- [x] connectivity_plus  100
- [x] device_info_plus 110
- [x]  network_info_plus 100
- [x] package_info_plus 110
- [x] sensors_plus 110
- [x] ~share_plus 100~ ([2.1.0-nullsafety.0](https://pub.dev/packages/share_plus/versions/2.1.0-nullsafety.0/score) has 110)
- [x] android_alarm_manager_plus 80
- [x] android_intent_plus 90 (android only)

**Comment by mhadaily** [comment]
We have now the highest score possible. 💯
