### ISSUE TITLE
[Bug]:  sendTriplet crash

### ISSUE THREAD

**Issue by Andrushka1012** [fluttercommunity/plus_plugins#1617]
### Platform

iOS 14

### Plugin

sensors_plus

### Version

sensors_plus: ^1.4.1

### Flutter SDK

3.3.10

### Steps to reproduce

I got crash in my firebase crashlitic
on
sensors_plus
FLTSensorsPlusPlugin.m - Line 114
sendTriplet + 114. 

I don't use that plugin by my own, but i use https://pub.dev/packages/shake, so it's comes from here.
Please veriify

### Logs

```shell
Crashed: NSOperationQueue 0x11dd229a0 (QOS: UNSPECIFIED)
0  Flutter                        0x12aac (Missing UUID 3adbf2891ee63561a26df1652313df7e)
1  sensors_plus                   0x64c0 sendTriplet + 114 (FLTSensorsPlusPlugin.m:114)
2  Foundation                     0x121b2c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
3  Foundation                     0x1e6d8 -[NSBlockOperation main] + 100
4  Foundation                     0x123dc8 __NSOPERATION_IS_INVOKING_MAIN__ + 20
5  Foundation                     0x1e394 -[NSOperation start] + 784
6  Foundation                     0x1247c0 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
7  Foundation                     0x12428c __NSOQSchedule_f + 180
8  libdispatch.dylib              0x43b34 _dispatch_block_async_invoke2 + 104
9  libdispatch.dylib              0x61298 _dispatch_client_callout + 16
10 libdispatch.dylib              0x39a70 _dispatch_continuation_pop$VARIANT$armv81 + 404
11 libdispatch.dylib              0x391d8 _dispatch_async_redirect_invoke + 588
12 libdispatch.dylib              0x462c4 _dispatch_root_queue_drain + 344
13 libdispatch.dylib              0x46a5c _dispatch_worker_thread2 + 108
14 libsystem_pthread.dylib        0xb580 _pthread_wqthread + 212
15 libsystem_pthread.dylib        0xe86c start_wqthread + 8
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.2.1 22D68 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [x] I'm using the latest version of the plugin
- [x] All dependencies are up to date with `flutter pub upgrade`
- [x] I did a `flutter clean`
- [ ] I tried running the example project

**Comment by Andrushka1012** [comment]
it's hard to tell, cause I found this error in my firebase crashlitic, and there is no extra info

**Comment by vbuberen** [comment]
In such case we can't help here

**Comment by dleurs** [comment]
I got the same crashes with iOS users, 28 cases since the app launch on production 6 months ago,  and ~15k users.

I also did not found a way to reproduce (It may be related to a scanning feature, with mobile_scanner)

Got the issue on iOS 15 abd 16, flutter 3.3.10

<img width="505" alt="image" src="https://user-images.githubusercontent.com/58068925/229733908-b0c2fd10-f0ad-4860-9f29-419cd117a0f2.png">

**Comment by fehmidevoteam** [comment]
Hello i still have same crash in IOS any news please?

**Comment by ziqq** [comment]
Hello, i have same crash in IOS, have any news?

**Comment by ciriousjoker** [comment]
Same here. It only happens when the device is in the background.

> Crashed: NSOperationQueue 0x10560f120 (QOS: UNSPECIFIED)
> 0  Flutter                        0x1b97c (Missing UUID 4c4c448255553144a1489826506458ca)
> 1  Flutter                        0x5d7468 (Missing UUID 4c4c448255553144a1489826506458ca)
> 2  sensors_plus                   0x46d4 sendTriplet + 164
> 3  Foundation                     0x9cee8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
> 4  Foundation                     0x73bbc -[NSBlockOperation main] + 100
> 5  Foundation                     0x73b50 __NSOPERATION_IS_INVOKING_MAIN__ + 12
> 6  Foundation                     0x38c10 -[NSOperation start] + 684
> 7  Foundation                     0x3895c __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 12
> 8  Foundation                     0x3d9fc __NSOQSchedule_f + 168
> 9  libdispatch.dylib              0x46630 _dispatch_block_async_invoke2 + 104
> 10 libdispatch.dylib              0x64780 _dispatch_client_callout + 16
> 11 libdispatch.dylib              0x3bd48 _dispatch_continuation_pop$VARIANT$armv81 + 436
> 12 libdispatch.dylib              0x3b518 _dispatch_async_redirect_invoke + 732
> 13 libdispatch.dylib              0x48c68 _dispatch_root_queue_drain + 328
> 14 libdispatch.dylib              0x49430 _dispatch_worker_thread2 + 160
> 15 libsystem_pthread.dylib        0x1b94 _pthread_wqthread + 224
> 16 libsystem_pthread.dylib        0x1720 start_wqthread + 8

**Comment by vbuberen** [comment]
This week I merged a few contributions which were aiming to add support of variable sampling rate for sensors, but the person also changed the iOS implementation adding correct thread handling as required by recent Flutter versions. I suppose these changes could also help with this issue. I plan to release the update either end of this week or start of next, depending on when have time to update documentation. 
Version will be 4.0.1. So those, who have this issue can either wait for this release or try out mentioned changes already from the `main` branch. I would appreciate feedback in either case.

To try changes from the main branch declare the plugin this way:
```
sensors_plus:
       git:
         url: git@github.com:fluttercommunity/plus_plugins.git
         ref: main
```

**Comment by vbuberen** [comment]
New version of `sensors_plus` is in production for 2 weeks already. 
Anyone can provide feedback about this issue? Is it still there?
