### ISSUE TITLE
[share_plus]: Showing wrong label.

### ISSUE THREAD

**Issue by SwiftDeveloper859** [fluttercommunity/plus_plugins#1618]
### What is your question?

Hi All, we are building an application using flutter for both iOS and Android platform.
In This app we are using the flutter  "share_plus" library with version "4.5.3" to share the image. when we select more then one image for sharing is always showing  count with text "Documents" for example if we select 2 images it shows "2 documents". 
Can anybody suggest us, how we can change the text from "documents" to "photos"?

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
> 4.5.3

Any reason to use that old version?

> when we select more then one image for sharing is always showing count with text "Documents"

Would appreciate if you provide information in more detailed manner, like on which platform it happens, show a screenshot, etc.

**Comment by SwiftDeveloper859** [comment]
Hi @vbuberen , Thanks for the response.

> Any reason to use that old version?

We are using the version 4.5.3 because from version 5.0.0 onward, we are getting the conflicts with the other libraries we are using like "file_picker" and "flutter_local_notifications".

> Would appreciate if you provide information in more detailed manner, like on which platform it happens, show a screenshot, etc.

It happens in iOS when we select more than one image to share. 
Here is a screenshot of the issue. we want to change the label from "2 Documents" to "2 Photos".

![Simulator Screen Shot - iPhone 14 Pro - 2023-03-17 at 15 34 49](https://user-images.githubusercontent.com/127758004/225874421-0c2dd3ea-af22-43e7-9a3b-f96e6d2f1719.png)

**Comment by SwiftDeveloper859** [comment]
@vbuberen  Any feedback.

**Comment by vbuberen** [comment]
Unfortunately can't help here as not proficient with iOS.

**Comment by SwiftDeveloper859** [comment]
Is there any solution regarding this issue or is there any other recommended library for this issue.
