### ISSUE TITLE
[iPad] Share window is displayed at the bottom of the screen, just very little part of it is visible

### ISSUE THREAD

**Issue by mustaffa** [fluttercommunity/plus_plugins#1637]
### What is your question?

Hello, 
I have the following code as per examples and notes regarding iPad specific requirement. I receive no errors but the share window is popped up at the bottom of the screen, only a small part of it visible. 

final box = context.findRenderObject() as RenderBox?;
....
Share.shareXFiles(
      [file],
      sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size,
    );

<img width="654" alt="image" src="https://user-images.githubusercontent.com/3439692/226565742-7c3ff919-814f-4c47-a200-ce3daf015fda.png">

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by wildsurfer** [comment]
I'm facing the same issue
