### ISSUE TITLE
[Question]: Have any of you encountered a situation where the value of the wifbssid obtained on an iOS device is one digit less than on an Android device when using the network_info_plus plugin?

### ISSUE THREAD

**Issue by MeiChao** [fluttercommunity/plus_plugins#1638]
### What is your question?

Have any of you encountered a situation where the value of the wifbssid obtained on an iOS device is one digit less than on an Android device when using the network_info_plus plugin?
The value obtained on iOS.
![image](https://user-images.githubusercontent.com/10571589/226840437-02b0787f-6f05-4503-baed-70a67194d8ce.png)

 The value obtained on Android.
![image](https://user-images.githubusercontent.com/10571589/226840590-ce236c72-b59d-4045-9982-bc9851b43d80.png)

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
No, haven't seen this issue yet. Could I ask you to try if it can be reproduced with latest release of network_info_plus `3.0.3`?

**Comment by MeiChao** [comment]
> No, haven't seen this issue yet. Could I ask you to try if it can be reproduced with latest release of network_info_plus `3.0.3`?

the same There are missing digits
