### ISSUE TITLE
When i build my app in release mode using: flutter build apk --release, the package connectivity_plus doesnt work anymore, and keeps returning false when i check internet connection status, the app is working fine in debug mode.

### ISSUE THREAD

**Issue by zeljko94** [fluttercommunity/plus_plugins#1639]
### What is your question?

Did i miss some configuration or does this package not work correctly in release mode?
If it does not work in release mode, can you recommend me another package that works in release mode??

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by iamranchojr** [comment]
@zeljko94 Close the issue then since it is not really an issue.
