### ISSUE TITLE
[share_plus] sharePositionOrigin PlatformException on iPad

### ISSUE THREAD

**Issue by stx** [fluttercommunity/plus_plugins#1640]
### Platform

iPad13,6

### Plugin

share_plus

### Version

6.3.1

### Flutter SDK

3.7.5

### Steps to reproduce

Unsure exactly how to reproduce, but we're seeing this error rarely in production on iPad:

```
PlatformException: PlatformException(error, sharePositionOrigin: argument must be set, {{0, 0}, {0, 0}} must be non-zero and within coordinate space of source view: {{0, 0}, {834, 1194}}, null, null)
  File "message_codecs.dart", line 653, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 315, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "method_channel_share.dart", line 134, in MethodChannelShare.shareFilesWithResult
```

The triggering code:

```await Share.shareXFiles(<XFile>[XFile(path)]);```

The referenced file is a screenshot generated by https://pub.dev/packages/screenshot - so maybe it's empty and that's unhandled by share_plus?

Same issue is seen here: https://www.cloverfield.co.jp/2023/01/26/flutter%E3%80%80share-sharefiles-deprecated%E3%80%80sharexfiles%E3%82%A8%E3%83%A9%E3%83%BC/?doing_wp_cron=1679592278.2726008892059326171875
 

### Code Sample

```
      Uint8List imageData = await ScreenshotController().captureFromWidget(
        widget,
        context: context,
        pixelRatio: 2,
      );

      Directory directory = await getApplicationDocumentsDirectory();

      String path = '${directory.path}/image.png';

      await XFile.fromData(imageData).saveTo(path);

      await Share.shareXFiles(<XFile>[XFile(path)]);
```

### Logs

```shell
n/a
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by jingluoguo** [comment]
maybe you need add **sharePositionOrigin** in iPad. example.

**Comment by stx** [comment]
@jingluoguo Perhaps, but it works >99.9% of the time without it, so I assume share_plus is handling it correctly but missing some edge case.

**Comment by jingluoguo** [comment]
@stx `share_plus` requires iPad users to provide the `sharePositionOrigin` parameter.

Without it, `share_plus` will not work on iPads and may cause a crash or letting the UI not responding.

**Comment by stx** [comment]
@jingluoguo Ah, I see now in the readme! Thank you.

**Comment by DevanshiGor** [comment]
I have solved it with
