### ISSUE TITLE
[Bug]: Share method moves the screen up and hides the status bar in some devices

### ISSUE THREAD

**Issue by m-maheshwari-04** [fluttercommunity/plus_plugins#1655]
### Platform

Android 11

### Plugin

share_plus

### Version

6.3.1

### Flutter SDK

3.3.10

### Steps to reproduce

I'm using the share_plus package in my Flutter app to allow users to share content. However, when I call the Share.share method, the screen moves up and the status bar is not visible on some devices. I've added a SafeArea widget as the parent of my Scaffold, but the issue still persists.

Steps to reproduce:

1) Add the share_plus package to your Flutter project.
2) Create a screen with a Scaffold widget and a SafeArea widget as its parent.
3) In the Scaffold body, add a button that calls the Share.share method when tapped.
4) Run the app on a device where this issue occurs.

The issue is occurringin some specific devices (I faced the issue in Samsung devices).
Device information:
Device:  Samsung Galaxy A50

### Logs

```shell
[+2630 ms] I/ViewRootImpl@3765dd0[MainActivity](23844): ViewPostIme pointer 0
[  +83 ms] I/ViewRootImpl@3765dd0[MainActivity](23844): ViewPostIme pointer 1
[ +111 ms] I/ViewRootImpl@3765dd0[MainActivity](23844): MSG_WINDOW_FOCUS_CHANGED 0 1
[ +211 ms] I/SurfaceControl(23844): nativeRelease nativeObject s[527430200384]
[   +1 ms] I/SurfaceControl(23844): nativeRelease nativeObject e[527430200384]
[        ] I/SurfaceControl(23844): nativeRelease nativeObject s[527431208896]
[        ] I/SurfaceControl(23844): nativeRelease nativeObject e[527431208896]
[        ] I/SurfaceControl(23844): nativeRelease nativeObject s[527431206208]
[        ] I/SurfaceControl(23844): nativeRelease nativeObject e[527431206208]
[ +135 ms] D/InputTransport(23844): Input channel destroyed: 'ClientS', fd=108
[  +17 ms] I/SurfaceControl(23844): nativeRelease nativeObject s[527431206496]
[        ] I/SurfaceControl(23844): nativeRelease nativeObject e[527431206496]
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2728], locale en-IN)
    • Flutter version 3.3.10 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.76.0)
    • VS Code at C:\Users\mukun\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.70

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

![Screenshot_20230331-012103](https://user-images.githubusercontent.com/58637235/228949406-ef4a130c-4b82-4747-a173-1760f3a3b45e.jpg)
![Screenshot_20230331-012108_Android System](https://user-images.githubusercontent.com/58637235/228949415-80bf6aee-25da-46cb-aeda-35ae77d60fc7.jpg)

**Comment by thudaohd** [comment]
I have the same issue. do you have any solution?

**Comment by m-maheshwari-04** [comment]
> I have the same issue. do you have any solution?

No. Do share the solution if you find any.

**Comment by vbuberen** [comment]
Thanks for your report, but it is not `share_plus` issue as the plugin just calls a default share intent in Android and doesn't render anything itself on Android as it is not supported on this platform. So the issue you are reporting is either with Flutter or specific to some devices, not with `share_plus` plugin.

**Comment by m-maheshwari-04** [comment]
Okay thanks for the clarification. But any possible solution for this issue? As it is very significant and I am facing it with other share packages also.
