### ISSUE TITLE
[Question]: Sensor plus

### ISSUE THREAD

**Issue by athiraHash** [fluttercommunity/plus_plugins#1656]
### What is your question?

Accelerometer repeating same values

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
What is the question here? Stream from accelerometer provides you current value from the platform, so it can provide multiple repeating value.

**Comment by vbuberen** [comment]
Closing due to no reply
