### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hiral1987** [fluttercommunity/plus_plugins#1664]
### Platform

Android 12

### Plugin

share_plus

### Version

6.3.1

### Flutter SDK

3.0.0

### Steps to reproduce

Save image on your external storage for eg : /sdcard/NotesApp/1679229095384.jpg.
Then call Share.shareFiles or Share.XFiles & pass image path.

i got below error

E/flutter ( 7334): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Share failed, '/sdcard/NotesApp/1679229095384.jpg': The source file doesn't exist., null, null)
E/flutter ( 7334): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 7334): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 7334): <asynchronous suspension>

### Code Sample

```dart
Share.shareFiles(_imageList, text: '${_titleController.text}\n\n${_noteController.text}');
```

### Logs

```shell
E/flutter ( 7334): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Share failed, '/sdcard/NotesApp/1679229095384.jpg': The source file doesn't exist., null, null)
E/flutter ( 7334): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 7334): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 7334): <asynchronous suspension>
E/flutter ( 7334):
```

### Flutter Doctor

```shell
PS D:\FlutterProj\note_app> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.22621.1413], locale en-IN)
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.75.1)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by hiral1987** [comment]
Anyone pls provide solution to this

**Comment by vbuberen** [comment]
Could you share the code snippet including the file path that you provide? I assume something is wrong with the path you provide.

**Comment by hiral1987** [comment]
I have already shared filepath & code snippet on github which i tried.

You can use same code to reproduce.

Thanks & Regards,
Hiral Dharod

**Comment by vbuberen** [comment]
> I have already shared filepath & code snippet on github which i tried.

I can't reproduce as I clearly explained that I assume that the issue is in file paths you provide and your snippet has no info on what is `_imageList` and which items you have in that list. Can't help you without a proper full sample to reproduce.
