### ISSUE TITLE
sensor_plus: Change the sampling rate 

### ISSUE THREAD

**Issue by athenawisdoms** [fluttercommunity/plus_plugins#1668]
### What is your question?

How do you change the sampling rate of the sensors (eg. accelerometer) when using the `sensors_plus` plugin? I'm currently interested in Android sensors, not iOS (yet).

Thanks!

Related:
- https://github.com/flutter/flutter/issues/25971

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
There is no way to change the rate in the plugin at the moment.
