### ISSUE TITLE
[Bug]: network_info_plus 3.0.2 WINDOWS NOT WORKING 

### ISSUE THREAD

**Issue by ameetaujla** [fluttercommunity/plus_plugins#1669]
https://ibb.co/qgHdcfW

please check this screenshot also 

### Platform

windows 11

### Plugin

network_info_plus

### Version

latest

### Flutter SDK

latest

### Steps to reproduce

not working on latest version of windows 10 , 11 ,,

please check 

Thanks,

### Logs

```shell
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method wifiGatewayAddress on channel dev.fluttercommunity.plus/network_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      _MyhomeState.getValues (package:starr_pro_flutter/screens/dashboard_home.dart:138:25)
<asynchronous suspension>
```

### Flutter Doctor

```shell
all good
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Gray-Ice** [comment]
I got this problem when I using **getWifiIP()** at **android**.
Flutter **version**: 

```
flutter --version
Flutter 3.7.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 90c64ed42b (6 weeks ago) • 2023-03-21 11:27:08 -0500
Engine • revision 9aa7816315
Tools • Dart 2.19.5 • DevTools 2.20.1
```

My code:
```
final info = NetworkInfo();
final String? ip = await info.getWifiIP();
```

Error message:

```
E/flutter (13448): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method wifiIPAddress on channel dev.fluttercommunity.plus/network_info)
E/flutter (13448): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
E/flutter (13448): <asynchronous suspension>

```

**Comment by ameetaujla** [comment]
bro its working fine on android. i am facing issues on windows 11

**Comment by ameetaujla** [comment]
@vbuberen thank you, I will test it and get back to you tomorrow :)

**Comment by ameetaujla** [comment]
@vbuberen 
hello bro, I have tested your latest version 4.0.0 
final wifiIP = await info.getWifiIP(); // 192.168.1.43

it's working fine on Windows 10 and 11, but getwifiname method is not working it's returning null. 

and it will work only if we connect to wifi, if the computer is connected with a LAN cable, it's returning null. 

Thanks, for the help 

great work. 

Thank you
