### ISSUE TITLE
[Bug]:  Failed to build iOS app   connectivity_plus  after update xcode 14.3

### ISSUE THREAD

**Issue by samithe7** [fluttercommunity/plus_plugins#1672]
### Platform

Ios 

### Plugin

 connectivity_plus

### Version

3.0.3

### Flutter SDK

3.7.10

### Steps to reproduce

 without    connectivity_plus   my app build   but when i add this   app not build

### Logs

```shell
Failed to build iOS app
Error (Xcode): File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 14.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3 22E252 darwin-arm64, locale
    en-AU)
    • Flutter version 3.7.10 on channel stable at
      /Users/developer/Documents/appdev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (4 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/developer/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390
      /Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/developer/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 78618507-057D-4F78-A794-6BF368A58293 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64
      • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by smunoz-ml** [comment]
This is kind of a duplicate of #1665. It's the same issue.

**Comment by samithe7** [comment]
no issue is not fixed  . without connectivity_plus  everything is ok  . but when add  connectivity_plus   app not build and show   ......


Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
Error launching application on iPhone 14 Pro Max.

**Comment by vbuberen** [comment]
> no issue is not fixed . without connectivity_plus everything is ok . but when add connectivity_plus app not build and show

Did you update to Flutter 3.7.11 and still have this issue? Or you replied without updating Flutter?

**Comment by samithe7** [comment]
> > no issue is not fixed . without connectivity_plus everything is ok . but when add connectivity_plus app not build and show
> 
> Did you update to Flutter 3.7.11 and still have this issue? Or you replied without updating Flutter?
✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-arm64, locale
    en-AU)
    • Flutter version 3.7.11 on channel stable at
      /Users/developer/Documents/appdev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (3 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/developer/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390
      /Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/developer/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E261
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by kollinmurphy** [comment]
Updating to Flutter 3.7.11 solved it for me.

**Comment by danieledelgiudice** [comment]
I currently have Flutter 3.7.12 and I am still experiencing this issue.
I haven't tried to downgrade to 3.7.11 though.

**Comment by vbuberen** [comment]
For those who still have the issue I would ask to try the 4.0.0 version of the plugin and share the feedback.

**Comment by samithe7** [comment]
everything is ok now .

**Comment by samithe7** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/1806

**Comment by samithe7** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/1786

**Comment by vbuberen** [comment]
@samithe7 Don't spam the repo with links to unrelated issues. This is formal warning.

**Comment by vbuberen** [comment]
For those affected in 3.10 check this comment: https://github.com/fluttercommunity/plus_plugins/issues/1806#issuecomment-1545332556

**Comment by bdtask9900** [comment]
Thanks for your response. this problem solve 
https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3

**Comment by vbuberen** [comment]
> Thanks for your response. this problem solve
https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3

This is not a proper solution as forces to set min iOS to 13.

The real solution to the build issue will land in Flutter 3.10.1: https://github.com/flutter/flutter/issues/126549#issuecomment-1548874721

**Comment by vbuberen** [comment]
Reopening to let other users see the issue faster

**Comment by FullstackWEB-developer** [comment]
https://stackoverflow.com/questions/78044358/flutter-connectivity-plus-package-builds-in-vs-code-but-fails-in-xcode/78348879#78348879

I think this issue didn't solved yet.
Is this just Xcode issue?
Anyone please help me
