### ISSUE TITLE
[Question]: Can i determine active network information?

### ISSUE THREAD

**Issue by IamDean10** [fluttercommunity/plus_plugins#1681]
### What is your question?

How can i determine active network information? wifi full information or sim card information?

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by jaypathak9460** [comment]
Yes, I had already searched for those unable to find on google any there any way to get all the information I have check [connectivity_plus](https://pub.dev/packages/connectivity_plus) but it only provides what kind of internet device is using like Wifi or mobile but do not have its strength and carrier details
