### ISSUE TITLE
[Question]: is there any way to change display language in share_plus

### ISSUE THREAD

**Issue by vvviettt** [fluttercommunity/plus_plugins#1683]
### What is your question?

![438541D7-6FE3-4419-8CBE-C5E081FF175E](https://user-images.githubusercontent.com/97574971/231993504-41c132de-bfc8-4c43-ba79-2d981bb333d7.png)
is there any way to change display language in share_plus?
Thank you because reply!

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by a250059653** [comment]
I also encountered this problem, I want to display Chinese on ios, please let me know if you solve it, thank you！

**Comment by xiongzhaoxu** [comment]
这个问题没有解决方案吗？我也想在分享的时候目标app的名字显示为中文
