### ISSUE TITLE
[Question]: [android_alarm_manager_plus] not working if the app stops / ends

### ISSUE THREAD

**Issue by desmeit** [fluttercommunity/plus_plugins#1685]
### What is your question?

I try to run a periodic task, even if the app is stopped:

```
 if (Platform.isAndroid) {
    final int helloAlarmID = 0;
    await AndroidAlarmManager.periodic(
        const Duration(minutes: 1), helloAlarmID, callbackDispatcher,
        wakeup: true, rescheduleOnReboot: true);
  }
```

It is working perfectly if the app is running in fore- ore background but if I terminate the app the task is not running anymore.

in your documentation you write:
`"printHello will then run (roughly) every minute, even if the main app ends."`

and on the other hand you write:
`"The Android OS will not fire alarms for apps that have been force stopped."`

Can you explain in more detail what exactly you mean by that? What is meaning by "end" and what is meaning by "stop"?

How can I make the periodic task run even if the app is not running in the background or foreground? I want to update the text of a widget every minute.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by madeeldev** [comment]
I was facing the same error. This is how I resolved it & it is mentioned in the package docs. **Likely the device is running some battery optimization software that is preventing the alarm from firing.** Check out [dontkillmyapp.com](https://dontkillmyapp.com/) to find out more about optimizations done by different vendors.
