### ISSUE TITLE
[Question]: Invalid podfile

### ISSUE THREAD

**Issue by TheCarpetMerchant** [fluttercommunity/plus_plugins#1691]
### What is your question?

Doing `pod install`, I run into this error :
```
[!] Invalid `Podfile` file: No such file or directory @ rb_file_s_symlink - (C:\\Users\\user\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\device_info_plus-8.2.0\\, D:/Code/Flutter/test_project/ios/.symlinks/plugins/device_info_plus)
```

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Do you still have this issue?

**Comment by TheCarpetMerchant** [comment]
It doesn't work on my PC, but I made it work in a Mac VM without any changes, so I'd say it's not really worth investigating ; I'll close this.
