### ISSUE TITLE
[Question]: How to get info on mobile data

### ISSUE THREAD

**Issue by somdipdey** [fluttercommunity/plus_plugins#1707]
### What is your question?

I am trying to get info on mobile data using the following code:

```
// Connected to mobile data, check if it's at least 4G (LTE)
      var mobileData = await Connectivity().getNetworkType();
      return mobileData == ConnectivityResult.mobile &&
          (await Connectivity().getCarrierName() ?? '')
              .toLowerCase()
              .contains('lte');
```
However, it seems like getNetworkType() method and getCarrierName() method are not defined. How can I update the code to understand whether the smartphone has access to 4G LTE or higher?

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
There is no support of these properties in the connectivity_plus plugin at the moment, so can't help you here.
