### ISSUE TITLE
[device_info_plus]<windows> add more information return like MacAddress , windowsVersion , ...

### ISSUE THREAD

**Issue by Ali-Fadaei** [fluttercommunity/plus_plugins#177]
I want lock windows app for specific hardware for some reasons to do this I need get some unique keys from clients hardware like 'bios UUID' or 'MacAddress' but I didn't find any thing for flutter desktop windows platform. there are packages for Android and ios that returns MAC and bios UUID like platform_device_id and device_info but they don't support desktop platform, finally I found plus plugins that support device info for windows but there are few properties presented! I think this should be grow with necessary properties like bios UUID or something unique for hardware / MacAdress / windows Version / userName / and so forth!

**Comment by ueman** [comment]
Device Info Plus for Windows already uses the win32 package.
So you can easily use that repo as an example:

- See https://github.com/timsneath/win32/tree/main/example/manifest for WIndows Version. Do note the readme for restrictions.
- See https://github.com/timsneath/win32/blob/main/example/sysinfo.dart for some more system information.
