### ISSUE TITLE
Share_plus Could not resolve com.android.tools.build:gradle:7.4.2.

### ISSUE THREAD

**Issue by InspectlyMads** [fluttercommunity/plus_plugins#1770]
### What is your question?

I am having an issue with share_plus when building to appcenter. I am also using device_info_plus which works perfectly fine.

I am getting this message:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_appcenter_bundle'.
> Could not resolve all files for configuration ':flutter_appcenter_bundle:classpath'.
   > Could not resolve com.android.tools.build:gradle:7.4.2.
     Required by:
         project :flutter_appcenter_bundle
      > No matching variant of com.android.tools.build:gradle:7.4.2 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.4' but:
          - Variant 'apiElements' capability com.android.tools.build:gradle:7.4.2 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'javadocElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'runtimeElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'sourcesElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':flutter_appcenter_bundle' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':flutter_appcenter_bundle' of type org.gradle.api.Project.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
It is some issue in your project configuration, not `share_plus` plugin.

**Comment by mohas** [comment]
I have the same problem, why does this packages locks to a specific gradle plugin version and says nothing in the docs to install it? the project builds OK without share_plus so there is nothing wrong with the project itself

**Comment by vbuberen** [comment]
> I have the same problem, why does this packages locks to a specific gradle plugin version and says nothing in the docs to install it? the project builds OK without share_plus so there is nothing wrong with the project itself

It doesn't lock to any specific Gradle version. You only need to have something newer than Gradle plugin 4.2.
With such tone of your comment I can only suggest you to not use `share_plus` plugin if you are so sure that everything is fine with the project.

**Comment by mohas** [comment]
how do you check your gradle plugin version? `gradlew --version` shows 7.5 on my machine

**Comment by vbuberen** [comment]
You are confusing Gradle version and Android Gradle plugin versions. These are different things, so the output you are providing is the version of Gradle that you have installed on your maching. 
Android Gradle plugin version (AGP) is specified in the `build.gradle` file of your project. 

Here is an example: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/android_alarm_manager_plus/android/build.gradle#L11

**Comment by vbuberen** [comment]
> Facing same problem. Nothing changes and suddenly this started appearing.

Hi. It shouldn't happen without any changes as you say.
Please provide your `build.gradle` file content from `.../android` path of your project.
