### ISSUE TITLE
[Bug]: share_plus >=6.0.0 is incompatible with file_picker >=5.2.11 

### ISSUE THREAD

**Issue by lcarielo** [fluttercommunity/plus_plugins#1792]
### Platform

Android 13

### Plugin

share_plus

### Version

6.3.4

### Flutter SDK

3.7.12

### Steps to reproduce

My project works with "file_picker" and "share_plus" dependence. When I updated both dependencies it gave me that error:

```
Because share_plus >=6.0.0 depends on win32 ^3.0.0 and file_picker >=5.2.11 depends on win32 ^4.1.3, share_plus >=6.0.0 is incompatible with file_picker >=5.2.11.
So, because my_project depends on both file_picker ^5.3.0 and share_plus ^6.3.4, version solving failed.
pub get failed
```

Any solution?

### Logs

```shell
Because share_plus >=6.0.0 depends on win32 ^3.0.0 and file_picker >=5.2.11 depends on win32 ^4.1.3, share_plus >=6.0.0 is incompatible with file_picker >=5.2.11.
So, because my_project depends on both file_picker ^5.3.0 and share_plus ^6.3.4, version solving failed.
pub get failed
```

### Flutter Doctor

```shell
carielo@MacBook-Pro-de-Luis my_project % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-x64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Use https://dart.dev/tools/pub/dependencies#dependency-overrides till plugins are updated
