### ISSUE TITLE
[Bug]: MissingPluginException when using `FlutterFragment.withNewEngine()`

### ISSUE THREAD

**Issue by marenovakovic** [fluttercommunity/plus_plugins#1800]
### Platform

Android 13

### Plugin

package_info_plus

### Version

4.0.0

### Flutter SDK

3.7.12, 3.10.0

### Steps to reproduce

Embed Flutter into existing Android app as per documentation and add new `FlutterFragment` with `FlutterFragment.withNewEngine()`.
https://docs.flutter.dev/add-to-app/android/add-flutter-fragment
Works fine with cached engine.

### Code Sample

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  configureDependencies();
  await runAppWithFlavor();
}

Future<void> runAppWithFlavor() async {
  final platformInfo = await PackageInfo.fromPlatform();
  Flavor.fromPackageInfo(platformInfo).match(
    (error) => throw error,
    (flavor) {
      ...
      runApp(OrderEngineApp(flavor: flavor));
    },
  );
}
```

### Logs

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:43)
<asynchronous suspension>
#2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
<asynchronous suspension>
#3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:41:26)
<asynchronous suspension>
#4      runAppWithFlavor (package:my_package/main.dart)
<asynchronous suspension>
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0 darwin-arm64, locale
    ...)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by marenovakovic** [comment]
yes with cached engine I init it during `Application.onCreate` and I set Flutter route that's using `package_info_plus` later in app lifecycle.
there's nothing much to it. I have `Application.onCreate`, setting `FlutterFragment` with cached engine and than Flutter code that I provided is called.

**Comment by vbuberen** [comment]
I was asking more about code sample for the case that doesn't work for you.
In any case can't help here at the moment as not familiar with this embedding topic.

**Comment by marenovakovic** [comment]
There is no more info. That's it.

**Comment by marenovakovic** [comment]
I didn't solve it, stopped using the library.

**Comment by TheHypnoo** [comment]
@marenovakovic 

It's a bit contradictory, but after fighting for a while and just asking. I removed an implementation and that's when everything started working great.

If in your case you have a plugin made by you, and if you use ActivityAware, stop using it, it's what broke it.

Regards!
