### ISSUE TITLE
[Request]: Update win32 to 5.0.0

### ISSUE THREAD

**Issue by tomaszpolanski** [fluttercommunity/plus_plugins#1801]
### Plugin

package_info_plus

### Use case

Any plugin that uses `win32` would need to have `win32` updated to `5.0.0` as [that is the version](https://pub.dev/packages/win32/changelog#500) that supports dart 3.0.

Still, this can be overcome by using `dependency_overrides` therefore it is not a critical issue for Flutter 3.10

### Proposal

Update the following packages to use `win32: ^5.0.0` instead of `4.0+` version
- share_plus
- device_info_plus
- package_info_plus
- network_info_plus

**Comment by vbuberen** [comment]
It is quite too early to create another breaking release of Plus Plugins considering that Dart 3.0 was released just yesterday. I would like to prolong our support of older Dart versions, especially, since we have just bumped the min Dart version already this week.

**Comment by tomaszpolanski** [comment]
Thanks for the replay. Sure, that's understandable. 
People that will have the issue, could for now resolve it by adding to `pubspec.yaml` override:
```
dependency_overrides:
  win32: ^5.0.0
```

**Comment by nimr77** [comment]
I had to remove it 
https://github.com/fluttercommunity/plus_plugins/compare/main...nimr77:plus_plugins:main
it was breaking the build in my app 4h ago

**Comment by vbuberen** [comment]
Thanks to #1805 next release will support `win32: ^5.0.0` without overrides.

**Comment by miguelmato** [comment]
Offtopic, feel free to remove: Is it possible to get rid of platform specific dependencies like win32 if you only care about mobile and have Flutter CLI disabled for all but mobile?

**Comment by vbuberen** [comment]
New versions released with broader constraints, so closing the issue.
