### ISSUE TITLE
[share_plus] Subsequent calls to the sharesheet will cause it to be empty even after restarting the application

### ISSUE THREAD

**Issue by JagandeepBrar** [fluttercommunity/plus_plugins#181]
## System info

Issue occurs on: Tested on iOS, unsure about Android
Plugin name: share_plus
Plugin version: 2.0.0
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.3 20E5196f darwin-x64, locale en-CA)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[!] Android Studio (not installed)
[✓] VS Code (version 1.54.1)
[✓] Connected device (1 available)
```

## Steps to Reproduce

1. Use `Share.shareFiles([path])` to share a file
2. The share sheet will show, and can successfully be shared to another app or to the filesystem. Dismissing the sheet will also lead to the error.
3. On next load of the share sheet, only the header is available, none of the sharing options are there (just a big empty area).

## Logs

```
[User Defaults] Couldn't read values in CFPrefsPlistSource<0x28045ba00> (Domain: com.apple.Sharing, User: kCFPreferencesCurrentUser, ByHost: No, Container: kCFPreferencesNoContainer, Contents Need Refresh: No): accessing preferences outside an application's container requires user-preference-read or file-read-data sandbox access
<CATransformLayer: 0x282aa52e0> - changing property backgroundColor in transform-only layer, will have no effect
[core] SLRemoteComposeViewController: (this may be harmless) viewServiceDidTerminateWithError: Error Domain=_UIViewServiceErrorDomain Code=1 "(null)" UserInfo={Terminated=disconnect method}
[ShareSheet] connection invalidated
[ShareSheet] connection interrupted
[ShareSheet] connection invalidated
[ShareSheet] connection interrupted
[ShareSheet] connection invalidated
[ShareSheet] connection interrupted
[ShareSheet] connection invalidated
[ShareSheet] connection interrupted
[ShareSheet] connection invalidated
[ShareSheet] connection interrupted
```

These two will get logged together in sequence, rapidly:
```
[ShareSheet] connection invalidated
[ShareSheet] connection interrupted
```

It will continue even after a hot reload, a restart. The empty share sheet will even continue if I completely close and restart the application. The only solution is to either reinstall the app or to reboot the device.

**Comment by JagandeepBrar** [comment]
Also to note, this occurs on both debug and release builds.

**Comment by JagandeepBrar** [comment]
As a a workaround, I have switched to the `share` package (2.0.1) which supports NNBD. While it does throw the same initial error (Couldn't read value...), it does not cause the share sheet to break on recurring calls.

**Comment by miquelbeltran** [comment]
Could be related to this change here: https://github.com/fluttercommunity/plus_plugins/pull/118

this is the only functionality that is different to the `share` package.

**Comment by JagandeepBrar** [comment]
After upgrading Flutter to v2.0.5, this issue appears to have disappeared! Must have been something in either v2.0.0 or v2.0.1 that was conflicting with this package.
