### ISSUE TITLE
Windows support for null safety

### ISSUE THREAD

**Issue by bksubhuti** [fluttercommunity/plus_plugins#1835]
### Plugin

flutter pub add package_info_plus_windows 

### Use case

After figuring out that package info does not work in windows and too much is involved with placing a bug report,
I noticed that there was a package for linux and also tried the same for windows.
However, I cannot add the package because it was written so long ago and seems to not have the settings for null safety.  
I'm using your latest  package 4..0.1
and the same with the share plus.
as of May 20th

here is the output
```
PS C:\git\tipitaka-pali-reader> flutter pub add package_info_plus_windows                

The lower bound of "sdk: '>=2.5.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety

```
When I used windows without the above package (can't add it).. you package says that version is 1.0.0 and build number is blank.  It works perfectly fine in Android.
We already call 
  WidgetsFlutterBinding.ensureInitialized();

but we don't use the package unless the about dlg is called.

I assume I need the windows package and linux packages for desktop . maybe even macOS.

We publish all 5 OS. 
We have 2000 users on android and 300+ users on Windows .   Apple ios and MacOS not sure because another volunteer publishes for us.
( The free app is called:  Tipitaka Pali Reader)

It was an idea to use your package because we are lazy to update the manual version numbers in code, but the yaml  version number increments are required for app store updates.

### Proposal

Make null safety so the error does not show up and that flutter 3.10 lets you safely add
flutter pub add package_info_plus_windows 

or give a solution to make windows work (and linux and mac)

**Comment by bksubhuti** [comment]
It does not seem to be documented what is needed to make Desktop versions work.  I assume you need to add the proper desktop packages.

**Comment by vbuberen** [comment]
> Make null safety so the error does not show up and that flutter 3.10 lets you safely add
flutter pub add package_info_plus_windows or give a solution to make windows work (and linux and mac)

> It does not seem to be documented what is needed to make Desktop versions work. I assume you need to add the proper desktop packages.

All Plus Plugins packages support null safety for a very long time. The output that you show clearly indicates that it is your project that has the lower Dart version as 2.5.0. If you would check Plus plugins constraints you would see that our lower constraint is much higher than 2.12 (version where null-safety was introduced): https://github.com/fluttercommunity/plus_plugins/blob/main/packages/package_info_plus/package_info_plus/pubspec.yaml#L47

So you need to deal with your project setup and there is nothing `not documented`. Closing as invalid.

**Comment by bksubhuti** [comment]
Windows does not work.  Shall I make a bug.. the requirements to make a bug report would require a lot of items.
although i did check google.
I did do flutter dr and clean

BTW:  Here is my flutter dr. which shows that I'm using proper dart.

C:\git\tipitaka-pali-reader> flutter doctor -v
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1555], locale en-US)
    • Flutter version 3.10.0 on channel stable at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (11 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\bksub\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\bksub\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.58

[√] Network resources
    • All expected network resources are available.

**Comment by mhadaily** [comment]
@bksubhuti  can you please create another bug report issue please? this issue seems to be closed and I am afraid your issue will get lost here.
