### ISSUE TITLE
package_info_plus   version solving failed.  with new http 1.0.0

### ISSUE THREAD

**Issue by samithe7** [fluttercommunity/plus_plugins#1840]
### Platform

all

### Plugin

 package_info_plus  

### Version

4.0.0

### Flutter SDK

3.10.1

### Steps to reproduce

no need

### Code Sample

```dart
no need
```

### Logs

```shell
no need
```

### Flutter Doctor

```shell
no need
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
This is incomplete report.

`http` 1.0.0 requires Dart 3. For now we are not going to bump min Dart to 3, thus, use `dependency_overrides` to get the latest `http` version.

**Comment by mernen** [comment]
Couldn't you change the dependency to `http: ">=0.13.5 <2.0.0"`, i.e. supporting both 0.13 and 1.0 simultaneously? AFAIK there's no BC break on 1.0 other than the Dart version.

**Comment by vbuberen** [comment]
> Couldn't you change the dependency to `http: ">=0.13.5 <2.0.0"`

Good idea. Considering how `http` package is used in the plugin, it can be done. Thanks for suggesting.

**Comment by vbuberen** [comment]
Just published a new version of `package_info_plus` with relaxed constraints, so users now free to use either pre 1.0 `http` or 1.0 and onwards. Check our 4.0.2 version of `package_info_plus`.

Closing a completed.
