### ISSUE TITLE
[Bug]: device_info_plus Android build fails with old Android Gradle Plugin version

### ISSUE THREAD

**Issue by laxkarparas1** [fluttercommunity/plus_plugins#1846]
### Platform

Android 13

### Plugin

device_info_plus

### Version

9.0.1

### Flutter SDK

3.8.0

### Steps to reproduce

i just upgrade dependecies with pub upgrade , and after that i run project it give me this error
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deorwine19/.pub-cache/hosted/pub.dev/device_info_plus-9.0.1/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':device_info_plus'.
> No signature of method: build_36ag8bk7nhdb94jzgekqpyvd6.android() is applicable for argument types: (build_36ag8bk7nhdb94jzgekqpyvd6$_run_closure2) values: [build_36ag8bk7nhdb94jzgekqpyvd6$_run_closure2@475ac029]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1

### Logs

```shell
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deorwine19/.pub-cache/hosted/pub.dev/device_info_plus-9.0.1/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':device_info_plus'.
> No signature of method: build_36ag8bk7nhdb94jzgekqpyvd6.android() is applicable for argument types: (build_36ag8bk7nhdb94jzgekqpyvd6$_run_closure2) values: [build_36ag8bk7nhdb94jzgekqpyvd6$_run_closure2@475ac029]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.8.0-12.0.pre.23, on macOS 13.2.1 22D68 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
This error means that your projects uses a really old Android Gradle Plugin version (older than 4.2). Update your project setup as it is mentioned in the changelogs file https://pub.dev/packages/device_info_plus/changelog#900
