### ISSUE TITLE
[Question]: Because no versions of package_info_plus match >4.0.1 <5.0.0 

### ISSUE THREAD

**Issue by admonxetrii** [fluttercommunity/plus_plugins#1858]
### What is your question?

Could not update google_fonts due to this error

Because no versions of package_info_plus match >4.0.1 <5.0.0 and package_info_plus 4.0.1 depends on http ^0.13.5, package_info_plus ^4.0.1 requires http ^0.13.5.
And because google_fonts >=4.0.5 depends on http ^1.0.0, package_info_plus ^4.0.1 is incompatible with google_fonts >=4.0.5.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Thanks for report, but I have doubts that you did any search as [the last issue](#1854) before yours is about the same topic. Closing as duplicate.
