### ISSUE TITLE
[Bug] [Documentation]: share_plus package example main.dart link broken in pub.dev 

### ISSUE THREAD

**Issue by AKR-2803** [fluttercommunity/plus_plugins#1861]
### Platform

NA

### Plugin

share_plus

### Version

7.0.1

### Flutter SDK

NA

### Steps to reproduce

The example link "example/lib/main.dart" on [share_plus](https://pub.dev/packages/share_plus/example) is broken

**current link** : [example/lib/main.dart](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/example/lib/main.dart)

 to be replaced with : 

**correct link** : [example/lib/main.dart](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/share_plus/example/lib/main.dart) 

### Code Sample

```dart
NA
```

### Logs

```shell
NA
```

### Flutter Doctor

```shell
NA
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Thanks for reporting. 
Seems like it is connected with https://github.com/dart-lang/pub-dev/issues/3288
