### ISSUE TITLE
device_info_plus all fields are nullable

### ISSUE THREAD

**Issue by xvrh** [fluttercommunity/plus_plugins#187]
It seems all the fields in the models of `device_info_plus` (ie [`AndroidDeviceInfo`](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus_platform_interface/lib/model/android_device_info.dart), [`IosDeviceInfo`](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus_platform_interface/lib/model/ios_device_info.dart)) are declared nullable.

In the migrated `device_info` package, the same field are non-null: ie [`AndroidDeviceInfo`](https://github.com/flutter/plugins/blob/master/packages/device_info/device_info_platform_interface/lib/model/android_device_info.dart)

Why this difference?

**Comment by Schwusch** [comment]
It seems `device_info` has chosen to default missing values to empty string.
When I tried that strategy initially, it broke a bunch of tests, so I went with the least breaking change.
It's not necessarily the best strategy though, depending on how you want to represent a missing value.

**Comment by miquelbeltran** [comment]
Also worth saying that the fork was done before the migration to null safety, so these type of differences are expected.

IMO if the original code could return null values, the new code should as well, providing empty strings instead changes the functionality.

@xvrh I hope our answers helped clarify your questions, I will close this issue for now.
