### ISSUE TITLE
[windows] [linux] Developing and debugging native plugin code

### ISSUE THREAD

**Issue by gocal** [fluttercommunity/plus_plugins#189]
Hi, I'd like to convert one of the plugins to be compatible with the linux / windows platforms. This requires some native cpp code to be added. Where can I find some hints, information on how can I setup my development process (ide, debugger, intellisense) to be able to easily create and develop a new plugin ?

I've only found information about Android / iOS OEM plugin debugging at https://flutter.dev/docs/testing/oem-debuggers, but it would be really helpful to work with the Windows/Linux debugger as well.

**Comment by mhadaily** [comment]
@gocal  Thanks for this issue and sorry for our delay. 

Which plugin do you want to convert? it seems we have all our plugins supporting Linux at the moment!

@jpnurmi might also be able to help you with Linux development.

**Comment by jpnurmi** [comment]
I like to write generic C++ classes separately in my favourite IDE where I can easily test and debug them. Then I'll just integrate them with the Flutter plugin I'm working on. I don't remember if we actually managed to implement all Linux plugins are pure Dart packages in the end, but at least a few Windows plugins were implemented like this:

- https://github.com/fluttercommunity/plus_plugins/blob/main/packages/battery_plus_windows/windows/system_battery.cpp
- https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus_windows/windows/network_manager.cpp
- ...

**Comment by mhadaily** [comment]
close due to inactivity and answering the question.
