### ISSUE TITLE
[linux] issue in version handling with ffi 

### ISSUE THREAD

**Issue by PrashantSaxena07** [fluttercommunity/plus_plugins#1895]
### What is your question?

Because untitled1 depends on device_info_plus ^9.0.2 which depends on ffi ^2.0.1, ffi ^2.0.1 is required.
So, because untitled1 depends on ffi ^1.0.0, version solving failed.

But other packages of my project are depending uppon 1.0.0, none of the version of device_info is supporting it

my pakcgae list:
  archive: ^3.3.6
  bot_toast: ^4.0.1
  connectivity_plus: ^4.0.1
  convert: ^3.0.2
  cron: ^0.5.1
  cupertino_icons: ^1.0.2
  current_location: ^0.0.3
  data_table_2: ^2.3.5
  datetime_picker_formfield: ^2.0.0
  did_change_dependencies: ^1.0.0
  desktop_lifecycle: ^0.1.0
  desktop_window: ^0.4.0
  device_info_plus: ^7.0.0
  dio: ^5.1.2
  dotted_border: ^2.0.0+3
  dropdown_button2: ^2.1.3
  equatable: any
  ffi: ^1.0.0
  file_picker: ^5.0.0
  firebase_core:
  flutter_bloc: ^8.0.1
  flutter_desktop_sleep: ^0.0.2
  flutter_image_compress: ^1.1.3
  flutter_image: ^4.1.5
  flutter_isolate: ^2.0.4
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  flutter_platform_alert: ^0.3.0
  flutter_to_debian: ^1.0.4
  flutter_window_close: ^0.2.2
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hive_listener: ^1.2.1
  hive: ^2.2.3
  http: ^0.13.4
  image: ^3.0.8
  in_app_notification: ^1.1.2
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.3.1
  jwt_decoder: ^2.0.1
  launch_at_startup: ^0.2.2
  loading_gifs: ^0.3.0
  logger: ^1.1.0
  minio:
  multi_window: ^0.2.0
  network_info_plus: ^3.0.5
  nativeshell: ^0.1.16
  package_info_plus:
  path_provider:
  path: ^1.8.0
  process_run: ^0.13.0
  provider:
  quds_popup_menu: ^0.0.1+1
  rxdart: ^0.27.5
  screen_retriever: ^0.1.3
  sentry_flutter: ^6.19.0
  shared_preferences: ^2.0.7
  shell: ^2.0.0
  system_tray: ^2.0.1
  timer_builder: ^2.0.0
  timezone_utc_offset: ^1.1.0
  timezone: ^0.8.0
  url_launcher: any
  win_capture: ^0.0.4
  win_tracker: ^0.0.6
  window_manager: ^0.3.4
  window_to_front: ^0.0.3
  winhooker: ^0.0.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

Package Name                 Current  Upgradable   Resolvable   Latest       

direct dependencies:        
archive                      -        3.3.7        3.3.7        3.3.7        
bot_toast                    -        4.0.4        4.0.4        4.0.4        
connectivity_plus            -        *3.0.6       4.0.1        4.0.1        
convert                      -        3.1.1        3.1.1        3.1.1        
cron                         -        0.5.1        0.5.1        0.5.1        
current_location             -        0.0.3        0.0.3        0.0.3        
data_table_2                 -        2.5.1        2.5.1        2.5.1        
datetime_picker_formfield    -        2.0.1        2.0.1        2.0.1        
desktop_lifecycle            -        0.1.1        0.1.1        0.1.1        
desktop_window               -        0.4.0        0.4.0        0.4.0        
device_info_plus             -        *4.0.0       *4.0.0       9.0.2        
did_change_dependencies      -        1.0.0        1.0.0        1.0.0        
dio                          -        5.2.0        5.2.0        5.2.0        
dotted_border                -        2.0.0+3      2.0.0+3      2.0.0+3      
dropdown_button2             -        *1.9.4       2.1.3        2.1.3        
equatable                    -        2.0.5        2.0.5        2.0.5        
ffi                          -        *1.2.1       *1.2.1       2.0.2        
file_picker                  -        *4.6.1       *4.6.1       5.3.2        
firebase_core                -        2.13.1       2.13.1       2.13.1       
flutter_bloc                 -        8.1.3        8.1.3        8.1.3        
flutter_desktop_sleep        -        0.0.2        0.0.2        0.0.2        
flutter_image                -        4.1.6        4.1.6        4.1.6        
flutter_image_compress       -        *1.1.3       2.0.3        2.0.3        
flutter_isolate              -        2.0.4        2.0.4        2.0.4        
flutter_local_notifications  -        *9.9.1       *12.0.4      14.1.1       
flutter_native_timezone      -        2.0.0        2.0.0        2.0.0        
flutter_platform_alert       -        *0.3.0       0.4.0        0.4.0        
flutter_to_debian            -        1.0.4        1.0.4        1.0.4        
flutter_window_close         -        0.2.2        0.2.2        0.2.2        
font_awesome_flutter         -        10.4.0       10.4.0       10.4.0       
get_it                       -        7.6.0        7.6.0        7.6.0        
google_fonts                 -        *3.0.1       *4.0.4       5.0.0        
hive                         -        2.2.3        2.2.3        2.2.3        
hive_flutter                 -        1.1.0        1.1.0        1.1.0        
hive_listener                -        1.2.1        1.2.1        1.2.1        
http                         -        *0.13.6      *0.13.6      1.0.0        
image                        -        *3.1.3       *3.1.3       4.0.17       
in_app_notification          -        1.1.2        1.1.2        1.1.2        
intl                         -        *0.17.0      *0.17.0      0.18.1       
json_annotation              -        4.8.1        4.8.1        4.8.1        
json_serializable            -        6.7.0        6.7.0        6.7.0        
jwt_decoder                  -        2.0.1        2.0.1        2.0.1        
launch_at_startup            -        0.2.2        0.2.2        0.2.2        
loading_gifs                 -        0.3.0        0.3.0        0.3.0        
logger                       -        1.3.0        1.3.0        1.3.0        
minio                        -        3.5.0        3.5.0        3.5.0        
multi_window                 -        0.2.0        0.2.0        0.2.0        
nativeshell                  -        0.1.16       0.1.16       0.1.16       
network_info_plus            -        *2.3.2       *3.0.5       4.0.1        
package_info_plus            -        *1.4.2       *1.4.2       4.0.2        
path_provider                -        2.0.15       2.0.15       2.0.15       
process_run                  -        *0.12.5+3    0.13.0       0.13.0       
provider                     -        6.0.5        6.0.5        6.0.5        
quds_popup_menu              -        0.0.1+1      0.0.1+1      0.0.1+1      
rxdart                       -        0.27.7       0.27.7       0.27.7       
screen_retriever             -        0.1.6        0.1.6        0.1.6        
sentry_flutter               -        *6.22.0      7.7.0        7.7.0        
shared_preferences           -        2.1.1        2.1.1        2.1.1        
shell                        -        2.0.0        2.0.0        2.0.0        
system_tray                  -        2.0.3        2.0.3        2.0.3        
timer_builder                -        2.0.0        2.0.0        2.0.0        
timezone                     -        *0.8.0       0.9.2        0.9.2        
timezone_utc_offset          -        1.1.0        1.1.0        1.1.0        
url_launcher                 -        6.1.11       6.1.11       6.1.11       
win_capture                  -        *0.0.4       *0.0.4       0.0.5        
win_tracker                  -        0.0.8        0.0.8        0.0.8        
window_manager               -        *0.2.9       0.3.4        0.3.4        
window_size                  -        0.1.0 (git)  0.1.0 (git)  0.1.0 (git)  
window_to_front              -        0.0.3        0.0.3        0.0.3        
winhooker                    -        0.0.7        0.0.7        0.0.7      

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
You need to either update other dependencies in your project or use the version of `device_info_plus` which is suggested in your output

> device_info_plus - *4.0.0 *4.0.0 9.0.2
