### ISSUE TITLE
[Question]:  Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.22.

### ISSUE THREAD

**Issue by jarvan11** [fluttercommunity/plus_plugins#1900]
### What is your question?

My project use  org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10,The following error occurs in android studio，what should i do？

> Could not resolve all files for configuration ':package_info_plus:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.22.
     Required by:
         project :package_info_plus
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.22.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.7.22/kotlin-gradle-plugin-1.7.22.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.7.22/kotlin-gradle-plugin-1.7.22.pom'.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by GalangPratamaS** [comment]
same issue

**Comment by GalangPratamaS** [comment]
please check your wifi, maybe your internet / wifi have firewall like mine.
my solution is change the wifi source

**Comment by kartik-ashok** [comment]
Hey Did you got solution Please help me If you got?
