### ISSUE TITLE
[Bug]: Signature issue

### ISSUE THREAD

**Issue by jeevanwst** [fluttercommunity/plus_plugins#1901]
### Platform

Android 13

### Plugin

connectivity_plus

### Version

4.0.1

### Flutter SDK

3.10.3

### Steps to reproduce

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/m1proa/.pub-cache/hosted/pub.dev/connectivity_plus-4.0.1/android/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':connectivity_plus'.
> No signature of method: build_89kt74gv4i2tx26bkbte4euk1.android() is applicable for argument types: (build_89kt74gv4i2tx26bkbte4euk1$_run_closure2) values: [build_89kt74gv4i2tx26bkbte4euk1$_run_closure2@d5b1c28]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 739ms
Exception: Gradle task assembleDebug failed with exit code 1

### Logs

```shell
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/m1proa/.pub-cache/hosted/pub.dev/connectivity_plus-4.0.1/android/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':connectivity_plus'.
> No signature of method: build_89kt74gv4i2tx26bkbte4euk1.android() is applicable for argument types: (build_89kt74gv4i2tx26bkbte4euk1$_run_closure2) values: [build_89kt74gv4i2tx26bkbte4euk1$_run_closure2@d5b1c28]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 739ms
Exception: Gradle task assembleDebug failed with exit code 1
```

### Flutter Doctor

```shell
m1proa@m1proa freightcarrier % flutter --version
Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f92f44110e (7 days ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1
m1proa@m1proa freightcarrier % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.1 22C65 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (4 available)
    ! Error: iPhoneSE is busy: Fetching debug symbols for iPhoneSE. Xcode will continue when iPhoneSE is finished. (code -10)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
This issue means that your project uses old version on Android Gradle Plugin in the `build.gradle` file.
You need to have at least version 4.2 to use latest Plus Plugins as stated in changelogs: https://pub.dev/packages/device_info_plus/changelog#900
