### ISSUE TITLE
[Bug]: Outdated Documentation

### ISSUE THREAD

**Issue by XeroDays** [fluttercommunity/plus_plugins#1906]
### Platform

Android

### Plugin

share_plus

### Version

7.0.2

### Flutter SDK

3.10

### Steps to reproduce

Share.shareFiles is lsited in documentation  but it is showing as deprecated  or obsolete .

`Share.shareFiles([imgFile.path], text: 'Great picture');`

<img width="524" alt="image" src="https://github.com/fluttercommunity/plus_plugins/assets/38852291/7d5df836-48db-4021-85f7-d253cbe0799c">

It is showing like this in documentation
<img width="856" alt="image" src="https://github.com/fluttercommunity/plus_plugins/assets/38852291/03dac19e-8bc7-481b-9ca5-cdc23ccc4753">

### Code Sample

```dart
Share.shareFiles([imgFile.path], text: 'Great picture');
```

### Logs

```shell
no
```

### Flutter Doctor

```shell
no
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Thanks for spotting. Feel free to create a PR with a fix for this.
