### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by deepika134** [fluttercommunity/plus_plugins#1910]
I created a sample for the device_info_plus package with the help of the example code snippet provided on [pub.dev](https://pub.dev/packages/device_info_plus/example). However, I am encountering the following exception when running the sample on the Android platform. For your reference, I have attached a sample to replicate the issue on your end. It can be downloaded from the attachment.

**Exception Details:**

<img width="877" alt="Untitled" src="https://github.com/fluttercommunity/plus_plugins/assets/87310214/eef0ff6b-6495-4474-b189-bbb00c780708">

**Flutter Doctor log:**

<img width="617" alt="doctor" src="https://github.com/fluttercommunity/plus_plugins/assets/87310214/caf064f1-3841-4c94-ab06-34180eaca812">

**Package Version** 
 device_info_plus: ^9.0.2

[device_info_plus.zip](https://github.com/fluttercommunity/plus_plugins/files/11737972/device_info_plus.zip)

### Checklist before submitting a question

- [ ] I Google'd a solution and I couldn't find it
- [ ] I searched on StackOverflow for a solution and I couldn't find it
- [ ] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Your project has minSDK for Android set to 16. `device_info_plus` requires at least 19 and aligns with min Android SDK supported by Flutter.

**Comment by peter100u** [comment]
what should ios minSdk  ?
