### ISSUE TITLE
[Bug]: Couldn't share to Instagram

### ISSUE THREAD

**Issue by onguc** [fluttercommunity/plus_plugins#1916]
### Platform

ipad 16.3

### Plugin

share_plus

### Version

7.0.2

### Flutter SDK

3.7.12

### Steps to reproduce

i get this error when i want to share to instagram on my ipad. (no problem on android)
![instagram paylaşımı](https://github.com/fluttercommunity/plus_plugins/assets/13952171/f24de3b6-b569-4eb8-8d1c-f5acb0a62c09)

I also want it to appear like below when posting on Instagram.

![IMG_5B14499E8897-1](https://github.com/fluttercommunity/plus_plugins/assets/13952171/9deb45c4-4c51-4525-861f-868bce7c4fe2)

Does anyone have an idea? Thanks

### Code Sample

```dart
Share.shareFiles(
          [imagePath],
          subject: product.productName ?? "",
          text: product.productUrl ?? "",
          sharePositionOrigin: positionOrigin(isIpad),
        );
```

### Logs

```shell
[+8018 ms] [NSExtension] Extension request contains input items but the extension point does not specify a set of allowed payload classes. The extension point's NSExtensionContext subclass must
implement `+_allowedItemPayloadClasses`. This must return the set of allowed NSExtensionItem payload classes. In future, this request will fail with an error.
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3 22E252 darwin-arm64, locale tr-TR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vijaybheda-bosctech** [comment]
I attempted to share a content and link on Instagram, but encountered an error stating, "Can't send media - Try copying and sending the link instead." 

Could someone assist me in sharing text and a link through the Instagram iOS app?

**Comment by vijaybheda-bosctech** [comment]
> I attempted to share a content and link on Instagram, but encountered an error stating, "Can't send media - Try copying and sending the link instead."
> 
> Could someone assist me in sharing text and a link through the Instagram iOS app?

I've test with other dependencies but it didn’t work.

https://pub.dev/packages/social_share
https://pub.dev/packages/share
https://pub.dev/packages/share_plus
https://pub.dev/packages/flutter_share_me

**Comment by ericdolson** [comment]
Bump! I need this as well. Not being able to share a single image to instagram is a bummer. I would love this to be made available! Thank you :)

**Comment by tchowski** [comment]
Any update on this?

**Comment by vbuberen** [comment]
It is not a bug of plugin, but issue artificially created by Meta for their shitty apps.

**Comment by mohmedelsayed** [comment]
i finally solved this issue ..  this issue is instagram consider image and text caption as multibale image and can't share it due to instagram issue .. to solve , let's consider i have function to share image :
`_shareSheet(File file) async {
    try {
      await Share.shareXFiles([XFile(file.path)], text: "Sayed");
     } catch (error) {
       return;
    }
  }`
to solve issue 
code should be  :
`_shareSheet(File file) async {
    try {
      await Share.shareXFiles([XFile(file.path)], text: null);
     } catch (error) {
       return;
    }
  }`

 so , try to change 
`Share.shareFiles(
          [imagePath],
          subject: product.productName ?? "",
          text: product.productUrl ?? "",
          sharePositionOrigin: positionOrigin(isIpad),
        );`
         to 
         `Share.shareFiles(
          [imagePath],
          subject: null,
          text: null,
          sharePositionOrigin: positionOrigin(isIpad),
        );`

**Comment by Meistro77** [comment]
> i finally solved this issue .. Issue:
> 
> Instagram considers image and text caption as multiple images, preventing successful sharing due to an Instagram issue. The original _shareSheet function was designed to share an image with a text caption. To address the problem, it is recommended to modify the function as follows:
> 
> Original Function: _shareSheet(File file) async { try { await Share.shareXFiles([XFile(file.path)], text: "Mohamed El-Sayed"); } catch (error) { return; } }
> 
> Modified Function:
> 
> _shareSheet(File file) async { try { await Share.shareXFiles([XFile(file.path)], text: null); } catch (error) { return; } }
> 
> This change ensures that when sharing an image, no text is included, resolving the issue with Instagram's interpretation.
> 
> Additionally, there's a recommendation to update the usage of Share.shareFiles in the code. The original usage: Share.shareFiles( [imagePath], subject: product.productName ?? "", text: product.productUrl ?? "", sharePositionOrigin: positionOrigin(isIpad), ); Should be updated to:
> 
> Share.shareFiles( [imagePath], subject: null, text: null, sharePositionOrigin: positionOrigin(isIpad), );
> 
> This change aligns with the modified _shareSheet function, ensuring that no text is shared along with the image.
> 
> Please review and consider implementing these changes to address the Instagram sharing issue.

You available for hire?

**Comment by arslankaleem7229** [comment]
> Meistro77


Instagram Story posting don't work but resolved other issues. Thanks

**Comment by sushrutshelf** [comment]
how to then use the same share to share to messenger apps with link? Is there any way around this or do i need to build my custom UI sharing. 
If instagram: text null
If other: product URL

**Comment by FarhanSajid1** [comment]
> how to then use the same share to share to messenger apps with link? Is there any way around this or do i need to build my custom UI sharing. If instagram: text null If other: product URL

I was thinking we need a way to be able to determine which social media platform we are sharing to and what type of share it is? Like for example, I noticed if we want to share to Instagram, but share as a story, we have to add in the text. If we want to share to instagram as a story or post, we have to remove the text. Though this isn't ideal, we should be able to do all of them in one shot, and use the text if it's a reel

**Comment by RyotaroIsoyama** [comment]
I believe the issue can be resolved by checking if the activity type is Instagram and preventing the text from being passed in the following function:

```
activityViewController:(UIActivityViewController *)activityViewController
         itemForActivityType:(UIActivityType)activityType
```
The check can be performed like this:

`if([activityType isEqualToString:@"com.burbn.instagram.shareextension"])`

In the `(void)shareFiles:` function, SharePlusData objects for both images and text are created and added to a list. I thought the solution might be to exclude the text SharePlusData from the list when the activity type is Instagram. However, since I'm not very familiar with Objective-C, I wasn't able to implement the fix myself.

Does anyone have a solution for this?
