### ISSUE TITLE
[Bug]: version 3.0.5 is not require sdk 2.1.2 , its show error and need > 2.18

### ISSUE THREAD

**Issue by yogithesymbian** [fluttercommunity/plus_plugins#1924]
### Platform

7

### Plugin

connectivity_plus

### Version

3.0.5

### Flutter SDK

2.17.6

### Steps to reproduce

wrong documentation

### Code Sample

```dart
-
```

### Logs

```shell
-
```

### Flutter Doctor

```shell
-
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Could you be more clear on what you are trying to report?
