### ISSUE TITLE
[network_info_plus 1.0.0][Windows] - winsock2.h

### ISSUE THREAD

**Issue by Carl-CWX** [fluttercommunity/plus_plugins#193]
Building for windows the build fails with many errors. The problem relates to including winsock2.h after windows.h.

Moving `#include <winsock2.h>` to before `#include <windows.h>` solves the issue
Moving `#include "include/network_info_plus_windows/network_info.h"` above other includes like plugin_registrar_windows.h is needed too as they include windows.h

Moving the headers around then builds cleanly.

## System info

Issue occurs on: Windows
Plugin name: network_info_plus
Plugin version: v1.0.0
Flutter doctor output:

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.18363.1440], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
[√] Android Studio (version 3.5)
[√] Connected device (3 available)
```

## Steps to Reproduce

Add to plugin to project from pub.dev and build

**Comment by YowFung** [comment]
Detailed operation: #202
