### ISSUE TITLE
[Bug]: Android `getSerial` should be removed (or at least have a flag), otherwise app stores are rejecting the app

### ISSUE THREAD

**Issue by fzyzcjy** [fluttercommunity/plus_plugins#1948]
Hi thanks for the packages! However, in some app stores, it is forbidden to call `getSerial` (without writing it in privacy doc - but I never really need it, so should not write in that doc), and the app gets rejected.

In https://github.com/fluttercommunity/plus_plugins/issues/948, @vbuberen said:

> On iOS Apple forbids to get unique device identifiers like serial number. Google goes the same way, so it makes no sense in adding this functionality, even if it is planned to be used on old versions of iOS or Android.

However, IMHO this functionality is already in the latest package:

https://github.com/fluttercommunity/plus_plugins/blob/7ddbfb50028287dee0e3fcb30f33d05d3c32faeb/packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt#L84

Therefore, I propose to remove it, or at least provide a flag to not trigger this function call. It is because, if you call `Build.getSerial()`, no matter what Android system returns, your app is already marked as rejected by the app stores.

P.S. Currently I did this very simple hack: https://github.com/fzyzcjy/plus_plugins/commit/81d5cd9134267122260c6e27fb17ac153301ec8b 

### Platform

Android latest

### Plugin

device_info_plus

### Version

latest

### Flutter SDK

latest

### Steps to reproduce

Try to publish apps which calls device_info_plus to app stores.

### Logs

```shell
N/A
```

### Flutter Doctor

```shell
latest
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
You needed to search better for reasoning about getting serial into the package as there was also #840 where you can find the explanation on why it was added.

What bugs me here is how you get rejected due to this reason as I currently have like 5 ongoing projects which have `device_info_plus` and publish updates of the app on a bi-weekly basis. During the last year I haven't seen a single rejection with this reason 🤔 and the apps are for different countries.

While I agree that we shouldn't use identifiers the reasoning in #840 is Ok and since there were no reports so far about some being rejected due to having `getSerial` in code, I am not really convinced that we need to drop the functionality. 

Could you share some info/screenshots about this rejection?

**Comment by fzyzcjy** [comment]
@vbuberen Hi thanks for the information

> You needed to search better for reasoning about getting serial into the package as there was also https://github.com/fluttercommunity/plus_plugins/issues/840 where you can find the explanation on why it was added.

As is mentioned in the title, it would be great to at least have a flag enabling/disabling it. I totally agree it is definitely added for a reason :)

> What bugs me here is how you get rejected due to this reason
Could you share some info/screenshots about this rejection?
UPD: Ah, I missed that it is not about the Google Play Store, but something else.

Yes, it is not Google Play, but app stores in China. The stores automatically checks calls like this, and require me to add some sentences in privacy contract documentation explicitly saying my app needs this privacy data. However, as you know, since I never need it, I should not write that paragraph in doc - otherwise it is not the fact.

**Comment by vbuberen** [comment]
> As is mentioned in the title, it would be great to at least have a flag enabling/disabling it.

It reminds me the situation with Android ID we had a year ago. 
Potentially, we could think about doing something similar and move serial into a different package, as I don't see a good way of doing some flag that would allow to avoid automatic checks like you described.

**Comment by fzyzcjy** [comment]
> as I don't see a good way of doing some flag that would allow to avoid automatic checks like you described.

It seems the check is done dynamically, i.e. as long as we do not execute that line we are safe. Thus maybe simply pass an argument from Dart is enough.

**Comment by vbuberen** [comment]
I thought about it more and would like to test a permission check via `PackageInfo()` before calling `getSerial()`. I will create a branch with such check and would ask you to check if it would allow to avoid being automatically rejected.

**Comment by fzyzcjy** [comment]
@vbuberen Thank you, I will try that when available1

**Comment by vbuberen** [comment]
Here is the branch: https://github.com/vbuberen/plus_plugins/tree/refactor/device_info

You can try it out like this:
```
device_info_plus:
       git:
         url: git://github.com:vbuberen/plus_plugins.git
         ref: refactor/device_info
```

Unfortunately, I see that check that I have added are not enough to handle all cases when some app can request serial, so don't think this change can be merged into the plugin and released in its current form.

**Comment by fzyzcjy** [comment]
> Unfortunately, I see that check that I have added are not enough to handle all cases when some app can request serial, so don't think this change can be merged into the plugin and released in its current form.

Hmm so will this approach be used in the master branch? e.g. if there are other checks to be added, I will wait for those and test once, since I do not want to get rejected for too many times (which I am worried whether me or my app will be marked as something like "bad app").

**Comment by vbuberen** [comment]
> Hmm so will this approach be used in the master branch?

I still need to find the way to check all 4 conditions (from https://developer.android.com/reference/android/os/Build#getSerial()) including device owner mode, which was something that the author of PR with serial retrieving was using. In case we can check all 4 conditions then yes, it will be merged into main. Otherwise, having only permission check will break functionality for some users who comply with other conditions Google has for this function.

**Comment by fzyzcjy** [comment]
I see. Then I may need to wait for that.

**Comment by liang-notes** [comment]
> > Hmm so will this approach be used in the master branch?
> 
> I still need to find the way to check all 4 conditions (from https://developer.android.com/reference/android/os/Build#getSerial()) including device owner mode, which was something that the author of PR with serial retrieving was using. In case we can check all 4 conditions then yes, it will be merged into main. Otherwise, having only permission check will break functionality for some users who comply with other conditions Google has for this function.

Hi @vbuberen   We also met this compliance issue recently. When this approach be used in master?

**Comment by vbuberen** [comment]
Unfortunately, I wasn't able to find a way to check all 4 conditions when the app is allowed to get serial number, so no updates here. In case there is somebody who knows how to implement it - I would appreciate such a PR into the plugin.
