### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mostafaalimorsy** [fluttercommunity/plus_plugins#1951]
### Platform

all

### Plugin

package_info_plus_windows-1.0.5

### Version

1.0.5

### Flutter SDK

3.10.2

### Steps to reproduce

when run or build release 

### Logs

```shell
../../../.pub-cache/hosted/pub.dev/package_info_plus_windows-1.0.5/lib/src/file_version_info.dart:13:17: Error: Field 'wLanguage' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? wLanguage;
                ^
../../../.pub-cache/hosted/pub.dev/package_info_plus_windows-1.0.5/lib/src/file_version_info.dart:16:17: Error: Field 'wCodePage' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? wCodePage;
                ^
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0 22A380 darwin-x64, locale
    en-US)
    • Flutter version 3.10.2 on channel stable at
      /Users/mmorsy/flutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (6 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mmorsy/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Redmi Note 9S (mobile) • 18b5bb36 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)        • macos    • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
The package `package_info_plus_windows` is discontinued and not maintained anymore as stated on this page: https://pub.dev/packages/package_info_plus_windows
Switch to just `package_info_plus` instead.

**Comment by mostafaalimorsy** [comment]
Yes, I use it but this error I had

**Comment by vbuberen** [comment]
`package_info_plus_windows-1.0.5` in your logs indicate that you use a very old version of the plugin. Update to the latest one, because 1.0.5 was long before discontinuing `package_info_plus_windows`, so of course it is not compatible with latest null safety requirements.

**Comment by mostafaalimorsy** [comment]
Yes, I have to use it because my project is old and that version fits with others, I could fix it in the local cache but when I try to use CI/CD I face it

**Comment by fiizzy** [comment]
@mostafaalimorsy any update on this error? Were you able to get it fixed?

**Comment by fiizzy** [comment]
In case anyone has this issue, I was able to solve it by:
1. use `any` for any dependency version conflict you might have that causes your `pub get ` to exit with `code 1`
2. After using `any`, run `pub get`, it should successfully work with` exit code 0`. Make sure you check the `pubspec` log for the specific dependency version that you just updated, which `pub get` intelligently got for you.
3. Now, change the original dependency version (`any`) back to 2 above with the correct version from the printed log ( just so you can keep track of the package version)
