### ISSUE TITLE
[android_intent] Clean-up iOS subproject

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#196]
We must rename channel name in our plus plugins 

 private static final String CHANNEL_NAME = "plugins.flutter.io/android_intent";

**Comment by miquelbeltran** [comment]
Why?

They are currently named "dev.fluttercommunity.plus/android_intent" so it doesn't conflict with the original plugin.

**Comment by mhadaily** [comment]
ops, sorry it seems I search and I found this https://github.com/fluttercommunity/plus_plugins/blob/92798cfbd217d45933fd9d8d3d5735d86a5ea379/packages/android_intent_plus/ios/Classes/AndroidIntentPlugin.m

this is probably a mistake by me, you can ignore it then. It funny because on my local machine I also can find this channel name!

**Comment by miquelbeltran** [comment]
Oh I see, but also this is weird because that's the iOS code for the android-only plugin. Let me rename this ticket and keep it open.

**Comment by mhadaily** [comment]
this might also be helpful https://github.com/fluttercommunity/plus_plugins/blob/92798cfbd217d45933fd9d8d3d5735d86a5ea379/packages/android_intent_plus/android/src/test/java/io/flutter/plugins/androidintent/MethodCallHandlerImplTest.java

**Comment by mhadaily** [comment]
We still have ```[FlutterMethodChannel methodChannelWithName:@"plugins.flutter.io/android_intent"``` 

https://github.com/fluttercommunity/plus_plugins/blob/main/packages/android_intent_plus/ios/Classes/AndroidIntentPlugin.m#L18-L19

should we consider removing/renaming this?

**Comment by mhadaily** [comment]
sending a PR here https://github.com/fluttercommunity/plus_plugins/pull/410

**Comment by fabiancrx** [comment]
Is this still an issue after #410  got merged ?

**Comment by miquelbeltran** [comment]
thanks for noticing @fabiancrx
