### ISSUE TITLE
[Bug]:  Connectivity Plus won't compile with flutter `>=3.3.0`

### ISSUE THREAD

**Issue by xsahil03x** [fluttercommunity/plus_plugins#1960]
### Platform

ALL

### Plugin

Connectivity Plus

### Version

^4.0.0

### Flutter SDK

3.3.10

### Steps to reproduce

1. Add `connectivity_plus: ^4.0.0` to a brand new app using Flutter 3.3.10.
2. flutter pub get

### Logs

```shell
Because connectivity_plus >=3.0.0 depends on flutter_web_plugins from sdk which depends on js 0.6.4, connectivity_plus >=3.0.0 requires js 0.6.4.
So, because example depends on connectivity_plus ^4.0.0 which depends on js ^0.6.5, version solving failed.
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.4.1 22F82 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by xsahil03x** [comment]
Linked [PR](https://github.com/fluttercommunity/plus_plugins/pull/1740) which updated the `js` dependency.

**Comment by xsahil03x** [comment]
@vbuberen can you please take a look?

**Comment by vbuberen** [comment]
Yes, sure. Have a limited availability due to multiple reasons, but will take a look today. Thanks for ping.

**Comment by xsahil03x** [comment]
@vbuberen you might also want to consider adding `ci` checks for the packages. This is how we do it in [stream_chat](https://github.com/GetStream/stream-chat-flutter/blob/develop/.github/workflows/legacy_version_analyze.yml). But for a more general approach you can look into this [PR](https://github.com/flutter/packages/pull/4428) in `flutter/packages`.
