### ISSUE TITLE
[Question]: is it working on android to run every 5s?

### ISSUE THREAD

**Issue by webroy** [fluttercommunity/plus_plugins#1964]
### What is your question?

this doesn't run every 5 seconds. every interation has an other delay between.

await AndroidAlarmManager.periodic(const Duration(seconds: 5), alarmID, backgroundPositionTracker,
      allowWhileIdle: true, exact: true, rescheduleOnReboot: true, wakeup: true);

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [x] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by aakash-pamnani** [comment]
I think minimum duration to set a repeating alarm is 60 seconds. You cannot set alarm less than 60 seconds.
