### ISSUE TITLE
[Bug]: Using intent package crashes the realm based app in release builds

### ISSUE THREAD

**Issue by milindgoel15** [fluttercommunity/plus_plugins#1968]
### Platform

Android 13

### Plugin

android intent plus

### Version

4.0.1

### Flutter SDK

3.10.5

### Steps to reproduce

1. Added android intent plus.
2. Built a release apk
3. The app crashes with realmexception

```console
realmexception: error opening realm at path ./default.realm. error code: 1018 . message: failed to open file at path './default.realm.lock': read-only file system flutter
```
Also, weirdly, while building the release apk with the plugin, it outputs all the files to android/app/build/outputs and build/app/outputs/flutter-apk folders instead of the usual build/app/outputs folders only.

### Logs

```shell
These are the logs from debug variant of prod release. (i ran with prod flavor tho) Any debug variant works fine. Release build doesnt

https://pastebin.com/14r4cw4Z
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1992], locale en-IN)
    • Flutter version 3.10.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • ANDROID_SDK_ROOT = C:\Users\Lenovo\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code, 64-bit edition (version 1.80.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.66.0

[✓] Connected device (1 available)
    • 2109119DI (mobile) • 417812e0 • android-arm64 • Android 13 (API 33)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by milindgoel15** [comment]
An update to this issue. I am not sure if it's a plugin issue or a Gradle problem. But in my case, I solved this by changing the subProjects block present in Android/build.gradle file back to 2 separate blocks. For some reason, having them combined raises the realm exception as mentioned above, breaking the app only after adding the intent package.

**Comment by vbuberen** [comment]
> But in my case, I solved this by changing the subProjects block present in Android/build.gradle file back to 2 separate blocks. For some reason, having them combined raises the realm exception as mentioned above, breaking the app only after adding the intent package.

Could you please share a code snippet on what changed and helped you? Would appreciate it as didn't get what was the solution.

**Comment by milindgoel15** [comment]
Any update on this? We can close this issue if it's something not fixable on the plugin's end.
