### ISSUE TITLE
[Bug]: Deprecated and unsafe operatins while using android_intent_plus

### ISSUE THREAD

**Issue by milindgoel15** [fluttercommunity/plus_plugins#1969]
### Platform

Android

### Plugin

android intent plus

### Version

4.0.1

### Flutter SDK

3.10.5

### Steps to reproduce

Add android_intent_plus and build debug/release apk.
It will display warnings:

Note: C:\Users\Lenovo\AppData\Local\Pub\Cache\hosted\pub.dev\android_intent_plus-4.0.1\android\src\main\java\dev\fluttercommunity\plus\androidintent\IntentSender.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Lenovo\AppData\Local\Pub\Cache\hosted\pub.dev\android_intent_plus-4.0.1\android\src\main\java\dev\fluttercommunity\plus\androidintent\MethodCallHandlerImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

### Logs

```shell
Note: C:\Users\Lenovo\AppData\Local\Pub\Cache\hosted\pub.dev\android_intent_plus-4.0.1\android\src\main\java\dev\fluttercommunity\plus\androidintent\IntentSender.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Lenovo\AppData\Local\Pub\Cache\hosted\pub.dev\android_intent_plus-4.0.1\android\src\main\java\dev\fluttercommunity\plus\androidintent\MethodCallHandlerImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1992], locale en-IN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Android Studio (version 2022.2)
[✓] VS Code, 64-bit edition (version 1.80.1)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
These are not bugs an there is an intentional use of some functions due to the plugin supporting multiple Android versions.
