### ISSUE TITLE
[Bug]: Facing an issue with the latest iOS version (iOS 16.5.1) while using the Connectivity Check Listener. The problem is that the listener seems to be continuously calling without network switches from mobile data to Wi-Fi or vice versa.

### ISSUE THREAD

**Issue by MadavaramRamesh** [fluttercommunity/plus_plugins#1984]
### Platform

iOS 16.5.1

### Plugin

connectivity_plus

### Version

4.0.1

### Flutter SDK

3.7.8

### Steps to reproduce

1. Install the latest version of  iOS 16.5.1.
2. Implement the Connectivity Check Listener.
3. See the listener calling without switching networks between mobile data and Wi-Fi.

### Code Sample

```dart
late StreamSubscription<ConnectivityResult> _connectivitySubscription;
_connectivitySubscription = Connectivity()
        .onConnectivityChanged
        .listen((ConnectivityResult result) {
      if (result == ConnectivityResult.mobile ||
          result == ConnectivityResult.wifi) {
        callAPIs();
      }
    });
```

### Logs

```shell
-
```

### Flutter Doctor

```shell
apples-MacBook-Pro:ios apple$ flutter doctor -v 
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.0.1 22A400 darwin-x64, locale en-US)
    • Flutter version 3.7.8 on channel stable at /Users/apple/Documents/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (4 months ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Users/apple/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.248

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by mariam-wahba** [comment]
@MadavaramRamesh  same issue

**Comment by mariam-wahba** [comment]
Hello everyone, 

I removed connectivity_plus plugin and i replaced it with this code instead and it worked very well.

class BaseRepository {
  Future<bool> hasNetwork() async {
    bool resultNetwork = false;
    //   await Connectivity().checkConnectivity().then((value) {
    //     if (value == ConnectivityResult.mobile) {
    //       // I am connected to a mobile network.
    //       result = true;
    //     } else if (value == ConnectivityResult.wifi) {
    //       // I am connected to a wifi network.
    //       result = true;
    //     } else {
    //       result = false;
    //     }
    //   });
    //   return result;
    // }

    try {
      final result = await InternetAddress.lookup('google.com');
      if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
        if (result[0].type == InternetAddressType.IPv4) {
          resultNetwork = true;
        }
        print("Connected via WiFi");
      } else if (result[0].type == InternetAddressType.IPv6) {
        resultNetwork = true;
        print("Connected via Cellular Data");
      }
      return resultNetwork;
    } on SocketException catch (e) {
      print("No network connectivity: ${e.message}");
      return false;
    }
  }
}
