### ISSUE TITLE
[Bug]: Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10

### ISSUE THREAD

**Issue by Abolfazl-MI** [fluttercommunity/plus_plugins#2018]
### Platform

+9

### Plugin

share_plus

### Version

7.1.0

### Flutter SDK

3.10.6

### Steps to reproduce

as I always I just add share_plus with command of `flutter pub add share_plus`
then I use the share x file function like this 
then I try to run the app for firs time without testing the functionality I got this error

### Code Sample

```dart
await screenshotController
            .captureFromWidget(storyWidget)
            .then((bites) async {
          String tempDir = (await getTemporaryDirectory()).path;
          File imageFile =
              File('$tempDir/${DateTime.now().microsecondsSinceEpoch}.png');
          imageFile.createSync();
          _imagePath = imageFile.path;
          log(imageFile.path);
        }).then((value) async {
          final result = await Share.shareXFiles([XFile(_imagePath)],text: 'Install ravin to read your own quotes');
        });```
```

### Logs

```shell
Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
```

### Flutter Doctor

```shell
╭─abolfazl@abolfazl ~ 
╰─$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.2 LTS 5.19.0-50-generic,
    locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at
      /home/abolfazl/dev/flutter_linux_3.7.8-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/abolfazl/Android/Sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at:
      /home/abolfazl/dev/android-studio-2022.1.1.21-linux(2)/android-studio/jbr/
      bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.1)
    • Android Studio at
      /home/abolfazl/dev/android-studio-2022.1.1.21-linux(2)/android-studio
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • Linux (desktop)         • linux         • linux-x64      • Ubuntu 22.04.2
      LTS 5.19.0-50-generic
    • Chrome (web)            • chrome        • web-javascript • Google Chrome
      115.0.5790.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by iamcaominhtien** [comment]
I have the same issue and i found the solution. Go to build.gradle of share_plus-7.1.0 and change
     from: implementation 'androidx.core:core-ktx:1.10.1'
     to: implementation 'androidx.core:core-ktx:1.9.0'
Hope this help!

**Comment by hatch01** [comment]
How do you manage to do it?
Do you fork the repo and modify it in your fork, and then depend on it with git?

**Comment by hatch01** [comment]
> I have the same issue and i found the solution. Go to build.gradle of share_plus-7.1.0 and change from: implementation 'androidx.core:core-ktx:1.10.1' to: implementation 'androidx.core:core-ktx:1.9.0' Hope this help!

How do you manage to do it?
Do you fork the repo and modify it in your fork, and then depend on it with git?

**Comment by iamcaominhtien** [comment]
> > I have the same issue and i found the solution. Go to build.gradle of share_plus-7.1.0 and change from: implementation 'androidx.core:core-ktx:1.10.1' to: implementation 'androidx.core:core-ktx:1.9.0' Hope this help!
> 
> How do you manage to do it?
> Do you fork the repo and modify it in your fork, and then depend on it with git?
> 

I fixed it directly on the share_plus library that I downloaded from pub.dev, I just made a simple app so I didn't use anything else to manage it.

**Comment by NdegwaJulius** [comment]
> Ok, after a lot of testing, on Flutter stable, 3.10.6, here is what I found, but I don't understand what really append. I created a new project with `flutter create myproject`. If I add share_plus with `flutter pub add share_plus`. Then if modify the minSdkVersion to 19. However, it fails to compile with this log :
> 
> ```
> Resolving dependencies... 
>   collection 1.17.1 (1.18.0 available)
>   matcher 0.12.15 (0.12.16 available)
>   material_color_utilities 0.2.0 (0.8.0 available)
>   source_span 1.9.1 (1.10.0 available)
>   stack_trace 1.11.0 (1.11.1 available)
>   stream_channel 2.1.1 (2.1.2 available)
>   test_api 0.5.1 (0.6.1 available)
> Got dependencies!
> 
> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1336 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkReleaseDuplicateClasses'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.internal.jdk7.JDK7PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.internal.jdk7.JDK7PlatformImplementations$ReflectSdkVersion found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.io.path.ExperimentalPathApi found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.io.path.PathRelativizer found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.io.path.PathsKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.io.path.PathsKt__PathReadWriteKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.io.path.PathsKt__PathUtilsKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.jdk7.AutoCloseableKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.random.jdk8.PlatformThreadLocalRandom found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$1 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$2 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$3 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$4 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
> 
>      Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 39s
> Running Gradle task 'assembleRelease'...                           39,7s
> Gradle task assembleRelease failed with exit code 1
> ```
> 
> If I modify in android/build.gradle the line `classpath 'com.android.tools.build:gradle:7.3.0'` to `classpath 'com.android.tools.build:gradle:7.4.2'`, I get these warnings:
> 
> ```
> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1336 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkReleaseDuplicateClasses'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.internal.jdk7.JDK7PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.internal.jdk7.JDK7PlatformImplementations$ReflectSdkVersion found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.io.path.ExperimentalPathApi found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.io.path.PathRelativizer found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.io.path.PathsKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.io.path.PathsKt__PathReadWriteKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.io.path.PathsKt__PathUtilsKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.jdk7.AutoCloseableKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk7-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10)
>      Duplicate class kotlin.random.jdk8.PlatformThreadLocalRandom found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$1 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$2 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$3 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$4 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
> 
>      Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 20s
> Running Gradle task 'assembleRelease'...                           20,7s
> Gradle task assembleRelease failed with exit code 1
> ```
> 
> Lastly, if I add image_picker of file_selector dependency with `flutter pub add file_selector`, it builds perfectly without errors :
> 
> ```
> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1336 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
> Running Gradle task 'assembleRelease'...                           25,0s
> ✓  Built build/app/outputs/flutter-apk/app-release.apk (17.2MB).
> ```
> 
> Does anyone have an idea on why this is happening?
> 
> Ps : at each build, I run `flutter clean ; flutter build apk`

I'm still facing the same issue as you

**Comment by yamadade** [comment]
I was able to get rid of the error by commenting out the following part of build.gradle.


-share_plus-7.10.0 
  - android
   -  build.gradle


```gradle
        implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
     //  implementation 'androidx.core:core-ktx:1.9.1'    <= this
        implementation 'androidx.annotation:annotation:1.5.0'
```

**Comment by pyrossh** [comment]
`flutter pub add file_selector` fixed this for me even though I don't use that package.

**Comment by pyrossh** [comment]
This also works as I didn't want an unused package, Add this to your `android/app/build.gradle`
```
configurations.all {
    resolutionStrategy {
        eachDependency {
            if ((requested.group == "org.jetbrains.kotlin") && (requested.name.startsWith("kotlin-stdlib"))) {
                useVersion("1.8.0")
        }
    }
}
```

**Comment by hsynshnl** [comment]
> `flutter pub add file_selector` fixed this for me even though I don't use that package.

yes it worked for me too

**Comment by xsahil03x** [comment]
Add this to your android dependencies.

```gradle
// org.jetbrains.kotlin:kotlin-bom artifact purpose is to align kotlin stdlib and related code versions.
// See: https://youtrack.jetbrains.com/issue/KT-55297/kotlin-stdlib-should-declare-constraints-on-kotlin-stdlib-jdk8-and-kotlin-stdlib-jdk7
implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.10"))
```

**Comment by MuhammadArslan-apex** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/2052#issuecomment-1689208215
this one solved my problem

**Comment by koraybalci** [comment]
> [#2052 (comment)](https://github.com/fluttercommunity/plus_plugins/issues/2052#issuecomment-1689208215) this one solved my problem. Upgrading ext.kotlin_version = '1.7.10' to '1.8.10' fixed the issue. in android/build.gradle

> `flutter pub add file_selector` fixed this for me even though I don't use that package.

Both of the above suggestions created following problem (although succeeding the build of apk) for me:
```
.gradle/caches/transforms-3/c4988ff80110f75080a936fc6f044848/transformed/core-1.10.1/jars/classes.jar!/META-INF/core_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
```

I then tried to upgrade my `android` in my flutter project by deleting the folder and rerunning `flutter create .` as mentioned in https://stackoverflow.com/a/69490239/68887
A few changes happened in android folder regarding gradle (git diff) apparently, but still the above issue (warning?) persists.

I also tried to update Android SDK (v34 updates were pending) via Android Studio. Not helped, still the above error.

**Comment by koraybalci** [comment]
This is what helped me to get rid of the above issue: https://stackoverflow.com/a/76372243/68887

**Comment by KangZayd** [comment]
> [#2052 (comment)](https://github.com/fluttercommunity/plus_plugins/issues/2052#issuecomment-1689208215) this one solved my problem. Upgrading ext.kotlin_version = '1.7.10' to '1.8.10' fixed the issue. in android/build.gradle

Worked for me.

**Comment by PenguinBIUBIUBIU** [comment]
> `flutter pub add file_selector` fixed this for me even though I don't use that package.

i change nothing but this command, works fine!

**Comment by miquelbeltran** [comment]
Probably because of this:

https://github.com/flutter/packages/blob/b966e748f10d8b457bea6ecd35ca34735e1d683f/packages/file_selector/file_selector_android/android/build.gradle#L46-L48

I remember discussing this issue with @vbuberen (sorry for the mention), and he also sent me this document from the Flutter team with a proposal to solve the issue: https://docs.google.com/document/d/1qeeM5QG-jiafttSgvc7yvC19IDRggFFZQTktBVxL6sI/edit?resourcekey=0-HLEAiBOMxAlQxDs-mEeffw

We do not use `implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.10"))` in our plugins, but we should probably try this.

Meanwhile, if you add that dependency to your own Flutter project, that would have the same effect as adding the `file_selector` plugin.

Does anyone have a sample project with this issue, so I can do some research?

**Comment by vbuberen** [comment]
> We do not use implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.10")) in our plugins, but we should probably try this.

We don't need to do this. This is the issue that happened somewhere in Kotlin 1.8.x where different versions were not resolving properly. Here is the issue in the issue tracker of Jetbrains: https://youtrack.jetbrains.com/issue/KT-54136/Duplicated-classes-cause-build-failure-if-a-dependency-to-kotlin-stdlib-specified-in-an-android-project

I have already provided the solution previously that can helps for this case in another issue: https://github.com/fluttercommunity/plus_plugins/issues/1673#issuecomment-1523203485

So this needs no action from plugins side, but users to update their project's/plugin's Kotlin version.

**Comment by vbuberen** [comment]
One more thing that I noticed is that after updating to Kotlin 1.9.20 such workarounds are not needed as it is fixed by Jetbrains themselves.

In the issue that is mentioned in that file_selector Gradle file such fix commit for 1.9.20 is mentioned as well: https://github.com/jetbrains/kotlin/commit/aaa068596c1bf6210e4f72ad6e1744f19c9eca75

**Comment by tmps-TuTM** [comment]
> Add this to your android dependencies.
> 
> ```groovy-gradle
> // org.jetbrains.kotlin:kotlin-bom artifact purpose is to align kotlin stdlib and related code versions.
> // See: https://youtrack.jetbrains.com/issue/KT-55297/kotlin-stdlib-should-declare-constraints-on-kotlin-stdlib-jdk8-and-kotlin-stdlib-jdk7
> implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.10"))
> ```


It's working for me, thanks

**Comment by Tergeltengis** [comment]
Here is my solution in flutter:

`android/gradle/settings.gradle`
```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false  // <-----this row
}
```
to 

```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.8.0" apply false // <-----this row
}
```

**Comment by paramjeet198** [comment]
I have the same issue, when i added share_plus package to my project.

After updating kotlin plugin to latest version, Issue has been resolved:
Old version:     id "org.jetbrains.kotlin.android" version "1.7.10" apply false
New version:      id "org.jetbrains.kotlin.android" version "1.9.24" apply false

![image](https://github.com/user-attachments/assets/fabee46f-6bfb-4e68-8a05-3008392a1a0e)
