### ISSUE TITLE
package_info_plus for linux returns empty `packageName`

### ISSUE THREAD

**Issue by marandaneto** [fluttercommunity/plus_plugins#203]
expected to return `name` from `pubspec.yaml` or, (`BINARY_NAME` or `APPLICATION_ID`) from `CMAKELists.txt`, but at least an App's identifier.

**Comment by miquelbeltran** [comment]
Confirmed that on Linux the Package Name appears as "Not set" when running the example:

![image](https://user-images.githubusercontent.com/2494376/115228720-691e2a80-a112-11eb-89e1-1b7214487e5d.png)

On MacOS it appears `io.flutter.plugins.packageInfoExample` in contrast.

**Comment by mhadaily** [comment]
@jpnurmi can you take a look at this when you have time?

**Comment by jpnurmi** [comment]
The package information is fetched from `version.json` which is written by the Flutter tool. For some reason Flutter does not write any package name there:
https://github.com/flutter/flutter/blob/49733a485075305b2e62edf9cfe4dbffe901d72e/packages/flutter_tools/lib/src/project.dart#L349

**Comment by mhadaily** [comment]
correct, that also applied to `web` I don't think we can do much here unless we figure out why there is no packageName in `version.json`, I have opened an issue here, let's see if we get any response. https://github.com/flutter/flutter/issues/84107

**Comment by mhadaily** [comment]
I sent a PR https://github.com/flutter/flutter/pull/88457

**Comment by fabiancrx** [comment]
@mhadaily should package name be added to `package_info_plus_linux` and `package_info_plus_web` although with its current implementation(from your PR flutter/flutter/#88457) it would return the same app name for both web and linux package_name ?
![image](https://user-images.githubusercontent.com/37002358/161322644-ec12f4d8-ff04-4094-bc4e-3461de8eba79.png)

**Comment by mhadaily** [comment]
yes please do that @fabiancrx and @jpnurmi will review later. thank you
