### ISSUE TITLE
[Request]: Make BaseDeviceInfo sealed

### ISSUE THREAD

**Issue by SunlightBro** [fluttercommunity/plus_plugins#2033]
### Plugin

device_info_plus

### Use case

Support Dart 3 [class modifiers](https://dart.dev/language/class-modifiers).
To allow switch statements over `BaseDeviceInfo`.

### Proposal

BaseDeviceInfo could be a `sealed` class so the compiler allows
exhaustive pattern matching over baseDeviceInfo

```dart
final info = await DeviceInfoPlugin().deviceInfo;

final string = switch (info) {
  AndroidDeviceInfo() => 'android',
  IosDeviceInfo() => 'iOS',
  LinuxDeviceInfo() => 'linux',
  MacOsDeviceInfo() => 'mac',
  WebBrowserInfo() => 'web',
  WindowsDeviceInfo() => 'win',
}
```

**Comment by vbuberen** [comment]
Thanks for suggestion, but for now we don't have plans to force users to move to Dart 3. But later we will definitely consider this improvements.
