### ISSUE TITLE
[Request]:  Get IP Address of Cellular network.

### ISSUE THREAD

**Issue by khanjasir90** [fluttercommunity/plus_plugins#2036]
### Plugin

connectivity_plus

### Use case

Sometimes user may be connected to cellular network and we would require the ip address of the same.

### Proposal

Now connectivity plus only gets the ip address of wifi network that you are connected, I propose that there should also be a way to get the ip address of the cellular network.

**Comment by GeonSeon** [comment]
I need it, too.. Will it be possible?

**Comment by miquelbeltran** [comment]
Maybe this should be for network_info_plus rather than connectivity_plus

**Comment by miquelbeltran** [comment]
Duplicated of https://github.com/fluttercommunity/plus_plugins/issues/420
