### ISSUE TITLE
[Request]: add share link preview feature

### ISSUE THREAD

**Issue by Jacqueline94-Koo** [fluttercommunity/plus_plugins#2054]
### Plugin

share_plus

### Use case

when user share the link to other social media, the shared link will show original link title, image and link description.

### Proposal

something link the image below.

<img width="308" alt="Screenshot 2023-08-21 at 4 43 42 PM" src="https://github.com/fluttercommunity/plus_plugins/assets/62096300/f7ed91cf-b09c-4123-8796-855c590b454c">

**Comment by vbuberen** [comment]
Link preview is something that is not controlled by `share_plus` and totally up to link itself and the app where this link is used.
