### ISSUE TITLE
[network_info_plus] Request: Provides subnet mask, gateway, broadcast address and other information

### ISSUE THREAD

**Issue by YowFung** [fluttercommunity/plus_plugins#206]
I hope this plugin can provide the following information:
- subnet mask
- gateway
- broadcast address
- IPv6

**Comment by Elias8** [comment]
Hi @YowFung 👋,

I think the things you mentioned are included in the latest version via PR #355. So please check the latest version and close the issue.

Thanks.

**Comment by YowFung** [comment]
Nice! Thank you very much!
