### ISSUE TITLE
[Question]: is there a way to remove unused permission added by this package?

### ISSUE THREAD

**Issue by Somtobro** [fluttercommunity/plus_plugins#2105]
### What is your question?

On publishing my app, I noticed 3 permissions I don't need and after debugging I found out it's from this package.
Is it possible to remove them somehow?

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by nohli** [comment]
Hi. Which package and which permissions do you mean?

**Comment by Somtobro** [comment]
The share_plus package.
I also saw a similar complaint on Reddit.

**Comment by arpitsharma007** [comment]
You can remove any unused permission by adding this in your flutter project android manifest.xml file:
<uses-permission android:name="android.permission.CAMERA" tools:node="remove" />

The above example will remove camera permission from the app

The path of android manifest file will be: project_name/android/app/src/main/AndroidManifest.xml

**Comment by Somtobro** [comment]
I know that @arpitsharma007 
Check this out
This is someone's else having the same issue on Reddit
https://www.reddit.com/r/androiddev/comments/14plscw/new_permissions_added_to_my_flutter_app_update/

**Comment by vbuberen** [comment]
> On publishing my app, I noticed 3 permissions I don't need and after debugging I found out it's from this package.
Is it possible to remove them somehow?

I would like to see any proofs that it is `share_plus` that adds permissions first.
`share_plus` doesn't add any additional permissions on Android.

**Comment by vbuberen** [comment]
Closing as no info provided.
