### ISSUE TITLE
首次安装，网络授权后，要5，6秒，onConnectivityChanged状态才回来

### ISSUE THREAD

**Issue by ShuangZiMoYin** [fluttercommunity/plus_plugins#2114]
### What is your question?

首次安装，网络授权后，要5，6秒，onConnectivityChanged状态才回来

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Could you write your question on English?

**Comment by nohli** [comment]
DeepL:

> The first time you install it, it takes 5 or 6 seconds for the onConnectivityChanged status to come back after network authorization

**Comment by vbuberen** [comment]
Thanks, I can use translation tools too, but it is about respecting the fact that people communicate using English here and would be good to use translation tool from the reporter side before reporting/starting a discussion instead of forcing the rest of community to go and translate.
