### ISSUE TITLE
Missing share_plus share files implementation in web

### ISSUE THREAD

**Issue by CodeDoctorDE** [fluttercommunity/plus_plugins#212]
There is a share files method in the html.navigator, see [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)

**Comment by ueman** [comment]
I think the share plugin should probably build on https://pub.dev/packages/cross_file instead of taking paths. That way it would be cross platform.

**Comment by CodeDoctorDE** [comment]
Any updates?
_I don't want that this issue will be closed_

**Comment by ThexXTURBOXx** [comment]
I would be willing to give this one a try. I will be home on the 5th October and will try to find a solution to this then, if possible :)

**Comment by ThexXTURBOXx** [comment]
Status update:
After careful consideration, I decided to implement the solution @ueman suggested:
> I think the share plugin should probably build on https://pub.dev/packages/cross_file instead of taking paths. That way it would be cross platform.

This will add new functions on all platforms to take `XFile` objects instead of paths. The old functions will be deprecated with a hint to call the new ones.

**Comment by ueman** [comment]
Just as a heads up, I was working on it in https://github.com/fluttercommunity/plus_plugins/pull/318 but never really had the time to finish it up. I guess it's already mostly done. Maybe it's of help for whoever starts working on this issue.

**Comment by ThexXTURBOXx** [comment]
> Just as a heads up, I was working on it in https://github.com/fluttercommunity/plus_plugins/pull/318 but never really had the time to finish it up. I guess it's already mostly done. Maybe it's of help for whoever starts working on this issue.

I should have looked earlier for work on this :)
After comparison, I will see which ideas I can implement into my solution as well, thanks for sharing! :)

**Comment by bhaveshraj336** [comment]
@ThexXTURBOXx I can help you in these if you want?

**Comment by ThexXTURBOXx** [comment]
My implementation is nearly finished. There is only one issue that needs to be fixed, so I think I am okay for now, but thanks :)
