### ISSUE TITLE
[Bug]: uuid plugin update required

### ISSUE THREAD

**Issue by BrainRayChristensen** [fluttercommunity/plus_plugins#2137]
### Platform

N.A.

### Plugin

share_plus

### Version

7.1.0

### Flutter SDK

3.13.2

### Steps to reproduce

1. Create a project with `flutter create your_project_name`
2. Add `uuid: ^4.0.0` and ` share_plus: ^7.1.0` to the dependencies for the project
3. Run `flutter pub get`

### Logs

```shell
[share_plus_version_conflict] flutter pub get
Resolving dependencies...
Because share_plus >=7.1.0 depends on share_plus_platform_interface ^3.3.0 which depends on uuid ^3.0.7, share_plus >=7.1.0 requires uuid ^3.0.7.
So, because share_plus_version_conflict depends on both uuid ^4.0.0 and share_plus ^7.1.0, version solving failed.


You can try one of the following suggestions to make the pubspec resolve:
* Consider downgrading your constraint on share_plus: flutter pub add share_plus:^6.0.1
* Consider downgrading your constraint on uuid: flutter pub add uuid:^3.0.7
exit code 1
```

### Flutter Doctor

```shell
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4.1 22F770820d darwin-arm64, locale en-US)
    • Flutter version 3.13.2 on channel stable at /Users/user/cli/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (10 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Use `dependency_overrides` till another update for plugins is released.

https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by vbuberen** [comment]
Alternatively, as https://github.com/fluttercommunity/plus_plugins/pull/2140 is merged into `main` you can use `share_plus` right from `main` till new releases are done. To do so you need to declare the plugin like this:
```
  share_plus:
    git:
      url: git@github.com:fluttercommunity/plus_plugins.git
      path: packages/share_plus/share_plus
      ref: main
```

**Comment by giorgio79** [comment]
Thank you @vbuberen

**Comment by CaviarChen** [comment]
I believe a new version of `share_plus` is released but we also need a new version of `share_plus_platform_interface`. 
https://github.com/fluttercommunity/plus_plugins/commit/aabc67f396bd2105e60b4d73133fae5cae2d64de

**Comment by vbuberen** [comment]
> I believe a new version of share_plus is released but we also need a new version of share_plus_platform_interface.
https://github.com/fluttercommunity/plus_plugins/commit/aabc67f396bd2105e60b4d73133fae5cae2d64de

Thanks for catching it. Seems like Melos missed this update due to commit having `chore` in it. Will release a new version shortly.

**Comment by vbuberen** [comment]
@giorgio79 New version is already available on pub.dev, so feel free to use it.

**Comment by vbuberen** [comment]
`share_plus v7.2.1` and `share_plus_platform_interface v3.3.1` have have a range ">=3.0.7 <5.0.0" for uuid, so closing this issue.
