### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by shaoxinlaw** [fluttercommunity/plus_plugins#2138]
### What is your question?

I suspect that the Gradle version of the project is inconsistent and incompatible with yours. Can you add a condition in the build.gradle file for `namespace 'dev.fluttercommunity.plus.sensors'` like this: 
`if (project.android.hasProperty("namespace")) {
        namespace 'dev.fluttercommunity.plus.sensors'
    }`

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
No, there will be no conditions added for that. We specifically released a major version bump (breaking change) specifically to let people know that they should update their Gradle versions if they want to get the latest Plus Plugins releases.

Here is an example of changelog explaining this in `battery_plus`: https://pub.dev/packages/battery_plus/changelog#400
