### ISSUE TITLE
[Bug]: [share_plus] Share bottom sheet hides the status bar.

### ISSUE THREAD

**Issue by hashirshoaeb** [fluttercommunity/plus_plugins#2143]
### Platform

Android 13: Galaxy S20 Ultra 5G Model Name: SM-G988B/DS

### Plugin

share_plus

### Version

7.0.1

### Flutter SDK

3.10.2

### Steps to reproduce

Tap a button to tripper share.

### Code Sample

```dart
void _onTap() {
    Share.shareWithResult('share this');
  }
```

### Logs

```shell
Launching lib/main.dart on SM G988B in debug mode...
```

### Flutter Doctor

```shell
Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (4 months ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by hashirshoaeb** [comment]
https://github.com/fluttercommunity/plus_plugins/assets/35165481/a1ea3716-00ab-47d3-bf8a-0d88369c7162

**Comment by kalismeras61** [comment]
@hashirshoaeb did you find something to fix it ?

**Comment by deverlex** [comment]
same issue on Galaxy A7

**Comment by ckolenchenko** [comment]
The same at the Galaxy A52s

**Comment by tensarflow** [comment]
same on galaxy s22

**Comment by tanlocle0495** [comment]
@vbuberen  are you sure ??
