### ISSUE TITLE
[Bug]: Incorrect connection status on Galaxy S10e in power saving mode

### ISSUE THREAD

**Issue by iriya-kom** [fluttercommunity/plus_plugins#2144]
### Platform

Android 12

### Plugin

connectivity_plus

### Version

 ^4.0.1

### Flutter SDK

3.10.6

### Steps to reproduce

I'm using Connectivity().onConnectivityChanged.listen method.
1. Turn off the internet
2. Hide application
3. Turn on the internet while app on background

Without power saving mode stream gives right connection statuses, but when power saving is enabled it always gives ConnectivityResult.none even if you returned connection while on background.

### Code Sample

```dart
void _listenConnectivity() {
    connectivityStreamSubscription =
        Connectivity().onConnectivityChanged.listen(
      (ConnectivityResult result) async {
        Logger().d(result);
        emit(
          state.copyWith(
            isConnection: result != ConnectivityResult.none,
          ),
        );
      },
    );
  }
```

### Logs

```shell
No backticks or errors detected.
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1848], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] Connected device (5 available)
[√] Network resources
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by linhnv-guide-vn** [comment]
Hi @iriya-kom , 
I also get the same error.
I checked the source code, onConnectivityChanged listen cannot work with the battery saver mode case.
So I have solution
When open app from Background to Foreground, I call function NetworkUtil.isNetworkConnected() then update the variable into Model.
