### ISSUE TITLE
[Question]: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0

### ISSUE THREAD

**Issue by shinexoh** [fluttercommunity/plus_plugins#2147]
### What is your question?

I found an error when executing `flutter clean` -> `flutter build apk` ,  but it does not directly terminate the build. Instead, it will be packaged successfully. I want to know what impact this situation will have? 

no issues were found during the use of the successfully built application

![image](https://github.com/fluttercommunity/plus_plugins/assets/98050229/d6ace653-a866-4d52-97a6-3f1e8eb8726d)

This is the kotlin version written by my `android/build.gradle`
I upgraded it from 1.7.10 to 1.8.10 a few days ago because use the latest dependency requires 1.8.0 or higher, so I upgraded it , similar to https://github.com/fluttercommunity/plus_plugins/issues/2018

![image](https://github.com/fluttercommunity/plus_plugins/assets/98050229/28449f9e-6bd0-4a76-8ddb-0c3da748d3b7)

This is my `pubspec.yaml` dependency

![image](https://github.com/fluttercommunity/plus_plugins/assets/98050229/6fc94aea-fa1f-4999-bfb3-ec90d804fc51)

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by PabloAznarez** [comment]
same here

**Comment by KoheiKanagu** [comment]
The same error occurred when I set `ext.kotlin_version = '1.9.10'`

**Comment by lucamenor** [comment]
@shinexoh I had the same problem using these dependencies below

```
device_info_plus: ^9.1.0
package_info_plus: ^4.2.0
share_plus: ^7.0.2
```

I managed to get around it by making the following adjustments

In android/build.gradle
```
ext.kotlin_version = '1.8.22' 
dependencies {
        classpath 'com.android.tools.build:gradle:7.4.0'
}
```

But if it doesn't work, you can try the solution to this issue too
https://github.com/flutter/flutter/issues/130412
