### ISSUE TITLE
[Bug]: connectivity_plus crashes when running on real IOS device

### ISSUE THREAD

**Issue by ambstuc** [fluttercommunity/plus_plugins#2155]
### Platform

IOS 16.6.1

### Plugin

connectivity_plus

### Version

4.0.2

### Flutter SDK

3.13.5

### Steps to reproduce

1. Create new Flutter project in VS-Code ('empty flutter project'). Code attached is unchanged from the template project

2. Run project on real IOS device (iPhone 13 pro in m case). Output:
>Launching lib/main.dart on ... in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXX
Xcode build done.
(lldb) 2023-09-21 22:53:07.512889+0100 Runner[853:88338] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
Connecting to VM Service at ws://127.0.0.1:64855/EZy9MDloE_s=/ws

4. install connectivity_plus (flutter pub add connectivity_plus)

5. Re-run project. Output:
>Xcode build done.
(lldb) 2023-09-21 22:56:21.599196+0100 Runner[858:90229] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: (Runner) stopped.
Error launching application on device.

### Code Sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}
```

### Logs

```shell
Log too long to be attached
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.82.1)
[✓] Connected device (3 available)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by lvsecoto** [comment]
same for me

'''
@discardableResult
  private func ensurePathMonitor() -> NWPathMonitor {
    if (_pathMonitor == nil) {
      let pathMonitor = NWPathMonitor() // 《= Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
      pathMonitor.start(queue: queue)
      pathMonitor.pathUpdateHandler = pathUpdateHandler
      _pathMonitor = pathMonitor
    }
    return _pathMonitor!
  }
'''

**Comment by adil-nangyal** [comment]
<img width="1792" alt="Screenshot 2023-09-22 at 11 40 51 AM" src="https://github.com/fluttercommunity/plus_plugins/assets/72001891/cbe4f87c-e747-4993-81eb-40947e1176bb">
![Screenshot 2023-09-22 at 11 40 51 AM (2)](https://github.com/fluttercommunity/plus_plugins/assets/72001891/d6ee7c95-6a8b-4c7f-bc09-831023e79ff3)

Same issue

**Comment by ganwumeng** [comment]
<img width="983" alt="image" src="https://github.com/fluttercommunity/plus_plugins/assets/38616251/28555740-d830-4b23-8f8b-4279d0dad4a7">
Same for me.It's quite normal last time I used it.

**Comment by ganwumeng** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/2154

It's a useful way to solve this problem temporarily.

**Comment by vbuberen** [comment]
Unfortunately, don't have real iOS device available, so can't check and fix it. Would appreciate somebody taking care of it and opening a PR.

**Comment by ts-lawrence** [comment]
It seems 4.0.2 works on ios 17, but crashes on earlier versions.

**Comment by AlexeyRottCr** [comment]
Same, only works on IOS 17

**Comment by fvisticot** [comment]
App crash with iOS16.X
I made the the test after upgrading to iOS17 and it works.

**Comment by adrianvintu** [comment]
Crashes for me as well 16.6.1

**Comment by adrianvintu** [comment]
My code needed 2 changes, one for this plugin, one for the new Flutter version (i think)

```
platform :ios, '13.0'
....
post_install do |installer|
  installer.pods_project.targets.each do |target| 
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      #https://github.com/fluttercommunity/plus_plugins/issues/2154#issuecomment-1730330223
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'

      #https://stackoverflow.com/a/77134628/5734049
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
  end
end }
```

**Comment by WieFel** [comment]
+1 on iPhone SE running iOS `15.7.9` and Flutter `3.13.0`

**Comment by Bennik2000** [comment]
+1 on iPhone 6s running iOS `15.7.7` and Flutter `3.13.6`

**Comment by ChargerMc** [comment]
+ 1 iOS `15.5`

**Comment by tsgofficial** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/2154 this one worked for me

**Comment by vbuberen** [comment]
I encourage everyone to try the fix from #2169 to let me know that I can merge and release an update for `connectivity_plus`.

To do so, declare the plugin the following way:
```
connectivity_plus:
    git:
      url: git@github.com:fluttercommunity/plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus
      ref: update/connectivity_plus_min_ios
```

**Comment by ByJoker8625** [comment]
> I encourage everyone to try the fix from #2169 to let me know that I can merge and release an update for `connectivity_plus`.
> 
> To do so, declare the plugin the following way:
> 
> ```
> connectivity_plus:
>     git:
>       url: git@github.com:fluttercommunity/plus_plugins.git
>       path: packages/connectivity_plus/connectivity_plus
>       ref: update/connectivity_plus_min_ios
> ```

This is working for me

**Comment by vbuberen** [comment]
Thank you very much for your feedback and for the fix of the link. I will merge the PR and will try to release updates for plugins this week.

**Comment by nambui2000k** [comment]
when do you update new version? @vbuberen

**Comment by vbuberen** [comment]
Read the message above

**Comment by tal412** [comment]
I have multiple users still reporting the issue. The app uses the latest version of the library and yet it still crushes. 
After updating to iOS 17 the issue was solved for them but I got some negative reviews for that.

**Comment by matthijs166** [comment]
This fixed it for us! https://stackoverflow.com/questions/77147216/error-encountered-only-below-ios-17-devices-thread-1-exc-bad-access-code-1-a

**Comment by vbuberen** [comment]
> The app uses the latest version of the library and yet it still crushes.
It means that you couldn't adjust your project to have deployment target 12.

It is explicitly mentioned in the changelogs that the projects needs to have iOS 12 as min deployment target. For those who still have issues it means that your project isn't adjusted correctly.

Here is a comment with the person, who had the same issue adjusting the project: https://github.com/fluttercommunity/plus_plugins/issues/2276#issuecomment-1773056178
