### ISSUE TITLE
hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler[Bug]: 

### ISSUE THREAD

**Issue by OpenJarvisAI** [fluttercommunity/plus_plugins#2167]
### Platform

hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler

### Plugin

hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler

### Version

hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler

### Flutter SDK

hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler

### Steps to reproduce

hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler

### Code Sample

```dart
hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler
```

### Logs

```shell
hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler
```

### Flutter Doctor

```shell
hare_plus-6.3.4/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt:19:23 Unresolved reference: MethodCallHandler
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Please fill in the bug template correctly or I will close this issue.

**Comment by OpenJarvisAI** [comment]
@vbuberen Can u see the error above??

**Comment by vbuberen** [comment]
The log you provided is meaningless and not helpful. Having no other info requested in our template also makes this issue invalid. So, please, open a proper issue report if you want to get some help

**Comment by dariobrux** [comment]
Me too, same error.
I updated to `share_plus: ^7.1.0`, no errors during pub get. But when I try to run the application, the building fails with this exception:

```
e: file:///Users/dbruzzese/.pub-cache/hosted/pub.dev/share_plus-7.1.0/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:10:24 Unresolved reference: Share

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':share_plus:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

**Comment by AlexisL61** [comment]
`flutter clean` solved this error for me
