### ISSUE TITLE
[Question]: Is it possible to identify the deviceType that is being used to play audio in?

### ISSUE THREAD

**Issue by arnab** [fluttercommunity/plus_plugins#2168]
### What is your question?

_I had asked this on [StackOverflow here](https://stackoverflow.com/questions/77192730/flutter-just-audio-how-can-i-identify-the-devicetype-that-is-being-used-to-play) and one comment mentioned that this is possible with `device_info_plus`. I am already using this, but don't see how to identify the audio channel/device being used. Hence, asking here:_

---

I am using `just_audio` with `audio_service` and `just_audio_background` to play audio in my app (in-app as well as background audio).

Is it possible for me to identify the type of device that is being used to play the audio? Such as, is the audio being played via the device (iOS/Android phone/tablet) itself, or perhaps via Bluetooth, CarPlay, AndroidAuto etc.

---

I could not find anything relevant in SO, in just_audio docs, or in device_info and issues. _And ChatGPT is hallucinating (it's telling me some methods that don't exist, but if they did - would have been exactly what I wanted)_ :) 

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
No, `device_info_plus` won't help you with this. I will reply to that SO question as well with some suggested packages to achieve what you want.
