### ISSUE TITLE
[package_info_plus] Duplicated macos podspecs

### ISSUE THREAD

**Issue by MisterJimson** [fluttercommunity/plus_plugins#22]
Quick question about the structure and macos support.

For the plugins that support macos, why is there a podspec in both the app facing package and in the dedicated platform package?

Example:
https://github.com/fluttercommunity/plus_plugins/tree/main/packages/package_info_plus_macos/macos
https://github.com/fluttercommunity/plus_plugins/tree/main/packages/package_info_plus/macos

**Comment by MisterJimson** [comment]
The bug label got automatically set, I can’t remove it.

**Comment by jpnurmi** [comment]
It's a workaround for https://github.com/flutter/flutter/issues/46618. Same as what was done in for example https://github.com/flutter/plugins/pull/2386:
- https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/macos/url_launcher.podspec
- https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_macos/macos/url_launcher_macos.podspec

Without a dummy .podspec in the main package you'll get a build error:
```
[!] No podspec found for `package_info_plus` in `Flutter/ephemeral/.symlinks/plugins/package_info_plus/macos`
```
