### ISSUE TITLE
iOS classes should not use `FLT` prefix

### ISSUE THREAD

**Issue by stuartmorgan** [fluttercommunity/plus_plugins#2215]
### Platform

iOS

### Plugin

Various

### Version

N/A

### Flutter SDK

N/A

### Steps to reproduce

Currently a number of the plugins are using the `FLT` prefix for Objective-C classes. The [purpose of Obj-C prefixing](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html) is to avoid naming collisions, which cause undefined behavior at runtime, so the prefix is supposed to be something unlikely to be used by others. However, `FLT` is used by the Flutter team, which means using `FLT` here *maximizes* the chance of collisions, rather than minimizing them, since developers using the plugins are very likely to have Flutter-team-authored Obj-C code in their app as well.

The plugins here should change to something specific to this organization/repo (e.g., `CPP` for Community Plus Plugins) rather than `FLT`.

### Logs

```shell
N/A
```

### Flutter Doctor

```shell
N/A
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Thanks for sharing. I think something like `FPP` from Flutter Plus Plugins would fit good here.
This issue seems pretty easy, so I will leave it for now to let somebody willing to take part in Hacktoberfest to pick it up. In case nobody picks it up by the end of October I will change names myself.

**Comment by vbuberen** [comment]
To anybody, who is willing to resolve this issue, the task is to find all `FLT-` prefixed classes in `ios` parts of plugins and change prefixes to `FPP-`.
