### ISSUE TITLE
[Question]: Contribution documentation on E2E testing seems outdated

### ISSUE THREAD

**Issue by dumazy** [fluttercommunity/plus_plugins#2217]
### What is your question?

Looking at `CONTRIBUTING.md`, more specifically the [part about running end-to-end tests](https://github.com/fluttercommunity/plus_plugins/blob/88312e14987a2adacc2bb8edae752940cba56207/CONTRIBUTING.md#end-to-end-e2e-tests), it seems that these refer to old driver tests.

```
cd packages/sensors_plus/sensors_plus/example
flutter drive --target=./test_driver/sensors_plus_e2e.dart
```
While there are no more `test_driver` directories in the repository.

It seems like the e2e tests were migrated from driver to integration tests in [this PR](https://github.com/fluttercommunity/plus_plugins/pull/966), but the docs were not updated.

Running the integration tests works fine.
```
cd packages/battery_plus/battery_plus/example
flutter test integration_test/battery_plus_test.dart
```

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Indeed it is outdated. Help appreciated here 😉
