### ISSUE TITLE
[Question]: iOS model number (data.ustname.machine) resulting "iPhone12,8" but the device is "iPhone SE"

### ISSUE THREAD

**Issue by shishir2sr** [fluttercommunity/plus_plugins#2225]
### What is your question?

I am working on a project where I need to parse the device model.  I have providing below code portion 
`else if (Platform.isIOS) {
      IosDeviceInfo iosInfo = await deviceInfo.iosInfo;
      deviceInfoModel = deviceInfoModel.copyWith(
        deviceModel: iosInfo.utsname.machine,
      );}`
      
      here the api ustname.machine returns "iPhone 12,8" but the actual model no. is "iPhone SE". How to solve it?
      

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Plugin returns correct `machine` name, which is not the same as the model name you used to. 
It is also explained in API docs: https://pub.dev/documentation/device_info_plus/latest/device_info_plus/IosUtsname/machine.html

At the moment there is no reliable way to get `iPhone SE` string as you want using `device_info_plus`.
