### ISSUE TITLE
[Bug]: Xcode15.0 Packaging will crash

### ISSUE THREAD

**Issue by LuoGuoXin** [fluttercommunity/plus_plugins#2239]
### Platform

iOS 15

### Plugin

connectivity_plus

### Version

4.0.2

### Flutter SDK

4.0.2

### Steps to reproduce

When I package with xcode15 version, phones below iOS17 will crash, and iOS17 phones will function normally

### Code Sample

```dart
·
```

### Logs

```shell
·
```

### Flutter Doctor

```shell
·
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
You marked ` I searched issues in this repository and couldn't find such bug/problem`, but it seems you didn't actually search. Try to use search first.
