### ISSUE TITLE
[Bug]: Failed to notify project evaluation listener.

### ISSUE THREAD

**Issue by AymericLeFeyer** [fluttercommunity/plus_plugins#2240]
### Platform

Android 13

### Plugin

device_info_plus

### Version

10.0.0

### Flutter SDK

3.13.6

### Steps to reproduce

I just migrate my project from Flutter 3.3.10 to 3.13.6. I also remove the `device_info` plugin for the `device_info_plus`

When I do a `flutter run`, I have and error for device_info_plus. I tried both latest versions.

Version 9.0.3 -> `No signature of method: build_3yf56km10ih9pn6s5mky6sfu0.android() is applicable for argument types`
Version 10.0.0 -> `Cannot invoke method substring() on null object`

I can still launch my app in web

### Logs

```shell
* What went wrong:
A problem occurred configuring project ':device_info_plus'.
> Failed to notify project evaluation listener.
   > Cannot invoke method substring() on null object
   > compileSdkVersion is not specified. Please add it to build.gradle
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
```No signature of method: build_3yf56km10ih9pn6s5mky6sfu0.android() is applicable for argument types``` - it means your projects uses a very old Android Gradle Plugin (older than 4.2). Update it to use `device_info_plus` 9.x and newer.

**Comment by AymericLeFeyer** [comment]
That was the problem, well done @vbuberen
