### ISSUE TITLE
[Bug]: Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by asoseil** [fluttercommunity/plus_plugins#2258]
### Platform

iOS 17

### Plugin

package_info_plus

### Version

4.1.0

### Flutter SDK

3.13

### Steps to reproduce

On build there a lexical problem on package_info_plus-4.1.0/ios/Classes/FLTPackageInfoPlusPlugin.h:4:8

### Logs

```shell
Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
/Users/alessio/.pub-cache/hosted/pub.dev/package_info_plus-4.1.0/ios/Classes/FLTPackageInfoPlusPlugin.h:4:8

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
[✓] Connected device (4 available)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by asoseil** [comment]
Seems the variable name is renamed on master, but the package published on pub.dev is not yet updated with the latest  changes

**Comment by vbuberen** [comment]
You tried to update the package or just added it?

> Seems the variable name is renamed on master, but the package published on pub.dev is not yet updated with the latest changes

It has nothing to do with your problem if you didn't try to update to 5.0.0 (which was retracted yesterday) and now back. In case you tried to update to 5.0.0 you need to do `flutter clean` as 4.1.0 is currently the latest release.

**Comment by roneicouto** [comment]
@asoseil : Have you been successful? Any solution?
