### ISSUE TITLE
[Bug]: connectivity_plus doesn't have support for iOS in latest version. Had to revert to the previous one

### ISSUE THREAD

**Issue by zthrive** [fluttercommunity/plus_plugins#2260]
### Platform

iOS

### Plugin

connectivity_plus

### Version

5.0.0

### Flutter SDK

3.13.7

### Steps to reproduce

run flutter build ios

### Logs

```shell
N/A
```

### Flutter Doctor

```shell
Not relevant
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by zthrive** [comment]
After upgrading to the latest version of the plugin (5.0.0) I cannot build for iOS any longer. After reverting back to the older version, all is good

**Comment by vbuberen** [comment]
Current bug report is invalid without logs and information what exactly is wrong. Provide information properly.

**Comment by zthrive** [comment]
The app just doesn't build for iOS with the latest (5.0.0) version, that is the only thing. There is no other information that I can provide.
After reverting to the previous version (4.0.2) of the plugin, the app builds for iOS as expected.

**Comment by vbuberen** [comment]
If you can't provide even logs from build fails there is no way to help you. 
Thus, I am closing the bug report as invalid.
