### ISSUE TITLE
[Bug]: Unsupported class file major version 61

### ISSUE THREAD

**Issue by kjt666** [fluttercommunity/plus_plugins#2261]
### Platform

Android 12

### Plugin

connectivity_plus

### Version

5.0.0

### Flutter SDK

3.13.2

### Steps to reproduce

Using version 5.0.0

Android Studio compilation encountered an error

Cause 1: org.gradle.api.GradleException: Failed to create Jar file /Users/kjt/.gradle/caches/jars-8/947c1318c2bb7024446bea1314544a0f/lint-model-31.1.2.jar.

Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61

### Logs

```shell
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':connectivity_plus'.
> Failed to create Jar file /Users/kjt/.gradle/caches/jars-8/947c1318c2bb7024446bea1314544a0f/lint-model-31.1.2.jar.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':connectivity_plus' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':connectivity_plus' of type org.gradle.api.Project.

Cause 1: org.gradle.api.GradleException: Failed to create Jar file /Users/kjt/.gradle/caches/jars-8/947c1318c2bb7024446bea1314544a0f/lint-model-31.1.2.jar.

Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[!] Xcode - develop for iOS and macOS (Xcode 15.0)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] Connected device (3 available)
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
I would appreciate if you really used search in Google and among issues in this repo before opening such bug reports. 
There were tons of same issues already and it is connected with your project using old Android Gradle Plugin version (older than 4.2). Update it and everything will work again.
