### ISSUE TITLE
[Question]: network_info_plus: ^4.0.2 for MacOS Sonoma 14 returns null when calling _networkInfo.getWifiBSSID();

### ISSUE THREAD

**Issue by LiveRock** [fluttercommunity/plus_plugins#2263]
Platform
MacOS 14.0

Plugin
connectivity_plus

Version
4.0.2

Flutter SDK
3.13.7 Stable

Code Sample
```
final _networkInfo = NetworkInfo();
wifiName = await _networkInfo.getWifiName();
```

Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.

### What is your question?

Using network_info_plus: ^4.0.2 

On MacOS Sonoma 14, 

calling _networkInfo.getWifiBSSID()

returns null

Previously, when I was using the last MacOS and network_info_plus 4.0.0, it was working. I am not sure whether it is Sonoma or network_info_plus 4.0.2 that is causing this. Xcode also upgraded to 15.0

Help!

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by LiveRock** [comment]
#2156 and #1652 are related to iOS. I am using MacOS. I checked, there are no "Access WiFi information capability" for MacOS in Xcode.

**Comment by ahmetbesli** [comment]
@LiveRock same on me. Still no solution for the problem

**Comment by 988494** [comment]
flutter 3.13.8 也是同样有这个问题

**Comment by vbuberen** [comment]
There is an explanation regarding MacOS that there is a need for proper location privilege:

https://github.com/fluttercommunity/plus_plugins/issues/2156#issuecomment-2024966551

**Comment by LiveRock** [comment]
Still facing the same issue with MacOS with the latest versions:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for Peter iPhone 15 Pro Max. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
