### ISSUE TITLE
[Request]: network_info_plus: Implement getWifiSubmask() on Windows

### ISSUE THREAD

**Issue by tareksander** [fluttercommunity/plus_plugins#2264]
### Plugin

network_info_plus

### Use case

I want to scan all IP addresses in the local network for a local multiplayer game, and this package worked fine under Linux, but on Windows it throws an unimplemented exception for `getWifiSubmask()`.

### Proposal

Implement `getWifiSubmask()` on Windows and/or document for each method on which platforms it's implemented.

**Comment by vbuberen** [comment]
Addressed by https://github.com/fluttercommunity/plus_plugins/pull/2666
