### ISSUE TITLE
[Question]: How to share it just Specific App

### ISSUE THREAD

**Issue by DevloperAnuj** [fluttercommunity/plus_plugins#2273]
### What is your question?

How can i just share xfiles to whatsapp only ?

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
There is no way to do so.
