### ISSUE TITLE
[connectivity][plugin] Add a new state to indicate when both Mobile-Data and WiFi are connected

### ISSUE THREAD

**Issue by avkonst** [fluttercommunity/plus_plugins#228]
> Note: cloned from https://github.com/flutter/flutter/issues/80427 as per [this suggestion](https://github.com/flutter/flutter/issues/80427#issuecomment-819746288)

## Use case

It would be useful to know when both MobileData and WiFi are connected. Right now, for example connectivity plugin returns (precedence) WiFi when both WiFi and MobileData are connected.

## Proposal

Add a new state to indicate in connectivity plugin when both Mobile-Data and WiFi are connected.

**Comment by sudo-saksham** [comment]
Hey, here I tried to do this but the code is getting only activeNetworkInfo() (so even if both WiFi and Mobile Network is connected, then only the one through which we browse will return). Is there any method from which we can access all the network connections the device currently has. I looked in the docs and found out that **[getAllNetworks](https://developer.android.com/reference/android/net/ConnectivityManager#getAllNetworks())** is one such method, but it's depracated in API Level 31. So is there any other method? @mhadaily
