### ISSUE TITLE
[Bug]: Unable to share post crashing on some devices

### ISSUE THREAD

**Issue by kartikmalhotra** [fluttercommunity/plus_plugins#2281]
### Platform

IOS

### Plugin

share_plus

### Version

7.2.1

### Flutter SDK

3.13.8

### Steps to reproduce

Tapping on the app in the bottom sheet opened by the share_plus package crashes and doesn't open the app.

Similar Issue
[385](https://github.com/fluttercommunity/plus_plugins/issues/385)

### Code Sample

```dart
await Share.shareFiles(mediaPath, "threads",text: post.message ?? "");
```

### Logs

```shell
[NSExtension] Extension request contains input items but the extension point does not specify a set of allowed payload classes. The extension point's NSExtensionContext subclass must implement `+_allowedItemPayloadClasses`. This must return the set of allowed NSExtensionItem payload classes. In future, this request will fail with an error.
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 12.6 21G115 darwin-arm (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.70.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

### Checklist before submitting a bug

- [ ] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Y-ndm** [comment]
Facing the same issue with the same error output. In my case it's when trying to share to Instagram on an Iphone 11.
