### ISSUE TITLE
[battery_plus] Unhandled exception on an Android device at app startup

### ISSUE THREAD

**Issue by mregnauld** [fluttercommunity/plus_plugins#231]
## System info

Issue occurs on: Android 7.0, on a Samsung Galaxy Tab A (2016)
Plugin name: battery_plus
Plugin version: 1.0.1
Flutter doctor output:

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.0.1 20B29 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

## Steps to Reproduce

1. Create a new Flutter app, as described here: [https://pub.dev/packages/battery_plus/example](https://pub.dev/packages/battery_plus/example)
2. Run the app on a Samsung Galaxy Tab A (2016) with Android 7.0 installed
3. I got the following error, even though it's actually working:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(UNAVAILABLE, Charging status unavailable, null, null)
```

Since I catch every unhandled exception in my app by displaying a custom page, it's very annoying for my case.

After some research, it appears that the error occurs on the first call of `BatteryPlusPlugin.getBatteryLevel()`.
Not sure, but I think it can quickly be fixed by removing the last 2 lines of the `onListen()` function:

```Java
int status = getBatteryProperty(BatteryManager.BATTERY_PROPERTY_STATUS);
publishBatteryStatus(event, status);
```

The status should still be published at startup thanks to the broadcast receiver (worth chechking, though).

Thanks.

**Comment by mregnauld** [comment]
OK so for those who encounter the same problem, here is a simple workaround:

just call :

```Dart
await battery.batteryLevel;
```

before calling:

```
battery.onBatteryStateChanged.listen((BatteryState state) { ... });
```

**Comment by mregnauld** [comment]
Any update on this? Could it be fixed quickly?
Thanks.

**Comment by miquelbeltran** [comment]
Hi @mregnauld. Currently there's no one available to fix the issue. If you would like to do it and submit a PR we would be more than thankful.

**Comment by mhadaily** [comment]
please check out the latest version, and let us know if you still have this issue.

**Comment by mregnauld** [comment]
It works now, thanks, even though I have a warning saying that the library uses a deprecated api (for Android).

**Comment by ChristianEdwardPadilla** [comment]
Hi @mregnauld could you check if adding a break statement to the following line fixes the issue for you?
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java

I'll be pushing a change to add the break statement, but in the meantime I'd be curious if it helps you locally.

**Comment by mregnauld** [comment]
Sorry for the (very) late answer, but for information, I can't reproduce the bug with battery_plus 2.1.1.
