### ISSUE TITLE
For Android Sdk 33 and 34 is not working. alarm trigger is not triggering

### ISSUE THREAD

**Issue by engineer-ece** [fluttercommunity/plus_plugins#2311]
### What is your question?

For Android Sdk 33 and 34 is not working. alarm trigger is not triggering

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Please provide proper tech information if you want to report a bug. `not working` is a very broad definition.
