### ISSUE TITLE
n China can't download "com. Android. View the build: gradle: 8.1.2"

### ISSUE THREAD

**Issue by 988494** [fluttercommunity/plus_plugins#2313]
### What is your question?

In China can't download "com. Android. View the build: gradle: 8.1.2", the source of all domestic accelerated in China are not "com. Android. View the build: gradle:" 8.1.2 version, Can you modify a common version, such as 8.1.1 

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
No, can't help here. Don't want to comply with China's special policy and support it this way.
