### ISSUE TITLE
[BUG]: nodename is wrong 

### ISSUE THREAD

**Issue by scuti-dai** [fluttercommunity/plus_plugins#2317]
### Platform

Iphone 12 pro max (16.1.2)

### Plugin

device_info_plus

### Version

9.1.0

### Flutter SDK

3.13.9

### Steps to reproduce

1: Update device name is "Minh Đại 26.3 在以为自己是"
2: Use device_info_plus for get nodename

=> Result: Minh-ai-3-zaiijikoze

### Code Sample

```dart
final IosDeviceInfo iosDeviceInfo = await deviceInfo.iosInfo;
print(iosDeviceInfo.utsname.nodename);
```

### Logs

```shell
flutter: Minh-ai-3-zaiijikoze
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.10.6, on macOS 14.0 23A344 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Plugin shows data that is returned from the system and doesn't modify the content returned, so it is not an issue in the plugin and we can't do anything here.
