### ISSUE TITLE
[Bug]: permission_handler: Undefined symbol: _OBJC_CLASS_$_FLTPackageInfoPlusPlugin

### ISSUE THREAD

**Issue by Jay-57blocks** [fluttercommunity/plus_plugins#2318]
### Platform

iOS15.6

### Plugin

permission_handler

### Version

11.0.1

### Flutter SDK

3.13.6

### Steps to reproduce

I can't provide an example because I can't start the program, it just returns the error

Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FLTPackageInfoPlusPlugin
2

Error launching application on IPHONE.

<img width="872" alt="image" src="https://github.com/fluttercommunity/plus_plugins/assets/132547846/b76edcf2-b1ef-4c3e-9a62-faab8aa1d99c">

### Code Sample

```dart
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
```

### Logs

```shell
Launching lib/main_qa.dart on PS FOR IPHONE in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: HM772XXXX
Xcode build done.                                           30.0s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FLTPackageInfoPlusPlugin
2

Error launching application on PS FOR IPHONE.
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6.1 22G313 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.83.1)
[✓] Connected device (5 available)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
This is not a repo for `permission_handler` package.

**Comment by Jay-57blocks** [comment]
@vbuberen Sorry, this problem was caused by me changing the name of the Flutter iOS project. The new Flutter version supports changing the project name. This caused the iOS GeneratedPluginRegistrant.m code to not be successfully generated. As a result, the plug-in could not be found. The iOS project needed to be deleted and restarted. Generate a new project and configure it. This question may be useful to others later.
