### ISSUE TITLE
[Request]: Will you use the pigeon plug-in to refactor the code?

### ISSUE THREAD

**Issue by GanZhiXiong** [fluttercommunity/plus_plugins#2369]
### Plugin

Any one

### Use case

[pigeon | Dart Package](https://pub.dev/packages/pigeon)

### Proposal

It seems that pigeon will be more efficient, and it is also officially recommended.

**Comment by vbuberen** [comment]
It wouldn't bring any benefits except adding additional overhead for maintenance. So for now no such plans.
