### ISSUE TITLE
[Request]: My app overflowed by app whome choosen to share

### ISSUE THREAD

**Issue by AlexeyVolkhin** [fluttercommunity/plus_plugins#2372]
### Plugin

share_plus

### Use case

I want to share a picture from my app to dialog in app named "Telegram"
Then I pressed arrow "Back", but I don't returned on my app screen, I returned on main screen "Telegram"

### Proposal

I need to detect, when user tap on some app to share, and if it "Telegram", to some func

Or any other solution, what you can suggest
<img width="419" alt="Снимок экрана 2023-11-09 в 17 57 45" src="https://github.com/fluttercommunity/plus_plugins/assets/121279152/490582d6-db39-4420-9a19-baed8ad12a88">

**Comment by AlexeyVolkhin** [comment]
<img width="419" alt="Снимок экрана 2023-11-09 в 17 57 45" src="https://github.com/fluttercommunity/plus_plugins/assets/121279152/9efd44a0-ccac-4512-afcd-4c3eafb3ee89">

**Comment by vbuberen** [comment]
No support to russians
