### ISSUE TITLE
[Bug]: [share_plus] Doesn't work on the web platform: opens a new tab to about:blank

### ISSUE THREAD

**Issue by darkstarx** [fluttercommunity/plus_plugins#2375]
### Platform

web

### Plugin

share_plus

### Version

7.2.1

### Flutter SDK

3.13.6

### Steps to reproduce

Just try to share text on the web platform (Crhome).
And you closed the issue https://github.com/fluttercommunity/plus_plugins/issues/190 in vain, the bug is still happens.

### Code Sample

```dart
final renderBox = _shareButtonKey.currentContext
      ?.findRenderObject() as RenderBox?;
    final shareButtonRect = renderBox == null
      ? null
      : renderBox.localToGlobal(Offset.zero) & renderBox.size;
    final id = widget.id;
    final title = _model?.title ?? '';
    final link = 'https://online.schtandart.com/node/$id';
    final result = await Share.shareWithResult(l10n.shareNewsMessage(title, link),
      sharePositionOrigin: shareButtonRect,
    );
    print('!!!=== ${result.status} ${result.raw}');
```

### Logs

```shell
!!!=== ShareResultStatus.unavailable dev.fluttercommunity.plus/share/unavailable
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-x64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by VersaDesenvolvimento** [comment]
It`s not working on Windows 11 

Edition	Windows 11 Pro
Version	23H2
Installed on	‎28/‎01/‎2023
OS build	22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22631.3007], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
[√] Android Studio (version 2022.2)
[√] Connected device (5 available)
[√] Network resources

  share_plus: ^7.2.2

"dev.fluttercommunity.plus/share/unavailable"

Code sample:

    final temp = await getTemporaryDirectory();
    final path = "${temp.path}/image.png";
    await File(path).writeAsBytes(u8);

    XFile xFile = XFile(path, name: "image.png", mimeType: "image/png");
    // XFile xFile = XFile.fromData(u8, name: "image.png", mimeType: "image/png");

    try {
      ShareResult retorno = await Share.shareXFiles([xFile]);
  } catch (e) {
      debugger();
    }

![image](https://github.com/fluttercommunity/plus_plugins/assets/111573785/cf2c2b66-4191-4ed7-b4d4-d256b54570e2)

![image](https://github.com/fluttercommunity/plus_plugins/assets/111573785/c30654ec-13ef-4849-b236-b18699cbfb7b)
