### ISSUE TITLE
[Bug]: Freezing and crashing the program due to getSystemMemoryInMegabytes() error

### ISSUE THREAD

**Issue by mohammadjalalis** [fluttercommunity/plus_plugins#2383]
Hi,
When running the program on some Windows operating systems, we encounter the following error. Currently, this error message occurred on a virtual machine with 8 GB of memory.

Edition	Windows 10 Home
Version	21H2
OS build	19044.1620

![Untitled](https://github.com/fluttercommunity/plus_plugins/assets/32570964/45827f05-6cb3-48e6-82f8-1a3056d4d4c0)

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by shuax** [comment]
```
WindowsException: Error 0x00000000: A operação foi concluída com êxito.
  File "device_info_plus_windows.dart", line 127, in DeviceInfoPlusWindowsPlugin.getSystemMemoryInMegabytes
  File "device_info_plus_windows.dart", line 87, in DeviceInfoPlusWindowsPlugin.getInfo
  File "device_info_plus_windows.dart", line 40, in DeviceInfoPlusWindowsPlugin.deviceInfo
  File "device_info_plus.dart", line 93, in DeviceInfoPlugin.windowsInfo
...
(5 additional frame(s) were not displayed)
```

I encountered the same problem and it was automatically collected by sentry.
