### ISSUE TITLE
[network_info] ios: handle deprecation of `CNCopyCurrentNetworkInfo`

### ISSUE THREAD

**Issue by daadu** [fluttercommunity/plus_plugins#240]
## System info

Issue occurs on: iOS 
Plugin name: network_info_plus
Plugin version: nil
Flutter doctor output: nil

[`CNCopyCurrentNetworkInfo`](https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo) is deprecated in iOS 14.0, it recommends to use [NEHotspotNetwork
.fetchCurrentWithCompletionHandler](https://developer.apple.com/documentation/networkextension/nehotspotnetwork/3666511-fetchcurrentwithcompletionhandle). 

I am not a native iOS developer but as far as I read, the new method is part of `HotspotHelper API` which requires special entitlements from Apple (requesting them manually [here](https://developer.apple.com/contact/request/hotspot-helper/)).

Either
1. deprecating iOS completely
2. implement `HotspotHelper API` and integrate with current handler

**Comment by daadu** [comment]
Looks like ` fetchCurrentWithCompletionHandler` does not require Hotspot Helper entitlement.

> +fetchCurrentWithCompletionHandler: does not require the Hotspot Helper entitlement. Unfortunately that fact is not documented officially (r. 74976266). Fortunately, there’s lots of good info about this method in the doc comments in <NetworkExtension/NEHotspotNetwork.h>.
> 
> Share and Enjoy
from Official source in Apple forum - https://developer.apple.com/forums/thread/675211?answerId=664741022#664741022

**Comment by phan-dev** [comment]
I got same issue.
Need someone implements that support iOS 14+

**Comment by miquelbeltran** [comment]
You can be that someone :star2:

**Comment by daadu** [comment]
I am working on it on another plugin [alternadom/WiFiFlutter#142], will patch the same here once done.

**Comment by mhadaily** [comment]
version 1.3.0 published
