### ISSUE TITLE
 [connectivity_plus] Upgrade dbus dependency

### ISSUE THREAD

**Issue by cedvdb** [fluttercommunity/plus_plugins#244]
dbus dependency in connectivity linux is outdated

**Comment by jpnurmi** [comment]
Yet better, port to ready-made [nm](https://pub.dev/packages/nm) now that it exists.

**Comment by mhadaily** [comment]
@jpnurmi there is a new version for https://pub.dev/packages/nm,

**Comment by jpnurmi** [comment]
Upgrading the dbus package as requested should be straightforward and less risky. Porting to nm would be the right thing to do, but it means basically rewriting the package. nm.dart just didn't exist when connectivity_plus_linex was implemented, so I had to access the D-BUS API directly.
