### ISSUE TITLE
[Bug]: Error: Type            'ApiResponse' not found.

### ISSUE THREAD

**Issue by motazKhogali** [fluttercommunity/plus_plugins#2441]
### Platform

Simulators iPhone all versions 

### Plugin

package_info_plus_linux

### Version

4.2.0

### Flutter SDK

3.16.0

### Steps to reproduce

I don't even add to my package I think it part of other packages 

the short message I get is : 
```
[        ] Error (Xcode): [+1169 ms]
           ../../../.pub-cache/hosted/pub.dev/package_info_plus-4.2.0/lib/src/package_info_plus_linux.dart:29:10:
Error: Type
           'ApiResponse' not found.
           
[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 13.
```

### Logs

```shell
[  +30 ms] Failed to build iOS app
[        ] Error (Xcode): [+1169 ms]
           ../../../.pub-cache/hosted/pub.dev/package_info_plus-4.2.0/lib/src/package_info_plus_linux.dart:29:10:
Error: Type
           'ApiResponse' not found.
           
[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 13.
[   +1 ms] "flutter run" took 21,990ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:752:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by motazKhogali** [comment]
open_filex:
    dependency: "direct main"
    description:
      name: open_filex
      sha256: a6c95237767c5647e68b71a476602fcf4f1bfc530c126265e53addae22ef5fc2
      url: "https://pub.dev"
    source: hosted
    version: "4.3.4"
  package_info_plus:
    dependency: transitive
    description:
      name: package_info_plus
      sha256: "7e76fad405b3e4016cd39d08f455a4eb5199723cf594cd1b8916d47140d93017"
      url: "https://pub.dev"
    source: hosted
    version: "4.2.0"
  package_info_plus_platform_interface:
    dependency: transitive
    description:
      name: package_info_plus_platform_interface
      sha256: "9bc8ba46813a4cc42c66ab781470711781940780fd8beddd0c3da62506d3a6c6"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.1"

**Comment by vbuberen** [comment]
`package_info_plus` has no such class, so the problem comes from another plugin.
https://pub.dev/documentation/package_info_plus/latest/search.html?q=ApiResponse
