### ISSUE TITLE
[Enhancement]: Target platform is IOS 11 on most of the plus plugins xcode complains and wants 12 +

### ISSUE THREAD

**Issue by vengines** [fluttercommunity/plus_plugins#2442]
### Platform

IOS

### Plugin

most of them

### Version

latest

### Flutter SDK

all

### Steps to reproduce

If you compile in xcode or use verbose you will get warnings for most of the plus plugins targeting platform ios 11 or older all should be changed to 12 + we have been manually changing in our app to 12 to get rid of all the warnings

### Code Sample

```dart
from the podspec file of  wakelock_plus

s.platform = :ios, '11.0'
```

### Logs

```shell
none issue
```

### Flutter Doctor

```shell
none issue
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Thanks for reporting. It is already being taken care of step by step.
