### ISSUE TITLE
Sensors_plus: UserAccelerometer Z reporting incorrect values

### ISSUE THREAD

**Issue by richtea99** [fluttercommunity/plus_plugins#2444]
### Platform

Android 13

### Plugin

sensors_plus

### Version

3.1.0

### Flutter SDK

3.13.6

### Steps to reproduce

This is potentially a device-specific problem, or it may be a code issue - it's not clear to me.
I bring it up just in case other devs have the same problem with other devices.

Device: Lenovo Tab P11 2nd Gen device, running Android 13

UserAccelerometer Z reports a large non-zero value when device is stationary:
- device held vertical/perpendicular to the ground, value = ~0.0 (correct)
- device held flat/parallel to the ground facing downwards, value = ~20.0 (incorrect),  i.e. 2* gravity

In contrast the Accelerometer Z value is always correct.

Since the UserAccelerometer values are derived from Accelerometer (according to the docs) it seems there may be a bug in the UserAccelerometer logic.

I'm happy to test any potential fixes, since I have access to the Lenovo device.

### Logs

```shell
-
```

### Flutter Doctor

```shell
.../Development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.1.1 23B81 darwin-arm64, locale en-GB)
    • Flutter version 3.13.6 on channel stable at .../Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (10 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at .../Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2021.3)
    • Android Studio at .../Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
There is no fix for this issue, because plugin uses standard SensorsManager from Android and requests UserAcceleromemeter sensor in parameters. No modification of returned by Android data happens by the plugin.

**Comment by richtea99** [comment]
OK, thanks for confirming.
