### ISSUE TITLE
Custom samplingPeriod doesn't work on Android

### ISSUE THREAD

**Issue by ClemPalf** [fluttercommunity/plus_plugins#2448]
### Platform

Android 13

### Plugin

sensors_plus

### Version

4.0.1

### Flutter SDK

3.16.1

### Steps to reproduce

Hi,

In a simple flutter app, just run the code sample.  
It works fine on IOS, the message "Event received" is logged every 4 seconds.  
On Android however, it seems like the samplingPeriod is always blocked at ~0.5 second (approximately).  

Regards,

### Code Sample

```dart
accelerometerEventStream(samplingPeriod: const Duration(seconds: 4))
            .listen((event) {
          print("Event received");
        });
```

### Logs

```shell
No exceptions/errors were logged.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.16.1, on macOS 14.1.2 23B92 darwin-arm64, locale en-FR)
    • Flutter version 3.16.1 on channel stable at /Users/clem/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (11 days ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/clementpalfroy/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/clem/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • iPhone de Clément (mobile) • 00008030-000259AA0E01802E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)            • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Please read the documentation first. It is explicitly mentioned there that it is not guaranteed on Android that the specified sampling rate will be applied. It is considered by the Android OS as a recommendation.
https://plus.fluttercommunity.dev/docs/sensors_plus/usage

So it is really up to a device that you use as during testing of this feature I noticed that on some Samsung devices sampling rate behaved differently compared to Pixel devices.

**Comment by ClemPalf** [comment]
My bad, it was properly highlighted and I should not have missed it. 
Thanks @vbuberen!

**Comment by vbuberen** [comment]
Thanks to you as well. I will add this note to README as well for better visibility as your case showed that having on website only is not enough.
