### ISSUE TITLE
android_intent_plus canResolveActivity with package name failure

### ISSUE THREAD

**Issue by doc-rj-celltrak** [fluttercommunity/plus_plugins#245]
## System info

Issue occurs on: Android
Plugin name: android_intent_plus
Plugin version: 1.0.1
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

• No issues found!
```

## Steps to Reproduce

1. Use the canResolveActivity() method with a package name for an app that is not installed. For example, if Chrome is not installed, but another browser is installed. Use this intent: 

  static const _chromeTestIntent = AndroidIntent(
    action: 'android.intent.action.VIEW',
    data: 'https://www.google.com',
    package: 'com.android.chrome',
  );

2. canResolveActivity() will return true if *any* app can handle the intent's action. However, it should only return true if the Chrome package is installed and can handle the intent.

The problem is that the buildIntent() method is called from onMethodCall() before testing the intent. The buildIntent() method checks if the intent can be resolved and sets the package to null (removing the package condition) if it cannot.

```
    if (intent.resolveActivity(applicationContext.getPackageManager()) == null) {
        Log.i(TAG, "Cannot resolve explicit intent - ignoring package");
        intent.setPackage(null);
    }
```

**Comment by miquelbeltran** [comment]
Thanks for noticing this! PRs with the fix are welcome too.

**Comment by doc-rj-celltrak** [comment]
I suppose this logic is consistent if the assumption is that they will use this plugin to launch the intent after testing it. However, it's a bit strange to ignore a package-explicit intent's intent, and just use any app. So maybe the overall behavior should be changed, or at least better documented?

**Comment by doc-rj-celltrak** [comment]
I agree. If the side effect is removed, though, hopefully it's not a breaking change for too many folks. I doubt it.

**Comment by navczydev** [comment]
@mhadaily , I would like to work on this issue.

**Comment by mhadaily** [comment]
@navczydev go ahead,looking forward to the PR.

**Comment by miquelbeltran** [comment]
It can be closed, I will prepare the release in a moment

**Comment by navczydev** [comment]
Thank you, It was a great experience to contribute to the community.
