### ISSUE TITLE
Migrate Android plugins from jcenter to mavenCentral 

### ISSUE THREAD

**Issue by jmagman** [fluttercommunity/plus_plugins#246]
## Use case

The jcenter maven repo is sunsetting and is now readonly https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter.

## Proposal
Migrate plugins build.gradle configs from `jcenter()` to `mavenCentral()` maven repository if all dependencies are present there.

https://github.com/fluttercommunity/plus_plugins/blob/dad827d30d6211a0b5fa8422bf4c4a8ae3391c77/packages/android_alarm_manager_plus/android/build.gradle#L4-L20
```diff
buildscript {
    repositories {
        google()
-       jcenter()
+       mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}

allprojects {
    repositories {
        google()
-       jcenter()
+       mavenCentral()
    }
}
```

This was done in flutter/flutter app templates and example apps in https://github.com/flutter/flutter/issues/78338 and the 1p plugins in https://github.com/flutter/flutter/issues/82847.

**Comment by miquelbeltran** [comment]
Thanks for the proposal, PRs with the fix are welcome!

**Comment by jpnurmi** [comment]
@mhadaily Is there anything left to do, or can this be closed?

**Comment by mhadaily** [comment]
yes, we can close it
