### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SileoWorkSpace** [fluttercommunity/plus_plugins#2473]
### Platform

android

### Plugin

device_info_plus 9.1.0

### Version

9.1.0

### Flutter SDK

3.16.0

### Steps to reproduce

While fetching data in android device getting some error,
<img width="293" alt="Screenshot 2023-12-22 at 1 02 05 PM" src="https://github.com/fluttercommunity/plus_plugins/assets/112624500/b60d7a2a-996e-4ac9-9e74-5f0e93549248">

### Logs

```shell
no log found
```

### Flutter Doctor

```shell
no found
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by LBYPatrick** [comment]
It does not seem like an error coming from our framework...This popup window is spawned by developer's code rather than us. Can you provide your code snippet for checking device info? Also, we do need to see logs in order to assist you, thank you!
