### ISSUE TITLE
[Request]: support HarmonyOS 

### ISSUE THREAD

**Issue by zmtzawqlp** [fluttercommunity/plus_plugins#2480]
### Plugin

package_info_plus

### Use case

OpenHarmony will support flutter base on Flutter 3.7.12.  it comes from https://gitee.com/openharmony-sig/flutter_flutter.

### Proposal

I can help to work on this. but i need to which version should i work on for those plugins.

**Comment by zmtzawqlp** [comment]
all plugins are in one Repository, it's hard to pick the version base on 3.7.12

**Comment by vbuberen** [comment]
What do you mean under `support HarmonyOS`? What is required there?

You don't need to pick any version. You clone the repo and do the work and then open the PR. Read the https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md for more information.

**Comment by zmtzawqlp** [comment]
> What do you mean under `support HarmonyOS`? What is required there?
> 
> You don't need to pick any version. You clone the repo and do the work and then open the PR. Read the https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md for more information.

but flutter for harmonyOS is base on flutter sdk 3.7.12。  i think we need to work on the version of package_info  which fit flutter sdk 3.7.12

**Comment by vbuberen** [comment]
> but flutter for harmonyOS is base on flutter sdk 3.7.12。 i think we need to work on the version of package_info which fit flutter sdk 3.7.12

So what is the problem? `package_info_plus` works with 3.7.12 version fine.

**Comment by zmtzawqlp** [comment]
> > but flutter for harmonyOS is base on flutter sdk 3.7.12。 i think we need to work on the version of package_info which fit flutter sdk 3.7.12
> 
> So what is the problem? `package_info_plus` works with 3.7.12 version fine.

i mean `package_info_plus` can't run on 3.7.12 , because web and win are not supported on 3.7.12. they are request dart 3.2,  and 3.7.12 is on 2.19.6

**Comment by vbuberen** [comment]
Ah, got it now.
In such case users from HarmonyOS should use older versions of `package_info_plus`. Or HarmonyOS should start using newer Flutter version. 

There are no plans and no desire to do something special because China wants so with their censorship games or whatever it is this time. Plus package will move on with the rest of Flutter ecosystem.

**Comment by zmtzawqlp** [comment]
I know that only the old version can be used. My idea is, if possible, to create a new branch, find the code compatible with version 3.7.12, and make it suitable for HarmonyOS. Then, we can release a special version. If possible, it would be best to base it on the FlutterCommunity. I can help with this, but of course, if you find it inconvenient, can I create my own package based on FlutterCommunity's code?

**Comment by vbuberen** [comment]
I think it is more a question about licence type the project has: https://github.com/fluttercommunity/plus_plugins/blob/main/LICENSE
