### ISSUE TITLE
[Request]: Adding the sensitivity percentage

### ISSUE THREAD

**Issue by alireza-hnzpv** [fluttercommunity/plus_plugins#2502]
### Plugin

sensors_plus

### Use case

hi,
I am using accelerometerEventStream. This sensor is constantly vibrating much more with the smallest vibration. Please add the sensitivity percentage to this package so that the received numbers change more smoothly.

### Proposal

aaaa

**Comment by vbuberen** [comment]
>  This sensor is constantly vibrating much more with the smallest vibration. Please add the sensitivity percentage to this package so that the received numbers change more smoothly.

You have an option to set sensor sample rate since 4.0.1 version, so pick the latest version and set the sampling rate you need. No other configurable options available. Moreover, you can filter your stream in your app as you wish.

> aaaa

That is not the best way to fill in requests.
