### ISSUE TITLE
Wifi name comes with double quotes

### ISSUE THREAD

**Issue by elmar001** [fluttercommunity/plus_plugins#2505]
### What is your question?

Previosly this package was working in my app without any issue. Recently, I have noticed that Wifi name now has double quotes around it:
final wifiName = await info.getWifiName();
debugPrint("This is WIFI name: ");
debugPrint(wifiName.toString());
// Prints: "WifiName" instead of WifiName

Interesting thing is that I am using a bit older version (^2.1.3) of this package and have not updated version number.
The question is how is this happening? Bug created as a result of this change in production app.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
I would ask you to report issues in the latest versions as it doesn't make sense to guess if the issue is present in the latest version or it is fixed already.

**Comment by miquelbeltran** [comment]
This was already discussed here: https://github.com/fluttercommunity/plus_plugins/issues/1326
