### ISSUE TITLE
Share plugin does not work on iOS when it is invalid for a view controller to be presented on iOS's root view controller

### ISSUE THREAD

**Issue by searchy2** [fluttercommunity/plus_plugins#251]
Copied from the original share plugin at https://github.com/flutter/flutter/issues/67103
There is a PR to resolve the issue that was rejected because they stopped taking PRs on the original repo.

https://github.com/flutter/plugins/pull/3105

The solution looks good. 
What is needed to get the fixes merged into this library?

**Comment by miquelbeltran** [comment]
Anyone can copy the changes into a new PR and submit it here. Help is welcome!

**Comment by searchy2** [comment]
@sianxz I'm going to go ahead and copy your commit into the new repo. Hope you don't mind!
