### ISSUE TITLE
[Request]: share_plus-7.2.1\android\src\main\kotlin\dev\fluttercommunity\plus\share\Share.kt:139:55: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java

### ISSUE THREAD

**Issue by dimiril** [fluttercommunity/plus_plugins#2519]
### Plugin

share_plus-7.2.1

### Use case

C:\Users\zoom\AppData\Local\Pub\Cache\hosted\pub.dev\share_plus-7.2.1\android\src\main\kotlin\dev\fluttercommunity\plus\share\Share.kt:139:55: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
        val resInfoList = getContext().packageManager.queryIntentActivities(
                                                      ^
C:\Users\zoom\AppData\Local\Pub\Cache\hosted\pub.dev\share_plus-7.2.1\android\src\main\kotlin\dev\fluttercommunity\plus\share\SharePlusPendingIntent.kt:31:20: warning: 'getParcelableExtra(String!): T?' is deprecated. Deprecated in Java
            intent.getParcelableExtra<ComponentName>(Intent.EXTRA_CHOSEN_COMPONENT)

### Proposal

C:\Users\zoom\AppData\Local\Pub\Cache\hosted\pub.dev\share_plus-7.2.1\android\src\main\kotlin\dev\fluttercommunity\plus\share\Share.kt:139:55: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
        val resInfoList = getContext().packageManager.queryIntentActivities(
                                                      ^
C:\Users\zoom\AppData\Local\Pub\Cache\hosted\pub.dev\share_plus-7.2.1\android\src\main\kotlin\dev\fluttercommunity\plus\share\SharePlusPendingIntent.kt:31:20: warning: 'getParcelableExtra(String!): T?' is deprecated. Deprecated in Java
            intent.getParcelableExtra<ComponentName>(Intent.EXTRA_CHOSEN_COMPONENT)
C:\Users\zoom\AppData\Local\Pub\Cache\hosted\pub.dev\share_plus-7.2.1\android\src\main\kotlin\dev\fluttercommunity\plus\share\Share.kt:139:55: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
        val resInfoList = getContext().packageManager.queryIntentActivities(
                                                      ^
C:\Users\zoom\AppData\Local\Pub\Cache\hosted\pub.dev\share_plus-7.2.1\android\src\main\kotlin\dev\fluttercommunity\plus\share\SharePlusPendingIntent.kt:31:20: warning: 'getParcelableExtra(String!): T?' is deprecated. Deprecated in Java
            intent.getParcelableExtra<ComponentName>(Intent.EXTRA_CHOSEN_COMPONENT)

**Comment by vbuberen** [comment]
This doesn't cause any issues to functionality and a simple warning.
Will be resolved when packages migrate to target SDK 34 which will happen later this year.
