### ISSUE TITLE
[share_plus] How could we call sync function when clicked an option from share sheet?

### ISSUE THREAD

**Issue by MCYBA** [fluttercommunity/plus_plugins#252]
## Use case
I want to run some process just before forwarding to the selected option from the share sheet. This could be very useful for providing the customization ability to users by option about content been sharing.

## Proposal

Exactly I want to call a function after clicking an option and start to hold the sharing, Then calling another function to stop waiting and complete sharing.

**Comment by muhammadidrees** [comment]
If I understand correctly, you want a function to be called after the user has selected the share option so you may edit the content being shared. Once the user has made modifications they could continue sharing.

Is there any particular reason why you want this to be after the share option has been selected? You can simply ask the user to make modifications before calling the share method itself.

**Comment by MCYBA** [comment]
The particular reason is sharing the media content to the specific platform with compatibility of that platform's standards such as dimensions. If the user can select the target platform first, we can set the editing environment by it.

**Comment by muhammadidrees** [comment]
I guess that makes sense. (Still can't come up with a use case though :sweat_smile: ). 

But the thing is to make this work you would need the information about the platform via which the content is being shared and the dimension requirements of that platform. :thinking:

**Comment by MCYBA** [comment]
Why not? Instagram, Facebook, Twitter, Tiktok, etc. all have their own size specifications. If you try to use a media that is cropped for Instagram, that won't exactly fit others.
