### ISSUE TITLE
[Question]: Using share_plus with KaKaoTalk doesn't work properly

### ISSUE THREAD

**Issue by llllilliliii** [fluttercommunity/plus_plugins#2520]
### What is your question?

When using share_plus for sharing both images and text with shareXFiles, KakaoTalk cannot share the text properly. It only shares images. But KaKaoTalk offers its own sharing API so I decided to use it.

Is there any options for it? My idea is inserting if conditions like comparing package names and when it equals to KakaoTalk's , It opens KaKao's own sharing API or goes to initiating the method which opens it.

btw, I'm korean sorry for my bad english :) 

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
No, there are no plans and desire to support companies like Meta or KakaoTalk with their custom sharing APIs. 
Ask KakaoTalk to use generally available APIs instead of creating their own.
