### ISSUE TITLE
[Request]: README add note about VPN

### ISSUE THREAD

**Issue by AVaccar** [fluttercommunity/plus_plugins#2522]
### Plugin

connectivity_plus

### Use case

I spent a lot of time debugging why the application on my phone wasn't detecting connectivity changes when i was enabling/disabling the wifi.  
In the end i had the duck duck go vpn enabled that was impeding network changes to be triggered.  
The moment i disabled it, the `Connectivity().onConnectivityChanged.listen` started working as expected.

### Proposal

Add a note in the readme about VPN next to the example of the stream subscription

**Comment by vbuberen** [comment]
With [6.0.1](https://pub.dev/packages/connectivity_plus/changelog#601) release of the plugin it is not the case anymore as the result returned from the plugin now contains multiple connectivity types, so now your case should also work properly.

Closing as resolved.
