### ISSUE TITLE
[Question]: not getting wifi name and bssid. before i was getting it now again i used this package don't give me result

### ISSUE THREAD

**Issue by Alka0028** [fluttercommunity/plus_plugins#2528]
### What is your question?

not getting wifi name and bssid. before i was getting it now again i used this package don't give me result

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Would you mind proving more info, because currently it is not clear which platform, which plugin versions affected, etc.?

**Comment by Alka0028** [comment]
problem solved
