### ISSUE TITLE
[Bug]: Bump MACOSX_DEPLOYMENT_TARGET to Flutter minimum (10.14)

### ISSUE THREAD

**Issue by luisredondo** [fluttercommunity/plus_plugins#2529]
# Description

Flutter actively replaces targets 10.11 and 10.13 in their source code. Reference: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/macos/migrations/macos_deployment_target_migration.dart#L51

They did a whole doc explaining why to stop support for 10.13: https://docs.google.com/document/d/1wHqr2cob78VfUKhOFEKjaUM_mnV4gL-mg3gSQCFhF7Y/edit

Here is another issue tracking the progress of the update, where it highlights platforms that will lose support if minimun target is >10.13:  https://github.com/flutter/flutter/issues/114445

I think the minimum target for MacOS should be bump in all the `plus_plugins` to the minimum one that the latest stable version supports, since the warning is there for a reason, which it's probably to prevent unexpected behavior. 

I can implement this if you agree with the bumping!

### Platform

macos

### Plugin

connectivity_plus

### Version

connectivity_plus: ^5.0.2

### Flutter SDK

3.16.5

### Steps to reproduce

1. Create a flutter default project with the latest stable version.
2. Add `connectivity_plus` as dependency.
3. `flutter run -d macos`
4. Look at the console and we should see what listed in `Logs`.

### Logs

```shell
/Users/user/flutter_project/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.2.99. (in target 'ReachabilitySwift' from project 'Pods')
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.0 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Hey @luisredondo 
Could you share if there are plan to create such PRs in some nearest time or later?
Asking, because I would like to release this change of min support MacOS as a major version bump and, ideally, I would like to combine some other breaking change PRs together, like #2508 to not increase major version many times.

**Comment by luisredondo** [comment]
> Hey @luisredondo Could you share if there are plan to create such PRs in some nearest time or later? Asking, because I would like to release this change of min support MacOS as a major version bump and, ideally, I would like to combine some other breaking change PRs together, like #2508 to not increase major version many times.

Hey @vbuberen! I will do it later today. 🙌
