### ISSUE TITLE
[file_selector_plus] would be a great addition 

### ISSUE THREAD

**Issue by tlueder** [fluttercommunity/plus_plugins#253]
At the moment there is no null safety and cross platform plugin available.

## Use case

Select files on any platform.

## Proposal

Combine the existing plugins into one truly cross platform plugin

https://pub.dev/packages/file_selector
https://pub.dev/packages/file_selector_linux
https://pub.dev/packages/file_selector_macos
https://pub.dev/packages/file_selector_web
https://pub.dev/packages/file_selector_windows

And add Android and iOS support .

**Comment by mhadaily** [comment]
Thanks for the proposal. We have no plan to fork more plugins at the moment but this is a great one if we want. 
We can escalate this to the flutter team but I'd suggest you open an issue in the Flutter repo and link back to this issue for cross-reference.

**Comment by stuartmorgan** [comment]
@tlueder Can you explain why you want to see a fork of `file_selector`? The web version is already endorsed, and endorsing the desktop implementations you've listed is the plan (as their README says) as soon as the necessary test infrastructure exists. iOS and Android implementations of the plugin would be welcome in the flutter/plugins repository.
