### ISSUE TITLE
[Question]: How to start a SEND_MULTIPLE  intent that sends multiple photos?

### ISSUE THREAD

**Issue by alex-georgiou** [fluttercommunity/plus_plugins#2539]
### What is your question?

Hello,

I am trying to use `android_intent_plus` version `4.0.3` to start an `android.intent.action.SEND_MULTIPLE` intent that will send a bunch of JPEG photos.

I couldn't find any examples on how to send multiple files using this plugin.

I am getting a runtime exception and I am not sure what I'm doing wrong, or if there is an issue with the plugin when attaching multiple Uris.

I have my photo Uris in a variable `photoUriPaths` of type `List<Uri>` and all the Uris start with `content://`. My code:

	if (Platform.isAndroid) {
	  AndroidIntent intent = AndroidIntent(
		action: 'android.intent.action.SEND_MULTIPLE',
		type: 'image/jpeg',
		arrayArguments: <String, List<dynamic>>{
		  'android.intent.extra.STREAM': photoUriPaths,
		},
		flags: [
		  Flag.FLAG_ACTIVITY_NEW_TASK,
		  Flag.FLAG_GRANT_READ_URI_PERMISSION,
		],
	  );

	  await intent.launch();
	}

The above throws an exception:

	E/flutter ( 5851): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument: Instance of '_SimpleUri'
	E/flutter ( 5851): #0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:464:7)
	E/flutter ( 5851): #1      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:454:9)
	E/flutter ( 5851): #2      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:461:9)
	E/flutter ( 5851): #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
	E/flutter ( 5851): #4      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:459:13)
	E/flutter ( 5851): #5      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:461:9)
	E/flutter ( 5851): #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
	E/flutter ( 5851): #7      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:459:13)
	E/flutter ( 5851): #8      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:602:18)
	E/flutter ( 5851): #9      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:311:34)
	E/flutter ( 5851): #10     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:495:12)
	E/flutter ( 5851): #11     AndroidIntent.launch (package:android_intent_plus/android_intent.dart:150:20)

However, it also doesn't work when I pass the Uris as a `List<String>` type:

	V/IntentSender( 5851): Sending intent Intent { act=android.intent.action.SEND_MULTIPLE typ=image/jpeg flg=0x10000001 (has extras) }
	W/Bundle  ( 5851): Key android.intent.extra.STREAM expected ArrayList<android.net.Uri> but value was of a different type.  The default value <null> was returned.
	W/Bundle  ( 5851): Attempt to cast generated internal exception:
	W/Bundle  ( 5851): java.lang.ClassCastException: Cannot cast [Ljava.lang.String; to java.util.ArrayList
	W/Bundle  ( 5851): 	at java.lang.Class.cast(Class.java:4109)
	W/Bundle  ( 5851): 	at android.os.BaseBundle.getValueAt(BaseBundle.java:404)
	W/Bundle  ( 5851): 	at android.os.BaseBundle.getValue(BaseBundle.java:381)
	W/Bundle  ( 5851): 	at android.os.BaseBundle.getArrayList(BaseBundle.java:1527)
	W/Bundle  ( 5851): 	at android.os.Bundle.getParcelableArrayList(Bundle.java:1090)
	W/Bundle  ( 5851): 	at android.content.Intent.getParcelableArrayListExtra(Intent.java:9228)
	W/Bundle  ( 5851): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:12362)
	W/Bundle  ( 5851): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1871)
	W/Bundle  ( 5851): 	at android.app.Activity.startActivityForResult(Activity.java:5589)
	W/Bundle  ( 5851): 	at android.app.Activity.startActivityForResult(Activity.java:5547)
	W/Bundle  ( 5851): 	at android.app.Activity.startActivity(Activity.java:6045)
	W/Bundle  ( 5851): 	at android.app.Activity.startActivity(Activity.java:6012)
	W/Bundle  ( 5851): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
	W/Bundle  ( 5851): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:101)
	W/Bundle  ( 5851): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	W/Bundle  ( 5851): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	W/Bundle  ( 5851): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	W/Bundle  ( 5851): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	W/Bundle  ( 5851): 	at android.os.Handler.handleCallback(Handler.java:958)
	W/Bundle  ( 5851): 	at android.os.Handler.dispatchMessage(Handler.java:99)
	W/Bundle  ( 5851): 	at android.os.Looper.loopOnce(Looper.java:205)
	W/Bundle  ( 5851): 	at android.os.Looper.loop(Looper.java:294)
	W/Bundle  ( 5851): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
	W/Bundle  ( 5851): 	at java.lang.reflect.Method.invoke(Native Method)
	W/Bundle  ( 5851): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	W/Bundle  ( 5851): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

However, when I try to view a single file, the following works and opens a photo viewer:

	if (Platform.isAndroid) {
	  AndroidIntent intent = AndroidIntent(
		action: 'action_view',
		data: photoUriPaths.first.path, // this is the path without any content:// or any other schema prefix
		type: 'image/jpeg',
		flags: [
		  Flag.FLAG_ACTIVITY_NEW_TASK,
		  Flag.FLAG_GRANT_READ_URI_PERMISSION,
		],
	  );

My `flutter doctor` output:

	Doctor summary (to see all details, run flutter doctor -v):
	[✓] Flutter (Channel stable, 3.16.9, on Ubuntu 20.04.6 LTS 5.4.0-169-generic, locale en_US.UTF-8)
	[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
	[✓] Chrome - develop for the web
	[✓] Linux toolchain - develop for Linux desktop
	[✓] Android Studio (version 2022.3)
	[✓] Connected device (3 available)
	[✓] Network resources

	• No issues found!

Any help will be **greatly** appreciated.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
> I couldn't find any examples on how to send multiple files using this plugin.

I am curios on why you decided to not use `share_plus` for this purpose as it would be more suitable, from my point of view. Are there any reasons for such pick?

> W/Bundle  ( 5851): Key android.intent.extra.STREAM expected ArrayList<android.net.Uri> but value was of a different type.  The default value <null> was returned.

I will take a look, but this doesn't seem right to me.

**Comment by alex-georgiou** [comment]
I did not consider `share_plus`. Thank you, I will have a look.

I guess this question can be closed.

**Comment by ozyl** [comment]
This problem does exist. Currently, android_intent_plus does not support sharing SEND_MULTIPLE EXTRA_STREAM, and share_plus does not support specifying action, package, and category. The scenario is to specify app to send pictures, and I hope to add support in android_intent_plus.

这个问题是存在的，目前android_intent_plus 不支持分享SEND_MULTIPLE EXTRA_STREAM, share_plus不支持指定action,package,category。场景是指定app发送图片，希望在android_intent_plus添加支持。
