### ISSUE TITLE
[Bug]: Building App Bundle does throws error with share_plus 7.2.2

### ISSUE THREAD

**Issue by Wegi** [fluttercommunity/plus_plugins#2543]
### Platform

Android

### Plugin

share_plus

### Version

7.2.2

### Flutter SDK

3.16.9

### Steps to reproduce

`flutter build appbundle` after adding share_plus 7.2.2 to the dependencies.

### Logs

```shell
e: file:///<path>/.pub-cache/hosted/pub.dev/share_plus-7.2.2/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt:22:26 Unresolved reference: ShareSuccessManager
e: file:///<path>/.pub-cache/hosted/pub.dev/share_plus-7.2.2/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt:160:59 Unresolved reference: ShareSuccessManager

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':share_plus:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
Running Gradle task 'bundleRelease'...                             47,7s
Gradle task bundleRelease failed with exit code 1
```

### Flutter Doctor

```shell
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1.1 23B81 darwin-arm64, locale de-DE)
    • Flutter version 3.16.9 on channel stable at /Users/wegi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (vor 7 Tagen), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wegi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/wegi/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/wegi/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Users/wegi/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone von Alexander (mobile) • 00008130-000A64562491401C • ios            • iOS 17.2.1 21C66
    • macOS (desktop)               • macos                     • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
> e: file:///<path>/.pub-cache/hosted/pub.dev/share_plus-7.2.2/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt:160:59 Unresolved reference: ShareSuccessManager

This doesn't make any sense as `ShareSuccessManager` is shipped with `share_plus`, not even in platform interface dependency. It looks to me like some issue with dependency resolution.

I have just tried to create a new Flutter project, add 7.2.2 and run `flutter build appbundle` - everything works as expected on a new empty project. Thus, I would ask you to provide a reproducer or look for the problem at your project setup.

<img width="590" alt="Screenshot 2024-02-02 at 10 00 37" src="https://github.com/fluttercommunity/plus_plugins/assets/13467769/17e1ffde-240e-44c8-af03-732300bd7e40">

**Comment by Wegi** [comment]
Yeah, thats what I found weird too. 7.2.1 made no problems. I'll try to make a minimum example project with the error later. 👍

**Comment by vbuberen** [comment]
Could you share which version of Android Gradle Plugin and Kotlin your project uses?

**Comment by Wegi** [comment]
Kotlin version 1.9.10
Gradle Plugin 7.4.2

**Comment by Wegi** [comment]
I also cannot reproduce the error with a fresh project. I guess it is as you said some dependency collision. Sorry for the trouble.

I'll close this now.

**Comment by vbuberen** [comment]
> Kotlin version 1.9.10

Out of curiosity - what happens if you change it to `1.8.20` or `1.7.22`? Would that make your project work?
Because a few months ago I had to revert Kotlin in plugins from `1.9.10` as on projects where dependencies use a big variety of older versions of Kotlin users often had some troubles with building.

**Comment by Wegi** [comment]
It worked with 1.8.20, but also worked, when I changed it back to 1.9.10. Starting to believe it was a gradle caching issue or something similar.

**Comment by vbuberen** [comment]
Thanks for sharing. Hope it would help somebody else with such mysterious issue in future.

**Comment by lucien144** [comment]
What helped me in an existing project was to change this line in `android/build.gradle` from:

`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"`

to

`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"`
