### ISSUE TITLE
deviceMemory: Expected a value of type 'int', but got one of type 'Null'

### ISSUE THREAD

**Issue by KirillArtemenko** [fluttercommunity/plus_plugins#255]
I have an error **TypeErrorImpl (Expected a value of type 'int', but got one of type 'Null')** when i trying to get webBrowserInfo on web version of my app:
`final WebBrowserInfo webBrowserInfo = await deviceInfoPlugin.webBrowserInfo;`

deviceMemory value is None and it produces an error: ""

This what i got on "map" variable inside WebBrowserInfo.fromMap(map) method:
![2021-05-27_14-33-23](https://user-images.githubusercontent.com/667503/119819631-404f3900-bef9-11eb-8d14-eb16481fe19d.png)

As we can see "deviceMemory" -> null and it's produce an error.

this simple fix is solve my problem, maybe you need to add this:
```
deviceMemory: map['deviceMemory'],
// replaced to
deviceMemory: map['deviceMemory'] ?? 0,
```

Flutter version: 2.2.0
Issue occurs on: Web
Plugin name: device_info_plus
Plugin version: 1.0.1
Flutter doctor output: all is ok

**Comment by miquelbeltran** [comment]
Thanks for the report @KirillArtemenko ! PRs with the fix are more than welcome.

**Comment by KirillArtemenko** [comment]
> Thanks for the report @KirillArtemenko ! PRs with the fix are more than welcome.
PR ready!
https://github.com/fluttercommunity/plus_plugins/pull/256

**Comment by KirillArtemenko** [comment]
I created another PR, it is better coz more backward compatible and no need any changes for ios/android of plugin developers.

https://github.com/fluttercommunity/plus_plugins/pull/257

**Comment by miquelbeltran** [comment]
Version 2.0.0 with the fixes are published

**Comment by KirillArtemenko** [comment]
Thank you but still not available here https://pub.dev/packages/device_info_plus
Update please.

**Comment by miquelbeltran** [comment]
It's up now, I had an issue with the publishing script
