### ISSUE TITLE
[device_info_plus] Provide toMap functions

### ISSUE THREAD

**Issue by vHanda** [fluttercommunity/plus_plugins#259]
It would be nice if`AndroidDeviceInfo` and `IosDeviceInfo` have a public `toMap` function, as this helps a lot with debugging / serialization. The implementation of `toMap` is already provided in the [example](https://github.com/flutter/plugins/blob/master/packages/device_info/device_info/example/lib/main.dart#L60). I'm duplicating this in many projects.

There is a similar [issue](https://github.com/flutter/flutter/issues/54430) which could also be fixed by this.

This bug was originally filled over here - https://github.com/flutter/flutter/issues/75406 - but it was closed without tracking it here :(

**Comment by jpnurmi** [comment]
@vHanda Thanks for the suggestion. Would you be willing to help out and create a PR?

**Comment by reverie-ss** [comment]
Any update on this fix?
