### ISSUE TITLE
[Request]: Dependency JS Update

### ISSUE THREAD

**Issue by yunusemrecetin** [fluttercommunity/plus_plugins#2598]
### Plugin

connectivity_plus

### Use case

Many packages are using "js 0.7.0" but "connectivity_plus" is using older one. It's can update for the future?

### Proposal

Because connectivity_plus 5.0.2 depends on js ^0.6.4 and flutter_native_splash >=2.3.11 depends on js ^0.7.0, connectivity_plus 5.0.2 is incompatible with flutter_native_splash >=2.3.11.
So, because flutter_app depends on both flutter_native_splash 2.3.11 and connectivity_plus 5.0.2, version solving failed.

**Comment by IchordeDionysos** [comment]
Would probably be solved by dropping js dependency in favor of https://github.com/fluttercommunity/plus_plugins/issues/2600

**Comment by IchordeDionysos** [comment]
@vbuberen shouldn't the js dependency removed entirely in favor of web.

To enable compiling to WASM?

**Comment by vbuberen** [comment]
It will be removed, but later. I have seen your issues about WASM, but we already keep track of it as I mentioned one of related issues.

**Comment by miquelbeltran** [comment]
Closed in #2621, the dependency to `js` has been removed
