### ISSUE TITLE
[package_info_plus_web] Location of version.json

### ISSUE THREAD

**Issue by deakjahn** [fluttercommunity/plus_plugins#26]
The plugin supposes that `version.json` is in the root of the website but this is not the case if the app is placed into a folder. It should be looked for in the app root, not the website root.

**Comment by mhadaily** [comment]
Hello, 

you need to switch to the `master` channel. and then you'll see there will be a `version.json` which flutter is generating that. we will add more description and details to this package in the next release. here is the link to PR https://github.com/flutter/flutter/pull/64644/files

**Comment by deakjahn** [comment]
I'm not really sure how that relates to what I wrote. :-)

The `version.json` is generated all right. It's in the correct location. The problem is with the code that _reads_ it, not the one that _creates_ it.

The line at https://github.com/fluttercommunity/plus_plugins/blob/98e295bbed33d2b71f473af38e3165693ced7935/packages/package_info_plus_web/lib/package_info_plus_web.dart#L21 reads it from the root of the referenced website. The problem is that it isn't necessary there. It might be below this root folder if the app has been installed into a folder below the website root.

**Comment by mhadaily** [comment]
@deakjahn thanks again for clarification. 
I will investigate more and will add a bug fix. or alternatively, feel free to continue by sending a PR to fix this issue if you would like to help to fix this issue.

**Comment by jpnurmi** [comment]
I have pushed a fix proposal: https://github.com/fluttercommunity/plus_plugins/pull/32

**Comment by mhadaily** [comment]
This was fixed and will be released soon. https://github.com/fluttercommunity/plus_plugins/pull/32
