### ISSUE TITLE
[Request]: (device_info_plus): migrate to pkg:web from dart:html

### ISSUE THREAD

**Issue by dxvid-pts** [fluttercommunity/plus_plugins#2601]
### Plugin

device_info_plus

### Use case

Flutter web apps are required to migrate from `dart:html` to `package:web` to use WASM.

### Proposal

This issue tracks the upgrade process for `device_info_plus`.

See https://docs.flutter.dev/platform-integration/web/wasm and https://pub.dev/packages/web for more information

**Comment by amorenew** [comment]
any updates?

**Comment by miquelbeltran** [comment]
> any updates?

https://github.com/fluttercommunity/plus_plugins/issues/2600#issuecomment-1952001128

**Comment by amorenew** [comment]
@miquelbeltran wow, it closed same day I asked 😁😂

**Comment by amorenew** [comment]
@miquelbeltran I made a PR with a different account to fix this issue

https://github.com/fluttercommunity/plus_plugins/pull/2622

**Comment by miquelbeltran** [comment]
> @miquelbeltran I made a PR with a different account to fix this issue
> 
> #2622

Looks like the PR has nothing to do with this issue. Maybe you are mixing packages? The PR is modifying package_info_plus code and this ticket is about device_info_plus.

**Comment by amorenew** [comment]
@miquelbeltran oh no I made a mistake, I will open an issue for package_info_plus
it is night here, I need to focus more 😭😱

**Comment by miquelbeltran** [comment]
`package_info_plus` is already using web

**Comment by miquelbeltran** [comment]
On `device_info_plus`: `Navigator.deviceMemory` seems to be missing in the current `web` implementation.

<img width="423" alt="image" src="https://github.com/fluttercommunity/plus_plugins/assets/2494376/bd42553b-c0f2-4e4d-b74a-abc69509fe7a">

References: 
- https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory
- https://api.dart.dev/stable/3.3.0/dart-html/Navigator/deviceMemory.html
