### ISSUE TITLE
[Request]: (sensors_plus) Migrate to `package:web` to support WASM

### ISSUE THREAD

**Issue by IchordeDionysos** [fluttercommunity/plus_plugins#2602]
### Plugin

sensors_plus

### Use case

Compiling to WASM

### Proposal

The short version:
- Migrate usage of dart:html to package:web
- Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop

This will allow compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

**Comment by miquelbeltran** [comment]
Did a quick check and seems that APIs like `LinearAccelerationSensor`, `Accelerometer`, etc. have not been ported to the `web` package, but they exist in `dart:html`.
