### ISSUE TITLE
[Request]: (share_plus) Migrate to `package:web` to support WASM

### ISSUE THREAD

**Issue by IchordeDionysos** [fluttercommunity/plus_plugins#2603]
### Plugin

share_plus

### Use case

Compiling to WASM

### Proposal

The short version:

Migrate usage of dart:html to package:web
Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop
This will allow compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

**Comment by sgehrman** [comment]
2 weeks and nothing.   What is taking so long??????

**Comment by miquelbeltran** [comment]
> 2 weeks and nothing. What is taking so long??????

https://github.com/fluttercommunity/plus_plugins/issues/2600#issuecomment-1952001128

In case you need this change urgently, you can also run a local fork with your changes. If you do, please consider submitting a PR with the change and your findings.

**Comment by vbuberen** [comment]
> 2 weeks and nothing. What is taking so long??????

This is an open source project, so you are more than welcome to do this yourself. Otherwise you can demand anything from people who support packages in their free time.

**Comment by muhib349** [comment]
Trying to work on this issue, however, I'm not getting any leads to initialize the navigator and how to use the share method, if anyone has an idea please let me know. thanks

**Comment by muhib349** [comment]
> Do you have a fork/branch somewhere @muhib349 to have a look?

Yes, you can have a look on this branch,

https://github.com/muhib349/plus_plugins/tree/issue2603

**Comment by IchordeDionysos** [comment]
@muhib349 you used the correct navigator, however it seems like the `share` method is not yet supported on the `package:web`.

What you could do is instead of relying on the `package:web`, use `dart:js_interop` and write your own JavaScript interop function.

This is how it's written in the `package:web`.

It could look a bit like:

```dart
import 'dart:js_interop';

extension type Navigator._(JSObject _) implements JSObject {
  # todo: Use correct return type and parameters :)
  external void share();
}
```

Then you can use that custom Navigator class and call it just like it would exist.
You wouldn't have to depend on `package:web` at all.

You might be required to set the minimum Dart Version to 3.3 though to use those [new Extension Types](https://medium.com/dartlang/dart-3-3-325bf2bf6c13#:~:text=Introducing%20Extension%20Types)

I hope this helps.

**Comment by miquelbeltran** [comment]
Yes, this helps a lot! 

Keep in mind that the original `dart:html` share method did some extra work: https://api.dart.dev/stable/3.3.0/dart-html/Navigator/share.html, so maybe that will need to be done as well.

Also, a similar solution was discussed here for the missing `deviceMemory` property for Navigator: https://github.com/dart-lang/web/issues/192#issuecomment-1971707999

And just for reference: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

Finally, probably also worth opening a ticket on the `dart-lang/web` repo asking them to incorporate the missing method from `dart:html`.

**Comment by muhib349** [comment]
Thanks a lot, @IchordeDionysos and @miquelbeltran. Meanwhile, I'm trying to implement.
