### ISSUE TITLE
[Request]: Please bump to web dependency to include 0.5.0

### ISSUE THREAD

**Issue by blaneyneil** [fluttercommunity/plus_plugins#2608]
### Plugin

package_info_plus

### Use case

package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0, which is blocking upgrades of other packages (and the web package itself)

### Proposal

please update the constraints to at least include web <=0.5.0

**Comment by miquelbeltran** [comment]
Done in https://github.com/fluttercommunity/plus_plugins/pull/2605 pending to be released.
