### ISSUE TITLE
[Request]: update dependencies

### ISSUE THREAD

**Issue by npateras** [fluttercommunity/plus_plugins#2619]
### Plugin

package_info_plus

### Use case

I need to update some deps on my project, but this package currently cannot run with their newest versions:
— http
— web
— meta

### Proposal

Please update the dependencies for the package.

**Comment by miquelbeltran** [comment]
`web` in `package_info_plus` has been updated in this PR: https://github.com/fluttercommunity/plus_plugins/pull/2605

Please use the search function next time.
