### ISSUE TITLE
[Request]: support the 'web ^0.5.0'

### ISSUE THREAD

**Issue by dvoloshyn** [fluttercommunity/plus_plugins#2620]
### Plugin

package_info_plus

### Use case

Because package_info_plus >=5.0.1 depends on web >=0.3.0 <0.5.0 and drift >=2.16.0 depends on web ^0.5.0, package_info_plus >=5.0.1 is incompatible with drift >=2.16.0.
So, because worldofgoals depends on both drift >=2.16.0 and package_info_plus >=5.0.1, version solving failed.

### Proposal

Support the 'web ^0.5.0'

**Comment by miquelbeltran** [comment]
https://github.com/fluttercommunity/plus_plugins/pull/2605

Please use the search function next time
