### ISSUE TITLE
[Request]: (package_info_plus): migrate to pkg:web from dart:html

### ISSUE THREAD

**Issue by amorenew** [fluttercommunity/plus_plugins#2623]
### Plugin

package_info_plus

### Use case

Flutter web apps are required to migrate from dart:html to package:web to use WASM.

### Proposal

This issue tracks the upgrade process for package_info_plus.

See https://docs.flutter.dev/platform-integration/web/wasm and https://pub.dev/packages/web for more information

**Comment by amorenew** [comment]
the fix is here
https://github.com/fluttercommunity/plus_plugins/pull/2622

**Comment by hnvn** [comment]
This one blocks upgrading many other dependencies, please address it, thank you so much

**Comment by amorenew** [comment]
@hnvn the PR is already opened, I need a review for it @miquelbeltran  could help too
https://github.com/fluttercommunity/plus_plugins/pull/2622

**Comment by miquelbeltran** [comment]
`package_info_plus` already uses `web`: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/package_info_plus/package_info_plus/pubspec.yaml#L36
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart#L7

This ticket description doesn't look correct to me.

**Comment by hnvn** [comment]
oh, @miquelbeltran please review and release this [fix](https://github.com/fluttercommunity/plus_plugins/commit/d24474d7b388fe43a9dd339b708834470bb14c90)

**Comment by miquelbeltran** [comment]
We are currently waiting for other breaking changes to land, and our planned release schedule is for mid-March.

Meanwhile, you can use a git reference to the package code directly, https://dart.dev/tools/pub/dependencies#git-packages we will appreciate the feedback if you can do it!
