### ISSUE TITLE
share_plus: 1.2.0 shareFiles() via WeChat only send the image file, but not the text (/subject)

### ISSUE THREAD

**Issue by mingwugmail** [fluttercommunity/plus_plugins#265]
## System info

Issue occurs on: only tested Android
Plugin name: share_plus
Plugin version: 1.2.0
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 1.22.6, on Microsoft Windows [Version 10.0.21390.1], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)
• No issues found!
```

## Steps to Reproduce

very basic example:
```
import 'package:share_plus/share_plus.dart';

...

Share.shareFiles(
                        [imagePath],
                        text: imgUrl,
                        subject: imgUrl
                      );
```

When share via WeChat, only the image is sent, but none of text / subject is sent.

In contrast, if share via Gmail, all the image, text & subject are sent.

Has anyone able to make it work on WeChat?

**Comment by leidig54** [comment]
Also occurs on iOS. Wont share image to WhatsApp if there is text present. Same story with Facebook.

**Comment by miquelbeltran** [comment]
Current version of share_plus is `2.1.2`.

Can you confirm you are using the latest version?

**Comment by leidig54** [comment]
Can confirm am on 2.1.2

**Comment by miquelbeltran** [comment]
Going to mark this as duplicated to #261 and will add info there

**Comment by samderlust** [comment]
I think we should open this again since #261 has been closed due to the author doesn't need to share text and images at the same time

**Comment by miquelbeltran** [comment]
I disagree, this is a limitation of sharing works on those apps, nothing to do with the plugin.
