### ISSUE TITLE
[Announcement]: 📢 package web migration and releases

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#2653]
This ticket contains up-to-date information regarding the state of the migration from `dart:html` to package `web`: https://pub.dev/packages/web

This is a live ticket and information posted here will be changing.

As always, we would like to remind you that this is a project run by volunteers in their free time, and ask you to be mindful when asking for updates. Repeated requests and general unprofessional behavior is considered a breach of our [Code of Conduct](https://github.com/fluttercommunity/plus_plugins/blob/main/CODE_OF_CONDUCT.md).

### When will be packages migrated?

**Update 2024-03-20**: All packages that have a web implementation have been migrated.

#### Packages migrated

- `package_info_plus`
- `device_info_plus`
- `connectivity_plus`
- `sensors_plus`
- `share_plus`
- `battery_plus`

#### Packages that don't require migration to `web`

- `android_alarm_manager_plus`
- `android_intent_plus`
- `network_info_plus`

All these packages are not supported on web.

#### Tickets

You can search in the repo for a specific package to see if it has been migrated, or if it still in progress:

- https://github.com/fluttercommunity/plus_plugins/issues/2600
- https://github.com/fluttercommunity/plus_plugins/issues/2601
- https://github.com/fluttercommunity/plus_plugins/issues/2602
- https://github.com/fluttercommunity/plus_plugins/issues/2603
- https://github.com/fluttercommunity/plus_plugins/pull/2316
- https://github.com/fluttercommunity/plus_plugins/pull/2625
- https://github.com/fluttercommunity/plus_plugins/pull/2605
- https://github.com/fluttercommunity/plus_plugins/pull/2624
- https://github.com/fluttercommunity/plus_plugins/pull/2697
- https://github.com/fluttercommunity/plus_plugins/pull/2720

### When will be packages released?

**Update 2024-03-20**: Releases should be going out this week, if everything is correct.

#### Dependency Overrides

If you have `web` package conflicts, you can try to override the version using "dependency override" https://dart.dev/tools/pub/dependencies#dependency-overrides, but there is no warranty that versions are compatible. **Do this under your own risk!**

```
dependency_overrides:
  web: ^0.5.0
```

#### Git Ref

You can also use a [git ref](https://dart.dev/tools/pub/dependencies#git-packages) to reference a specific commit in your pubspec.yml, so you don't have to wait for a package release. **Do this under your own risk!**

```
dependencies:
  package_info_plus:
    git: 
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/package_info_plus/package_info_plus
      ref: branch or commit sha
```

### I have a version conflict with the package `web`

Due to the package `web` being fairly new, each new release can be potentially a major release, and will require a new plus plugin release.

You can try using `dependency_overrides` as explained above to fix the issue, although the code may not be compatible with the selected `web` version.

### Latest Firebase Packages are incompatible with Plus Plugins Package

We are aware. This is due to Firebase plugins adding a dependency to `web: ^0.5.0`.

You can solve this issue with the `dependency_overrides` as mentioned before, until a new release with the updated dependency is released.

This will happen again when `web: 0.6.0` is released!

### Min Dart SDK version

Because `web` `0.5.0` depends on the sdk version `3.3.0`, all plugins using this package will start using sdk `>=3.3.0`.
This may require using the latest stable Flutter releases.

**Comment by navaronbracke** [comment]
@miquelbeltran The missing API's are probably because they are non-standard.

We can however, provide the missing API's using extension types, so I don't think any of those migrations are actually blocked.

See https://github.com/dart-lang/web?tab=readme-ov-file#compatibility

**Comment by miquelbeltran** [comment]
All web packages have been migrated now, and the releases should be published this week.

Special thank you to @koji-1009 for taking care of the migration of `share_plus, `sensors_plus` and `battery_plus`.

**Comment by miquelbeltran** [comment]
New package releases have been published.

It should also be easier to keep up with the web package updates, otherwise please try to use `dependency_override` before opening a ticket asking for a version upgrade.

Closing this issue now and un-pinning it.
