### ISSUE TITLE
[Request]: Show iOS user known device model names 

### ISSUE THREAD

**Issue by vbuberen** [fluttercommunity/plus_plugins#2656]
### Plugin

device_info_plus

### Use case

Currently on iOS plugin can't show user-known or commercial (not sure the correct word for it) device model. What I mean is that user of the plugin won't see something like `iPhone 15 Pro Max` or `iPad Air 5th generation`, etc. 

There are 2 properties for device model name available:
1. https://pub.dev/documentation/device_info_plus/latest/device_info_plus/IosDeviceInfo/model.html
2. https://pub.dev/documentation/device_info_plus/latest/device_info_plus/IosUtsname/machine.html
However, both of these params can't return model name like those that users got used to see.

There was a related question last year: #2225 

### Proposal

Considering adding https://github.com/devicekit/DeviceKit as a dependency in iOS part of the plugin and add a new property called something like `commercialModel` (or whichever suits better to indicate which type of device model name it is.

DeviceKit has this code that should help us with getting the required property: https://stackoverflow.com/a/26962452/7339798

After looking more at that repo I feel like we even could use more of features available in DeviceKit for plugin's functionality.

**Comment by kwent** [comment]
Looks pretty straightforward and would make the world a better place for us humans :)
