### ISSUE TITLE
[Request]: `package_info_plus` should be compatilbe with `web: ^0.5.0`

### ISSUE THREAD

**Issue by RoarGronmo** [fluttercommunity/plus_plugins#2657]
### Plugin

package_info_plus

### Use case

When trying to upgrade some of our plugins, `package_info_plus` seem to be the one to blame because of following dependency defiency when pinning i.e. plugin `http: ^1.2.1`: 

```
Because no versions of package_info_plus match >5.0.1 <6.0.0 and package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0, package_info_plus ^5.0.1 requires web >=0.3.0 <0.5.0.
And because http >=1.2.1 depends on web ^0.5.0, package_info_plus ^5.0.1 is incompatible with http >=1.2.1.
So, because m_office depends on both http ^1.2.1 and package_info_plus ^5.0.1, version solving failed.
```
Could you please update the dependencies in `package_info_plus` so it is compatible with `web: ^0.5.0` ?

secondly: 

If we try to pin plugin `drift: ^2.16.0`, we got same result:
```
Because no versions of package_info_plus match >5.0.1 <6.0.0 and package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0, package_info_plus ^5.0.1 requires web >=0.3.0 <0.5.0.
And because drift >=2.16.0 depends on web ^0.5.0, package_info_plus ^5.0.1 is incompatible with drift >=2.16.0.
So, because m_office depends on both drift ^2.16.0 and package_info_plus ^5.0.1, version solving failed.
```

We appriciate if it could be resolved relatively soon or do you have another suggestion to remedy ?

### Proposal

Could you please update the dependencies in `package_info_plus` so it is compatible with `web: ^0.5.0` ?

**Comment by hnvn** [comment]
I stuck with this issue too, it blocks me from upgrade `google_maps_flutter` to its latest version

**Comment by miquelbeltran** [comment]
Please use the search function, this has been already discussed here: https://github.com/fluttercommunity/plus_plugins/issues/2653
