### ISSUE TITLE
[Bug]: package_info_plus depends on an old version of the web package.

### ISSUE THREAD

**Issue by darkstarx** [fluttercommunity/plus_plugins#2667]
### Platform

all

### Plugin

package_info_plus

### Version

5.0.1

### Flutter SDK

3.19.3

### Steps to reproduce

```yaml
dependencies:
  cross_file: ^0.3.4+1
  package_info_plus: ^5.0.1
```

### Logs

```shell
[mobile] flutter pub get
Resolving dependencies...
Because every version of api from path depends on cross_file ^0.3.4+1 which depends on web ^0.5.0, every version of api from path requires web ^0.5.0.
And because package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0 and no versions of package_info_plus match >5.0.1 <6.0.0, api from path is incompatible with package_info_plus ^5.0.1.
So, because my_project depends on both api from path and package_info_plus ^5.0.1, version solving failed.
exit code 1
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.0 23A344 darwin-x64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
It is not a bug. And there is a pinned message about next releases and web in particular.

**Comment by darkstarx** [comment]
@vbuberen
1. `And there is a pinned message about next releases and web in particular.`
Where is the link to that message? Can you share it?

2. `You could at least try and spend a few minutes checking issues instead of lying with checkmarks that you searched anything.`
There is no any issue about this problem in this repo.

Additionally there are many other packages that require the web package version 5.0. And, this package prevents us from updating them in our projects, so it would be nice to fix this issue as soon as possible. Thanks.
