### ISSUE TITLE
[Request]: Add ability to share to instagram stories as sticker layer

### ISSUE THREAD

**Issue by lisovyk** [fluttercommunity/plus_plugins#2670]
### Plugin

share_plus

### Use case

I'd like to export a picture as a moveable sticker to instagram stories, as far as I can tell it exports as background. 
Here are [the docs for instagram sharing api](https://developers.facebook.com/docs/instagram/sharing-to-stories/)

### Proposal

Add an optional parameter to `Share.shareXFiles()` consisting of optional parameters and flags that would be utilized when sharing to popular apps like instagram (background layer or sticker layer, bg colors)

**Comment by miquelbeltran** [comment]
I don't think this is a feature for the share package, but rather something a more focused plugin could implement. Please take a look at the existing packages in pub.dev, or consider creating a package exposing this functionality.

The goal of the share package is to expose the standard OS methods to share content with other apps, not implementing a 3rd party spec like the described in the link you provided.

Sorry, I will have to close this one.
