### ISSUE TITLE
[Bug]: Exception: Failed to launch running on web

### ISSUE THREAD

**Issue by rptoca** [fluttercommunity/plus_plugins#2676]
### Platform

chrome web Version 122.0.6261.112 (Official Build) (arm64) on Mac Sonoma 14.4

### Plugin

share_plus: 

### Version

^7.2.2

### Flutter SDK

3.19.2

### Steps to reproduce

Call Share.shareWithResult(); and I get 

```
Error: Exception: Failed to launch mailto:?subject=Hello%20Subject&body=Hello%20Text
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
packages/share_plus/src/share_plus_web.dart 58:9                             share
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
```

From the user perspective it works as expected showing me my mail client with all of the fields filled and the app doesn't crash in a way that terminates it. 

### Code Sample

```dart
final result = await Share.shareWithResult(
                'Check out this event: $eventUrl',
                subject: 'Re: Event ${event.summary}',
              );
```

### Logs

```shell
I did this and it said "body is too long (maximum is 65536 characters)... since this is easily reproducible from the example, I'm going to assume it's not necessary or can be easily reproduced by the support team.
```

### Flutter Doctor

```shell
peter@FredBookMax:~/Projects/oc-app% flutter doctor -v
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.4 23E214 darwin-arm64, locale en-US)
    • Flutter version 3.19.2 on channel stable at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (2 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/peter/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • Peter’s iPhone (mobile)  • 00008020-000E24613E92002E • ios            • iOS 17.4 21E219
    • FredPhoneMaxPro (mobile) • 00008101-00125C620AE8001E • ios            • iOS 17.4 21E219
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Can you retry with the version `8.0.2`?

**Comment by rptoca** [comment]
The issue continues to be there in 8.0.2.  On the web the behavior remains the same.  It displays the email, but generates the error.  The app continues to run.  

Here’s what the exception looks like:

[log] Share API is not supported in this User Agent.
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following _Exception was thrown:
Exception: Failed to launch
mailto:?subject=Re%3A%20Challenge%20Picnic%20in%20the%20Park&body=Check%20out%20this%20event%3A%20https%3A%2F%2Fevents.ourcommunityapp.com%2Factivity%2F0c801c95-cca1-46f3-8a60-c5220b29f28c

When the exception was thrown, this was the stack:
../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
../packages/share_plus/src/share_plus_web.dart 128:9                            shareWithResult
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
../dart-sdk/lib/async/zone.dart 1407:47                                         _rootRunUnary
../dart-sdk/lib/async/zone.dart 1308:19                                         runUnary
../dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
../dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
../dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
../dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
../dart-sdk/lib/async/future_impl.dart 713:7                                    <fn>
../dart-sdk/lib/async/zone.dart 1399:13                                         _rootRun
../dart-sdk/lib/async/zone.dart 1301:19                                         run
../dart-sdk/lib/async/zone.dart 1209:7                                          runGuarded
../dart-sdk/lib/async/zone.dart 1249:23                                         callback
../dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
../dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by miquelbeltran** [comment]
In short, this is working as expected, unfortunately an error caused by the `url_launcher` plugin ultimately.

Some details:

"Share API is not supported in this User Agent." this is reported when the web implementation tries to run the method `canShare` with the provided data, and it throws a `NoSuchMethodError` exception. That's because the browser does not support the method. The error is displayed in the logs using `developer.log`.

Then, the second issue is that the call to `urlLauncher.launchUrl` is returning `false`. This causes the plugin to throw an exception `Exception('Failed to launch {uri}');` which is what you see here: `Exception: Failed to launch mailto:?subject=Re%3A%20Challenge%20P....`

My recommendation would be to catch this exception, and it is up to you if you want to ignore it or report it to your crash reporting system.

As you say, the email client opens, but the `url_launcher` plugin still decided to return false here, which is why the share plugin throws the `Failed to launch` exception back to the plugin user.
