### ISSUE TITLE
[Request]: Version solving failed.

### ISSUE THREAD

**Issue by kjxbyz** [fluttercommunity/plus_plugins#2680]
### Plugin

package_info_plus

### Use case

Version compatibility error reported when upgrading firebase.

```
  firebase_analytics: ^10.8.10
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
```

```
Because no versions of sentry_flutter match >7.17.0 <8.0.0 and sentry_flutter 7.17.0 depends on package_info_plus >=1.0.0 <=5.0.1, sentry_flutter ^7.17.0 requires
  package_info_plus >=1.0.0 <=5.0.1.
And because package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0 and firebase_messaging_web >=3.7.0 depends on web ^0.5.1, if sentry_flutter ^7.17.0 and
  firebase_messaging_web >=3.7.0 then package_info_plus >=1.0.0 <5.0.1.
And because homing_pigeon depends on firebase_messaging ^14.7.20 which depends on firebase_messaging_web ^3.7.0, sentry_flutter ^7.17.0 requires package_info_plus
  >=1.0.0 <5.0.1.
So, because homing_pigeon depends on both package_info_plus ^5.0.1 and sentry_flutter ^7.17.0, version solving failed.
```

### Proposal

Please refer to the user case.

**Comment by pamafe1976** [comment]
Appart from the new Firebase update, in my case it is preventing me from upgrading http package to 1.2.1

```
Resolving dependencies...
Because no versions of package_info_plus match >5.0.1 <6.0.0 and package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0, package_info_plus ^5.0.1 requires web >=0.3.0 <0.5.0.
And because http >=1.2.1 depends on web ^0.5.0, package_info_plus ^5.0.1 is incompatible with http >=1.2.1.
```

**Comment by EricPHassey** [comment]
> Appart from the new Firebase update, in my case it is preventing me from upgrading http package to 1.2.1
> 
> ```
> Resolving dependencies...
> Because no versions of package_info_plus match >5.0.1 <6.0.0 and package_info_plus 5.0.1 depends on web >=0.3.0 <0.5.0, package_info_plus ^5.0.1 requires web >=0.3.0 <0.5.0.
> And because http >=1.2.1 depends on web ^0.5.0, package_info_plus ^5.0.1 is incompatible with http >=1.2.1.
> ```

Same issue here. http 1.2.1 has issues. If I downgrade that to 1.2.0 then my other firebase packages have issues that need to be resolved.

**Comment by miquelbeltran** [comment]
This is discussed in the pinned issue: https://github.com/fluttercommunity/plus_plugins/issues/2653
