### ISSUE TITLE
Update library web to 0.5.1

### ISSUE THREAD

**Issue by JgomesAT** [fluttercommunity/plus_plugins#2685]
### Platform

Flutter

### Plugin

package_info_plus

### Version

5.0.1

### Flutter SDK

3.19.4

### Steps to reproduce

INcompatible with web 0.5.1 error with other libraries already updated

### Logs

```shell
INcompatible with web 0.5.1 error with other libraries already updated
```

### Flutter Doctor

```shell
no error
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Being discussed here: https://github.com/fluttercommunity/plus_plugins/issues/2653
