### ISSUE TITLE
[Request]: Update web to 0.5.1 to avoid dependency conflcits with firebase

### ISSUE THREAD

**Issue by danielgomezrico** [fluttercommunity/plus_plugins#2689]
### Plugin

package_info_plus

### Use case

If you include firebase with this version theres a dependency failure:

firebase_core: 2.27.1

### Proposal

Update web to 0.5.1

**Comment by miquelbeltran** [comment]
This is already being discussed here https://github.com/fluttercommunity/plus_plugins/issues/2653
