### ISSUE TITLE
fix: update for package info plus plugin

### ISSUE THREAD

**Issue by naninydhruva** [fluttercommunity/plus_plugins#2698]
### What is your question?

Hi team,

I see that package info plus has update but not released in pub dev, due to this our application has version conflicts while updating it kindly can you release a new version in pub dev

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
This is already been discussed in https://github.com/fluttercommunity/plus_plugins/issues/2653
