### ISSUE TITLE
[Bug]: Null Package Version Web

### ISSUE THREAD

**Issue by EricPHassey** [fluttercommunity/plus_plugins#2699]
### Platform

Web

### Plugin

package_info_plus

### Version

5.0.1

### Flutter SDK

3.19.3

### Steps to reproduce

Not sure where the issue lies.

When I build it locally, it works fine. When I upload it to Firebase Hosting, I get package is null. Appears that it can't find the version.json file? It's in my build/web folder.

Happy to give additional information if the issue lies with me or with Firebase Hosting.

### Logs

```shell
No logs due to running on Firebase Hosting
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.2 23C64 darwin-x64, locale en-US)
    • Flutter version 3.19.3 on channel stable at /Users/preventamedical/Software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (7 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Users/preventamedical/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /Volumes/Macintosh HD/Users/preventamedical/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.2 23C64 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Seems that the issue is the same as reported here: https://github.com/fluttercommunity/plus_plugins/issues/2732

At the moment, the plugin tries to load the version.json based on the base url on the browser.

So if flutter app is opened on `www.example.com`, it looks for `www.example.com/version.json`, however, if the html and the flutter app are hosted in different places, paths, etc, the plugin cannot figure out the right location.

We are considering adding a custom param you devs can set the version.json location manually for those, and/or try to obtain the app location url somehow and not just use the browser window base url.

**Comment by miquelbeltran** [comment]
Hi, in this PR https://github.com/fluttercommunity/plus_plugins/pull/2733 there is a potential fix for this issue. It has been merged to `main`, so before we do a release, I'd like to know if it solves your issue. Could you try the package using a git-reference? https://dart.dev/tools/pub/dependencies#git-packages

**Comment by EricPHassey** [comment]
> Hi, in this PR #2733 there is a potential fix for this issue. It has been merged to `main`, so before we do a release, I'd like to know if it solves your issue. Could you try the package using a git-reference? https://dart.dev/tools/pub/dependencies#git-packages

Just had time to try this.

I've done the following:

  package_info_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/package_info_plus/package_info_plus
      ref: main    #branch name

And it appears I'm still getting the issue. Just Null on the web when hosted. It works fine locally.

**Comment by miquelbeltran** [comment]
@EricPHassey the method now has a custom parameter to set the base url where the app is installed and the `version.json` located.
1. Did you set it up?
2. Is the `version.json` present in your hosted app?

**Comment by EricPHassey** [comment]
I've confirmed my version.json is available in my "root" hosted app. I can physically see it by going to https://somepath.com/version.json

This should work "out the box", but obviously it doesn't and it can't find it for some reason. So if I then use the baseUrl custom param and point it to this, it still doesn't work or find it, even though I can physically go to that path and find it. 

This is what I see when I go to that root/version.json file on my Firebase hosted app.

{"app_name":"name","version":"1.2.8","package_name":"name"}

**Comment by EricPHassey** [comment]
> @EricPHassey the method now has a custom parameter to set the base url where the app is installed and the `version.json` located.
> 
> 1. Did you set it up?
> 2. Is the `version.json` present in your hosted app?

I've confirmed my version.json is available in my "root" hosted app. I can physically see it by going to https://somepath.com/version.json

This should work "out the box", but obviously it doesn't and it can't find it for some reason. So if I then use the baseUrl custom param and point it to this, it still doesn't work or find it, even though I can physically go to that path and find it. 

This is what I see when I go to that root/version.json file on my Firebase hosted app.

{"app_name":"name","version":"1.2.8","package_name":"name"}

**Comment by miquelbeltran** [comment]
It's strange indeed. The only idea I have is for you to fork the plugin project, and add logs in it to check why the lookup of the `versions.json` fails.

It would be in the method `_getVersionMap` of the `package_info_plus_web.dart`, print the `url` and the `response` and see if something doesn't look correct.

**Comment by EricPHassey** [comment]
> It's strange indeed. The only idea I have is for you to fork the plugin project, and add logs in it to check why the lookup of the `versions.json` fails.
> 
> It would be in the method `_getVersionMap` of the `package_info_plus_web.dart`, print the `url` and the `response` and see if something doesn't look correct.

Sorry for wasting your time. With your massive help, I was able to track the issue down. It was a CORS issue (that wasn't spitting out an error message even when printing) on Firebase Hosting. I was able to update the CORS file on /version.json and that was able to resolve it. 

Thanks for all your help!

**Comment by miquelbeltran** [comment]
Thanks for reporting back! That's good to know, I will add info about checking on the CORS server config to the README.
