### ISSUE TITLE
[share_plus] enable bold text before url

### ISSUE THREAD

**Issue by devuserPP** [fluttercommunity/plus_plugins#270]
Hello, 
when I call `Share.share('check out my website https://example.com');`,
 I would expect "check out my website" would be title with bold text continuing with new line for url.
Example:
**check out my website** <br>https://example.com
<br>
But it look like one line without bold text
check out my website https://example.com

Tested with Android 11 and share_plus: ^2.1.2

**Comment by Chinmay-KB** [comment]
Once the text is shared, is it not the responsibility of the recipient app to handle bold individually? For eg in Whatsapp anything wrapped in `*` is bold, which won't be true in let us say a SMS app or Twitter. So any ideas if that can be handled?

**Comment by ueman** [comment]
Yep, this is not possible. The receiving application may not even support changes of font features. So this issue can probably be closed.
