### ISSUE TITLE
[device_info_plus] Detect ios simulator phone type

### ISSUE THREAD

**Issue by zeroprofit** [fluttercommunity/plus_plugins#273]
Hi,

Here's the code to detect ios simulator phone type.  Originally, if device is simulator, plugin reports architecture for utsname.machine.  Replace (void)handleMethodCall in FLTDeviceInfoPlusPlugin.m under device_info_plus-1.0.1/ios/Classes folder.
```swift
(void)handleMethodCall:(FlutterMethodCall*)call result:(FlutterResult)result {
  if ([@"getIosDeviceInfo" isEqualToString:call.method]) {
    UIDevice* device = [UIDevice currentDevice];
    struct utsname un;
    uname(&un);

    NSString* machine;
    if([[self isDevicePhysical] isEqualToString:@"true"]) {
      machine = @(un.machine);
    } else {
      machine = [[NSProcessInfo processInfo] environment][@"SIMULATOR_MODEL_IDENTIFIER"];
    }

    result(@{
      @"name" : [device name],
      @"systemName" : [device systemName],
      @"systemVersion" : [device systemVersion],
      @"model" : [device model],
      @"localizedModel" : [device localizedModel],
      @"identifierForVendor" : [[device identifierForVendor] UUIDString],
      @"isPhysicalDevice" : [self isDevicePhysical],
      @"utsname" : @{
        @"sysname" : @(un.sysname),
        @"nodename" : @(un.nodename),
        @"release" : @(un.release),
        @"version" : @(un.version),
        @"machine" : machine,
      }
    });
  } else {
    result(FlutterMethodNotImplemented);
  }
}
```

**Comment by ekuleshov** [comment]
This is also related to package_info_plus when installer info on ios could be a simulator. See #78

**Comment by ekuleshov-idexx** [comment]
How is this completed?

**Comment by charlie-sanders** [comment]
I think it was just closed by the bot, I also need this

**Comment by ekuleshov** [comment]
@charlie-sanders I know it was, but the lack of owner's response is alerting.
@zeroprofit @mhadaily @miquelbeltran could you please reopen this?

**Comment by miquelbeltran** [comment]
@ekuleshov

If a feature request went stale, it is because we don't have the time and resources to implement it. If you want to invest time implementing it, then we are happy to review any PRs.

Also, please do not directly mention maintainers

**Comment by ekuleshov** [comment]
@miquelbeltran so, any feature requests maintainers don't have time and resources are going to be auto-closed?

I can look at providing a PR at least for android and iOS for this or a more general enhancement https://github.com/fluttercommunity/plus_plugins/issues/570. But it would be helpful to have maintainers to at least comment/reply on the issues to outline what API changes would be acceptable.
