### ISSUE TITLE
[Bug]: package_info_plus is not using the right URL to load the version.json file in web

### ISSUE THREAD

**Issue by AriasBros** [fluttercommunity/plus_plugins#2732]
### Platform

Any web browser

### Plugin

package_info_plus

### Version

5.0.1

### Flutter SDK

3.7.0 and above

### Introduction

As of Flutter 3.7.0, Flutter allow us to [pass an assetBase value](https://docs.flutter.dev/platform-integration/web/initialization#initializing-the-engine) when the Flutter web engine is initialized:

```js
_flutter.loader.loadEntrypoint({
    entrypointUrl: "https://www.my-app-domain.com/app/main.dart.js"
    onEntrypointLoaded: async function(engineInitializer) {
        let appRunner = await engineInitializer.initializeEngine({
            assetBase: "https://www.my-app-domain.com/app/"
        });
        appRunner.runApp();
    }
});
```

This allow us to load the application from a domain **my-business-domain.com** when the application is actually deployed in other one **my-app-domain.com**

### Bug

Having the next domains:

- **my-app-domain.com**: Serving the app files domain
- **my-business-domain.com**: Executing the app files domain

**package_info_plus** is failing because it is trying to load the file **version.json** using the second domain instead the first one

Other users are having the same issue: https://github.com/fluttercommunity/plus_plugins/issues/1409#issuecomment-1566603862

The problem of this issue is here: https://github.com/fluttercommunity/plus_plugins/blob/a3cd72f86ba47f43c507f8b83f89aac7519404de/packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart#L54

Instead to get the base URI using some Flutter API, it is being fetched using a web specific API, which returns the URL used in that moment by the browser, what as we could see previously, that URL could not be where the Flutter app is actually deployed.

### Logs

```shell
NA
```

### Flutter Doctor

```shell
NA
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Would be providing an optional parameter in `static Future<PackageInfo> fromPlatform()` with the custom version.json url enough to bypass this issue?

> Instead to get the base URI using some Flutter API

Does that exist? Can you provide more information?

**Comment by AriasBros** [comment]
> > Instead to get the base URI using some Flutter API
> 
> Does that exist? Can you provide more information?

Hi @miquelbeltran,

I sent a PR (https://github.com/fluttercommunity/plus_plugins/pull/2733) using the AssetManager to achieve the same result as the current implementation, but supporting in this way setups where the app is server from a different domain.

Flutter doesn't have a explicit public API to get this base URL, but with a little hack (using public API) it was possible to get it.

> Would be providing an optional parameter in `static Future<PackageInfo> fromPlatform()` with the custom version.json url enough to bypass this issue?

If the current implementation sent in the PR is not valid or good, I can take a look to change to this approach.

**Comment by miquelbeltran** [comment]
Thanks David! I replied in the PR
