### ISSUE TITLE
Privacy manifest file in share_plus plugin iOS

### ISSUE THREAD

**Issue by Ultranmus** [fluttercommunity/plus_plugins#2744]
### What is your question?

I noticed that there is a Privacy manifest file for iOS in the share_plus plugin repository. However, it seems that the check for it has not been passed, and there is no mention of it in the changelog. I'm curious about when this file is expected to be addressed or included officially in the plugin.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Ultranmus** [comment]
@miquelbeltran for (#2586) I can see that some checks has not been passed. So i was confused whether the privacy manifest file is  added or not.
![Screenshot 2024-03-21 185118](https://github.com/fluttercommunity/plus_plugins/assets/140942235/3b986ebd-0d07-41d4-bad0-bdf15705fe5a)

**Comment by miquelbeltran** [comment]
> @miquelbeltran for (#2586) I can see that some checks has not been passed. So i was confused whether the privacy manifest file is added or not.

Oh, I understand now. The PR was merged indeed. Hopefully Apple won't give us much trouble anymore :)
