### ISSUE TITLE
[Request]: Remove `ConnectivityResult.none` from the list of available networks

### ISSUE THREAD

**Issue by huycn** [fluttercommunity/plus_plugins#2752]
### Plugin

connectivity_plus

### Use case

With the latest changes, when there are no networks, `checkConnectivity()` or `onConnectivityChanged()` return a list with single element, `ConnectivityResult.none`. So, in order to check whether any network is available, we must check that the list contains a single element and that element is `ConnectivityResult.none`.

In the old API, `ConnectivityResult.none` made sense to make sure `null` never returned. But with a list as result, an empty list for `none` makes perfect sense to me. Checking the presence of `ConnectivityResult.none` for that seems really awkward and counter intuitive.

If the intent is that the list never be empty and users can safely to check the first element for "best" network connection, please update API documentation to explicit on that. Also, if `ConnectivityResult.none` is exclusive, that is `ConnectivityResult.none` is never be present in a list of more than one element. Please specify in API documentation as well. Without this guaranty, we cannot just do `!connectivity.contains(ConnectivityResult.none)` to check if there are any connections.

### Proposal

Remove `ConnectivityResult.none` from the list of result or specify the expected results in API documentation.

**Comment by miquelbeltran** [comment]
Hi, we recently had a similar internal discussion about this, as I also faced the awkward situation in which I had to check if "contains 'none' or empty".

Looking at the different platform implementations, there doesn't seem to be an edge case where None + another is expected (e.g. not possible to get None + VPN or similar), so I'd be in favor too of removing the None case and changing to an empty array. Of course, this would be a breaking change that would require a major release.

If you want to submit a PR with the change, I'll be happy to assist.

**Comment by huycn** [comment]
Thank you for a prompt reply!

I submitted a PR just to add documentation. As long as the behavior is guaranteed, I'm happy with it.

**Comment by miquelbeltran** [comment]
Thanks! merged.

That's correct, the plugin should never return an empty array. I checked the code and couldn't find a case for that. If it does, then it should be considered a bug and fixed. I am also tempted to add some sort of assert to ensure that.
