### ISSUE TITLE
[Question]: What happened to "displayMetrics"?

### ISSUE THREAD

**Issue by LiveRock** [fluttercommunity/plus_plugins#2754]
### What is your question?

What happened to "displayMetrics"?

After an update, it is undefined for Android device info:

 'displayWidthPixels': build.displayMetrics.widthPx,
    'displayWidthInches': build.displayMetrics.widthInches,
    'displayHeightPixels': build.displayMetrics.heightPx,
    'displayHeightInches': build.displayMetrics.heightInches,
    'displayXDpi': build.displayMetrics.xDpi,

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by LiveRock** [comment]
Ok, I saw the ChangeLog

**Comment by MilkBiscuit** [comment]
Experiencing the same issue, looking for change log also...

**Comment by Bisond** [comment]
Have you found similar documents? The feeling disappeared into thin air

**Comment by miquelbeltran** [comment]
https://pub.dev/packages/device_info_plus/changelog#1001

> BREAKING FIX(device_info_plus): Remove Display Metrics from Android Device Info ([#2731](https://github.com/fluttercommunity/plus_plugins/issues/2731)). ([c5af3322](https://github.com/fluttercommunity/plus_plugins/commit/c5af332207e44902ac92765da72d2acb213fae91))
