### ISSUE TITLE
[Request]: Expose value of ActivityManager.isLowRamDevice()

### ISSUE THREAD

**Issue by kpsroka** [fluttercommunity/plus_plugins#2759]
### Plugin

device_info_plus

### Use case

I want to be able to determine if the Android device the app is running on is powerful enough to run certain UI features smoothly. Android SDK exposes a method `isLowRamDevice()` on `ActivityManager` that returns a bit of information that correlates with expected device performance - and according to documentation is intended for my use case.

AFAIK it's not exposed by any flutter plugin on pub.dev.

### Proposal

Extend `AndroidDeviceInfo` with `final bool isLowRamDevice` field, populated with value from `ActivityManager.isLowRamDevice()`.

**Comment by miquelbeltran** [comment]
Hi K!

I think this should be possible.

As long as the `ActivityManager` can be obtained from the `Application` context and does not depend on `Activity` context, and doesn't break the `detectIncorrectContextUse` strict mode rule.

PRs are welcome! ;)
