### ISSUE TITLE
[Request]: 如何把这些需要分享的软件名称设置为中文呢？现在不管我如何设置这些都是显示为英文。

### ISSUE THREAD

**Issue by xiongzhaoxu** [fluttercommunity/plus_plugins#2762]
### Plugin

share_plus

### Use case

![WX20240328-230450@2x](https://github.com/fluttercommunity/plus_plugins/assets/6897602/b1c1bfc8-1396-4459-a405-35024b77d5af)

### Proposal

![WX20240328-230450@2x](https://github.com/fluttercommunity/plus_plugins/assets/6897602/d84472a0-3123-420e-894f-a701c399bc15)

**Comment by miquelbeltran** [comment]
This has been answered here: https://github.com/fluttercommunity/plus_plugins/issues/2696

Also, please write in English (you can use Google Translate)

**Comment by xiongzhaoxu** [comment]
> This has been answered here: #2696
> 
> Also, please write in English (you can use Google Translate)

How to set the names of these software that need to be shared to Chinese? Now no matter how I set these up, they always appear in English.
