### ISSUE TITLE
[Question]: connectivity_plus do not respond to Bluetooth switching in IOS

### ISSUE THREAD

**Issue by Silverviql** [fluttercommunity/plus_plugins#2767]
### What is your question?

I see a change in wifi status, but the bluetooth status does not work

I check on a physical device via usb iPhone 12 version ios: 16.6.1

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
You'll have to provide more information. 

- What are the exact steps you are taking?
- Can you provide a code sample?
- What is the expected result? 
- What is the actual result?
- What is the version of the plugin?

**Comment by Silverviql** [comment]
1. I turn Bluetooth on and off on my phone through the curtain, there are a lot of tasks
2. Example code this porject in git
3.  What to return information ConnectionResult.bluetooth after off/on Bluetooth
4. The plugin responds to turning wifi on or off in the curtain for many tasks
5. Last version i am test and my project and I tried running the example project. The result is the same

**Comment by miquelbeltran** [comment]
Hi, I think there's some confusion here.

The plugin provides information about internet/network connectivity using iOS NWPathMonitor.

The only case I think it may report bluetooth is if you are using some sort of bluetooth connected network interface.

It is not enough to have Bluetooth enabled, you actually need to have network connection through it.

You can check the docs of NWPathMonitor on Apple side to see how it works.

Youll probably need a different plugin to check if bluetooth is enabled or not.

**Comment by Silverviql** [comment]
@miquelbeltran 
But I didn't find in doc who ConnectivityResult.bluetooth anywhere for Linux only.

**Comment by miquelbeltran** [comment]
That's fair, I think we should document which cases can be supported on each platform because it is inconsistent, as it depends on what the platform offers.

**Comment by miquelbeltran** [comment]
Created a ticket for that: https://github.com/fluttercommunity/plus_plugins/issues/2776

**Comment by Silverviql** [comment]
@miquelbeltran in package flutter_blue_plus it is possible to monitor the status of bluetooth. Maybe in the future such functionality will appear in your plugin
