### ISSUE TITLE
[Question]:  Execution failed for task ':device_info_plus:compileReleaseJavaWithJavac'. > error: invalid source release: 17

### ISSUE THREAD

**Issue by hashiqvh** [fluttercommunity/plus_plugins#2777]
### What is your question?

Execution failed for task ':device_info_plus:compileReleaseJavaWithJavac'.
> error: invalid source release: 17
getting error when try to take build

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Use the search function or search online, this has been asked before
