### ISSUE TITLE
[Request]: Remove Reachability implementation from connectivity_plus ios & macos (darwin) 

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#2779]
### Plugin

connectivity_plus

### Use case

The plugin code contains two implementations, one using `NWPathManager` and one using a 3rd party library `Reachability`.

The plugin will always use `NWPathManager` on iOS 12 and macOS 10.14.

At the same time, the minimum supported iOS version is 12, and the minimum supported macOS version is 10.14. So the `Reachability` implementation would never be used.

### Proposal

Remove the `Reachability` implementation, cleanup the dependency too and simplify the code to always use the `NWPathManager`.

**Comment by ronyquail** [comment]
Hi, Im running into error with Reachability running on ios simulator. How can I remove the Reachability implementation? Im using flutter

**Comment by miquelbeltran** [comment]
@ronyquail please open a new bug report if you are having issues. Also please read the readme file of the plugin, which has information regarding simulators.
