### ISSUE TITLE
How to pass parameters in share_plus

### ISSUE THREAD

**Issue by zakblacki** [fluttercommunity/plus_plugins#278]
I've been  using `qr_flutter `plugin with `esys_flutter_share`
to generate QR Code and save it locally  inside  my app on button click I was using 
but it's not compatible now with latest package `get_storage `

Now I've replaced it with share_plus bit I don't know If it's possible to pass a controller or property  `byteData.buffer.asUint8List()`,as follow

    Future<void> _captureAndSharePng() async {
    try {
      RenderRepaintBoundary boundary =
      globalKey.currentContext.findRenderObject();
      var image = await boundary.toImage();
      ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
      Uint8List pngBytes = byteData.buffer.asUint8List();

      await Share.shareFiles(
         text:  'QR image', 'QR.png', byteData.buffer.asUint8List(), 'image/png');
    } catch (e) {
      print(e.toString());
    }
    }

**Comment by machadoguilhermebr** [comment]
I have the same question here, how could I share Uint8List image?

**Comment by ueman** [comment]
You have to write it to a file first. After that you can use the files path to share with share_plus.
