### ISSUE TITLE
[Bug]:   What went wrong: Execution failed for task ':device_info_plus:compileDebugJavaWithJavac'. > error: invalid source release: 17

### ISSUE THREAD

**Issue by sparrow-code** [fluttercommunity/plus_plugins#2809]
### Platform

Android 13

### Plugin

device_info_plus

### Version

10.0.1

### Flutter SDK

3.19.5

### Steps to reproduce

1. Import this library
`import 'package:device_info_plus/device_info_plus.dart';`
2. Write this function
`Future<bool> isSdk30OrHigher() async {
  AndroidDeviceInfo build = await DeviceInfoPlugin().androidInfo;
  return build.version.sdkInt >= 30;
}`
3. Simple Run Your Flutter App

### Code Sample

```dart
Future<bool> isSdk30OrHigher() async {
  AndroidDeviceInfo build = await DeviceInfoPlugin().androidInfo;
  return build.version.sdkInt >= 30;
}
```

### Logs

```shell
[   +5 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Execution failed for task
':device_info_plus:compileDebugJavaWithJavac'.
[        ] > error: invalid source release: 17
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.tasks.TaskExecutionException: Execution failed for    
task ':device_info_plus:compileDebugJavaWithJavac'.
[        ]      at
org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
[        ]      at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
```

### Flutter Doctor

```shell
√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version
    10.0.19045.4170], locale en-US)
    • Flutter version 3.19.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (5 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)      

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)    • Android SDK at C:\Users\SDWORLLD\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\SDWORLLD\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.   
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all
      of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.83.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (4 available)
    • Infinix X6739 (mobile) • 10256313A7110979 • android-arm64  • Android 13   
      (API 33)
    • Windows (desktop)      • windows          • windows-x64    • Microsoft    
      Windows [Version 10.0.19045.4170]
    • Chrome (web)           • chrome           • web-javascript • Google Chrome      123.0.6312.58
    • Edge (web)             • edge             • web-javascript • Microsoft    
      Edge 123.0.2420.65

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.



I did not install Visual Studio Because i have to never develop application for that
and it is heavy to
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
It is not a bug, but an issue with your configuration.

It is explicitly mentioned in changelogs that plugin now requires Java 17: https://pub.dev/packages/device_info_plus/changelog#1001

At the same time in your flutter doctor output I see that you use Java 11:
```
Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
```

You need to update your JDK.

**Comment by davidgtu** [comment]
Hi @vbuberen! Thank you for this as it helped me resolve this locally, however, I get this error in my CircleCI/Fastlane setup.

I've tried adding a step to installing JDK 17 but to no avail.

Do you have any resources on how I might be able to resolve this on CircleCI + Fastlane?

**Comment by vbuberen** [comment]
> I get this error in my CircleCI/Fastlane setup

This is not the right place to discuss as this issue doesn't relate to the plugin, but 3rd party services.

You need to install JDK 17 and set your runner to use it. There is enough information about it in Google: https://discuss.circleci.com/t/upgrade-java-to-jdk-17/46349

**Comment by JuYiYang** [comment]
> > 我在 CircleCI/Fastlane 设置中收到此错误
> 
> 这不是讨论的正确位置，因为这个问题与插件无关，而是与第三方服务有关。
> 
> 您需要安装 JDK 17 并设置您的运行程序才能使用它。谷歌中有足够的信息：https://discuss.circleci.com/t/upgrade-java-to-jdk-17/46349
Why am I using java --version on the command line to display my version as 17 when I am using flutter doctor -v to display my java version as 11
![image](https://github.com/fluttercommunity/plus_plugins/assets/107595466/eba7ac45-9b2e-4c5a-a969-e1d27685e3e6)
![image](https://github.com/fluttercommunity/plus_plugins/assets/107595466/edd61205-45db-494a-9d2d-73776e3e7ac7)

**Comment by bishnudev1** [comment]
I was getting the same error but for me downgrading java, grade version worked.
