### ISSUE TITLE
[android_intent_plus] Building app with plugin causes APK build output to be placed outside of <project dir>\build directory

### ISSUE THREAD

**Issue by jongkb** [fluttercommunity/plus_plugins#282]
## System info

Issue occurs on: Android
Plugin name: android_intent_plus
Plugin version: 1.0.1
Flutter doctor output:

```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.985], locale en-MY)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (11 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\Jason\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Users\Jason\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Mi A2 (mobile) • 2adfa93 • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome  • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)     • edge    • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!
```

## Steps to Reproduce

1. In Flutter 2.2.1 stable, create a new Flutter app project: `flutter create <project name>`
2. Add plugin to pubspec.yaml: `android_intent_plus: ^1.0.1`
3. `flutter build apk`

## Actual result

Build output is placed in `<project dir>\android\app\build` directory.

## Expected result

Build output is placed in the `<project dir>\build` directory.

## Workaround

I managed to work around the issue by modifying the `android\build.gradle` file to mirror the build.gradle content created  by earlier versions of Flutter.

Excerpt from `android\build.gradle` created by Flutter 2.2.1:
```

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

```

Changed to:
```

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}	
subprojects {   
    project.evaluationDependsOn(':app')
}

```

I wonder if there is something that can be fixed at the plugin level so as to avoid having to apply the workaround for each new project?

**Comment by v7lin** [comment]
i have same issue.
any news update?

**Comment by anaurelian** [comment]
I'm having the same issue.

When I use `android_intent_plus: ^3.0.1`, the `android/app/build/` directory is created, with dozens (hundreds?) of files. This directory is not in any `.gitignore`, so Android Studio asks to add all those files to the git commit.

I also tried with the now deprecated `android_intent: ^2.0.2` plugin, and the same thing happens.

@jongkb's workaround works.

I didn't encounter this issue with other plugins.

**Comment by swch01** [comment]
I just encountered this issue with `android_intent_plus`. The workaround described above resolved the issue.

**Comment by techouse** [comment]
> I just encountered this issue with `android_intent_plus`. The workaround described above resolved the issue.

Same here using

```yaml
android_intent_plus: ^4.0.3
```

The aforementioned workaround works.
