### ISSUE TITLE
[Bug]: Can't build in Codemagic

### ISSUE THREAD

**Issue by aggeloskoutanis** [fluttercommunity/plus_plugins#2829]
### Platform

14

### Plugin

package_info_plus

### Version

7.0.0

### Flutter SDK

3.0.19.5

### Steps to reproduce

I am trying to build my app with code magic. I have been using code magic for some years now. I try to build it with the command `flutter build apk --profile --dart-define staging=true` and I get the following error:

```
* What went wrong:
Execution failed for task ':package_info_plus:compileProfileJavaWithJavac'.
> error: invalid source release: 17
```

Locally, I can build the apk with the same command successfully. 

I use override dependency for package_info_plus because one of the package I am using they haven't updated yet their dependency to package_info_plus.

### Logs

```shell
* What went wrong:
Execution failed for task ':package_info_plus:compileProfileJavaWithJavac'.
> error: invalid source release: 17
```

### Flutter Doctor

```shell
Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-x64, locale en-GR)
    • Flutter version 3.19.5 on channel stable at /Users/{}/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (12 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/{}/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • B1B04D26-450C-4F2C-AFF3-F7A19AA19215 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4
      (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 14.4.1 23E224 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
![Screenshot_20240409-105245.png](https://github.com/fluttercommunity/plus_plugins/assets/13467769/d91f1f34-412b-4d81-a44d-4d5c78dec71b)

You could at least try and search for the issue instead of claiming that you did.
It was asked already multiple times here and not related to the plugin.

**Comment by kauemurakami** [comment]
Did anyone solve it? According to my friend, there are many solutions here but I haven't found them yet.

**Comment by aggeloskoutanis** [comment]
@kauemurakami yes, I found it. You have to set the java_home in code magic. 

Here is the answer:

https://stackoverflow.com/questions/77624676/stripe-androidcompilereleasejavawithjavac-error-invalid-source-release-17/78086249#78086249

**Comment by kauemurakami** [comment]
Thanks my friend, go try this.

**Comment by kauemurakami** [comment]
@aggeloskoutanis I fix my variables environment from your solution, but it still didn't work, but your answer helped my when run `flutter doctor -v`, and see the location current java version used comes from my Android Studio, that is 2021 release, therefore, I must set the Java version in the AS with the JAVA_HOME, which is correct and can be updated

For new searchers of this error, this can help you.
Run `flutter doctor -v` and see this code snippet 
```dart 
[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio1
    **• Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)** <- used Java version
```
Go Android Studio -> File -> Settings -> Build, Execution Deployment -> Gradle -> Gradle  JDK and set your new Java location

**Comment by aggeloskoutanis** [comment]
Locally, I had to update my Android studio. In code magic I had to set the java home path for iOS and Android. 

Glad I helped !

**Comment by kauemurakami** [comment]
@aggeloskoutanis Here use GA, in GA build perfectly dhiasuhd, thanks, Good week for you.
