### ISSUE TITLE
[Bug]: Insecure hashing algorithm SHA1 used

### ISSUE THREAD

**Issue by vitoramaral10** [fluttercommunity/plus_plugins#2833]
### Platform

Android 12

### Plugin

package_info

### Version

7.0.0

### Flutter SDK

3.19.5

### Steps to reproduce

1. Generate app with this command: flutter build apk --obfuscate --split-debug-info=./build/symbols
2. Upload the APK in [appsweep.com](https://appsweep.com)
3. Check the report generated

![Captura de tela 2024-04-10 134916](https://github.com/fluttercommunity/plus_plugins/assets/7594095/aa518f0b-2d3f-4e8f-bb91-6e0ef68f010d)

### Logs

```shell
Is not necessary to check this issue.
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [versÆo 10.0.19044.3086], locale pt-BR)
    • Flutter version 3.19.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (2 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\vitor.melo\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Ferramentas de Build do Visual Studio 2019 16.11.15)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Ferramentas de Build do Visual Studio 2019 version 16.11.32510.428
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.88.0)
    • VS Code at C:\Users\vitor.melo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.86.0

[√] Connected device (4 available)
    • 22041219NY (mobile) • fyx4z9eeqs65fmtw • android-arm64  • Android 14 (API 34)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [versÆo 10.0.19044.3086]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 122.0.6261.70
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 123.0.2420.81

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
The `package_info_plus` plugin uses the SHA1 algorithm to obtain the package SHA1 build signature.

**Comment by vitoramaral10** [comment]
SHA1 was broken in 2017, which means that it is possible to find two different files with the same SHA1 signature. This can be used for forgery and other attacks.

When working on developing critical applications (e.g. financial applications), any mention of non-secure items is reported.

**Comment by miquelbeltran** [comment]
I am aware that SHA1 shouldn't be used for cryptographic work.

What the package does, is to display the certificate fingerprint SHA1, which is the same as if you called `keytool -list -printcert -jarfile your-app.apk`, which would display the MD5, SHA1, and SHA256.

Changing the package so it won't use the SHA1 would be possible, but that would be a breaking change and should be properly documented. Please do not send PRs with unrelated changes in them, because we will close them.

Is this blocking you from releasing an application due to the security report?

**Comment by vitoramaral10** [comment]
Sorry for the PR, I was eager to help.

Any piece of code analyzed in which a high priority issue appears ends up affecting development, I can see what I can do on my part so as not to depend on this (having to explain these alerts).

**Comment by miquelbeltran** [comment]
No problem. You can create a fork of the plugin and remove the use of the SHA1 algorithm, since it will take a while until we will do a new release. 

Meanwhile, I will prepare a PR with the changes you provided and try to document the change.

I think it is good that Flutter devs avoid using SHA1 nevertheless for stuff like Firebase and similar, so it is a good change anyway.

**Comment by vitoramaral10** [comment]
Thanks for listening @miquelbeltran, and again I apologize for making the PR (my fault kkk).

Firebase is the champion in appearing these alerts, here it appears in almost all his packages, so I had to make a "redaction" to justify the use and suppress this failure of the reports.

For the time being, I'm going to use the modified fork since I haven't had any more problems until this issue is resolved,

**Comment by miquelbeltran** [comment]
That's probably the best, do a fork and setup a dependency overrides, so you ensure that your package is the one in use, as it will take a while until all package consumers upgrade.
