### ISSUE TITLE
[Bug]: CodeMagic Android build error

### ISSUE THREAD

**Issue by getBoolean** [fluttercommunity/plus_plugins#2839]
### Platform

CodeMagic Android sdk 34

### Plugin

android_intent_plus, connectivity_plus

### Version

android_intent_plus 5.0.2, connectivity_plus 6.0.2

### Flutter SDK

stable 3.19.5

### Steps to reproduce

Updated the plugin to v5 and some other plugins, and now codemagic builds fail. Works on my machine (Mac Mini M1 14.4.1)

I tried downgrading the plugin to v4, it gets the same error but for connectivity_plus

Maybe related: https://github.com/fluttercommunity/plus_plugins/issues/2251

### Logs

```log
== Building for Android ==

> flutter build apk --release --dart-define FLUTTER_APP_FLAVOR=prod --no-tree-shake-icons

Running Gradle task 'assembleRelease'...                        
Checking the license for package Android SDK Platform 34 in /usr/local/share/android-sdk/licenses
License for package Android SDK Platform 34 accepted.
Preparing "Install Android SDK Platform 34 (revision: 3)".
"Install Android SDK Platform 34 (revision: 3)" ready.
Installing Android SDK Platform 34 in /usr/local/share/android-sdk/platforms/android-34
"Install Android SDK Platform 34 (revision: 3)" complete.
"Install Android SDK Platform 34 (revision: 3)" finished.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android_intent_plus:compileReleaseJavaWithJavac'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 23s
Running Gradle task 'assembleRelease'...                           84.8s
Gradle task assembleRelease failed with exit code 1


Build failed :|
Failed to build for Android
```
```


### Flutter Doctor

```shell
Cant get it from codemagic
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
<img width="524" alt="Screenshot 2024-04-15 at 12 07 24" src="https://github.com/fluttercommunity/plus_plugins/assets/13467769/a6a20001-7c3b-4795-84e4-32ee23e06c55">

I have really high doubts that you really did any of items that you checked before opening this issue. There were a few issues on this topic already in this repo, not to mention numerous other repos and it can be Googled right away. 
This is not related to the plugin, but your Codemagic setup. There is even 

Won't share the link to the solution as believe it is a disrespect of other people's time to claim that you did something while in reality you didn't.

**Comment by getBoolean** [comment]
I spent many hours googling and trial and erroring before making this issue. I also linked the similar issue in this repo. I would be really thankful if you could share the link to the solution.

**Comment by vbuberen** [comment]
> I spent many hours googling and trial and erroring before making this issue

Sorry, but I still don't believe in this.

https://github.com/juliansteenbakker/mobile_scanner/issues/922#issuecomment-1914432008
