### ISSUE TITLE
[Question]: How to use plugins in alarm isolate

### ISSUE THREAD

**Issue by azeem-io** [fluttercommunity/plus_plugins#2851]
### What is your question?

I'm trying to use a plugin (https://pub.dev/packages/pick_or_save) inside the alarm isolate, but it doesn't seem to be working. The documentation doesn't explain it a lot either.
>If alarm callbacks will need access to other Flutter plugins, including the alarm manager plugin itself, it may be necessary to inform the background service how to initialize plugins depending on which Flutter Android embedding the application is using.

Is there an example somewhere how to do what the docs is saying?

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
`android_alarm_manager_plus` isn't suitable for doing some work in background. 
For such purposes take a look at plugins like https://pub.dev/packages/workmanager
