### ISSUE TITLE
[Bug]: Share_Plus IOS not showing the text i try to share

### ISSUE THREAD

**Issue by Omario64** [fluttercommunity/plus_plugins#2897]
### Platform

IOS 17

### Plugin

share_plus

### Version

9.0.0

### Flutter SDK

3.19.3

### Steps to reproduce

await Share.shareXFiles([XFile(tempPath)], subject: subject, text: body);
and u will see before u even choose the app (Plain text and 1 document)
<img width="436" alt="Skärmavbild 2024-05-02 kl  09 55 49" src="https://github.com/fluttercommunity/plus_plugins/assets/55831464/3156a524-9d4b-45c5-9f2a-af362d655ab3">

### Code Sample

```dart
final url = Uri.parse(imgToDownload);
    final response = await http.get(url);
    final tempDir = await getTemporaryDirectory();
    final shareImagesDir = Directory('${tempDir.path}/shareImages');
    if (!await shareImagesDir.exists()) {
      await shareImagesDir.create(recursive: true);
    }
    final tempPath = '${shareImagesDir.path}/imageFromUrl.jpg';

    List<int> bytes = response.bodyBytes;
    await File(tempPath).writeAsBytes(bytes);
    await Share.shareXFiles([XFile(${shareImagesDir.path}/imageFromUrl.jpg)], subject: subject, text: body); //NOT WORKING

    Share.share('check out my website https://example.com'); //WORKING WELL I SEE MY TEXT
```

### Logs

```shell
### Logs


na
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4.1 23E224 darwin-arm64, locale sv-SE)
    • Flutter version 3.19.3 on channel stable at /Users/USER/FSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (8 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/USER/Library/Android/sdk/
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/USER/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • XXXXXX-BE42-4932-BCD2-XXXXXX • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 124.0.6367.118

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Omario64** [comment]
@miquelbeltran I have spent time reading the README but there is no mention about the thing i face.
I DONT share to an app I just click on share button and don't choose an app, so the IOS built in share dialog what i'm talking about.
<img width="1027" alt="Skärmavbild 2024-05-06 kl  08 35 35" src="https://github.com/fluttercommunity/plus_plugins/assets/55831464/12a05e8c-1974-440b-9ca1-bf2b8e067540">

**Comment by miquelbeltran** [comment]
the apps listed in the share sheet are decided by the OS, not the plugin

**Comment by Omario64** [comment]
> the apps listed in the share sheet are decided by the OS, not the plugin

I know but i mean why i don't see the actual text instead of "plain text and 1 document"
Thanks

**Comment by miquelbeltran** [comment]
I believe it is because when sharing an image and a text, for UIActivityViewController is like sharing data items, and will display that (text and 1 document).


You can try to provide only the subject, or only the text, to see if that makes a difference.

If you can modify the iOS code, you can try to modify the implementation of the plugin when it comes to providing data to UIActivityViewController, e.g. implementing the metadata provider as shown here:  https://stackoverflow.com/a/58234878 The plugin doesn't support providing the metadata at the moment.
