### ISSUE TITLE
[Connectivity_plus] ConnectivityResult is (sometimes) wifi/mobile when Android is put into Airplane mode (or wifi/mobile is turned off) 

### ISSUE THREAD

**Issue by WilliamRWalsh** [fluttercommunity/plus_plugins#290]
## System info

Issue occurs on: Android
Plugin name: connectivity_plus
Plugin version: 1.0.2
Flutter doctor output:

```
[✓] Flutter (Channel unknown, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/willwalsh/Code/flutter
    • Framework revision 1d9032c7e1 (6 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/willwalsh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (3 available)
    • SM G973U (mobile)          • RF8M31B49SB                          • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • B7AA7050-F83C-495F-9A56-95991D7A5B52 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

## Issue

About 1 in every 12 times I turn on Airplane mode the result from the `onConnectivityChanged` listener is wifi/mobile when it should be None. If I call `.checkConnectivity()` it will also be wifi/mobile at this time.

I see the same result if I have wifi turned off and then I turn on/off mobile data a bunch of times - every dozen times or so the `ConnectivityResult` will be mobile when it should be None.

It doesn't appear to be happened with iOS, but I'm running iOS in an emulator.

## Steps to Reproduce

1. Subscribe to `Connectivity.onConnectivityChanged.listen()`
2. Put Android into Airplane mode
3. Check the `ConnectivityResult` that was sent to listener. It will sometimes be wifi/mobile.

## Some of the Code
```
  ConnectivityResult? current;
  final Connectivity _connectivity = Connectivity();
  final SCLogger _log = SCLogger('NetworkState');
  StreamSubscription<ConnectivityResult>? _subscription;

  Future<void> init() async {
    if (kIsWeb) {
      return;
    }
    _log.info('Starting Network Check');
    final connectivityResult = await _connectivity.checkConnectivity();
    _processResult(connectivityResult);
    _subscription = _connectivity.onConnectivityChanged.listen(_processResult);
  }

  void _processResult(ConnectivityResult connectivityResult) {
    if (current != connectivityResult) {
      current = connectivityResult;
      _log.info('Network State changed to ${connectivityResult.toString()}');
      notifyListeners();
    }
  }
```
What I'm sometimes seeing when mobile data is turned off
![Screen Shot 2021-06-07 at 12 09 12 PM](https://user-images.githubusercontent.com/35807526/121053504-71492c80-c789-11eb-94f4-afd72c83825f.png)

Please let me know if you need more information.

**Comment by utsavDave97** [comment]
any updates on this....as I am also facing the same issue @WilliamRWalsh

**Comment by innim98** [comment]
Any update on this issue?
This issue looks come from 1.0.2 patch which enables registerDefaultNetworkCallback instead of CONNECTIVITY_ACTION receiver.
It seems registerDefaultNetworkCallback is called back little bit earlier so getActiveNetwork() returns mobile or wifi even if the network is disconnected.
I guess we need to handle onLost() separately to update status to "none".

**Comment by mhadaily** [comment]
merged https://github.com/fluttercommunity/plus_plugins/pull/391 and relaesed 1.0.7

**Comment by WilliamRWalsh** [comment]
Looks like the issue is fixed. Thank you, @innim98 & @mhadaily!
