### ISSUE TITLE
[Question]: I want to share an instagram post with my app. 

### ISSUE THREAD

**Issue by ignicubeLaeeq** [fluttercommunity/plus_plugins#2904]
### What is your question?

I see that this package is helpful in sharing content from your application externally. 
My use case is to share external content with my app. For example i want to share an instagram reel using share button in instagram and use it inside my flutter application. 

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
The share_plus plugin can help you with that. The README contains some information regarding Meta apps (e.g. Instagram).
