### ISSUE TITLE
invalid source release 17 how i can solve this?

### ISSUE THREAD

**Issue by Talha137m** [fluttercommunity/plus_plugins#2908]
### What is your question?

* What went wrong:
Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.
> error: invalid source release: 17

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by krishnaviroja** [comment]
Facing the same issue

**Comment by alexobviously** [comment]
@vbuberen If you're going to close an issue as duplicate, it is good practice to at least link the issue you think it's a duplicate of.

> It was already discussed in this repo as well as can easily be found in Google.
When I search for this, the only issues I find are ones that you have closed as duplicate without any elaboration, so it would be good to link the issue.

**Comment by vbuberen** [comment]
This is not how it works. If you believe that your time is more valuable than other's people so instead of searching just mark the checkmark there is no desire to help such people.

Also, instead of wasting time writing another message and tagging people just use at least Google first.
