### ISSUE TITLE
[Bug]: invalid source release 17

### ISSUE THREAD

**Issue by gheorgheomni** [fluttercommunity/plus_plugins#2909]
### Platform

Codemagic

### Plugin

share_plus

### Version

latest

### Flutter SDK

latest

### Steps to reproduce

Create a project with latest version of some _plus pubs, setup a pipeline on codemagic and voila!

Do not close this, just give a real solution to it! We have a lot of existing projects on Codemagic that all crash now, after pub upgrade. And do not tell me I didn't search on Google.

### Logs

```shell
-
```

### Flutter Doctor

```shell
-
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
<img width="519" alt="Screenshot 2024-05-06 at 22 20 36" src="https://github.com/fluttercommunity/plus_plugins/assets/13467769/835207cb-70ff-4d2a-904c-a2c1e9bad678">

You obviously didn't as this was already discussed in this repo and also mentioned in the Codemagic repo as well. 
No help to people who are Ok to lie about what they did.

Closing as duplicate.

**Comment by alexobviously** [comment]
For anyone landing here from google and struggling to find the solution, here it is: https://github.com/fluttercommunity/plus_plugins/issues/2829#issuecomment-2053776864

**Comment by vbuberen** [comment]
@alexobviously You didn't find the right one. 
There was a solution provided much earlier for Codemagic users:
https://github.com/fluttercommunity/plus_plugins/issues/2760#issuecomment-2024057204

Please stop spamming closed issues.

**Comment by alexobviously** [comment]
@vbuberen That was the one that fixed it for me. Closed issues are the first place people look for solutions. And from one OSS maintainer to another, I suggest you learn to conduct yourself more appropriately. Being openly hostile is not a good look for our community.
