### ISSUE TITLE
Plus plugin for git information

### ISSUE THREAD

**Issue by gbloggs** [fluttercommunity/plus_plugins#293]
## Use case

Using the plus plugin for PackageInfo it is possible to view package version and build number. It would be desirable to be able to read the git details that existed at the time the flutter build was run.

## Proposal
Gradle (and maven) have plugins that create a properties file detailing the git properties at the start of the build. They generate a properties file that is included in the final binary that can be read by the running code to provide git based information,

e.g. see: https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties

would generate a file like this:

git.branch=wibble
git.build.host=my-pc
git.build.user.email=me@example.com
git.build.user.name=Eric Wimp
git.build.version=unspecified
git.closest.tag.commit.count=1
git.closest.tag.name=4.82.0
git.commit.id=0d2a4bb8fe5f992957ba996e84be5aef9e680f13
git.commit.id.abbrev=0d2a4bb
git.commit.id.describe=4.82.0-1-g0d2a4bb-dirty
git.commit.message.full=I fixed it!\n
git.commit.message.short=tactical fix
git.commit.time=2021-06-04T08\:03\:08+0100
git.commit.user.email=me@example.com
git.commit.user.name=Eric Wimp
git.dirty=true
git.remote.origin.url=https\://some-git-url.git
git.tags=
git.total.commit.count=1612

This info could then be parsed in any app and display useful info to devs ?

**Comment by Chinmay-KB** [comment]
Don't you think that a dev dependency makes more sense for this use case? When run it will create a file containing all the details which will then be bundled with the binary rather than have it in this plugin itself?
