### ISSUE TITLE
[Request]: Consider adding `topics` to `pubspec.yaml` for better discoverability

### ISSUE THREAD

**Issue by jonasfj** [fluttercommunity/plus_plugins#2941]
### Plugin

all

### Use case

Related packages can be hard to find.

### Proposal

Topics helps users on pub.dev discover packages, and related packages.

You can see a list of [topics here](https://pub.dev/topics).
You can also make your own topics.

Topics are added to `pubspec.yaml` as follows:

```yaml
topics:
 - my-topic
 - some-other-topic
```

See also: https://dart.dev/tools/pub/pubspec#topics

**Comment by vbuberen** [comment]
Thanks for suggestion and linking additional info. We will add topics at some point.
