### ISSUE TITLE
[Question]: Warning occurred during project building.

### ISSUE THREAD

**Issue by shinexoh** [fluttercommunity/plus_plugins#2943]
### What is your question?

I used the `android_intent_plus` package, and I encountered this warning when executing `flutter build apk`. However, the build process did not terminate, and there were no issues when using it.

![image](https://github.com/fluttercommunity/plus_plugins/assets/98050229/171b9aa7-bc13-4335-bf3e-eda2ad77e3ce)

my project Gradle config
gradle=7.6.4
kotlin=1.8.22
android.build.tools=7.4.2

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
You need to update your project to satisfy the requirements of the plugin: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_intent_plus#requirements

**Comment by shinexoh** [comment]
Okay, I didn't notice that before. thanks
