### ISSUE TITLE
[Bug]:  GeneratedPluginRegistrant.java:64: error: cannot find symbol

### ISSUE THREAD

**Issue by fisforfaheem** [fluttercommunity/plus_plugins#2947]
### Platform

android 13

### Plugin

9.0

### Version

9.0

### Flutter SDK

3.22

### Steps to reproduce

Launching lib/main.dart on Pixel 4 XL in debug mode...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/4edoc/Documents/beboro/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:64: error: cannot find symbol
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.share.SharePlusPlugin());
                                                                        ^
  symbol:   class SharePlusPlugin
  location: package dev.fluttercommunity.plus.share
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

### Logs

```shell
GeneratedPluginRegistrant.java:64: error: cannot find symbol
```

### Flutter Doctor

```shell
not applicable
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by fisforfaheem** [comment]
No, the plugin was working just fine before FLutter 3.22 upgrade, kindly do some checking.

**Comment by miquelbeltran** [comment]
Again, `GeneratedPluginRegistrant.java` is a file from your project, not a plugin file.

I checked the project compilation with our CI and locally, and it works as expected.

Please do some research, likely a `flutter clean` would be enough to fix the issue.

![image](https://github.com/fluttercommunity/plus_plugins/assets/2494376/5fb37d21-3191-4f47-aebe-5760b021b733)

**Comment by fisforfaheem** [comment]
Sure let me check, Also, I am using latest Gradle version 8.x and latest kotlin version 1.9, can you test with that as well.

**Comment by lucasvps** [comment]
Any ideas?
