### ISSUE TITLE
[Request]: FB Group Possibility to share image + text 

### ISSUE THREAD

**Issue by hajiboy95** [fluttercommunity/plus_plugins#2949]
### Plugin

share_plus

### Use case

 await Share.shareXFiles(
            [imageFile],
            text: 'sharemessage',
            subject: 'Example subject',
          );
          
          
          
          i try to share image + text. on whatsapp, telegram, fb feed it works perfectly fine, however in fb groups it doesn't work. only image is forwarded. 

### Proposal

forward text + image. is this possible ?

**Comment by miquelbeltran** [comment]
README of package already explains this is not possible
