### ISSUE TITLE
[Question]: Execution failed for task ':share_plus:compileReleaseJavaWithJavac'. > error: invalid source release: 17

### ISSUE THREAD

**Issue by mtiendat** [fluttercommunity/plus_plugins#2955]
### What is your question?

Execution failed for task ':share_plus:compileReleaseJavaWithJavac'. > error: invalid source release: 17
I got this issue when try to run build 

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
This has been asked a thousand times already, use the search

**Comment by fisforfaheem** [comment]
Ki

> This has been asked a thousand times already, use the search

Can you kindly write a solution or link to that solutions instead

**Comment by miquelbeltran** [comment]
OP selected "I searched issues in this repository and couldn't find such bug/problem" when they didn't do it, asking the same questions without doing some basic research wastes the maintainer team time.

As a reminder, this is a project run by volunteers on our free time.

![image](https://github.com/fluttercommunity/plus_plugins/assets/2494376/b38e4499-b31c-4e25-b5fb-84dd60c435ab)
