### ISSUE TITLE
[Request]: Fully support Flutter 3.22 and dart 3.4( atleast upgrade gradle and other dependecies)

### ISSUE THREAD

**Issue by fisforfaheem** [fluttercommunity/plus_plugins#2956]
### Plugin

share_plus

### Use case

help needed

### Proposal

Upgrade for flutter 3.22 and see what can be done

**Comment by miquelbeltran** [comment]
Can you specify which compile errors are you seeing?

**Comment by biaarno8** [comment]
Hi @miquelbeltran 

I have the same problem.
The compile error is:


![Screenshot 2024-05-23 alle 12 57 28 PM](https://github.com/fluttercommunity/plus_plugins/assets/144822121/e8a0e698-86e0-4531-b0d4-e7a2e455b7c4)

I try to remove your package, and without your package the app running correctly.
Please fix this error, because it's blocking

**Comment by miquelbeltran** [comment]
> Hi @miquelbeltran
> 
> I have the same problem. The compile error is:
> 
> ![Screenshot 2024-05-23 alle 12 57 28 PM](https://private-user-images.githubusercontent.com/144822121/333155463-e8a0e698-86e0-4531-b0d4-e7a2e455b7c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjIzMTgsIm5iZiI6MTcxNjQ2MjAxOCwicGF0aCI6Ii8xNDQ4MjIxMjEvMzMzMTU1NDYzLWU4YTBlNjk4LTg2ZTAtNDUzMS1iMGQ0LWU3YTJlNDU1YjdjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMTAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjlmZjRhMWE2ZjlmYjRhY2MyNmExNDg3NTllYzFiYTBiY2Q3Nzg0MTdmN2Y5OWU4MTVmNDAxNmUwYzRkNjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LgLPDs5rNukGUU4dwmycix_q0qjMGEu1XZ4jay8FWxo)
> 
> I try to remove your package, and without your package the app running correctly. Please fix this error, because it's blocking

<img width="1259" alt="image" src="https://github.com/fluttercommunity/plus_plugins/assets/2494376/a83557f8-f64b-4e1a-805e-e2567bec2ff7">

That has been discussed already in this repository, please use the search function.

**Comment by biaarno8** [comment]
Thank you @miquelbeltran

**Comment by fisforfaheem** [comment]
What was the solution? Kindly reference add to that discussion

**Comment by miquelbeltran** [comment]
> What was the solution? Kindly reference add to that discussion

The issue is that packages require Java 17 (jumped from Java 11). This version of Java is shipped with the latest Android Studio, so upgrading Android Studio would be enough to fix the issue. 

We also listed the package requirements are listed at the top of the README.md files of each package.

Running `flutter doctor -v` should show the Java version used as well.

**Comment by fisforfaheem** [comment]
this comes with latest ANDROID STUIO and FLUTTER 3.22[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

**Comment by liangzaifankun** [comment]
Hello, I also encountered the same problem. Did you solve it?

**Comment by miquelbeltran** [comment]
Could anyone provide a sample project with the compilation issue?

**Comment by miquelbeltran** [comment]
I've pinned some information regarding compilation issues here: https://github.com/fluttercommunity/plus_plugins/issues/2965

Also, I'd please ask you to fill the following issue form we just created for compile issues: https://github.com/fluttercommunity/plus_plugins/issues/new?assignees=&labels=compile%2Ctriage&projects=&template=COMPILATION.yaml&title=%5BCompile%5D%3A+
