### ISSUE TITLE
package_info_plus:compiledebugjavawithjavac'. > error: invalid source release: 17

### ISSUE THREAD

**Issue by Hemant301** [fluttercommunity/plus_plugins#2963]
### What is your question?

package_info_plus:compiledebugjavawithjavac'. > error: invalid source release: 17 errror

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/2809#issuecomment-2031636202

**Comment by miquelbeltran** [comment]
Also posted this pinned issue: https://github.com/fluttercommunity/plus_plugins/issues/2965
