### ISSUE TITLE
[Bug]: compileDebugJavaWithJavac'. > error: invalid source release: 17

### ISSUE THREAD

**Issue by Hemant301** [fluttercommunity/plus_plugins#2964]
### Platform

android 18

### Plugin

package_info_plus

### Version

6.0.0

### Flutter SDK

3.19.0

### Steps to reproduce

package_info_plus

### Code Sample

```dart
package_info_plus: ^5.0.2
```

### Logs

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package_info_plus:compileDebugJavaWithJavac'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Flutter Doctor

```shell
yes
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by kauzige** [comment]
Same here

**Comment by miquelbeltran** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/2809#issuecomment-2031636202

**Comment by miquelbeltran** [comment]
Also posted this pinned issue: https://github.com/fluttercommunity/plus_plugins/issues/2965
