### ISSUE TITLE
[Question]:  how can i share image + pdf file at single share

### ISSUE THREAD

**Issue by ShriniwasAnshika** [fluttercommunity/plus_plugins#2971]
### What is your question?

i want to share images and pdf or ppt kind file at single share but i can not able to share this on whatsapp it is share on telegram and gmail but not on whatsapp or teams why?and how can i sort this problem?

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
This is explained in the README of the package, also this has been asked in the repository issue tracker multiple times.

You cannot because Whatsapp doesn't implement the share protocol correctly, nothing to do with the plugin.
