### ISSUE TITLE
Production app bundle build warning uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by MikeMnD** [fluttercommunity/plus_plugins#301]
## System info

Issue occurs on:  Android
Plugin name: package_info_plus
Plugin version:  ^1.0.1

## Steps to Reproduce

`flutter build appbundle`

```
 Building with sound null safety 

Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-1.0.1\android\src\main\java\dev\fluttercommunity\plus\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

## Logs

[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.985], locale bg-BG)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android\SDK
    • ANDROID_SDK_ROOT = C:\Android\SDK
    • Java binary at: C:\Users\Mike\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Users\Mike\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • android-studio-dir = C:\Users\Mike\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\Mike\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7442.40
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!

**Comment by PhilipPurwoko** [comment]
Have you add this in your `res/xml` folder
https://github.com/fluttercommunity/plus_plugins/blob/a6303daccd2927b76aac91f17b284c983839a8a9/packages/share_plus/android/src/main/res/xml/flutter_share_file_paths.xml#L1-L4

**Comment by PhilipPurwoko** [comment]
I change the `minSdkVersion` from 17 to 21 in `app/src/build.gradle` and works perfectly
```
android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutproject"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}
```

**Comment by MikeMnD** [comment]
@PhilipPurwoko  I tried with minSdkVersion 21 and still the same warning about Deprecated API

> Have you add this in your `res/xml` folder ?
> https://github.com/fluttercommunity/plus_plugins/blob/a6303daccd2927b76aac91f17b284c983839a8a9/packages/share_plus/android/src/main/res/xml/flutter_share_file_paths.xml#L1-L4

Not sure where exactly should i put this in res folder there are any file except AndroidManifest?

**Comment by MikeMnD** [comment]
I've noticed something else, if i run: `flutter clean && flutter build appbundle --release`
```

D:\Flutter\converter_app>flutter clean && flutter build appbundle --release
Deleting build...                                                  403ms
Deleting .dart_tool...                                               5ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in converter_app...                      673ms

 Building with sound null safety 

Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-1.0.2\android\src\main\java\dev\fluttercommunity\plus\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Removed unused resources: Binary resource data reduced from 206KB to 206KB: Removed 0%
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        34,4s
√ Built build\app\outputs\bundle\release\app-release.aab (18.0MB).
```


But if I run only: `flutter build appbundle --release` there isn't any warning:


D:\Flutter\converter_app>flutter build appbundle --release

```
 Building with sound null safety 

Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                      2 130ms
√ Built build\app\outputs\bundle\release\app-release.aab (18.0MB).
```

**Comment by MikeMnD** [comment]
![image](https://user-images.githubusercontent.com/186191/122038179-011c5580-cdde-11eb-8c7c-2717e3b271b9.png)

Ок, I've created the xml in the specified folder, but there isn't any diference.
Also yes my mistake the AndroidManifest is in the main folder and not the res.

`D:\Flutter\converter_app>flutter clean && flutter build appbundle --release
Deleting build...                                                  387ms
Deleting .dart_tool...                                               5ms
Deleting .packages...                                                1ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in converter_app...                      996ms

 Building with sound null safety 

Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-1.0.2\android\src\main\java\dev\fluttercommunity\plus\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Removed unused resources: Binary resource data reduced from 206KB to 206KB: Removed 0%
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        34,2s
√ Built build\app\outputs\bundle\release\app-release.aab (18.0MB).
`


Could you test it on your side with:
`flutter clean && flutter build appbundle --release`

especially with `flutter clean && `

**Comment by PhilipPurwoko** [comment]
@MikeMnD  Yes, I have tried `flutter clean` and `flutter build` before. But not using the `&&` statement. I do it separately. I run `flutter clean` first, then run` flutter pub get` then the build command. Please try run `flutter pub get` after flutter `clean`, and see the result when run build command.

**Comment by MikeMnD** [comment]
I've update all plugins and info_plus to 1.0.3 still this is the result:

`Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-1.0.3\android\src\main\java\dev\fluttercommunity\plus\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.`

```
D:\Flutter\converter_app>
D:\Flutter\converter_app>flutter pub upgrade
Resolving dependencies...
  _fe_analyzer_shared 22.0.0
  analyzer 1.7.1
  archive 3.1.2
  args 2.0.0 (2.1.1 available)
  async 2.6.1 (2.7.0 available)
  boolean_selector 2.1.0
  characters 1.1.0
  charcode 1.2.0 (1.3.1 available)
  cli_util 0.3.0
  clock 1.1.0
  collection 1.15.0
  convert 3.0.0
  coverage 1.0.3
  crypto 3.0.1
  cupertino_icons 1.0.3
  fake_async 1.2.0
  ffi 1.1.2
> file 6.1.2 (was 6.1.1)
  file_picker 3.0.2+2
  flutter 0.0.0 from sdk flutter
  flutter_launcher_icons 0.9.0
  flutter_plugin_android_lifecycle 2.0.2
  flutter_test 0.0.0 from sdk flutter
  flutter_web_plugins 0.0.0 from sdk flutter
  glob 2.0.1
  http 0.13.3
  http_multi_server 3.0.1
  http_parser 4.0.0
  image 3.0.2
> in_app_purchase 1.0.5 (was 1.0.4)
> in_app_purchase_android 0.1.2 (was 0.1.1)
  in_app_purchase_ios 0.1.0+1
  in_app_purchase_platform_interface 1.0.0
  intl 0.17.0
  io 1.0.0
  js 0.6.3
  json_annotation 4.0.1
  logging 1.0.1
  matcher 0.12.10
  meta 1.3.0 (1.4.0 available)
  mime 1.0.0
> node_preamble 2.0.1 (was 2.0.0)
  package_config 2.0.0
> package_info_plus 1.0.3 (was 1.0.2)
  package_info_plus_linux 1.0.2
  package_info_plus_macos 1.1.1
  package_info_plus_platform_interface 1.0.1
  package_info_plus_web 1.0.2
  package_info_plus_windows 1.0.1
  path 1.8.0
  path_provider 2.0.2
  path_provider_linux 2.0.0
  path_provider_macos 2.0.0
  path_provider_platform_interface 2.0.1
  path_provider_windows 2.0.1
  pedantic 1.11.0
> permission_handler 8.1.1 (was 8.0.1)
> permission_handler_platform_interface 3.6.0 (was 3.5.1)
  petitparser 4.1.0 (4.2.0 available)
  platform 3.0.0
  plugin_platform_interface 2.0.0
  pool 1.5.0
  process 4.2.1
  pub_semver 2.0.0
  shelf 1.1.4
  shelf_packages_handler 3.0.0
  shelf_static 1.0.0
  shelf_web_socket 1.0.1
  sky_engine 0.0.99 from sdk flutter
  source_map_stack_trace 2.1.0
  source_maps 0.10.10
  source_span 1.8.1
  stack_trace 1.10.0
  stream_channel 2.1.0
  string_scanner 1.1.0
  term_glyph 1.2.0
  test 1.16.8 (1.17.8 available)
  test_api 0.3.0 (0.4.1 available)
  test_core 0.3.19 (0.3.28 available)
  typed_data 1.3.0
  vector_math 2.1.0
  vm_service 6.2.0 (7.1.0 available)
  watcher 1.0.0
  web_socket_channel 2.1.0
  webkit_inspection_protocol 1.0.0
> win32 2.1.5 (was 2.0.5)
  xdg_directories 0.2.0
  xml 5.1.2
  yaml 3.1.0
Downloading in_app_purchase 1.0.5...
Downloading package_info_plus 1.0.3...
Downloading permission_handler 8.1.1...
Downloading permission_handler_platform_interface 3.6.0...
Downloading in_app_purchase_android 0.1.2...
Downloading file 6.1.2...
Downloading win32 2.1.5...
Downloading node_preamble 2.0.1...
Changed 8 dependencies!
9 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

D:\Flutter\converter_app>flutter pub get
Running "flutter pub get" in converter_app...                      674ms

D:\Flutter\converter_app>flutter clean
Deleting build...                                                  421ms
Deleting .dart_tool...                                               5ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms

D:\Flutter\converter_app>flutter build appbundle --release
Running "flutter pub get" in converter_app...                      665ms

 Building with sound null safety 

Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-1.0.3\android\src\main\java\dev\fluttercommunity\plus\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Removed unused resources: Binary resource data reduced from 206KB to 206KB: Removed 0%
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        35,3s
√ Built build\app\outputs\bundle\release\app-release.aab (18.0MB).

D:\Flutter\converter_app>

```

**Comment by PhilipPurwoko** [comment]
@MikeMnD Interesting. I don't have more information for you. But, did you have tried to change the `compileSdkVersion` to`30` in `app/src/build.gradle`
