### ISSUE TITLE
App Stops when [Android alarm manager plus flutter ] runs when app is in background

### ISSUE THREAD

**Issue by ifeoluwajoshua** [fluttercommunity/plus_plugins#302]
The application gets killed when app runs in the background it works well in foreground

Error from debug console when in background

Starting AlarmService...
E/AndroidRuntime(14261): FATAL EXCEPTION: main
E/AndroidRuntime(14261): Process: com.joart.agroai, PID: 14261
E/AndroidRuntime(14261): java.lang.RuntimeException: Unable to create service dev.fluttercommunity.plus.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(14261): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3377)
E/AndroidRuntime(14261): 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(14261): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1702)
E/AndroidRuntime(14261): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14261): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(14261): 	at android.app.ActivityThread.main(ActivityThread.java:6524)
E/AndroidRuntime(14261): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14261): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:451)
E/AndroidRuntime(14261): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
E/AndroidRuntime(14261): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(14261): 	at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:366)
E/AndroidRuntime(14261): 	at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:104)
E/AndroidRuntime(14261): 	at dev.fluttercommunity.plus.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:155)
E/AndroidRuntime(14261): 	at dev.fluttercommunity.plus.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:124)
E/AndroidRuntime(14261): 	at dev.fluttercommunity.plus.androidalarmmanager.AlarmService.onCreate(AlarmService.java:345)
E/AndroidRuntime(14261): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3367)
E/AndroidRuntime(14261): 	... 8 more

flutter doctor - v

C:\Users\Ayomide\Desktop\agroai>flutter doctor -v
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
• Flutter version 2.0.0 at C:\src\flutter\flutter
• Framework revision 60bd88d (3 months ago), 2021-03-03 09:13:17 -0800
• Engine revision 40441def69
• Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at C:\Users\Ayomide\AppData\Local\Android\sdk
• Platform android-30, build-tools 29.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 45.1.1
• Dart plugin version 192.7761
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.56.2)
• VS Code at C:\Users\Ayomide\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.23.0

[√] Connected device (2 available)
• Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
• Edge (web) • edge • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!

**Comment by ifeoluwajoshua** [comment]
Issue solved

Adding android:name="io.flutter.app.FlutterApplication" to application

**Comment by miquelbeltran** [comment]
Hey @ifeoluwajoshua is there something that we could add to the README that could help others next time?

**Comment by ifeoluwajoshua** [comment]
I am not sure i added  "android:name="io.flutter.app.FlutterApplication" to application inside androidmanifest file and it worked
