### ISSUE TITLE
[Bug]: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. The following dependencies do not satisfy the required version: project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

### ISSUE THREAD

**Issue by mariamalbarghouti** [fluttercommunity/plus_plugins#3030]
### Platform

Android 12

### Plugin

share_info_plus

### Version

8.0.0

### Flutter SDK

 3.22.1

### Steps to reproduce

i can't run the app

### Logs

```shell
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

### Flutter Doctor

```shell
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2019 16.11.37)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.90.2)
[√] Connected device (4 available)
[√] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
This is an issue with your project configuration as it doesn't match the requirements stated in the README of the plugin: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus#requirements

Also, switch from `wakelock` to `wakelock_plus` as the original `wakelock` isn't maintained anymore.
