### ISSUE TITLE
"error: invalid source release: 17" and other compilation issues 

### ISSUE THREAD

**Issue by sivasankar2221** [fluttercommunity/plus_plugins#3035]
### What is your question?

Execution failed for task ':connectivity_plus:compileReleaseJavaWithJavac'.

error: invalid source release: 17

occurs when build but im using java  1_8  ,gradle 8.4 ,Flutter version 3.19.6

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [x] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Calvin-Ho** [comment]
Updating Android Studio to current latest version (version 2024.1) resolves this issue for me.  It seems to update the included JDK that Flutter uses and this fixes the build issue.

**Comment by yokesh2404** [comment]
Temporary solution Downgrade current version in to lower version its working fine.:)

**Comment by kj415j45** [comment]
See #2965

**Comment by vbuberen** [comment]
There is even a pinned issue on top of list of issues. 
Why is it so hard to actually search first instead of marking checkmarks? 🤦🏻‍♂️

**Comment by khaled-0** [comment]
For CI/CD. Fix is https://github.com/incrediblezayed/file_saver/issues/86#issuecomment-2028079330
