### ISSUE TITLE
Add option to add image from network

### ISSUE THREAD

**Issue by angwandi** [fluttercommunity/plus_plugins#3087]
### Plugin

share_plus

### Use case

Instead of just subject and text, add an option to add an image to spice up the shared experience.

### Proposal

Instead of just subject and text, add an option to add an image to spice up the shared experience.

**Comment by miquelbeltran** [comment]
That doesn't depend on the plugin but on the underlying OS implementation, and afaik this is not something they support.

You can always download that image and then share it using `shareXFile`.

**Comment by angwandi** [comment]
How come FlowLink does it then? 
Reference : https://extensions.dev/extensions/jauntybrain/firebase-flow-links

**Comment by angwandi** [comment]
Here for more details : app.get('*', (req, res, next) => {
// Define values
 ```
   const title = 'My Amazing Application';
    const subtitle = 'Find out more about my app...';
    const image = 'https://.../your-app-banner.jpg';

    // Load HTML template
    const templatePath = path.join(__dirname, './assets/html/index.html');

    // Replace handles with content
    var source = fs.readFileSync(templatePath, { encoding: 'utf-8' })
        .replaceAll('{{title}}', title)
        .replaceAll('{{subtitle}}', subtitle)
        .replaceAll('{{image}}', image);

    // Return the webpage
    return res.send(source);
});
```

Reference : https://medium.com/firebase-developers/dynamic-links-are-dead-what-to-do-c73ad0669540

**Comment by miquelbeltran** [comment]
That's a JavaScript project running server side that adds a hosted picture to a dynamic link URL. This has nothing to do with how the share functionality of the operating system works.
