### ISSUE TITLE
[package_info_plus] can't obtain PackageInfo before runApp()

### ISSUE THREAD

**Issue by just-a-normal-guy** [fluttercommunity/plus_plugins#309]
## System info
**Issue occurs on:** Android, maybe iOS too (I haven't tried)
**Plugin name:** package_info_plus
**Plugin version:** 1.0.2

**Flutter doctor output:**
```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Versione 10.0.19042.1052], locale it-IT)
    • Flutter version 2.2.1 at D:\Flutter SDK\flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\redacted\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.48
```

## Steps to Reproduce

**All I did was copying the code from [here](https://pub.dev/documentation/package_info_plus/latest/).
I tried both given versions of the code but the problem persists.**

main.dart:
```
import 'misc/appInfo.dart' as appInfo;

Future<void> main() async {
  await appInfo.init();
  runApp(MyApp());
}
```
appInfo:
```
import 'package:package_info_plus/package_info_plus.dart';

late String appName;
late String packageName;
late String version;
late String buildNumber;

Future<void> init() async {
  PackageInfo packageInfo = await PackageInfo.fromPlatform();

  appName = packageInfo.appName;
  packageName = packageInfo.packageName;
  version = packageInfo.version;
  buildNumber = packageInfo.buildNumber;
}
```

## Logs

**Error:**
```
Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:64574/XjXjsC5ht-k=/.
[  +23 ms] E/flutter (14669): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter (14669): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
[        ] E/flutter (14669): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
[        ] E/flutter (14669): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
[        ] E/flutter (14669): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:49)
[        ] E/flutter (14669): #4      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:32)
[        ] E/flutter (14669): #5      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:66:42)
[        ] E/flutter (14669): #6      init (package:checklist_app/misc/appInfo.dart:12:47)
[        ] E/flutter (14669): #7      main (package:checklist_app/main.dart:7:9)
[        ] E/flutter (14669): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
[        ] E/flutter (14669): #9      _rootRun (dart:async/zone.dart:1354:13)
[        ] E/flutter (14669): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter (14669): #11     _runZoned (dart:async/zone.dart:1789:10)
[        ] E/flutter (14669): #12     runZonedGuarded (dart:async/zone.dart:1777:12)
[        ] E/flutter (14669): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
[        ] E/flutter (14669): #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
[        ] E/flutter (14669): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[        ] E/flutter (14669): 
```

**Flutter analyze:**
```
Analyzing checklist_app...
No issues found! (ran in 1.3s)
```

**Comment by miquelbeltran** [comment]
Thanks @just-a-normal-guy do you use a specific device or is just the emulator?

**Comment by miquelbeltran** [comment]
I can't reproduce the issue when I run the example project, but if I move the `await PackageInfo.fromPlatform()` before the `runApp` call then it happens. So this looks like is a limitation of the package.

No idea how that is supposed to be fixed, but I will add a warning to the README. Any improvement PRs are wellcome

**Comment by jpnurmi** [comment]
Would it help to call `WidgetsFlutterBinding.ensureInitialized()` before trying to access the platform channels?

**Comment by just-a-normal-guy** [comment]
You know what, I hadn't thought about that.

**Comment by just-a-normal-guy** [comment]
> I can't reproduce the issue when I run the example project, but if I move the `await PackageInfo.fromPlatform()` before the `runApp` call then it happens. So this looks like is a limitation of the package.
> No idea how that is supposed to be fixed, but I will add a warning to the README. Any improvement PRs are wellcome
You know what, I hadn't thought about that.

> Thanks @just-a-normal-guy do you use a specific device or is just the emulator?
I use AndroidStudio's emulator

**Comment by just-a-normal-guy** [comment]
> Would it help to call `WidgetsFlutterBinding.ensureInitialized()` before trying to access the platform channels?

It does appear so, thanks.

**Comment by thor-jc** [comment]
Is there any way to include this package as part of a test?  It seems to work fine when I run an app in a web app.

```
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('package info test', () {
    test('can read from pubspec', () async {
      final pubSpecInfo = await PackageInfo.fromPlatform();
      expect(pubSpecInfo.appName, 'test app name');
    });
  });
}
```
Results in: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

Adding WidgetsFlutterBinding.ensureInitialized(); didn't make sense but also didn't help.

I assume that generally plugins are not loaded during test but I just wanted to double check.

Regards,
John

**Comment by miquelbeltran** [comment]
In general, you shouldn't call into native plugins through tests, except in e2e integration tests. Your code should wrap the plugin functionality, and you should inject that functionality/mock it when running tests.

**Comment by thor-jc** [comment]
Great just making sure.  Thanks for your time and this package.

**Comment by Zazo032** [comment]
If this is no longer an issue, can it be removed from the readme? https://pub.dev/packages/package_info_plus#android-and-potentially-all-platforms

**Comment by alfaruqrizqi18** [comment]
> > Would it help to call `WidgetsFlutterBinding.ensureInitialized()` before trying to access the platform channels?
> 
> It does appear so, thanks.

is this solved?

**Comment by gazialankus** [comment]
If it is solved, maybe this note from two years ago should be removed? https://github.com/fluttercommunity/plus_plugins/commit/a50f5ada496155d71c98040043b642bfdaa48b49

**Comment by SamuelMTDavies** [comment]
I don't think is resolved. I currently do some setup after calling WidgetsFlutterBinding.ensureInitialized() but before runApp.

It works as planned when profiling and debugging but when I run in release mode I constantly get the follow error.

```
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
```


runZonedGuarded doesn't help why would this fail on Release mode but not profile?

**Comment by subzero911** [comment]
I checked this too, neither in debug nor in release mode no errors occured.

**Comment by Milos5611** [comment]
I see this error in release mode on Android and it drives me crazy

**Comment by arthurgiani** [comment]
> I see this error in release mode on Android and it drives me crazy

Same. Works fine on debug but not on release.

**Comment by minhluankt** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
 
 I encountered this error when running on a device or Android 7.1 emulator. Could you help me resolve this issue?

**Comment by flaan4me** [comment]
import 'package:http/http.dart' as http;

var url = Uri.https('example.com', 'whatsit/create');
var response = await http.post(url, body: {'name': 'doodle', 'color': 'blue'});
print('Response status: ${response.statusCode}');
print('Response body: ${response.body}');

print(await http.read(Uri.https('example.com', 'foobar.txt')));
