### ISSUE TITLE
All: Change `homepage` from `pubspec.yaml` files to `https://github.com/fluttercommunity/plus_plugins`

### ISSUE THREAD

**Issue by jameshp** [fluttercommunity/plus_plugins#3092]
### Platform

-

### Plugin

-

### Version

-

### Flutter SDK

-

### Steps to reproduce

go to https://plus.fluttercommunity.dev/ -> see blank firebase hosting page

### Code Sample

```dart
-
```

### Logs

```shell
-
```

### Flutter Doctor

```shell
-
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
The website was taken down on purpose, as keeping the site code and documentation up to date was too much of an effort.

**Comment by jameshp** [comment]
thx @miquelbeltran  
ok,  makes sense. sorry for my confusion. 
i just looked at the battery_plus plugin package and there are 2 dead links still pointing to that site.  
https://pub.dev/packages/battery_plus 

![image](https://github.com/user-attachments/assets/4f895b1d-a536-4bca-afc3-387b6dfcb1bd)

**Comment by miquelbeltran** [comment]
Ah thanks, that needs to be removed from the pubspec.yaml files: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/battery_plus/battery_plus/pubspec.yaml#L4

**Comment by muhib349** [comment]
I have changed the **homepage** url to [https://github.com/fluttercommunity/plus_plugins](https://github.com/fluttercommunity/plus_plugins). Can you please confirm, what about [Plugin documentation website](https://plus.fluttercommunity.dev/docs/android_alarm_manager_plus/overview/) this link?

**Comment by miquelbeltran** [comment]
Did you submit a PR? @muhib349

**Comment by muhib349** [comment]
> Did you submit a PR? @muhib349
> 
> `homepage` should be `https://github.com/fluttercommunity/plus_plugins` or `https://github.com/fluttercommunity/plus_plugins/tree/main/packages/<package>` I think, but I am not sure which one of the two options is better.

I guess first one is better. I'm submitting the PR.
