### ISSUE TITLE
[all] Upgrade to `package:web` version `1.0.0`

### ISSUE THREAD

**Issue by Rexios80** [fluttercommunity/plus_plugins#3093]
### Plugin

all

### Use case

Dependency resolution

### Proposal

Upgrade all packages to `package:web` version `1.0.0`

**Comment by Rexios80** [comment]
I don't think there are any breaking changes, but there might be some cleanup to do if there are any extensions on JS types since version 1.0.0 added a bunch that didn't used to exist (and thus needed to be added manually)

**Comment by miquelbeltran** [comment]
We will probably get the PRs from dependabot within a week nevertheless ;)

Have you tried to do a `dependency_overrides`? any issues?

**Comment by Rexios80** [comment]
I have not tried anything since this is not urgent for me right now. I just wanted to bring attention to it.

**Comment by miquelbeltran** [comment]
I am pinning the issue, hopefully avoiding people creating the same ticket over and over.

**Comment by LucazzP** [comment]
I tried to add the web: 1.0.0 as a dependency_override, but it threw a bunch of exceptions on the share_plus_web, I think it is because the new web version as a new ShareData object, that conflicts with the ShareData object from share_plus.
Here is the exceptions:

```
      canShare = _navigator.canShare(data);
                                     ^
../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart:58:30: Error: The argument type 'ShareData/*1*/' can't be assigned to the parameter type 'ShareData/*2*/'.
 - 'ShareData/*1*/' is from 'package:share_plus/src/share_plus_web.dart' ('../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart').
 - 'ShareData/*2*/' is from 'package:web/src/dom/web_share.dart' ('../../../../../.pub-cache/hosted/pub.dev/web-1.0.0/lib/src/dom/web_share.dart').
      await _navigator.share(data).toDart;
                             ^
../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart:91:38: Error: The argument type 'ShareData/*1*/' can't be assigned to the parameter type 'ShareData/*2*/'.
 - 'ShareData/*1*/' is from 'package:share_plus/src/share_plus_web.dart' ('../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart').
 - 'ShareData/*2*/' is from 'package:web/src/dom/web_share.dart' ('../../../../../.pub-cache/hosted/pub.dev/web-1.0.0/lib/src/dom/web_share.dart').
      canShare = _navigator.canShare(data);
                                     ^
../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart:129:30: Error: The argument type 'ShareData/*1*/' can't be assigned to the parameter type 'ShareData/*2*/'.
 - 'ShareData/*1*/' is from 'package:share_plus/src/share_plus_web.dart' ('../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart').
 - 'ShareData/*2*/' is from 'package:web/src/dom/web_share.dart' ('../../../../../.pub-cache/hosted/pub.dev/web-1.0.0/lib/src/dom/web_share.dart').
      await _navigator.share(data).toDart;
                             ^
../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart:192:38: Error: The argument type 'ShareData/*1*/' can't be assigned to the parameter type 'ShareData/*2*/'.
 - 'ShareData/*1*/' is from 'package:share_plus/src/share_plus_web.dart' ('../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart').
 - 'ShareData/*2*/' is from 'package:web/src/dom/web_share.dart' ('../../../../../.pub-cache/hosted/pub.dev/web-1.0.0/lib/src/dom/web_share.dart').
      canShare = _navigator.canShare(data);
                                     ^
../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart:207:30: Error: The argument type 'ShareData/*1*/' can't be assigned to the parameter type 'ShareData/*2*/'.
 - 'ShareData/*1*/' is from 'package:share_plus/src/share_plus_web.dart' ('../../../../../.pub-cache/hosted/pub.dev/share_plus-9.0.0/lib/src/share_plus_web.dart').
 - 'ShareData/*2*/' is from 'package:web/src/dom/web_share.dart' ('../../../../../.pub-cache/hosted/pub.dev/web-1.0.0/lib/src/dom/web_share.dart').
      await _navigator.share(data).toDart;
                             ^
```

**Comment by miquelbeltran** [comment]
`share_plus` and `battery_plus` fail to build with `web` 1.0.0. 
`device_info_plus`, `connectivity_plus` and `package_info_plus` seem fine.

**Comment by miquelbeltran** [comment]
FYI for anyone who is getting `web` `1.0.0` issues: In `device_info_plus`, `package_info_plus` and `connectivity_plus` you can simply do a dependency overrides and set `web` to `1.0.0`, e.g.

```yaml
dependency_overrides:
  web: ^1.0.0
```

Learn more about managing dependencies here: https://dart.dev/tools/pub/dependencies

**Comment by miquelbeltran** [comment]
Changes in `share_plus` and `battery_plus` should be ready to land soon. Our current plan is to release all packages sometime next week (week 33).

Meanwhile, you can use dependency overrides and/or `git-ref` in your pubspecs if this is blocking you. If you do, please provide feedback if you encounter any issues.

**Comment by vbuberen** [comment]
After yesterday's release all plugins now support projects with `web: 1.0.0`, so closing this as completed.

**Comment by provokateurin** [comment]
What about https://github.com/fluttercommunity/wakelock_plus/issues/68?

**Comment by vbuberen** [comment]
> What about https://github.com/fluttercommunity/wakelock_plus/issues/68?

It is a separate repo maintained by another person.
