### ISSUE TITLE
[battery_plus_macos] Add integration test

### ISSUE THREAD

**Issue by Nash0x7E2** [fluttercommunity/plus_plugins#31]
Battery Plus macOS is currently missing integration tests.

## Objectives
- [ ] Add test cases for `getBatteryLevel`
- [ ] Add test cases for `onBatteryStateChanged`

**Comment by miquelbeltran** [comment]
The e2e tests seem to be located in https://github.com/fluttercommunity/plus_plugins/tree/main/packages/battery_plus/test, which already checks for `batterylevel`. Have you tried to run that test on MacOS?

(also, the test location is wrong, as I reported in https://github.com/fluttercommunity/plus_plugins/issues/28)
