### ISSUE TITLE
[Question]: Error: Missing permissions required by Build.getSerial: android.permission.READ_PRIVILEGED_PHONE_STATE [MissingPermission] Build.getSerial()

### ISSUE THREAD

**Issue by yoanadl** [fluttercommunity/plus_plugins#3110]
### What is your question?

I'm using health API plugins (v.10.2.0) for my Android development that depends on this plugin. But this error keeps persists as I need to get permission to use READ_PRIVILEGED_PHONE_STATE permission. My app is a usual workout application, do I need to make it to become a system app? This does not make sense to me.  I have searched for alternative (using Android.ID) but I don't think I can implement it to the plugin rightaway right?

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
>  development that depends on this plugin

You didn't specify which plugin. But from `getSerial()` I assume that it is about `device_info_plus`. 
No, there is no need to make your app a system app as the plugin handles the serial number retrieval in a way that if it is available - return serial, if not - catch the security exception and return `unknown`. 
You also didn't mention where you see this error. Is it in logs?

**Comment by yoanadl** [comment]
Yes, it is from the device_info_plus. And yes, I see it in the logs like this
`C:\Users\yoana\AppData\Local\Pub\Cache\hosted\pub.dev\device_info_plus-8.2.2\android\src\main\kotlin\dev\fluttercommunity\plus\device_info\MethodCallHandlerImpl.kt:84: Error: Missing permissions required by Build.getSerial: android.permission.READ_PRIVILEGED_PHONE_STATE [MissingPermission]
                    Build.getSerial()
                    ~~~~~~~~~~~~~~~~~

   Explanation for issues of type "MissingPermission":
   This check scans through your code and libraries and looks at the APIs
   being used, and checks this against the set of permissions required to
   access those APIs. If the code using those APIs is called at runtime, then
   the program will crash.

   Furthermore, for permissions that are revocable (with targetSdkVersion 23),
   client code must also be prepared to handle the calls throwing an exception
   if the user rejects the request for permission at runtime.`

**Comment by yoanadl** [comment]
This is the flutter doctor result

[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3880], locale en-ID)
    • Flutter version 3.22.3 on channel stable at C:\flutter_windows_3.22.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (12 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\yoana\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.0 Preview 7.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.10.34902.84
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\yoana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.72
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.74

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by vbuberen** [comment]
> Explanation for issues of type "MissingPermission":
This check scans through your code and libraries and looks at the APIs

I assume this is the default Android linter error. Don't know why it appears only when `health` plugin is used, but I would consider modifying your lint rules like already suggested to another user some time ago: https://github.com/fluttercommunity/plus_plugins/issues/1986

**Comment by yoanadl** [comment]
I have implemented both lintOptions and lint, but the error still persists..

**Comment by vbuberen** [comment]
> I have implemented both lintOptions and lint, but the error still persists..

It seems to me that it is the issue with your setup. I would advise you to check StackOverflow and other places to find out what is wrong with your setup.

As the initial question is answered and you confirmed that you don't see this error in the example app, closing this issue as resolved.

**Comment by ngockhanhbl** [comment]
same issue. :( .any update ?
