### ISSUE TITLE
[Request]:Enhancement Needed for Share_Plus: Multiple Templates for Sharing Content

### ISSUE THREAD

**Issue by yoko-stripes** [fluttercommunity/plus_plugins#3113]
### Plugin

share_plus

### Use case

Is it possible to add a feature to recognize the sharing method so we can use different templates depending on how the content is shared?

### Proposal

Example:
When the user attempts to share the content via X and Facebook, use Template A, and the rest, use Template B.

**Comment by vbuberen** [comment]
No, there is no such way to do so. The plugin triggers system share sheets, not some custom made widgets.

**Comment by yoko-stripes** [comment]
@vbuberen , Thank you for checking into this request and leaving a feedback.

**Comment by vbuberen** [comment]
Closing as resolved
