### ISSUE TITLE
[Compile]:  cast >=2.0.0 requires connectivity_plus >=4.0.0 <4.1.0.

### ISSUE THREAD

**Issue by AATMAN-ATOMIK** [fluttercommunity/plus_plugins#3143]
### Operating System

Windows 11

### Plugin

connectivity_plus

### Version

6.0.4

### Flutter SDK

3.22.0

### Compilation command

flutter pub get

### Dart Dependencies

```yaml
dependencies:
  flutter:
    sdk: flutter
  cast: ^2.0.0
  connectivity_plus: ^6.0.4
```

### Compilation Error

```shell
Because cast >=2.0.0 depends on bonsoir ^3.0.0 which depends on bonsoir_platform_interface ^3.0.0, cast >=2.0.0 requires bonsoir_platform_interface ^3.0.0.
And because bonsoir_platform_interface >=3.0.0 <4.1.0 depends on connectivity_plus >=4.0.0 <4.1.0, cast >=2.0.0 requires connectivity_plus >=4.0.0 <4.1.0.
So, because connectivity_test depends on both cast ^2.0.0 and connectivity_plus ^6.0.4, version solving failed.


You can try one of the following suggestions to make the pubspec resolve:
* Consider downgrading your constraint on cast: flutter pub add cast:^1.1.1
* Consider downgrading your constraint on connectivity_plus: flutter pub add connectivity_plus:^4.0.2
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3958], locale en-IN)
    • Flutter version 3.22.0 on channel stable at C:\src\flutter-3.22\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (3 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\kacha\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] VS Code (version 1.92.0)
    • VS Code at C:\Users\kacha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3958]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.129
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Deepakchowdavarapu** [comment]
I would like to work on this issue

**Comment by miquelbeltran** [comment]
There is no issue to be worked, it's a version solving problem. Either ask the developers of cast or bonsoir to upgrade their project to connectivity_plus 6 or use dependency overrides: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by AATMAN-ATOMIK** [comment]
> There is no issue to be worked, it's a version solving problem. Either ask the developers of cast or bonsoir to upgrade their project to connectivity_plus 6 or use dependency overrides: https://dart.dev/tools/pub/dependencies#dependency-overrides

The cast package has already updated their dependancies , its the issue with connectivity_plus package . And for information Cast Package doesn't depend on any plus_plugins. It depends on following " [bonsoir](https://pub.dev/packages/bonsoir), [flutter](https://api.flutter.dev/), [protobuf](https://pub.dev/packages/protobuf) ".


Note : There is no error in cast it uses all the latest dependancies. One of connectivity_plus dependency uses older version of bonsoir.


Without knowing about cast do not close the issue.

Please gather the information first and then reply. I have already done the version solving for bonsair first and it is not working because its already on its latest version. So that i had created the issue..

**Comment by AATMAN-ATOMIK** [comment]
> I would like to work on this issue

Yes please , this is not resolved yet.

**Comment by AATMAN-ATOMIK** [comment]
> There is no issue to be worked, it's a version solving problem. Either ask the developers of cast or bonsoir to upgrade their project to connectivity_plus 6 or use dependency overrides: https://dart.dev/tools/pub/dependencies#dependency-overrides

Okay will try to inform the Cast Package to update their dependancies. For now can i use older version of the connectivity_plus plugin like maybe 4.0.* in newer projects ?

**Comment by miquelbeltran** [comment]
IMO, there are several improvements in versions 5 and 6 that are worth it, e.g. stability issues on iOS specially.

`cast` seems to be using an old version of `bonsoir`, which has the old `connectivity_plus` dependency in it. Looking at both projects, it seems that never versions of `bonsoir` don't even use `connectivity_plus` anymore.

A quick solution for you would be to fork `cast` and fix it, or force an upgrade to `bonsoir` 5.x with a dependency overrides.

**Comment by AATMAN-ATOMIK** [comment]
> IMO, there are several improvements in versions 5 and 6 that are worth it, e.g. stability issues on iOS specially.
> 
> `cast` seems to be using an old version of `bonsoir`, which has the old `connectivity_plus` dependency in it. Looking at both projects, it seems that never versions of `bonsoir` don't even use `connectivity_plus` anymore.
> 
> A quick solution for you would be to fork `cast` and fix it, or force an upgrade to `bonsoir` 5.x with a dependency overrides.

Thanks for the reply , I have submitted the issue to the cast and they have resolved the dependency issue. Thanks for the quick response.
