### ISSUE TITLE
[package_info_plus] Docs suggestion

### ISSUE THREAD

**Issue by Ascenio** [fluttercommunity/plus_plugins#315]
In the usage there's this part:

> Or in async mode:
> ```dart
> PackageInfo.fromPlatform().then((PackageInfo packageInfo) {
>   String appName = packageInfo.appName;
>   String packageName = packageInfo.packageName;
>   String version = packageInfo.version;
>   String buildNumber = packageInfo.buildNumber;
> });
> ```
Don't you guys think it would be better to just leave the `await` version in the sample for simplicity?

**Comment by mhadaily** [comment]
Well, I think this is more of your choice, but writing synchronous code makes it easier to read.

**Comment by Ascenio** [comment]
But the `.then` gets code longer, I don't think it's any simpler.

**Comment by mhadaily** [comment]
well, long doesn't necessary is a bad thing always as long as it helps for readability. 

but I also agree with you, some devs might like it that way. you're welcome to send a PR and suggest both ways we have `await` now and you can also this `.then` if you like just below that as an alternative.

**Comment by Ascenio** [comment]
Actually it already shows both options. My suggestion was to remove the `.then` because it would make the docs smaller and in most cases we want to avoid it.

**Comment by mhadaily** [comment]
PR is welcome.

**Comment by Ascenio** [comment]
Sure.
