### ISSUE TITLE
[Compile]: add support for web:1.0.0

### ISSUE THREAD

**Issue by zkrige** [fluttercommunity/plus_plugins#3151]
### Operating System

any

### Plugin

package_info_plus

### Version

8.0.1

### Flutter SDK

3.24.0

### Compilation command

flutter pub add package_info_plus

### Dart Dependencies

```yaml
web:^1.0.0
```

### Compilation Error

```shell
Resolving dependencies... 
Because <APP> depends on package_info_plus ^8.0.1 which depends on web >=0.5.0 <=0.6.0, web >=0.5.0 <=0.6.0 is required.
So, because <APP> depends on web 1.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on web: flutter pub add web:^0.5.1
```

### Flutter Doctor

```shell
not relevant
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
There is a pinned ticket regarding this: https://github.com/fluttercommunity/plus_plugins/issues/3093
`package_info_plus` has already been migrated to web 1.0.0: https://github.com/fluttercommunity/plus_plugins/pull/3102
The package is pending for a release.

Meanwhile, you can simply set dependency overrides for web 1.0.0.

Please don't create new tickets when there is already a pinned ticket covering this topic.
