### ISSUE TITLE
[Request]: Target Java 21

### ISSUE THREAD

**Issue by RoarGronmo** [fluttercommunity/plus_plugins#3168]
### Plugin

device_info_plus

### Use case

Gradle may now use JDK 21.

This problem occures when using JDK 21 when project use `device_info_plus`:
```
[  +94 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':device_info_plus:compileDebugJavaWithJavac'.
[        ] > Could not resolve all files for configuration ':device_info_plus:androidJdkImage'.
[        ]    > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
[        ]       > Execution failed for JdkImageTransform: C:\Users\roarg\AppData\Local\Android\Sdk\platforms\android-34\core-for-system-modules.jar.
[        ]          > Error while executing process C:\Program Files\Android Studio\Android Studio 2024.2.1.1\jbr\bin\jlink.exe with arguments {--module-path C:\Users\roarg\.gradle\caches\transforms-3\5d81b8cd7172b408a512f4f8fbc5d462\transformed\output\temp\jmod --add-modules java.base --output C:\Users\roarg\.gradle\caches\transforms-3\5d81b8cd7172b408a512f4f8fbc5d462\transformed\output\jdkImage --disable-plugin system-modules}
[
```

AFAIK JDK 17 was the LOWEST JDK version `device_info_plus` was compatible with, not that it has to be pinned to JDK 17.

### Proposal

Make `device_info_plus` compatible with JDK 21.

Reference: https://github.com/flutter/flutter/issues/153156#issuecomment-2277874256

**Comment by vbuberen** [comment]
`device_info_plus` is already compatible with Java 21 and works fine in projects with such Java version. In the logs that you provided in the Flutter repository it is clearly mentioned that the Gradle version of the project isn't compatible with used Java version. 

It is an issue in your project setup + (possibly) something in the canary version of Android Studio that you use, not an issue of the plugin.
