### ISSUE TITLE
[Request]: Support different rates (delay) options than the default one

### ISSUE THREAD

**Issue by AhmedJHamdan** [fluttercommunity/plus_plugins#3174]
### Plugin

sensors_plus

### Use case

The value for the sensor delay in Android is hard coded as SENSOR_DELAY_NORMAL.
In my case I needed to use SENSOR_DELAY_UI, we should give the developer the possibility to choose what ever option fits their use case.

### Proposal

Just change the hardcoded value an give the dev the possibility to setup this value. I find time this week I may implement it myself.

**Comment by vbuberen** [comment]
> The value for the sensor delay in Android is hard coded as SENSOR_DELAY_NORMAL.

I think that you overlooked it in the code, but the plugin already supports setting sampling rate with both provided enum values and your specific values. Here is the Android part of the plugin that sets the sampling rate: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt#L49
