### ISSUE TITLE
[Bug]: Alarm manager plus 4.0.4 min sdk requires an upgrade

### ISSUE THREAD

**Issue by Silfalion** [fluttercommunity/plus_plugins#3185]
### Platform

All android versions

### Plugin

alarm manager plus

### Version

4.0.4

### Flutter SDK

3.24.0

### Steps to reproduce

Alarm manager plus version 4.0.3 used app compat 1.6.1 which still allowed minSdk 19 but the last version(4.0.4) bumped up app compat to 1.7.0 which now requires minSdk 21, otherwise it will throw an error when compiling.

### Logs

```shell
Error:
        uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [androidx.appcompat:appcompat-resources:1.7.0]
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on Ubuntu 23.10 6.9.3-060903-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on Ubuntu 23.10 6.9.3-060903-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources
```
```


### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
I see how that can be frustrating, but there are multiple solutions:

- You can stay with `4.0.3` (not `^4.0.3`)
- You can force an older version of app compat with a gradle dependency overrides: https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html
- Consider increasing your minSdk. You can consult usage of minSdks here: https://apilevels.com/ If I am not wrong, the Flutter SDK already defines the minSdk to be 21.

**Comment by Silfalion** [comment]
Thank you for your suggestions! They'll come in handy if I ever need the other ones as I already went with the first. 

However I created this issue so that it can maybe move to a pull request(I can make one to up the minSdk of the package), as it can't be fixed "organically". 

For instance, changing the minimum version number(tried on different projects) doesn't work, so it wouldn't be something that fixes itself, if you know what I mean.

Can this be left open until it's fixed? Don't know if there is another procedure to address it. 

Thank you again for having taken the time to look into this.

**Comment by miquelbeltran** [comment]
Do you mean the issue is in the `minSdk` defined in the package `build.gradle` https://github.com/fluttercommunity/plus_plugins/blob/0c5706fa0cda418e552980c93a52e15667e5bb3f/packages/android_alarm_manager_plus/android/build.gradle#L42 not the one defined in your project?

Our example has `minSdk` 21 and CI did not complain when the version bump PR was submitted: https://github.com/fluttercommunity/plus_plugins/blob/0c5706fa0cda418e552980c93a52e15667e5bb3f/packages/android_alarm_manager_plus/example/android/app/build.gradle#L50

**Comment by Silfalion** [comment]
Yes, that's what I mean. I was able to reproduce it just now after creating a dummy Flutter project and adding the dependency to it. Had to up the kotlin language version as well but that was also the case with my previous tests. This test was done with Flutter 3.22 and on my other projects with 3.24.

It's indeed weird the CI didn't throw anything. Had to dig deep to find out that AppCompat 1.7.0 have increased their minimum sdk to 21 and that was the issue.   The only difference I see in the build command in the CI is `--no-android-gradle-daemon`

Could you maybe try to replicate it with the same steps as in my first paragraph? Just a `flutter create alarm_test` project

**Comment by miquelbeltran** [comment]
I just did the following:

1. Created project with `flutter create alarm_test`
2. Added package with `flutter pub add android_alarm_manager_plus`
3. Compiled `flutter build apk --debug`  with and got an error, the output in "Flutter Fix" asked to increase Kotlin version.
4. Modified Kotlin version in `alarm_test/android/settings.gradle` to 1.9.25.
5. Compiled `flutter build apk --debug`  with and got an error, followed the error message and upgraded gradle.
6. Upgraded gradle wrapper to 8.4.
7. Compiled with `flutter build apk --debug` and it worked.

The Android compiler already told me what I had to do. This was with Flutter channel stable.

**Comment by Silfalion** [comment]
Thank you for taking the time to check.

Followed the exact same steps however on point 5 I get this error message instead:

```
ERROR:/$HOME/.gradle/caches/transforms-3/be1419da4fe0be95f01d98fa7c499e95/transformed/jetified-appcompat-resources-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
ERROR:/$HOME/.gradle/caches/transforms-3/f3a5639feb762d3d5d41a0adfe294d7d/transformed/appcompat-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-resources-1.7.0.aar (androidx.appcompat:appcompat-resources:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /$HOME/.gradle/caches/transforms-3/be1419da4fe0be95f01d98fa7c499e95/transformed/jetified-appcompat-resources-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform appcompat-1.7.0.aar (androidx.appcompat:appcompat:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /$HOME/.gradle/caches/transforms-3/f3a5639feb762d3d5d41a0adfe294d7d/transformed/appcompat-1.7.0-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Running Gradle task 'assembleDebug'...                             23.2s
Gradle task assembleDebug failed with exit code 1
```

Maybe the issue is only on my side? I deleted the .gradle folder multiple times following this issue but it still occurs. Well, if it's not reproducible on your side and the CI didn't complain then I guess there isn't much else to look into.

**Comment by miquelbeltran** [comment]
True, I also saw that issue, fixed it by changing `com.android.application` to `8.3.0`. 

I forgot to include that step when copying it.

This is my `settings.gradle`:

```
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.9.25" apply false
}

include ":app"
```

And the `gradle-wrapper.properties`:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-all.zip
```

**Comment by Silfalion** [comment]
Oh so that was the missing piece, makes sense now!

But how did you know to change the version? I mean, was it just the error that pointed you to it or was there another message?

If it's the former, maybe the package should have a requirement in the README for the `com.android.application` plugin being set at 8.x.x

**Comment by miquelbeltran** [comment]
Found it by searching for the error. https://stackoverflow.com/a/78319384

But it is indeed listed in the package README: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_alarm_manager_plus#requirements

Still, I kind of want to discuss this internally with the rest of the team because we get way too many tickets from people that have version conflicts, so we should ensure that the project builds when added to a freshly created project with `flutter create`.

**Comment by Silfalion** [comment]
Oh, I saw that stackoverflow Q and dismissed it because I thought it was meant to work version 7.3, so it couldn't be that.

Didn't notice it in the list, got used to requirements being shown as code blocks so I glanced over it, my bad.

Yeah, if it worked out of the box, especially since flutter still relies on 7.3 by default, it would be ideal. 

Thank you again for taking the time to look into this and pointing out the requirements, now I know what to look for next time.

Btw, any reason for using 8.x.x instead of staying with 7.3?

**Comment by denyocr93** [comment]
I managed to resolve this issue by applying the following configurations:

### `gradle-wrapper.properties`
```properties
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-all.zip
```

### `build.gradle`
```gradle
compileSdk = 34
ndkVersion = '27.0.12077973'
minSdk = 24
targetSdk = 34
```

### `settings.gradle`
```gradle
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.9.25" apply false
}
```

After applying these settings, the project built successfully. I hope this helps others encountering the same issue!
