### ISSUE TITLE
[Question]: Huawei and Honor models, can the text in the middle of the pop-up window be modified?

### ISSUE THREAD

**Issue by SheepYang1993** [fluttercommunity/plus_plugins#3186]
### What is your question?

![6bc1814f3ceb0e2c81cb19685769301](https://github.com/user-attachments/assets/de62a653-5285-41a8-8958-0ad0a52d0069)
如上图所示

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Please use translator and write on English, so others can understand without need to use translation tools.

**Comment by SheepYang1993** [comment]
Huawei and Honor models, can the text in the middle of the pop-up window be modified?
On the left is the Honor phone.
On the right is a Huawei phone.

**Comment by PenguinBIUBIUBIU** [comment]
same question, the ui for huawei is really ugly

**Comment by miquelbeltran** [comment]
The plugin doesn't have the capacity to change the phone OS UI, as it only calls to standard Android OS APIs.

This should be reported to Huawei instead.

**Comment by OnClickListener2048** [comment]
same here
