### ISSUE TITLE
[Bug]: when run flutter build apk --release  error

### ISSUE THREAD

**Issue by hzysunrain** [fluttercommunity/plus_plugins#3194]
### Platform

Android 14

### Plugin

device_info_plus

### Version

10.1.2

### Flutter SDK

3.24.0

### Steps to reproduce

when run ： flutter build apk --release

What went wrong:
Execution failed for task ':device_info_plus:compileReleaseJavaWithJavac'.
> ����: ��Ч��Դ���а棺17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 41s
Running Gradle task 'assembleRelease'...                          102.6s
Gradle task assembleRelease failed with exit code 1

### Logs

```shell
i run command: flutter build apk --release
```

### Flutter Doctor

```shell
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [版本 10.0.19045.4780], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.10.1)
[√] Android Studio (version 2023.1)
[!] Android Studio (version unknown)
    X Unable to determine Android Studio version.              
    X android-studio-dir = C:\DevelopmentSoftware\AndroidStudio
    X Unable to find bundled Java version.
[√] VS Code (version 1.92.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Error logs are missing and the `flutter doctor` command doesn't have the full output with `-v`.
We also have a "compile" issue template for compilation errors.

**Comment by vbuberen** [comment]
> ����: ��Ч��Դ���а棺17

From this line I suspect that is another one about Java 17.

If it is so, I would suggest to really use search instead of just marking checkmarks pretending to do so, because the solution is available both among already resolved issues here, in this repo, as well as on StackOverflow.

**Comment by hzysunrain** [comment]
Thanks.  The problem was solved by updating Android Studio to the latest version.
