### ISSUE TITLE
[Request]: Full Dart SDK compatibility 

### ISSUE THREAD

**Issue by poka-IT** [fluttercommunity/plus_plugins#3196]
### Plugin

package_info_plus

### Use case

For a CLI tool build with Dart, we cannot get the version number of the tool.

### Proposal

Make this package compatible with full Dart SDK, so we can use it to get version number from pubspec.yaml with a `--version` command for example.

**Comment by miquelbeltran** [comment]
I don't think the plugin can accomplish that, this sort of importation has to be exposed by the Dart SDK and so far the only way they do that is when Flutter generates a `version.json`. I don't think the Dart SDK does that.

Probably this request should go in the Dart language repository.

**Comment by Neutrino2711** [comment]
A Function to fetch version from 'pubspec.yaml' is needed 
1) dart pub add yaml [project terminal]
2) Add this function to your project/file 
String getVersion() {
  final file = File('pubspec.yaml');
  if (!file.existsSync()) {
    throw Exception('pubspec.yaml file not found');
  }

  final content = file.readAsStringSync();
  final yamlMap = loadYaml(content) as YamlMap;

  return yamlMap['version'] ?? 'Version not specified';
}
3) add these lines in main() function accept arguments while running the file from CLI
 if (arguments.contains('--version')) {
    final version = getVersion();
    print('Version: $version');
    return;
  } 
Now you can add --version flag while running the dart file

**Comment by miquelbeltran** [comment]
You need the path to the pubspec.yaml, and you need to distribute it when you create a dart binary. Not really a solution.

Since this is a Dart SDK issue, not a Flutter package issue, I will have to close this one. This should be brought to the Dart SDK team.
