### ISSUE TITLE
[Question]: Missing Privacy Manifest

### ISSUE THREAD

**Issue by Vincentcapri** [fluttercommunity/plus_plugins#3200]
### What is your question?

Hi, I got this email from Apple. Any solution for this?

ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/connectivity_plus.framework/connectivity_plus”, which includes connectivity_plus, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
This was already discussed here: https://github.com/fluttercommunity/plus_plugins/issues/2447 and here https://github.com/fluttercommunity/plus_plugins/issues/2751 among other tickets.

Please use the search function next time.
