### ISSUE TITLE
[Connectivity_plus] Error building for android

### ISSUE THREAD

**Issue by imtoori** [fluttercommunity/plus_plugins#322]
## System info

Issue occurs on: Android
Plugin name: connectivity_plus
Plugin version: 1.0.4
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)

• No issues found!

```

## Steps to Reproduce

1. build for android
2. it fails

## Logs

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

-----------

* Where:
Build file '/opt/hostedtoolcache/flutter/2.2.1-stable/x64/.pub-cache/hosted/pub.dartlang.org/connectivity_plus-1.0.4/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':connectivity_plus'.
> Could not get unknown property 'javaToolchains' for task ':app:compileDebugAndroidTestJavaWithJavac' of type org.gradle.api.tasks.compile.JavaCompile.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/opt/hostedtoolcache/flutter/2.2.1-stable/x64/packages/flutter_tools/gradle/flutter.gradle' line: 346

* What went wrong:
A problem occurred configuring project ':connectivity_plus'.
> Could not get unknown property 'android' for project ':connectivity_plus' of type org.gradle.api.Project.
```

**Comment by BitBlueDevStudio** [comment]
Same errors

**Comment by kephren226** [comment]
I have the same error 
Tried version 1..0.0 still the same error

**Comment by BitBlueDevStudio** [comment]
> I have the same error
> Tried version 1..0.0 still the same error

Yes, 1.0.0 also doesnt work, i dont know why it worked for me for the fisrt time. Now its doesnt work too )

**Comment by mlars84** [comment]
Same problem here. Flutter 2.2.2 with the environment set to `sdk: '>=2.12.0 <3.0.0'` fails when building for android devices and emulators with `Exception: Gradle task assembleDebug failed with exit code 1` from inside the connectivity_plus 1.0.4's build.gradle. More details from running `flutter run --verbose`:

```
[+2354 ms] FAILURE: Build completed with 2 failures.
[  +10 ms] 1: Task failed with an exception.
[        ] -----------
[        ] * Where:
[        ] Build file '/Users/matthewlarson/development/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus-1.0.4/android/build.gradle' line: 22
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':connectivity_plus'.
[        ] > Could not get unknown property 'javaToolchains' for task ':app:compileDebugAndroidTestJavaWithJavac' of type
com.android.build.gradle.tasks.AndroidJavaCompile.
[        ] * Try:
[  +27 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[   +1 ms] ==============================================================================
[        ] 2: Task failed with an exception.
[        ] -----------
[        ] * Where:
[        ] Script '/Users/matthewlarson/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 346
[        ] * What went wrong:
[        ] A problem occurred configuring project ':connectivity_plus'.
[        ] > Could not get unknown property 'android' for project ':connectivity_plus' of type org.gradle.api.Project.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[   +1 ms] ==============================================================================
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 3s
```

**Comment by mlars84** [comment]
This solution worked for me:

Change `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties` and run `./gradlew clean` in the android directory. After that I ran `flutter clean` and everything built as expected.

**Comment by kephren226** [comment]
> This solution worked for me:
> 
> Change `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties` and run `./gradlew clean` in the android directory. After that I ran `flutter clean` and everything built as expected.

Where the path for this command ./gradlew clean

**Comment by mlars84** [comment]
You can run it in the android directory: 

From your project's root dir:

- `cd android`
- `./gradlew clean`

**Comment by mlars84** [comment]
> You can run it in the android directory:
> 
> From your project's root dir:
> 
> * `cd android`
> * `./gradlew clean`

P.s., this command comes from the gradle-wrapper so should be available to you inside that android directory.

**Comment by kephren226** [comment]
> You can run it in the android directory:
> 
> From your project's root dir:
> 
>     * `cd android`
> 
>     * `./gradlew clean`

It worked for me 
thanks

**Comment by mlars84** [comment]
> > You can run it in the android directory:
> > From your project's root dir:
> > ```
> > * `cd android`
> > 
> > * `./gradlew clean`
> > ```
> 
> It worked for me
> thanks

Another note, if you're using firebase you will need to re-add your google-services.json since the clean command wipes it.

**Comment by kephren226** [comment]
> This solution worked for me:
> 
> Change `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties` and run `./gradlew clean` in the android directory. After that I ran `flutter clean` and everything built as expected.

Worked flawlessly

**Comment by MakufonSkifto** [comment]
> This solution worked for me:
> 
> Change `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties` and run `./gradlew clean` in the android directory. After that I ran `flutter clean` and everything built as expected.

I got this error after doing all this:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that C:\Program Files (x86)\Java\jre1.8.0_231 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1
```

I looked at [solutions](https://stackoverflow.com/questions/5730815/unable-to-locate-tools-jar) but nothing worked

**Comment by imtoori** [comment]
> This solution worked for me:
> 
> Change `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties` and run `./gradlew clean` in the android directory. After that I ran `flutter clean` and everything built as expected.

it worked! thanks!

**Comment by bhanuka96** [comment]
> This solution worked for me:
> 
> Change `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties` and run `./gradlew clean` in the android directory. After that I ran `flutter clean` and everything built as expected.

This solve this problem. But after that I got other plugin issues. Please re-open this issue

**Comment by kephren226** [comment]
> > This solution worked for me:
> > Change `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties` and run `./gradlew clean` in the android directory. After that I ran `flutter clean` and everything built as expected.
> 
> This solve this problem. But after that I got other plugin issues. Please re-open this issue

I'm not really sure but perhaps you are using plugins that do not support this gradle version

**Comment by martintadashi** [comment]
I just realized, its a duplicate from this: https://github.com/fluttercommunity/plus_plugins/issues/324
where its solved the same way
