### ISSUE TITLE
[Request]: Privacy Manifest Missing for Apple App Store Submission

### ISSUE THREAD

**Issue by ijashuzain** [fluttercommunity/plus_plugins#3246]
### Plugin

connectivity_plus

### Use case

When submitting an app to the Apple App Store that includes the connectivity_plus framework, the following error is encountered:

ITMS-91061: Missing privacy manifest - Your app includes "Frameworks/connectivity_plus.framework/connectivity_plus", which includes connectivity_plus, an SDK that was identified in the documentation as a privacy-impacting third-party SDK.

**Context**
Starting November 12, 2024, Apple requires privacy-impacting SDKs to include a privacy manifest file.
This affects new app submissions and updates that add new privacy-impacting SDKs.

### Proposal

**Request**
Please update the connectivity_plus SDK to include the required privacy manifest file to comply with Apple's new policy.

**Additional Information**
For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements

**Environment**
Flutter version: 3.24.1

**Steps to Reproduce**
Include connectivity_plus in a Flutter project
Build the iOS app
Submit the app to the App Store
Receive the ITMS-91061 error

Thank you for your attention to this matter.

**Comment by miquelbeltran** [comment]
The project already contains the manifest file. And this has been discussed multiple times in the repo issue tracker.

![image](https://github.com/user-attachments/assets/0f8caa64-17f2-4e9c-a81b-bc1b5502267a)

Main ticket is here: https://github.com/fluttercommunity/plus_plugins/issues/2447

**Comment by Splagov** [comment]
Looks like this issue fixed in device_info_plus version 10.0.1
Older version will cause ITMS-91061 error.

**Comment by ijashuzain** [comment]
Okay thankyou, i have mistakenly used old version👍

**Comment by maykhid** [comment]
> Looks like this issue fixed in device_info_plus version 10.0.1
> Older version will cause ITMS-91061 error.

Hi, I am a bit confused. The plug-in mentioned by the author is connectivity_plus not device_info_plus. How does this tie into the issue. I am actually trying to fix this issue on my end. I am using connectivity_plus v6.1.2.
