### ISSUE TITLE
[Question]: Connectiviy_plus

### ISSUE THREAD

**Issue by TiagoCrippa** [fluttercommunity/plus_plugins#3249]
### What is your question?

Even if the WiFi connection is activated, the error that you are not connected to the internet appears. However, most of the time it works normally without giving an error.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Having connectivity != having actual connection to the internet.

The plugin exposes the status of the network interface as reported by the OS, that doesn't mean that network interface is able to connect to the internet.
