### ISSUE TITLE
[sensors_plus] : Doubt regarding more sensors.

### ISSUE THREAD

**Issue by ritvij14** [fluttercommunity/plus_plugins#325]
Regarding sensors, the Android Open Source project official documentation lists a lot of sensors that can be accessed for their data. https://source.android.com/devices/sensors/sensor-types

My question is that will these sensors be added to the `sensors_plus` package as well soon? I wanted to know because one of my projects involves the usage of a magnetic field sensor (magnetometer), and I didn't see anything regarding that in docs for `sensors_plus`.

Also, can developers (like me) contribute to this code for the addition of their functioning to this package?

**Comment by mhadaily** [comment]
You are absolutely welcome to contribute and add any sensors. We welcome all PRs.
