### ISSUE TITLE
[Question]: device_info_plu uses old web 0.5.1 plugin which conflicts with the share_plus plugin

### ISSUE THREAD

**Issue by securexperts** [fluttercommunity/plus_plugins#3252]
### What is your question?

Hello, 

I use device_info_plus plugin but also share_plus plugin 
device_info_plus wants to use web 0.5.1, and share_plus 10.0.2 wants higher version of web. 

Can you please update to use web 1.0.0

at the moment I use 
dependency_overrides:
  web: ^1.0.0 

But I don't know if this impacts device_share_plus

Many Thanks

Roman

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
That shouldn't be the case, all plugins are either using `^1.0.0` or allow a range as `">=0.5.0 <2.0.0"`, so 1.0.0 should be resolved. You may have a dependency that is not up-to-date or is forcing 0.5 somewhere.

**Comment by securexperts** [comment]
OK Thanks, I just found where the downgrade came from. Sorry about that
