### ISSUE TITLE
[Request]: Request to provide android id

### ISSUE THREAD

**Issue by theMGR** [fluttercommunity/plus_plugins#3256]
### Plugin

device_info_plus

### Use case

provide android id from below link for reference

https://chromium.googlesource.com/external/github.com/flutter/plugins/+/refs/tags/url_launcher_macos-v0.0.1/packages/device_info/android/src/main/java/io/flutter/plugins/deviceinfo/MethodCallHandlerImpl.java?autodive=0%2F%2F%2F

### Proposal

need androidId, which is unique. it is used to check the device is already logged in another device or not. (from login api)

**Comment by vbuberen** [comment]
Please use search before opening an issue. `androidId` was removed from the plugin some time ago and there is a separate plugin now for this purpose: https://github.com/fluttercommunity/android_id
