### ISSUE TITLE
[connectivity_plus] Memory leak in Android ConnectivityPlus plugin

### ISSUE THREAD

**Issue by innim98** [fluttercommunity/plus_plugins#326]
## System info

Issue occurs on: Android
Plugin name: connectivity_plus
Plugin version: 1.0.4
Flutter doctor output:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
[✓] Connected device (3 available)

• No issues found!

```

## Steps to Reproduce

The Android Activity object is leaked whenever the application is closed.

1. Run the example application of connectivity_plus package
2. run below command to check the Activities
```
watch adb shell dumpsys meminfo io.flutter.plugins.connectivityexample
```
3. Press "BACK" key to close the example app and relaunch it from launcher
4. Repeat step 3, so you can see the number of Activities are increased one by one

## Logs

The output shows the number of `Activites` are increased without releasing.
By checking the code, I don't find any way to call `onCancel` in ConnectivityBroadcastReceiver.
The memory looks leaked because the receiver is not unregistered.

```
 Objects
               Views:       36         ViewRootImpl:        0
         AppContexts:       11           Activities:        4
              Assets:       12        AssetManagers:        0
       Local Binders:       23        Proxy Binders:       36
       Parcel memory:        6         Parcel count:       26
    Death Recipients:        0      OpenSSL Sockets:        0
            WebViews:        0
```

**Comment by mhadaily** [comment]
It's great you spot it, we will investigate more. however, if you have any solution now, it's great if you can contribute with one PR. we welcome you.

**Comment by innim98** [comment]
I tried to make a PR.
Do I need some permission to upload a commit?
'''
$ git push -u origin android-memory-leak-from-registered-receiver
Username for 'https://github.com': innim98@gmail.com
Password for 'https://innim98@gmail.com@github.com':
remote: Permission to fluttercommunity/plus_plugins.git denied to innim98.
fatal: unable to access 'https://github.com/fluttercommunity/plus_plugins.git/': The requested URL returned error: 403
'''

**Comment by innim98** [comment]
Made a PR https://github.com/fluttercommunity/plus_plugins/pull/353

**Comment by mhadaily** [comment]
Thanks, PR is merged, consider closing this issue if it looks good to you.

**Comment by innim98** [comment]
Fixed. Thank you.
