### ISSUE TITLE
[Bug]: privacy manifest needed for macOS

### ISSUE THREAD

**Issue by erf** [fluttercommunity/plus_plugins#3261]
### Platform

macOS 14.6

### Plugin

share_plus

### Version

10.0.2

### Flutter SDK

3.24.3

### Steps to reproduce

After i uploaded the macOS archive to App Store i received the following message:

> ITMS-91061: Missing privacy manifest - Your app includes “Contents/Frameworks/share_plus.framework/Versions/A/share_plus”, which includes share_plus, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements. 

### Code Sample

```dart
Include `share_plus` in a macOS build and archive it.
```

### Logs

```shell
N/A
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-NO)
    • Flutter version 3.24.3 on channel stable at /Users/erlend/.asdf/installs/flutter/3.24
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
<img width="543" alt="Screenshot 2024-09-20 at 12 06 41" src="https://github.com/user-attachments/assets/c75ab27e-db6b-4ccb-80bb-328f78ff2524">

Would appreciate if you really do search instead of lying.

https://github.com/fluttercommunity/plus_plugins/issues?q=is%3Aissue+is%3Aclosed+privacy+manifest

**Comment by dalerjun33** [comment]
If you still didn`t solve it. 
add this on info.plist for me it works.

<key>LSSupportsOpeningDocumentsInPlace</key>
	<true/>
<key>UIFileSharingEnabled</key>
	<true/>
<key>NSCameraUsageDescription</key>
<string>Это приложение требует доступа к камере для сканирования QR-кодов для оплаты и отправки фотографий при онлайн-идентификации.</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Этому приложению требуется доступ к галерее, чтобы вы могли установить фотографию профиля.</string>

**Comment by dalerjun33** [comment]
`
	<key>LSSupportsOpeningDocumentsInPlace</key>
	<true/>
	<key>UIFileSharingEnabled</key>
	<true/>
        <key>NSCameraUsageDescription</key>
    	<string>Это приложение требует доступа к камере для сканирования QR-кодов для оплаты и отправки фотографий 
        при онлайн-идентификации.</string>
    	
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Этому приложению требуется доступ к галерее, чтобы вы могли установить фотографию профиля.</string>
	
`
