### ISSUE TITLE
[Bug]: Error building Xcode archive: 

### ISSUE THREAD

**Issue by yassinsameh** [fluttercommunity/plus_plugins#3267]
### Platform

IOS

### Plugin

share_plus

### Version

10.0.2

### Flutter SDK

3.24.1

### Steps to reproduce

Archive the project via CI/CD like codemagic. I'm not sure why it runs correctly locally, codemagic has the same Xcode version, Flutter version and Cocoapods version but fails. It seems like a warning but it is failing the build.

Based on findings in similar errors, i believe the solution is the following:

Functions should be declared explicitly as: myFunction(void); instead of myFunction();

### Logs

```shell
* ARCHIVE FAILED *


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/flutter_tools.EEni8Y/flutter_ios_build_temp_dirFu9zrk/temporary_xcresult_bundle

    /Users/builder/.pub-cache/hosted/pub.dev/share_plus-10.0.2/ios/Classes/FPPSharePlusPlugin.m:10:44: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
    static UIViewController *RootViewController() {
                                               ^
                                                void
```

### Flutter Doctor

```shell
Flutter (Channel stable, 3.24.1, on macOS 14.4.1 23E224 darwin-arm64, locale en-DE)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.93.1)
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
It could be that code magic is treating compilation warnings as errors, still, a warning should be fixed.

In any case, please create a PR with your proposed changes and I'll take a look.

**Comment by yassinsameh** [comment]
Issue was with a crashlytics build phase, but in the CI/CD it only showed this in the build failure log hence my confusion. This is just a warning then with no failing ramification 👌

**Comment by vbuberen** [comment]
Closing as resolved

**Comment by habeshaweapp** [comment]
did you find any solutions please?
