### ISSUE TITLE
[Connectivity] Checking private or public Wi-Fi network

### ISSUE THREAD

**Issue by subzero911** [fluttercommunity/plus_plugins#327]
I want to check if I have connected to home Wi-Fi or public Wi-Fi (say, hotel Wi-Fi or hotspot) and depending on it, restrict some app features for security reasons.

**Comment by dim-apparence** [comment]
Hello, seems to be not possible on iOS, for now, :/ https://stackoverflow.com/questions/7030561/can-you-determine-if-wifi-security-is-enabled-on-network-youre-connected-to-on
