### ISSUE TITLE
[network_info_plus]   ios13、41  Get WiFi information and return null  

### ISSUE THREAD

**Issue by jahnli** [fluttercommunity/plus_plugins#328]
## System info

Issue occurs on: iOS / Android / both  ios
Plugin name: [network_info_plus] 
Plugin version: laset
Flutter doctor output:

```
[network_info_plus]   ios13、41  Get WiFi information and return null  
```

## Logs

```
```

```
```

```
```

**Comment by mhadaily** [comment]
It seems, your logs are not posted. can you please send them again. please also share your Flutter Doctor logs.
