### ISSUE TITLE
Android and IOS getWifiName not working.

### ISSUE THREAD

**Issue by abbadabbatech** [fluttercommunity/plus_plugins#330]
## System info

Issue occurs on: both
Plugin name:network_info_plus
Plugin version:1.0.2
Flutter doctor output:

```
paste it here...
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by Chinmay-KB** [comment]
Could you add the flutter doctor and the minimum code needed to reproduce it?
Thanks

**Comment by mhadaily** [comment]
@abbadabbatech it's hard to reproduce without logs and further information. Please provide your Flutter Doctor logs as well as let us know you are testing in Prod or Dev and on Real device or Simulator, which IOS/Android version and API are you using too.

**Comment by mhadaily** [comment]
released a new version. feel free to open again if you still have any problem
