### ISSUE TITLE
[Request]: Bump mime to v2

### ISSUE THREAD

**Issue by mgenware** [fluttercommunity/plus_plugins#3308]
### Plugin

share_plus

### Use case

`share_plus` is preventing us from upgrading our packages:
```
flutter pub upgrade --major-versions

Because every version of <some_package> from git depends on mime ^2.0.0 and share_plus >=7.0.0 depends on mime ^1.0.4, <some_package> from git is incompatible with share_plus >=7.0.0.
```

### Proposal

Bump `mime` from `share_plus` to v2

**Comment by miquelbeltran** [comment]
Feel free to submit a PR with the upgrade. This should have been upgraded by dependabot but it did not appear yet.

Also you can use dependency overrides, so nothing is blocking you.

**Comment by mafreud** [comment]
@miquelbeltran merged PR last week. So, we'll have to wait for the release.
https://github.com/fluttercommunity/plus_plugins/pull/3288

**Comment by mafreud** [comment]
Since image_picker (for web) uses mime v1, so we cannot use v2 for now for share_plus.

**Comment by miquelbeltran** [comment]
Ah I see it was increased for platform interface but not for the main package.

Looking at the changeling I saw one method now can return null, so I need to verify if that can cause an issue.

**Comment by miquelbeltran** [comment]
I am taking the PR you opened and I am changing it so:

- mime is set to a range that includes both v1 and v2, so it is backwards compatible
- checks for null return of `extensionFromMime`

**Comment by mafreud** [comment]
@miquelbeltran thank you!
