### ISSUE TITLE
[Bug]: Documentation inconsistency

### ISSUE THREAD

**Issue by reduxdj** [fluttercommunity/plus_plugins#3325]
### Platform

All

### Plugin

connectitvity_plus

### Version

6.0

### Flutter SDK

3.22

### Steps to reproduce

Flutter >=3.19.0 is what the change log supports but the readme says flutter >= 3.7

### Code Sample

```dart
N/a
```

### Logs

```shell
N/A
```

### Flutter Doctor

```shell
N/A
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Thanks for reporting. PRs are welcome, so if you would like to, feel free to open one with the fix.

**Comment by vbuberen** [comment]
Just looked at the pubspec of the plugin and curios what do you mean about requiring Flutter 3.19.0 if we have 3.7.0 there?
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus/pubspec.yaml#L15

**Comment by vbuberen** [comment]
Closing due to not response
