### ISSUE TITLE
Share.shareFiles Windows.

### ISSUE THREAD

**Issue by fabio21** [fluttercommunity/plus_plugins#333]
shareFiles() has not been implemented on Windows.

When the exception was thrown, this was the stack: 
#0      ShareWindows.shareFiles (package:share_plus_windows/share_plus_windows.dart:48:5)
#1      Share.shareFiles (package:share_plus/share_plus.dart:93:22)

**Comment by mhadaily** [comment]
@jpnurmi  do you know anything about this?

**Comment by jpnurmi** [comment]
@fabio21, do you happen to be aware of any API to share files on Windows?

**Comment by Coronon** [comment]
I think there is no such thing as 'native sharing' under windows. All I could think of is this feature: 
![image](https://user-images.githubusercontent.com/33808743/126413258-b66c0e93-f2cf-4eff-b438-5f73e6f0faf3.png)

When you click 'Share' this will allow you to share any file with around 3-4 apps: FeedbackHub, Snip & Sketch, Mail and (at least for me) OneNote. I don't think anyone actually uses this. I literally just discovered this 'feature' when looking for some native sharing ^^

**Comment by alexmercerind** [comment]
I may implement this.

**Comment by Coronon** [comment]
> I may implement this.

I think there is a general discussion at the moment if it even makes sense to support sharing on non-mobile platforms as pretty much no one uses those native ‘features’.

But I don’t want to stop you - go ahead :)

**Comment by alexmercerind** [comment]
> I think there is a general discussion at the moment if it even makes sense to support sharing on non-mobile platforms as pretty much no one uses those native ‘features’ (at least as far as I can tell).

Recently Windows 11 has given developers the ability to list their "non-Windows-Store" apps into this share menu aswell.
**Reference**: [Windows Developers | Extending the Context Menu and Share Dialog in Windows 11](https://blogs.windows.com/windowsdeveloper/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/)

Maybe we can see better apps being mentioned in this dialog soon (how about Flutter ones 😄)? We have a UWP WhatsApp in the store too. But still, it's kind of redundant.

**Comment by Coronon** [comment]
I didn’t know about that (maybe because I despise the new Windows look and feel? ^^).

If you can get it running that would sure be a nice addition 👍🏻 Maybe even have a look if you can implement the `WithResult` variant (you can ask me if you have any questions regarding that) :)
