### ISSUE TITLE
[Bug]: sharePositionOrigin crash although a valid Rect is being used

### ISSUE THREAD

**Issue by kaciula** [fluttercommunity/plus_plugins#3338]
### Platform

iPadOS 17.6.1, macOS 18

### Plugin

share_plus

### Version

10.1.0

### Flutter SDK

3.24.2

### Steps to reproduce

I'm getting crash reports but I cannot reproduce it on my own. It works correctly on the iPad simulators. The sharePositionOrigin Rect that I am sending is within bounds (as you can see in the error messages) but the error happens nonetheless. 

Here are some examples of errors:

MethodChannelShare.shareXFiles:

PlatformException(error, sharePositionOrigin: argument must be set, {{222, 739}, {300, 92}} must be non-zero and within coordinate space of source view: {{0, 0}, {1133, 744}}, null, null)

MethodChannelShare.shareFilesWithResult:

PlatformException(error, sharePositionOrigin: argument must be set, {{362, 701}, {300, 92}} must be non-zero and within coordinate space of source view: {{0, 0}, {1024, 768}}, null, null)

### Code Sample

```dart
// This is how I am computing the sharePositionOrigin Rect

final RenderBox? box = context.findRenderObject() as RenderBox?;
final Rect sharePositionOrigin = box!.localToGlobal(Offset.zero) & box.size;
```

### Logs

```shell
--
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-RO)
    • Flutter version 3.24.2 on channel stable at /Users/ka/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (8 weeks ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ka/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
I think the problem is that 701 + 92 > 768, so `CGRectContainsRect` will return false and so throw the exception.

**Comment by kaciula** [comment]
@miquelbeltran I was assuming the coordinates from the error log were the corners of the Rect.

Any suggestion for a better way to get a valid sharePositionOrigin? I'd prefer not to give a static Rect in the middle of the screen but a Rect close to the widget that was clicked.

**Comment by miquelbeltran** [comment]
>  I'd prefer not to give a static Rect in the middle of the screen but a Rect close to the widget that was clicked.

I think wrapping the target widget with a builder and obtaining the coordinates from the inmediate render object, just like the example project.

**Comment by kaciula** [comment]
> I think wrapping the target widget with a builder and obtaining the coordinates from the inmediate render object, just like the example project.

This is what I am currently doing (wrapping with a Builder) but I get the crash reports so it seems this approach does not work in all cases.

**Comment by miquelbeltran** [comment]
1024 x 768 (which was is reported as the controller.view in the iOS obj-c code) look like iPad mini & 2nd Gen iPads. Can you try your app on a simulator for those smaller devices?

**Comment by kaciula** [comment]
@miquelbeltran I have managed to reproduce this by placing the share button in a scroll view at the edge of the screen.

I've updated the code that computes the sharePositionOrigin to fall back to a rectangle in the middle of the screen if the computed rectangle does not fit the available screen.

```
Rect sharePositionOrigin(BuildContext context) {
  final RenderBox? box = context.findRenderObject() as RenderBox?;
  final Rect candidatePositionOrigin =
      (box!.localToGlobal(Offset.zero) & box.size);
  final double width = MediaQuery.sizeOf(context).width;
  final double height = MediaQuery.sizeOf(context).height;
  if (candidatePositionOrigin.left >= 0 &&
      candidatePositionOrigin.right < width &&
      candidatePositionOrigin.top >= 0 &&
      candidatePositionOrigin.bottom < height) {
    return candidatePositionOrigin;
  } else {
    return Rect.fromCenter(
      center: Offset(width / 2, height / 2),
      width: 100,
      height: 100,
    );
  }
}
```
