### ISSUE TITLE
[Bug]: Share file to AirDrop returns Success even if the file is not actually sent to someone

### ISSUE THREAD

**Issue by FizbyteSoftware** [fluttercommunity/plus_plugins#3342]
### Platform

Ios

### Plugin

share_plus

### Version

10.1.1

### Flutter SDK

3.24.3

### Steps to reproduce

Sharing any file with method "Share.shareXFiles([XFile(backupFile.path)]);"

Choosing AirDrop, then pressing Done or sliding down to dismiss pane, returns a successful file share, even though no device was chosen to send the file to. 

### Code Sample

```dart
any file sharing
```

### Logs

```shell
don't matter
```

### Flutter Doctor

```shell
some logs
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
It is not a bug. Plugin tracks result status only for the share sheet. Sharing via AirDrop happens in another app which shows its sheet on top of the system's share sheet. There is no tracking of status of the shared file inside other apps. When user clicks `Done` it is considered success. If user dismisses the AirDrop's sheet, the plugin will return dismissed correctly.

**Comment by FizbyteSoftware** [comment]
No,  If user dismisses the AirDrop's sheet, the plugin will return dismissed correctly." is not true, I have this code 
"
final ShareResult result = await Share.shareXFiles([XFile(backupFile.path)]);

      if (result.status == ShareResultStatus.success) {
        emit(state.copyWith(message: () => "Exported"));
      }"

 it's success if you press "Done" or your dismiss the pane by sliding down.

**Comment by vbuberen** [comment]
Read my comment again, because you definitely didn't understand what I wrote.

**Comment by vbuberen** [comment]
> No, "If user dismisses the AirDrop's sheet, the plugin will return dismissed correctly." is not true, I have this code

Yes, I made a mistake there in this part, but the rest stays the same - as soon as selected AirDrop it is considered success, because the data (message or image, etc.) is considered shared and plugin can't track what happens inside the destination app selected for sharing.
