### ISSUE TITLE
Java deprecated API warning

### ISSUE THREAD

**Issue by BillMac4440** [fluttercommunity/plus_plugins#335]
flutter\.pub-cache\hosted\pub.dartlang.org\network_info_plus-1.0.2\android\src\main\java\dev\fluttercommunity\plus\network_info\NetworkInfoPlusPlugin.java uses or overrides a deprecated API.

**Comment by Chinmay-KB** [comment]
From what I understand this is the warning shown due to v1 embedding and if this is done away with, projects created pre flutter version 1.12 and using this plugin will break. I am not sure if this warning can be done away with at this moment.

**Comment by mhadaily** [comment]
close and follow up in #314
