### ISSUE TITLE
[Question]: ITMS-91061: Missing privacy manifest

### ISSUE THREAD

**Issue by prabhjotdunglay** [fluttercommunity/plus_plugins#3359]
### What is your question?

Hi, 

While I was able to upload the app on App Store before 12th November but I was getting a warning on my email. "ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/share_plus.framework/share_plus”, which includes share_plus, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements."

Is there a solution for this so I can update the app as i think it won't allow me anymore to upload without fixing this.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
It seems that you didn't actually search the repo and just checked the checkmark. 

There is no such issue in plugins anymore.
