### ISSUE TITLE
[Bug]: Why does Samsung only retrieve part of the version number?

### ISSUE THREAD

**Issue by Hayolox** [fluttercommunity/plus_plugins#3361]
### Platform

Android 14

### Plugin

device_info_plus 

### Version

11.1.0

### Flutter SDK

3.24.3

### Steps to reproduce

Issue Description
I am developing an application to read the Version Number on Samsung devices. However, I noticed that the application only retrieves part of the data. For example, UP1A.231005.007.A556EXXS5AXI4 is only retrieved up to UP1A.231005.007, while the rest is not included.

Example Case
On a Samsung Galaxy device (e.g., model A556EXXS5AXI4), the full version number appears as:
UP1A.231005.007.A556EXXS5AXI4

But my application only retrieves:
UP1A.231005.007

Steps Taken
1. Ensured the application has all necessary permissions.
2. Used Android's built-in APIs to fetch system information (e.g., Build.VERSION or Settings.System).
3. Tested on non-Samsung devices, and the full data is retrieved correctly.

Questions

1. Is there a limitation on Samsung devices that causes only part of the version number to be retrieved?
2. How can I ensure that my application retrieves the full version number as displayed in the device settings?

### Code Sample

```dart
loadDeviceId() async {
    try {
      if (Platform.isAndroid) {
        _readAndroidBuildData(await deviceInfoPlugin.androidInfo);
      } else if (Platform.isIOS) {
        _readIosDeviceInfo(await deviceInfoPlugin.iosInfo);
      }
    } on PlatformException {
      appLog('Missing platform devices');
    }
  }

_readAndroidBuildData(AndroidDeviceInfo androidDeviceInfo) async {
    appLog('masuk ${androidDeviceInfo.id}');
    Prefs.setDeviceId(androidDeviceInfo.id + Constant.android);
  }
```

### Logs

```shell
UP1A.231005.007
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Dwidasa Iphone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
The `id` property is just reporting what the device manufacturer decided to put on here: https://developer.android.com/reference/android/os/Build#ID

So looks like Samsung is just concatenating the `Build.ID` with the `Build.MODEL` or similar on their settings screen.

Not a plugin bug.

**Comment by Hayolox** [comment]
> he `id` property is just reporting what the device manufacturer decided to put on here: https://developer.android.com/reference/android/os/Build#ID
> 
> So looks like Samsung is just concatenating the `Build.ID` with the `Build.MODEL` or similar on their settings screen.
> 
> Not a plugin bug.

is there any suggestion for uniq device id in flutter?

**Comment by miquelbeltran** [comment]
That would be `serialNumber` not `id`:

https://github.com/fluttercommunity/plus_plugins/blob/2d69758d86346203a37dabf876a7bb9862c1e553/packages/device_info_plus/device_info_plus/lib/src/model/android_device_info.dart#L134-L138

Read the documentation, as it has special requirements.

There is also https://pub.dev/packages/android_id which requires special permissions.

**Comment by Hayolox** [comment]
> That would be `serialNumber` not `id`:
> 
> https://github.com/fluttercommunity/plus_plugins/blob/2d69758d86346203a37dabf876a7bb9862c1e553/packages/device_info_plus/device_info_plus/lib/src/model/android_device_info.dart#L134-L138
> 
> Read the documentation, as it has special requirements.
> 
> There is also https://pub.dev/packages/android_id which requires special permissions.

when use serialNumber, result : unknown

**Comment by miquelbeltran** [comment]
Read the documentation before complaining: https://developer.android.com/reference/android/os/Build#getSerial()
