### ISSUE TITLE
[Request]: Update the minimum version configuration.

### ISSUE THREAD

**Issue by StanleyCocos** [fluttercommunity/plus_plugins#3366]
### Plugin

device_info_plus

### Use case

The current documentation and the minimum version of the plugin are incorrect and cannot run. I have submitted multiple update requests.

PR:

- device_info_plus: https://github.com/fluttercommunity/plus_plugins/pull/3362
- battery_plus: https://github.com/fluttercommunity/plus_plugins/pull/3364
- share_plus: https://github.com/fluttercommunity/plus_plugins/pull/3363
- device_info_plus: https://github.com/fluttercommunity/plus_plugins/pull/3362

### Proposal

Update to the correct configuration.

**Comment by vbuberen** [comment]
Thanks for opening and especially thanks for opening PRs right away. I will take a look a bit later today.
