### ISSUE TITLE
[Request]: Add CPU architecture to Windows device info

### ISSUE THREAD

**Issue by anayw2001** [fluttercommunity/plus_plugins#3367]
### Plugin

device_info_plus

### Use case

We were looking into adding architecture information for crash reports and plan to use this plugin.

### Proposal

I'd like the plugin to determine the CPU architecture of the host PC at runtime.

**Comment by miquelbeltran** [comment]
You can get that information directly from Dart, basically calling `Abi.current().toString()`

**Comment by anayw2001** [comment]
Hi Miquel, we unfortunately run x64 code on arm64, and we'd like to distinguish between the two in crash reports, so that is why we need the information at runtime.

**Comment by miquelbeltran** [comment]
> Hi Miquel, we unfortunately run x64 code on arm64, and we'd like to distinguish between the two in crash reports, so that is why we need the information at runtime.

Oh, I didn't realize you were preparing a PR as well.

Have you checked `Abi.current()`? 

The Dart team is also working on exposing the CPU architecture in https://github.com/dart-lang/sdk/pull/56959 so that could help.

In all cases, thanks for the contribution.
