### ISSUE TITLE
[Question]: [Bug]: 'BlueStacks' emulator is detected as physical device with `AndroidDeviceInfo.isPhysicalDevice`

### ISSUE THREAD

**Issue by naw2nd** [fluttercommunity/plus_plugins#3378]
### What is your question?

Here's my code for detecting if my apps run on a real device or emulator. 
 
 ```
 Future<bool> isRealDevice() async {
    try {
      if (Platform.isAndroid) {
        AndroidDeviceInfo androidDeviceInfo =
            await deviceInfoPlugin.androidInfo;
        return androidDeviceInfo.isPhysicalDevice;
      }
      if (Platform.isIOS) {
        IosDeviceInfo iosDeviceInfo = await deviceInfoPlugin.iosInfo;
        return iosDeviceInfo.isPhysicalDevice;
      }
      return false;
    } catch (e) {
      return false;
    }
  }
```

When I'm using Android Studio Emulator it is successfully detected as not a real device.
But when I tested it on BlueStacks emulator, it was detected as a real device (not emulated, as it should be).

it also happens in MEmu emulator (it was detected as a real device).

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Thanks for your report. On Android the detection of emulator devices is done manually by checking a combination of values in the `Build` class: https://github.com/fluttercommunity/plus_plugins/blob/40f9c42138bf1c80e6283f46e12109a0e66c0816/packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt#L95

Could I ask you to run `device_info_plus` example app on both of mentioned emulators and share outputs (screenshots or text, doesn't matter) here? Would like to update the list of variables indicating emulators.

**Comment by naw2nd** [comment]
This is screeshots from the example app (Build with latest flutter stable version 3.24.5) run on BlueStacks
![image](https://github.com/user-attachments/assets/aef38c57-4597-4c9f-9a34-7b3401dc71c1)
![image](https://github.com/user-attachments/assets/49d1bd59-5ee9-411c-b886-45459356da59)
**isPhysicalDevice = true**


This is screeshots from the example app run on Memu Play 9
![image](https://github.com/user-attachments/assets/b0dee631-bed5-41a4-8358-9f4d4807d23e)
![image](https://github.com/user-attachments/assets/df216212-a0f9-4273-b24c-a455f8c17670)
**isPhysicalDevice = true**

**Comment by miquelbeltran** [comment]
Basically this emulator is "faking" being a real device by providing fake data, this isn't really a bug in the plugin but a problem with your emulator who is providing fake data in the `Build` class.

**Comment by vbuberen** [comment]
Indeed. Looks like these companies do this on purpose to avoid checks in some apps.

**Comment by naw2nd** [comment]
My apps want to restrict users from using emulators because they can change their location to anywhere else on the map, and it's not detected as a mocked location. But when using those two emulators, it's not detected as an emulated device. Is there any other solution to this?

**Comment by miquelbeltran** [comment]
This is a problem that goes beyond the capacity of the plus plugins to solve.

My recommendation is probably to look for commercial anti-fraud libraries for Android and integrate them in your project.
