### ISSUE TITLE
[Question]: [network_info_plus] Error getting WiFi name in background mode.

### ISSUE THREAD

**Issue by alextran1502** [fluttercommunity/plus_plugins#3379]
### What is your question?

Hello,

I am trying to get WiFi when the app is in the background and run into the following error message.

```
flutter: MissingPluginException(No implementation found for method wifiName on channel dev.fluttercommunity.plus/network_info)
```

When the app is in the foreground, I can get the WiFi name without issues.

Here is my info.plist related content

```
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>We require this permission to access the local WiFi name for background upload mechanism</string>
	<key>NSLocationUsageDescription</key>
	<string>We require this permission to access the local WiFi name</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>We require this permission to access the local WiFi name</string>
```

Here is a screenshot of the app's capability in XCode

<img width="579" alt="image" src="https://github.com/user-attachments/assets/2317d6ad-0f35-454f-b444-e2488a440334">

Here is a screenshot of related content in the Podfile

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/9c6e70af-bd6d-48ea-8058-e9b6af5301fc">

I have set the Location permission to `Always` for the app

I have tried running `flutter clean`, `flutter pub get`, and rebuilding as well as uninstall and reinstall the app, but the issue is still there.

If someone got any pointer to get this run in iOS background mode, I'd greatly appreciate

Thanks,
Alex

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
> flutter: MissingPluginException(No implementation found for method wifiName on channel dev.fluttercommunity.plus/network_info)

This means that the flutter code cannot access the native code (i.e. method channel), has nothing to do with permissions.
There is something broken in your project, like having the wrong "pod" installed or similar.

**Comment by alextran1502** [comment]
Hmm, I've tried to rebuild the project, clear the pod files...etc. 

On Android, this operation runs fine in background mode, but not on iOS. 

Do you have any thoughts?

**Comment by alextran1502** [comment]
Ah, of course I forgot to register the plugin in the AppDelegate.swift file

```swift
      if !registry.hasPlugin("org.cocoapods.network-info-plus") {
        FPPNetworkInfoPlusPlugin.register(with: registry.registrar(forPlugin: "org.cocoapods.network-info-plus")!)
      }
```
