### ISSUE TITLE
Share different content depending on the target app

### ISSUE THREAD

**Issue by rocboronat** [fluttercommunity/plus_plugins#338]
## Use case

We want to share a different content depending on the app the user selects. For example, if the user chooses Twitter, we will share a landscape image. If the user selects Instagram Feed, we will share a square image. And if the user chooses Instagram Stories, a portrait image. And, in the rest of the cases, a regular square image.
## Proposal

We need to be able to tell the package-specific cases in addition to the generic ones. Something like my friend @alorma did [in this gist](https://gist.github.com/alorma/eb8d5c340c33c69ee0cfb941fe1f04f3).

**Comment by Chinmay-KB** [comment]
I think for implementing this, we can have 2 types of content, one specific to an app and another as a fallback for sharing on any other app. For the custom content, we can pass the package name for this that should be shared. I can think of this for android at least, no idea about the others :/

**Comment by rocboronat** [comment]
Totally agree :·) Oh, but the custom intent needs the package name but also the activity. For example, the Instagram package offers three Activities to receive shared data: Stories, the Feed, and Direct messages. Twitter does something similar.

**Comment by aytunch** [comment]
@rocboronat I like your proposal to differentiate between the possible share locations and curate our data accordingly. 

Do we at the moment have any way to customize the share dialog in terms of which apps to show and hide? Or can we programmatically understand which apps are installed and enabled for sharing in the users phone?

What I mean is I only want my users to share through Instagram (only story, not direct or feed) and whatsapp and no other 3rd party app. Is there a way to manage this? I believe the OS decides the options according to the file type so I am not too optimistic.

**Comment by alorma** [comment]
Hi @aytunch 

If you check the gist that @rocboronat mentions, there's a way to do that:

https://gist.github.com/alorma/eb8d5c340c33c69ee0cfb941fe1f04f3#file-intents-kt-L9

This will show an intent dialog with only `Intent.EXTRA_INITIAL_INTENTS, intents.toTypedArray()` intents...

**Comment by aytunch** [comment]
Hi @alorma 
I saw your gist with the telegram and whatsapp examples. But I think it is written in Kotlin and only for Android right? Is there a way to do this platform independent? at least for iOS and Android at the same time?

I just want my mp4 file cached videos to be shared through instagram stories and whatsapp in both iOS and Android.

**Comment by rocboronat** [comment]
Hello @aytunch ! I think your request is not exatly the same this issue talks about. So please, move your request into a new issue to avoid adding noise to this one. Thanks a lot 😊

**Comment by aytunch** [comment]
@rocboronat I created a new issue: https://github.com/fluttercommunity/plus_plugins/issues/379

**Comment by rocboronat** [comment]
@aytunch now I see that the issue you created is not the same behavior this PR request 😅

The idea is to share a story sized image in case the user chooses to share with Instagram Stories, a landscape one in case the user shares with Twitter... on Android, that's supported.

**Comment by miquelbeltran** [comment]
Hi all, we get requests asking for "share" mechanisms that target specific apps. 

The aim of the `share_plus` package is to provide a common interface to interact with the standard share functionality.

Implementing a plugin that uses "intents" crafted to target different apps would be out of scope of the share plugin, and would require building a new plugin from scratch, so unfortunately that's out of scope for the share plus plugin.

You can as well try to accomplish that goal on Android with the `android_intent_plus` package.
