### ISSUE TITLE
[Question]: Unhandled Exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by niikocap** [fluttercommunity/plus_plugins#3384]
### What is your question?

All works before the suddenly this pops up i updated device info plus and still the same

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [x] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by StanleyCocos** [comment]
I suggest you provide a more detailed description, such as which plugin you’re using and what actions you took. It would be best to include a minimal, reproducible example of the issue, so that the maintainers can quickly investigate the problem.

**Comment by miquelbeltran** [comment]
@niikocap device info plus on web? may be a duplicate or related to this one: https://github.com/fluttercommunity/plus_plugins/issues/3391

**Comment by niikocap** [comment]
Thank you for the concern and replies, btw the fix for this was to update the library.
