### ISSUE TITLE
[Bug]: IMU samplingPeriod has no effect on Android

### ISSUE THREAD

**Issue by eidolonFIRE** [fluttercommunity/plus_plugins#3393]
### Platform

Android 14

### Plugin

sensors_plus

### Version

6.1.0

### Flutter SDK

3.24.5

### Steps to reproduce

Initiate IMU service via the example code.
The `samplingPeriod` parameter has no effect an Android, but does on iOS.
Instead it seems to default to ~100-120hz. Possibly UI refresh rate? Or maybe just the shortest interval allowed?

### Code Sample

```dart
(Use provided example code)
```

### Logs

```shell
-
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.22631.4602], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.8.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[!] Android Studio (version 2022.1)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.94.2)
[√] Connected device (4 available)
[√] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
This is explained in the readme, do not create tickets before reading the documentation and don't check the "I read the readme" checkbox if you didn't.

![Screenshot_20241212-081121.png](https://github.com/user-attachments/assets/dfc992a6-417c-49bd-b9e1-8f82a9080aa5)
