### ISSUE TITLE
[Question]: device_info_plus has ITMS-91061: Missing privacy manifest  trouble

### ISSUE THREAD

**Issue by CHEN031226** [fluttercommunity/plus_plugins#3399]
### What is your question?

ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/device_info_plus.framework/device_info_plus”, which includes device_info_plus, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting February 12, 2025, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
You didn't specify the platform or package version, but I assume you refer to macos? In that case, related to https://github.com/fluttercommunity/plus_plugins/issues/3397

Like mentioned there, the package has the privacy manifest in it, so we have no idea why Apple doesn't accept it.

**Comment by miquelbeltran** [comment]
Check the changelog, the privacy manifest was added back in version 10: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/CHANGELOG.md

You need to upgrade the dependency
