### ISSUE TITLE
[Request]: Request to Add widthPx and heightPx in AndroidDisplayMetrics

### ISSUE THREAD

**Issue by SasikumarSf4252** [fluttercommunity/plus_plugins#3407]
### Plugin

device_info_plus

### Use case

It identifies the device's screen resolution(width, height) and helps modify the UI based on screen size.

### Proposal

The values mentioned above were previously available in the device_info_plus package up to version 9.1.1. However, they have been manually removed in later updates, and no alternative values are provided. These values are essential for my application. Could you consider re-adding them in an upcoming release, since they are critical for my use case?

Thank you!

**Comment by miquelbeltran** [comment]
Hello, sorry but this won't happen, we already discussed why here: https://github.com/fluttercommunity/plus_plugins/issues/2687 and here https://github.com/fluttercommunity/plus_plugins/pull/2731
