### ISSUE TITLE
Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by daviinjuguna** [fluttercommunity/plus_plugins#341]
## System info

Issue occurs on: iOS / Android / both
Plugin name:
Plugin version:
Flutter doctor output:

```
paste it here...
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by tungakanui** [comment]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_plus-1.0.4\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':connectivity_plus'.
> Could not get unknown property 'javaToolchains' for task ':app:compileDebugAndroidTestJavaWithJavac' of type com.android.build.gradle.tasks.AndroidJavaCompile.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 346

* What went wrong:
A problem occurred configuring project ':connectivity_plus'.
> Could not get unknown property 'android' for project ':connectivity_plus' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by tungakanui** [comment]
When I re-install Flutter, i can't compile this project

**Comment by renehw** [comment]
same problem here

**Comment by tungakanui** [comment]
> same problem here

I resolved this problem by downgrade vesion of connectivity

**Comment by renehw** [comment]
Which version did you use?

**Comment by tungakanui** [comment]
![image](https://user-images.githubusercontent.com/54916679/124510970-2d385e80-ddff-11eb-8251-cbd7d057a50a.png)


> Which version did you use?

**Comment by renehw** [comment]
Thanks, I decided to go back to using the versions compatible with version 2.7.0 of the SDK. However I found another solution if you want to use the latest versions. Here: [https://github.com/fluttercommunity/plus_plugins/issues/321](url)

**Comment by tungakanui** [comment]
oh thanks a lot.

**Comment by mhadaily** [comment]
@tungakanui does this https://github.com/fluttercommunity/plus_plugins/issues/321 have fixed your issue?

**Comment by octokim** [comment]
Seems like [this commit](https://github.com/fluttercommunity/plus_plugins/commit/b94d387d40ce4ee1749855d5b126114622ccbe35#diff-c79ab031ddc71a7cdc5d327ef86ce163cab97c3d8086d139de9bc04169ced29b) broke the lib.

**Comment by mhadaily** [comment]
Feel free to use version `1.0.5` if still you face any issue, please report back otherwise, please close this issue.

**Comment by dipinsonwani** [comment]
I am facing the same issue again, 
version -latest 6.0.5

Compilation Error - 

* What went wrong:
Execution failed for task ':connectivity_plus:compileReleaseJavaWithJavac'.
> error: invalid source release: 17


[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /Users/dipinsonwani/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/dipinsonwani/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0
    
    
   While using command- flutter build apk

**Comment by mrsrmn** [comment]
Same with 6.0.5

**Comment by miquelbeltran** [comment]
Take a look at #3303

**Comment by mrsrmn** [comment]
> Take a look at #3303

Thank you! This was very helpful :)
