### ISSUE TITLE
Showing wrong subject when share pdf through gmail in ios

### ISSUE THREAD

**Issue by soanpr123** [fluttercommunity/plus_plugins#346]
when share pdf through android it work perfect but when share pdf through gmail in ios it show subject same as text we passed but it should show title as subject.

**Comment by gbaccetta** [comment]
This is a Gmail issue, not related to this plugin. If you still encounter it and need a workaround, see my answer here: https://github.com/fluttercommunity/plus_plugins/issues/1056#issuecomment-1716352726
