### ISSUE TITLE
[Share_Plus] Showing wrong subject when share pdf through gmail in ios

### ISSUE THREAD

**Issue by soanpr123** [fluttercommunity/plus_plugins#347]
when share pdf through android it work perfect but when share pdf through gmail in ios it show subject same as text we passed but it should show title as subject.

**Comment by mhadaily** [comment]
Can you please share which version are you using? + flutter doctor + your ios Version? are you running on a real device?

**Comment by soanpr123** [comment]
Hi. forgive me for not being able to capture flutter doctor as i don't have my mac here.  i am using flutter version 1.22.6, ios version is 14.6 and real device, share_plus version is using 1.2.  but i am getting error content displayed in header on google gmail app when running on ios device.  on android it works fine and without this error.





> Can you please share which version are you using? + flutter doctor + your ios Version? are you running on a real device?

**Comment by soanpr123** [comment]
> Can you please share which version are you using? + flutter doctor + your ios Version? are you running on a real device?

this is the problem i get when sharing through google gmail app
![Uploading 38942F46-D532-4092-91DA-0EE13A29695A.png…]()

**Comment by soanpr123** [comment]
![7164227B-96E4-4792-A8E4-9DAEEA3D1D4D](https://user-images.githubusercontent.com/44558413/124642205-c926a080-deb9-11eb-9b70-33aa853deabe.png)

this is the problem i get when sharing through google gmail app


> Can you please share which version are you using? + flutter doctor + your ios Version? are you running on a real device?

**Comment by pszklarska** [comment]
Hey,

I get the same issue. It occurs when sharing text on iOS with the Gmail app. The subject is the same as the shared text, so for example with the following code:

```
Share.share('Shared text', subject: 'Subject');
```

The result on iOS using Gmail app is incorrect ("Shared text" is in the subject):

![IMG_0013](https://user-images.githubusercontent.com/8558760/133369653-73786fc2-6d06-4da5-b15d-35e8ecba4927.png)


The result on iOS using the default Mail app is correct ("Subject" is in the subject)

![IMG_0012](https://user-images.githubusercontent.com/8558760/133369657-a1b0d663-5db7-485d-a189-9bc111750e1f.PNG)


Running on a physical device (confirmed on iPhone 7, 8 and SE, iOS 13.3.1 and 14.0.1)
```
share_plus: ^2.1.4
```

flutter doctor -v
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.5.2 20G95 darwin-x64, locale
    en-AU)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] IntelliJ IDEA Community Edition (version 2020.1.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (4 available)
```

**Comment by kjawadDeveloper1** [comment]
Any update on this ?

**Comment by markzhong88** [comment]
need update on this, otherwise have to choose flutter_share

**Comment by mhadaily** [comment]
We have released a new version, please check it out and let us know if you still have this issue.

**Comment by markzhong88** [comment]
> We have released a new version, please check it out and let us know if you still have this issue.

Just upgrade to latest version 4.0.3 and still see the same email title and body in gmail app...

**Comment by samleecampspot** [comment]
Are there any updates here?  I just ran into this issue on iOS - Gmail app.

**Comment by jocgomez** [comment]
The problem persist in outlook too.

**Comment by shahbazhashmi** [comment]
Any update on this? It is happening with `share_plus: ^7.1.0` as well.

**Comment by CanaanMack** [comment]
I ran into this issue recently and I've been trying to find the exact cause.
But just this morning, it started working on a version of my code that hadn't been changed since I first ran into it.

It looks like Gmail had an update recently.

Can anyone else confirm if the subject is getting populated on the latest version of Gmail, without changes to the application?
