### ISSUE TITLE
Unable to add image to send to WhatsApp

### ISSUE THREAD

**Issue by Jayvd** [fluttercommunity/plus_plugins#360]
```

      AndroidIntent intent = AndroidIntent(
          action: 'action_view',
          data: "Text to Send",
          package: "com.whatsapp");

      intent.launch();
```

This only sends text, is it possible to add image along with the text please? Sorry for the question.

THANK YOU

**Comment by miquelbeltran** [comment]
There's already two issues asking the same, please search for "WhatsApp" on the issue tracker.

Link: https://github.com/fluttercommunity/plus_plugins/issues/261

**Comment by miquelbeltran** [comment]
You can use share_plus to send images. But you cannot send text AND image with share_plus, seems to be a limitation on WhatsApp and some other apps. Please next time use the search function as similar questions have been asked before: https://github.com/fluttercommunity/plus_plugins/issues/261

**Comment by AbodiSadiqGitHub** [comment]
I WANT TO SEND TO GROUP IN WHATSAPP, PLEASE.
'https://chat.whatsapp.com/JiATE6rTObME5UXacTIfcw' this is a group link,
message is 'hello',
how can i do?
THANKS ALOOT!
