### ISSUE TITLE
[share_plus] Share.shareFiles with multiple mp3s fails using the text parameter

### ISSUE THREAD

**Issue by mchlsndrn** [fluttercommunity/plus_plugins#362]
The issue was tested on a Android emulator - PIXEL 3 API 30 (Google Play).
I'm using share_plus: ^2.1.4.

```
const String STR_SHARE_SUBJECT = "Listen this!";
const String STR_SHARE_TEXT = "Audio files generated using $STR_APP_NAME.";

    List<String> filepaths = [];

    // [snip] add some files to filepaths here ...

    Share.shareFiles(
      filepaths,
      subject: STR_SHARE_SUBJECT,
      text: STR_SHARE_TEXT, // <---- throws exception only when "filePaths" contains multiple entries (as a workaround I'm not using text at the moment)
    );
```

> W/Bundle  ( 8645): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
> W/Bundle  ( 8645): Attempt to cast generated internal exception:
> W/Bundle  ( 8645): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
> W/Bundle  ( 8645): 	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1343)
> W/Bundle  ( 8645): 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1145)
> W/Bundle  ( 8645): 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:8364)
> W/Bundle  ( 8645): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:11345)
> W/Bundle  ( 8645): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:11308)
> W/Bundle  ( 8645): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1721)
> W/Bundle  ( 8645): 	at android.app.Activity.startActivityForResult(Activity.java:5320)
> W/Bundle  ( 8645): 	at android.app.Activity.startActivityForResult(Activity.java:5278)
> W/Bundle  ( 8645): 	at android.app.Activity.startActivity(Activity.java:5664)
> W/Bundle  ( 8645): 	at android.app.Activity.startActivity(Activity.java:5617)
> W/Bundle  ( 8645): 	at dev.fluttercommunity.plus.share.Share.startActivity(Share.java:114)

**Comment by mhadaily** [comment]
possible duplication https://github.com/fluttercommunity/plus_plugins/issues/176

**Comment by Boehrsi** [comment]
@mchlsndrn does the actual sharing works beside the thrown exception? I just tested it with the same emulator configuration and I can confirm the exception, but it's silent and the sharing itself works fine for me. More context can be found here https://github.com/fluttercommunity/plus_plugins/issues/176
