### ISSUE TITLE
Detect Connectivity problem 

### ISSUE THREAD

**Issue by hasanm08** [fluttercommunity/plus_plugins#366]
this package can not detect usb/bluetooth tethering as a connection

**Comment by mhadaily** [comment]
can you please let us know which version of this package you are using?

**Comment by hasanm08** [comment]
connectivity_plus: ^1.0.5

**Comment by Elias8** [comment]
Hi @hasanm08 👋,

Could you please confirm if you are still having this issue? If so, what platform are you having the issue on?

**Comment by hasanm08** [comment]
Hi, with Wich Version Should I try again? I had that problem on android 11 and connectivity_plus: ^1.0.5

**Comment by Elias8** [comment]
After looking at the latest version, the package has no support for USB/Bluetooth network type. 

Please stay tuned for the upcoming updates!
