### ISSUE TITLE
[sensors_plus]: Addition of Magnetometer

### ISSUE THREAD

**Issue by ritvij14** [fluttercommunity/plus_plugins#370]
## Use case
https://source.android.com/devices/sensors/sensor-types#magnetic_field_sensor
It would be a great addition to the sensors_plus package if we can have more kinds of sensors. We should add functionality to access the magnetic field sensor.

## Proposal
I would like to work on adding functionality to use this sensor through this package. It would be great if someone could list out all things that need to be added to the code other than the functionality (documentation, etc.) and I will add those too.

**Comment by ritvij14** [comment]
I would like to work on this.

**Comment by mhadaily** [comment]
Perfect, PR is welcome.

**Comment by Zabadam** [comment]
I have prepared an update that adds `MagnetometerEvent` class and `magnetometerEvents` stream.

Although I have not used Dart for web nor ever used Swift, the API was pretty straightforward.

Furthermore I have not contributed to a project of this scale before, so kindly guide me if I do something incorrectly.

Expect PR shortly.
