### ISSUE TITLE
[ShareSheet] connection invalidated

### ISSUE THREAD

**Issue by bakboem** [fluttercommunity/plus_plugins#372]
Unable to share after getting the picture at the bottom sheet.

**Comment by mhadaily** [comment]
Can you please elaborate more, if possible, please help us to reproduce it or give us a repo that can simply reproduce the error. Please also provide more information about your package version, flutter version, and so on.

**Comment by burakcbdn** [comment]
Same here on iOS when sharing file

**Comment by aloisdeniel** [comment]
I get the same error by simply running  this with a path pointing to a video file in application Document directory : 

```
return Share.shareFiles(
      [message.path],
    );
```

I'm running the app on an iPad.
