### ISSUE TITLE
[Share_Plus] Cannot share MP4 files via Airdrop, Mail, etc on iPhone

### ISSUE THREAD

**Issue by jackmchristie** [fluttercommunity/plus_plugins#375]
When I try to share MP4 files via AirDrop, I get the following console output: 
`[default] Failed to ssue sandbox token for URL: 'file:///var/mobile/Media/DCIM/100APPLE/IMG_0216.MP4' with error: 'Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Cannot issue a sandbox extension for file "/var/mobile/Media/DCIM/100APPLE/IMG_0216.MP4": Operation not permitted}'`

When I try to share MP4 files via Mail, I get the following console output: 
`[ShareSheet] canShareURLThroughMail returning NO. Reason: Failed to issue sandbox extension for /var/mobile/Media/DCIM/100APPLE/IMG_0216.MP4 with error 1.`

I also am having issues sharing with every other method except to Messages. When I try to share via Messages it works perfectly.

Any advice on this issue? Is it a bug? The fact that it is working for Messages, but nothing else leads me to believe that I am giving it the right permissions and filepath structure.

**Comment by jackmchristie** [comment]
I'm still running into this issue, but everything is working fine on the iOS simulator. Still looking into help for solving this issue.

**Comment by BLKKKBVSIK** [comment]
@jackmchristie Are you still running into this issue?
It seems that I can't reproduce it.

**Comment by BLKKKBVSIK** [comment]
@jackmchristie Hi.
Do you still encounter this issue? 
I can't reproduce it.
