### ISSUE TITLE
not calling callback

### ISSUE THREAD

**Issue by prabhunath111** [fluttercommunity/plus_plugins#378]
Future<void> beforePrintHello() async {
    print("Line253");
    final int helloAlarmID = 0;
    print("Line255");
    await AndroidAlarmManager.initialize();
    print("Line257");
    await AndroidAlarmManager.periodic(
      const Duration(seconds: 3),
      helloAlarmID,
      printHello,
    );
  }
void printHello() {
    print("Line246");
    final DateTime now = DateTime.now();
    final int isolateId = Isolate.current.hashCode;
    print(
        "Line240 [$now] Hello, world! isolate=${isolateId} function='$printHello'");
  }

**Comment by Elias8** [comment]
Hello @prabhunath111 👋,

Thanks for opening an issue.

Have you followed the steps from the documentation [here](https://pub.dev/packages/android_alarm_manager_plus)? You have to add some configurations to the native platforms, as mentioned in the documentation. 

Otherwise, it would be helpful if you share a link to your repository as this is not enough code to reproduce the issue you are having.

Hope that helps!

**Comment by Chinmay-KB** [comment]
Is the `printHello()` function a top level function? It won't work if it isn't.

**Comment by rulim34** [comment]
My callback also doesn't work.
Here is my code repo: https://github.com/rulim34/restologue_flutter

<details>
  <summary>Flutter Doctor</summary>

    [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.132], locale id-ID)
        • Flutter version 2.2.3 at C:\Users\Rulim\AppData\Local\Programs\Flutter\flutter
        • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
        • Engine revision 241c87ad80
        • Dart version 2.13.4
    
    [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
        • Android SDK at C:\Users\Rulim\AppData\Local\Android\sdk
        • Platform android-30, build-tools 30.0.3
        • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
        • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
        • All Android licenses accepted.
    
    [√] Chrome - develop for the web
        • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
    
    [√] Android Studio (version 4.1.0)
        • Android Studio at C:\Program Files\Android\Android Studio
        • Flutter plugin can be installed from:
           https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
           https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    
    [√] IntelliJ IDEA Community Edition (version 2021.2)
        • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition
        • Flutter plugin version 59.0.4
        • Dart plugin version 212.4746.57
    
    [√] VS Code (version 1.59.0)
        • VS Code at C:\Users\Rulim\AppData\Local\Programs\Microsoft VS Code
        • Flutter extension version 3.25.0
    
    [√] Connected device (3 available)
        • Redmi 5A (mobile) • f1aed3be7d05 • android-arm64  • Android 10 (API 29)
        • Chrome (web)      • chrome       • web-javascript • Google Chrome 92.0.4515.159
        • Edge (web)        • edge         • web-javascript • Microsoft Edge 92.0.902.67
    
    • No issues found!
</details>

**Comment by rulim34** [comment]
> My callback also doesn't work.
> Here is my code repo: https://github.com/rulim34/restologue_flutter
> 
> Flutter Doctor

Problem solved. I think you have to mention that the callback should be static function clearly on the doc.
