### ISSUE TITLE
[share_plus] [iOS] Instagram story does not show up in iOS while sharing video file

### ISSUE THREAD

**Issue by aytunch** [fluttercommunity/plus_plugins#380]
On iOS I can only see one Instagram icon and it is for sharing the video as a standard Instagram Post. 
On the other hand, in Android sharing a video file shows up all 3 options:

1. Instagram Feed
2. Instagram Direct
3. Instagram Story

I tried removing `text` and `mimeTypes` but there is no difference.
```
            await Share.shareFiles(
              [outputVideoPath],
              mimeTypes: ["video/mp4"],
              text: "Share: ${videoModel.title}",
            );
```

I looked at other plugins and they show Instagram story sharing icons however they only allow images as content.

**Comment by BLKKKBVSIK** [comment]
Hi, @aytunch.

Do you still encounter the issue?
I can't reproduce.

Linked video of my try:
https://youtu.be/7y7OJsGqLG8

**Comment by aytunch** [comment]
Hi @BLKKKBVSIK thanks for the great yt video you provided. Looking at it, I guess `share_plus` implemented this feature for iOS.
I implemented my own plugin for iOS and I am using it currently.
https://github.com/aytunch/instagram_video_story_share
