### ISSUE TITLE
connectivity_plus always showing ConnectivityResult.wifi on web, even when WiFI is switched off

### ISSUE THREAD

**Issue by rahatbs23** [fluttercommunity/plus_plugins#383]
## System info

Issue occurs on: Web
Plugin name: connectivity_plus
Plugin version: 1.0.6

## Steps to Reproduce

Running on Chrome browser, when connectivity state changes (I toggle Wifi), `onConnectivityChanged()` get called every time, but the enum value of ConnectivityResult always returns `ConnectivityResult.wifi`.

I tested the same in android, it works fine (shows `ConnectivityResult.none` while WiFI is turned off)

**Comment by daniellampl** [comment]
I agree with you. It doesn't matter if you are connected to wifi or not, it always returns `ConnectivityResult.wifi`

**Comment by danieldoddjr** [comment]
Same issue here.

**Comment by jpnurmi** [comment]
What does the live output print?

https://googlechrome.github.io/samples/network-information/

**Comment by jpnurmi** [comment]
I'm not sure why [`NetworkInformation.effectiveType`](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/effectiveType) is preferred over [`NetworkInformation.type`](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/type), and why `4g` is considered as... WiFi :eyes:

https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus_web/lib/src/utils/connectivity_result.dart
