### ISSUE TITLE
Null check operator used on a new value

### ISSUE THREAD

**Issue by henriqueArrazao** [fluttercommunity/plus_plugins#390]
![image](https://user-images.githubusercontent.com/65516006/127748669-26766804-73cf-4a5c-9e79-0279d766f4ac.png)

It just does not make any sense, does anyone have any idea what might be going on?

**Comment by DennisKragekjaer** [comment]
Same problem here actually

**Comment by mhadaily** [comment]
Can you please let us know which version of the package are you using?

**Comment by henriqueArrazao** [comment]
connectivity_plus: ^1.0.6, when I tried with the package "connectivity" happened the same thing.

**Comment by Lauriero** [comment]
Have the same issue

**Comment by Lauriero** [comment]
Just found how to solve it - just add `WidgetsFlutterBinding.ensureInitialized();` before initializing Connectivity.

**Comment by mhadaily** [comment]
@henriqueArrazao have you tried `WidgetsFlutterBinding.ensureInitialized();` as @Lauriero suggested?

**Comment by henriqueArrazao** [comment]
> @henriqueArrazao have you tried `WidgetsFlutterBinding.ensureInitialized();` as @Lauriero suggested?

Yes, thank you  @Lauriero
