### ISSUE TITLE
[package_info_plus] 1.0.4 has breaking change

### ISSUE THREAD

**Issue by HakkyuKim** [fluttercommunity/plus_plugins#392]
Hi, I believe `package_info_plus` violates semantic versioning spec in 1.0.4.

#340 added a required parameter to `PackageInfo`'s public constructor, this is a breaking change to [lines declaring `PackageInfo` as a non-nullable type with dummy values](https://github.com/bottlepay/plus_plugins/blob/a70e634f7094054fb7e13a1b917e49149e57411e/packages/package_info_plus/package_info_plus/example/lib/main.dart#L37-L43).

How about removing the required keyword and [releasing a new patch version](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version)?

**Comment by mhadaily** [comment]
Great catch, there must be some human mistake here, could you please fix it and send us a PR so we can release immediately? please add a changelog too. 

THANK YOU

**Comment by HakkyuKim** [comment]
@mhadaily 
Thank you for the quick response, I've submitted a PR which is linked to this issue. Please let me know if I need to fix anything else.
