### ISSUE TITLE
[share_plus] how to localize the strings on the screen ?

### ISSUE THREAD

**Issue by dizang2** [fluttercommunity/plus_plugins#394]
how to localize the strings on the screen ?

is there any way to bind with localization ?

thanks in advance.

**Comment by mhadaily** [comment]
Hi, Can you give a bit more context. Do you mean the Text where you share? or the modal that pops up natively from the system?

**Comment by mhadaily** [comment]
I believe you are looking for this. That's native UI. Have you followed https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle ?

closing, please feel free to reopen if that doesn't help you
