### ISSUE TITLE
 iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0

### ISSUE THREAD

**Issue by princegoyalcorevalue** [fluttercommunity/plus_plugins#395]
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99

**Comment by Elias8** [comment]
Hi @princegoyalcorevalue 👋,

Please look in to [this](https://stackoverflow.com/questions/63973136/the-ios-deployment-target-iphoneos-deployment-target-is-set-to-8-0-in-flutter) StackOverflow QA. 

Hope that helps!
