### ISSUE TITLE
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send.

### ISSUE THREAD

**Issue by zhangmiaocc** [fluttercommunity/plus_plugins#396]
W/FlutterJNI(21676): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: dev.fluttercommunity.plus/sensors/accelerometer. Response ID: 0

**Comment by AbdOoSaed** [comment]
### SAME ISSUE

**Comment by i124q2n8** [comment]
Late to the party. I had the same issue with the battery_plus plugin and solved it by using WidgetsBindingObserver to unsubscribe from the stream when the app goes in the background or the screen is locked.

https://stackoverflow.com/a/52890987

HTH

**Comment by komaxx** [comment]
@i124q2n8 
Thanks for your input!

That works - but doesn't help me unfortunately, as I need some data while the app is in background... 

I ended up just writing my own plugin to access sensor data. It's not a lot of code - but I'm still surprised how often such workarounds are required. Flutter's support-envelope can be a lot more restricitve than it seems.
