### ISSUE TITLE
[package_info_plus] I got build error 

### ISSUE THREAD

**Issue by xpwmaosldk** [fluttercommunity/plus_plugins#401]
My environment is
    • Flutter version 2.2.3 at /Users/dydeoddl/Downloads/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
and 
JAVA version is 8

I hope make apk but I got this error

```
flutter build apk --release


BUILD FAILED in 1m 17s                                                  
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      78.6s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin package_info_plus...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   718ms


FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'package_info'.
```

I used 3rd party code obfuscation tools at Android

**Comment by xpwmaosldk** [comment]
more infomation

```
[   +1 ms] "flutter appbundle" took 30,130ms.
[   +3 ms] The plugin package_info_plus could not be built due to the issue above.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:802:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:312:7)
           <asynchronous suspension>
           #3      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:492:15)
           <asynchronous suspension>
           #4      AndroidGradleBuilder.buildAab (package:flutter_tools/src/android/gradle.dart:249:5)
           <asynchronous suspension>
           #5      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:147:5)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by mhadaily** [comment]
which version of package info are you using?

**Comment by xpwmaosldk** [comment]
I'm using for  `package_info_plus: ^1.0.4`

**Comment by Ravi-lk** [comment]
Hello @mhadaily I will look into this and work on it 😊

**Comment by mhadaily** [comment]
@Ravi-lk go for it

**Comment by bhattishb92** [comment]
any solution?
[/Users/muhammadfurqan/Desktop/Olt/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:64](): error: package io.github.zeshuaro.google_api_headers does not exist
      flutterEngine.getPlugins().add(new io.github.zeshuaro.google_api_headers.GoogleApiHeadersPlugin());
                                                                              ^
[/Users/muhammadfurqan/Desktop/Olt/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:84](): error: package com.walle.modal_progress_hud_nsn does not exist
      flutterEngine.getPlugins().add(new com.walle.modal_progress_hud_nsn.ModalProgressHudNsnPlugin());
                                                                         ^
[/Users/muhammadfurqan/Desktop/Olt/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:94](): error: package dev.fluttercommunity.plus.packageinfo does not exist
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin());

**Comment by vinodlee** [comment]
AM also facing the same issue

Running Gradle task 'assembleDebug'...
/Users/vinothm/PX/exam_pannel/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:89: error: package dev.fluttercommunity.plus.packageinfo does not exist
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin());
                                                                              ^
1 error

FAILURE: Build failed with an exception.
