### ISSUE TITLE
share_plus crashes on IOS

### ISSUE THREAD

**Issue by EunyoungY** [fluttercommunity/plus_plugins#405]
share_plus crashes on IOS.
I tried on actual device(IOS) and simulator. 
![image](https://user-images.githubusercontent.com/43934072/129294794-4fb1313f-f1f7-4036-8bd9-9fdc3aeebf4e.png)

## System info

Issue occurs on: iOS
Plugin name: share_plus
Plugin version: 2.1.4
Flutter doctor output: 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.0)
[✓] Connected device (3 available)

## Steps to Reproduce

class Shares extends StatefulWidget {
  @override
  ShareState createState() => ShareState();
}

class ShareState extends State<Shares> { 
  final controller = ScreenshotController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Share Plugin Demo',
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Share Plugin Demo'),
          ),
          body: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(20.0),
              child: Column(
                // crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  captureWidget(),

                  TextButton(
                    onPressed: () async {
                      final image = await controller.captureFromWidget(captureWidget());
                     saveAndShare(image);
                      },
                    child: Text("capture widget"),
                  ), 
                ],
              ),
            ),

          )),

    );
  }

  Future saveAndShare(Uint8List bytes) async {
    final directory = await getApplicationDocumentsDirectory();
    final image = File('${directory.path}/share.png');
    image.writeAsBytes(bytes);

    final text = 'Shared ';
    await Share.shareFiles([image.path], text: text);
  }

  Widget captureWidget() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [ 
        Text("Widget", style: text2(color: gray1),), 
      ],
    );
  }

**Comment by apocalipse9** [comment]
Use await on image.writeAsBytes will solve your problem.
But the share still not working. Already tried.

**Comment by 865102930** [comment]
It crashes when I get an image from the library, I'm trying to solve the problem, finally, I find it returns nil when I use the "imageWithContentsOfFile" method. and then it crashes when the array adds the image.
![Snipaste_2021-08-24_18-08-59](https://user-images.githubusercontent.com/18364926/130598777-cff68612-eb26-4321-9a14-996d7e510752.png)

**Comment by speedlightwp** [comment]
Try to use this instead?

image.writeAsBytesSync(bytes);

**Comment by kapil708** [comment]
> Use await on image.writeAsBytes will solve your problem. But the share still not working. Already tried. Just share caption and text, not image. On Android works fine.

Thanks **await** work for me 👍

**Comment by kapil708** [comment]
> Use await on image.writeAsBytes will solve your problem. But the share still not working. Already tried. Just share caption and text, not image. On Android works fine.

Thanks **await** work for me 👍
