### ISSUE TITLE
why share language in english only?

### ISSUE THREAD

**Issue by tarektaamali** [fluttercommunity/plus_plugins#406]
The system language of my phone is frensh , but when i use the package share plus the language en ios usually  is en english.
How  to change the language popup to frensh?  
![Simulator Screen Shot - iPhone 8 - 2021-08-13 at 08 07 25](https://user-images.githubusercontent.com/17914433/129412009-0106bb92-863e-42d0-a037-b0e3527c9854.png)

**Comment by stuartmorgan** [comment]
That's native UI. Have you followed https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle ?

**Comment by ThinkBIG-Company** [comment]
> That's native UI. Have you followed https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle ?

This is the solution
Thanks

**Comment by loud-at-heart** [comment]
@mhadaily can I work on this task?

**Comment by mhadaily** [comment]
sure, @loud-at-heart

**Comment by mhadaily** [comment]
@loud-at-heart it seems we have a solution for this already, @tarektaamali can you confirm if the proposed solution works for you? and if so, please close this issue, if not, let @loud-at-heart know

**Comment by Nico04** [comment]
I confirm that the fix works perfectly for me, thanks !

**Comment by mhadaily** [comment]
Thank you for confirming.
