### ISSUE TITLE
Request to return a flag to count how much time i was shared something 

### ISSUE THREAD

**Issue by mustafa-707** [fluttercommunity/plus_plugins#407]
## Use case

I have a Post Share feature in my app and, I want to count if post was shared only , not when press on share icon 

i was tried to do it , but i didn't notice any feature to do it , please help if there's already something like that or it's need to add to plugin

**Comment by Chinmay-KB** [comment]
There is a similar enhancement request in [Issue #386](https://github.com/fluttercommunity/plus_plugins/issues/386).
