### ISSUE TITLE
Advertising Id

### ISSUE THREAD

**Issue by pmg1991** [fluttercommunity/plus_plugins#408]
## Use case

Advertising Id is missing from device info plus.

example:  https://pub.dev/packages/advertising_id

**Comment by mhadaily** [comment]
Free free to send us a PR if you feel this is valuable

**Comment by Elias8** [comment]
Hi @pmg1991 👋,

[Advertising Id](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en#zippy=%2Cadvertising-id-violations) is not a device feature. Instead, it comes from the [gms](https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient.Info)(google mobile/play services) SKD. And I don't think it would be good to add this feature to this package as many developers may not need it in their app, and it is unrelated to what the package is currently trying to solve/doing.

I am closing the issue for now. But feel free to reopen it if you have any suggestions.

Thanks! 👍
