### ISSUE TITLE
[connectivity_plus] onConnectivityChanged not updating status on Samsung One UI

### ISSUE THREAD

**Issue by rudrapr** [fluttercommunity/plus_plugins#419]
## System info

Issue occurs on: Android
Plugin name: connectivity_plus
Plugin version: 1.0.8
Flutter doctor output:

## Steps to Reproduce

1.  onConnectivityChanged stream not updating real-time status while checkConnectivity() works fine.
2.  I verified this problem only happens in the latest version on the Samsung One UI Core 2.0

**Comment by fernando-s97** [comment]
Any updates on that?
