### ISSUE TITLE
[android_alarm_manager_plus] Reschedule or clear alarms when app is launched after force stop

### ISSUE THREAD

**Issue by gazialankus** [fluttercommunity/plus_plugins#421]
## Use case

When we force stop the app, its alarms are cleared and they won't fire. However, these alarms that did not fire still show up in `AndroidAlarmManager.getScheduledAlarms()`. They stay in that list indefinitely because they never actually fire. 

## Proposal

When the user starts the app after a force stop, we can check the scheduled alarms, remove the ones that are in the past and reschedule the ones that are in the future. This way, a force stop followed by app launch would not prevent previously set alarms from firing.

**Comment by miquelbeltran** [comment]
mmhh true, I haven't thought about this edge case. I think we should revert https://github.com/fluttercommunity/plus_plugins/pull/384 probably then because this can lead to misunderstandings.

**Comment by Chinmay-KB** [comment]
Yup, this is not something I had thought about.  This will need more deliberations.

**Comment by gazialankus** [comment]
I guess past alarms should be rescheduled rather than deleted. Alarms that are set for dates in the past are fired as soon as possible. It could be that the alarm never actually fired and would have fired soon if the force stop had not happened. 

So maybe rescheduling all alarms at every start of the app would cover everything. Rescheduling the same alarm with the same id has no effect in Android if it was already there. 

- App stopped normally. App starts and reschedules everything with the same ids, no change.
- App is force stopped. App starts and reschedules everything, the cleared alarms are revived, as if the app was never force-stopped.

**Comment by miquelbeltran** [comment]
> I guess past alarms should be rescheduled rather than deleted.

That's not how the Android OS framework works unfortunately. We shouldn't reinvent how alarms work on the OS level. The feature @Chinmay-KB was a nice addon to keep track of Alarms but personally I think we are trying to overcome the OS limitations which shouldn't be the goal of this plugin. Rather, that should be managed by the app developer on the app level.

**Comment by gazialankus** [comment]
Fair enough. But I do believe this example could be improved: 

I just set up an alarm with id 11, force closed, set up one more alarm with the same id (11) and force closed. When I open the app again, I have two entries in the list and I can't ever get rid of them. 

1. It would be nice if I saw only one entry for alarms I set with the same id. I would see only the second one in the above example. So, alarms set with the same id should overwrite each other in this list. 
2. Optionally, it would be nice if I can clear this list. If I know I was force stopped this would be useful. Not sure if I can know that, though. So I'm not sure if this is a must.

**Comment by miquelbeltran** [comment]
That's why I think we should revert the feature, because doesn't respond to how Alarms work on the OS level. Managing a list of alarms should be on the app side and not on the plugin side.

**Comment by gazialankus** [comment]
Ok now I see your point. I think there could be a second plugin that complements this in this regard.

**Comment by miquelbeltran** [comment]
I ended up reverting the feature. Thanks again @Chinmay-KB for your work, I am sorry we have to pull the feature out!
