### ISSUE TITLE
upgrade  ios platform 10.0   #connectivity_plus

### ISSUE THREAD

**Issue by samithe7** [fluttercommunity/plus_plugins#428]
In Android  connectivity_plus is ok . but when i use connectivity_plus  on ios  it  always show no internet connection but my iOS simulator have internet   connection . i use firebase  firestore in my project  . so  my  ios platform 10.0   but connectivity_plus  ios platform 8.0  .

#connectivity_plus

**Comment by lkmandy** [comment]
I will like to work on this issue
