### ISSUE TITLE
No implementation found for method getAndroidDeviceInfo on channel dev.fluttercommunity.plus/device_info

### ISSUE THREAD

**Issue by josefrvaldes** [fluttercommunity/plus_plugins#433]
## System info

Issue occurs on: Android
Plugin name: device_info_plus
Plugin version: 0.7.2
Flutter doctor output: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.6, on Linux, locale es_ES.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (not installed)
[✓] VS Code (version 1.58.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

## Steps to Reproduce

I'm doing a very simple task: I just want to show a dialog if android version is lower than 11, so my code is just this:

```
var showDialog = true;
    if (Platform.isAndroid) {
      try {
        final deviceInfo = DeviceInfoPlugin();
        var androidInfo = await deviceInfo.androidInfo;
        if (androidInfo.version.sdkInt >= 30) {
          showDialog = false;
        }
      } catch (e) {
        print(e);
        showDialog = false;
      }
    }
```

And always it's thrown an error that it's exactly this one: `No implementation found for method getAndroidDeviceInfo on channel dev.fluttercommunity.plus/device_info`

flutter analyze shows no issues.

I've run the same project in different android emulators (versions 10 and 11) with the same result always. I've restarted, uninstalled, even cloned the repo again and tested in a different computer and I get always the same result.

**Comment by LinMaris** [comment]
I also meet this problem, this is strange.

No implementation found for method getAndroidDeviceInfo

I can't solve this problem through external methods
