### ISSUE TITLE
Not able to build appbundle

### ISSUE THREAD

**Issue by akashlilhare** [fluttercommunity/plus_plugins#437]
* What went wrong:
A problem occurred evaluating root project 'android_intent'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.1. If using the gradle wrapper, try editing the distributio
nUrl in C:\Users\91966\.gradle\daemon\4.10.1\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to g
et full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin android_intent_plus could not be built due to the issue above.

**Comment by lkmandy** [comment]
Hi @mhadaily 
I'll like to work on this issue

**Comment by mhadaily** [comment]
Go ahead @lkmandy
