### ISSUE TITLE
[plugin][sensors_plus] Need to specify sensor delay level.

### ISSUE THREAD

**Issue by windows7lake** [fluttercommunity/plus_plugins#439]
## Use case
In my case, I need to specify sensor delay level.
```
sensorManager.registerListener(sensorEventListener, sensor, sensorManager.SENSOR_DELAY_NORMAL);
```

## Proposal
sensorManager.SENSOR_DELAY_GAME is also needed.

**Comment by ghermana** [comment]
Considering that:
1. iOS uses [deviceMotionUpdateInterval](https://developer.apple.com/documentation/coremotion/cmmotionmanager/1616065-devicemotionupdateinterval) to set a time unit.
2. Android uses abstract delay level values ([SENSOR_DELAY_NORMAL](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_NORMAL), [SENSOR_DELAY_UI](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_UI), [SENSOR_DELAY_GAME](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_GAME), or [SENSOR_DELAY_FASTEST](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_FASTEST)) that seem to actually be tied to a maximum delay between two updates (https://developer.android.com/guide/topics/sensors/sensors_overview).

A generic interface to cover all platforms could take a maximum desired updated delay (in milliseconds) as a parameter and have predefined constants corresponding to the Android delays.

Would you be willing to accept a pull request that adds support for a maximum desired sensor update delay?

**Comment by zzzaJ** [comment]
Is there any update on this?

**Comment by Pierre2tm** [comment]
I miss the sensorManager.SENSOR_DELAY_GAME

**Comment by harshitmahapatra** [comment]
Hi, are you open to contributions regarding this issue?
I would like to contribute if possible.
