### ISSUE TITLE
[network_info_plus] getWifiName() returns SSID of disconnected network in Android

### ISSUE THREAD

**Issue by waltojac** [fluttercommunity/plus_plugins#441]
## System info

Issue occurs on: Android (LG G6, V40, more on 8.0.0)
Plugin name: network_info_plus
Plugin version: 1.0.2
Flutter doctor output:

```
-> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

• No issues found!
```

## Steps to Reproduce
1. Use Android WifiManager to add and connect to a local wifi access point
2. Turn off the access point
3. Get call NetworkInfo.getWifiName()
4. Examine that the SSID is the SSID of the now disconnected network, indefinitely (I added a 1 second poll for 3 minutes, and it kept returning the disconnected SSID)

Unfortunately, my company doesn't allow me to produce source code in issues, but I hope the issue is clear enough where it is not necessary. In the Android source code for `network_info_plus`, in the `NetworkInfo.java` file in the `String getWifiName()` function on line 19, the function gets connection info from the wifi manager, and simply returns the formatted SSID if available.

In my case after following the steps above, when I debug into this code, I see that the `wifiInfo.getSupplicantState()` returns `SupplicantState.DISCONNECTED`, but the function still returns the SSID of the disconnected network. I didn't think `WifiManager.getConnectionInfo()` would return connection info for a disconnected network, but there is nothing in Android docs stating that, and it seems up to the OEM as to whether they clear the WifiManger on disconnect of a network, so it will return info for a disconnected network.

My suggested solution is to add in the conditional of line 22 the following: `&& wifiInfo.getSupplicantState() == SupplicantState.COMPLETED`. Based on the docs for "COMPLETED": 
>...This state indicates that the supplicant has completed its processing for the association phase and that data connection fully configured.

This would ensure that getWifiName() only ever returns the SSID of the currently connected to wifi network, which seems more in line with the documentation on getWifiName(): "Obtains the wifi name (SSID) of the connected network".

**Comment by daniellampl** [comment]
@mhadaily I would like to work on that

**Comment by mhadaily** [comment]
it's all your @daniellampl
