### ISSUE TITLE
identifierForVendor is always change in ios after re-installing, i need unique id for ios device to limit Login.

### ISSUE THREAD

**Issue by tejtechtonic** [fluttercommunity/plus_plugins#447]
## System info

Issue occurs on: iOS
Plugin name: device_info_plus
Plugin version: 2.1.0

**Comment by shubh420** [comment]
Any update on this?
I am also facing this issue. UUID is getting reset after app update.

**Comment by tejtechtonic** [comment]
> Any update on this?
> I am also facing this issue. UUID is getting reset after app update.

Try this [https://pub.dev/packages/flutter_udid](flutter_udid), it gives accurate and static id.

**Comment by wahyu-handayani** [comment]
Hi @tejtechtonic ... right now I am trying your solution by using flutter_udid to get uniq id for ios device. I have tried it in one of simulator and there is no problem when I do uninstall my apps and then do reinstall... the id will static like what you said. I haven't try it in another simulator. So, I would like to ask you.. so far when you use flutter_udid package to get uniq id, is there any other problem that you get ?

**Comment by wahyu-handayani** [comment]
Hi @tejbhansahu  thank you very much for your reply and your help, right now I use flutter_udid like your suggestion before. Hope there is not any problem for the future

**Comment by Leffe108** [comment]
According to [Apple docs](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor), identifierForVendor is expected to change when you uninstall and re-install your app unless user has another app that you have also published that remains on the device during uninstall + re-install. It also mentions that test builds can cause it to change.

**Comment by Novaera** [comment]
We facing the same issue, any updates on this?

**Comment by swapnilgaikwad1507** [comment]
I am also getting the same issue from **identifierForVendor**. what could be the workaround for the same?

**Comment by ankitsaurabhinfosys** [comment]
any update on this?
