### ISSUE TITLE
android_intent_plus 2.0.0 launch app from background

### ISSUE THREAD

**Issue by spacekestrel** [fluttercommunity/plus_plugins#448]
I need to create an alarm clock functionality that open my application from the background. It seems that there is the way to do it using android_intent and android_alarm_manager_plus. I was looking for the right way to create such functionality, but this option does not work:
```
await AndroidAlarmManager.oneShot(
      Duration(seconds: 2), 1, setAlarm);
```
```
void setAlarm()async{
  AndroidIntent intent =
      AndroidIntent(action: 'action_view', package: 'com.example.test_alarm');
  await intent.launch().catchError((e) {
    print(e.toString());
  });
}
```
Debug console gives this:
```
I/IntentSender( 4886): Cannot resolve explicit intent - ignoring package
V/IntentSender( 4886): Sending intent Intent { act=android.intent.action.VIEW (has extras) }
```

**Comment by Chinmay-KB** [comment]
Launching an app from the background on its own was working until Android 9. There are several changes regarding this in Android 10. You can go through the changes in this page, [Background Starts](https://developer.android.com/guide/components/activities/background-starts).
