### ISSUE TITLE
PackageInfo.version does not work with windows desktop

### ISSUE THREAD

**Issue by jamolina2021** [fluttercommunity/plus_plugins#449]
Hi,

`PackageInfo.version` does not work with **windows desktop**
In the `pubspec.yaml `file version is **1.5.0**
`version: 1.5.0`
When I run the **web** application everything works fine.
```
   PackageInfo packageInfo = await PackageInfo.fromPlatform ();
   Config.version = packageInfo.version;
```
`packageInfo.version` returns **1.5.0**
However when I run the **windows desktop** application
`packageInfo.version` returns **1.0.0** 

Thank you very much for the help. 

Regards,
Jose A.Molina

**Comment by fabio21** [comment]
![Captura de tela 2021-09-16 090202](https://user-images.githubusercontent.com/8049768/133608698-9977ad88-261c-46c4-9ba1-8bc48e7ab6c4.png)
![Captura de tela 2021-09-16 090225](https://user-images.githubusercontent.com/8049768/133608711-63569193-c4b6-4532-8b6a-3aca361de173.png)

**Comment by Agondev** [comment]
> ![Captura de tela 2021-09-16 090202](https://user-images.githubusercontent.com/8049768/133608698-9977ad88-261c-46c4-9ba1-8bc48e7ab6c4.png) ![Captura de tela 2021-09-16 090225](https://user-images.githubusercontent.com/8049768/133608711-63569193-c4b6-4532-8b6a-3aca361de173.png)

This mean modifying the value separately from that of the one in the yaml file.

**Comment by ollydixon** [comment]
Anyway to automate this? Changing it manually each time is a bit bad.

**Comment by ollydixon** [comment]
This should be possible to implement now with the windows changes
