### ISSUE TITLE
[network_info_plus] Get IP on Wifi hotspot network

### ISSUE THREAD

**Issue by quentinleguennec** [fluttercommunity/plus_plugins#450]
Is there any way, using network_info_plus, to get the IP address on the network generated by a wifi hotspot? 
I'm trying to use my phone as a hotspot to connect to a raspberry Pi and when I create a wifi hotspot and call `NetworkInfo().getWifiIP()` or `NetworkInfo().getWifiBroadcast()` it returns null.

It will only return something when I connect to a classic wifi network.

**Comment by HasanAlqaisi** [comment]
I have a similar case, is it possible?
