### ISSUE TITLE
Share plugin doesn't await on future

### ISSUE THREAD

**Issue by alexlipa91** [fluttercommunity/plus_plugins#454]
## System info

Issue occurs on: both
Plugin name: ^2.1.4
Plugin version: 2.1.4

## Steps to Reproduce

I am using the plugin when tapping an Icon and I realized that the icon can be tapped mutliple consecutive times which would trigger many dialogs for sharing to be open. For this reason I added a boolean state `active` (intitialized to `false`) to understand when the button can be pressed.

```
InkWell(
        child: Icon(Icons.share, color: Colors.black),
        onTap: () async {
          if (active) {
            print("already active");
            return;
          }
          setState(() {
            active = true;
          });
          await Share.share("Wanna join this match?");
          setState(() {
            print("now can go");
            active = false;
          });
        });
```

However the string `now can go` is printed while the dialog button is still on, which means the `await` on `Share.share(...)` isn't really working

**Comment by Elias8** [comment]
Hi @alexlipa91 👋

Thanks for opening an issue.

The `Share.share` method doesn't wait for the result from each platform instead, it will just tell the platform to handle the request(open the share dialog), and the future will be complete. 

For now, I will close the issue in favor of #386. But feel free to reopen it if you have any questions or comments.

Hope that helps.
