### ISSUE TITLE
[package_info_plus] Web: fail to get PackageInfo (version) offline

### ISSUE THREAD

**Issue by alextekartik** [fluttercommunity/plus_plugins#456]
This is a issue I think related to https://github.com/fluttercommunity/plus_plugins/issues/225

It only happens on the Web while offline.

I have a PWA flutter application where I call `await PackageInfo.fromPlatform()` before running the app. This is the only part that is not working offline as it tries to trick the cache to force reading the version, since there is no network, it fails. I think it should try to read the version but on failure (no network), it should return a stale value as there is no reason we could not get the package name and version offline.

To reproduce, create a flutter app from the basic template, add `await PackageInfo.fromPlatform()` in main() publish somewhere, run it, turn of network and refresh...

**Comment by dupuisdavid** [comment]
Hi.
Could you let me know if this issue has been solved?
Thanks for your feedback.

**Comment by miquelbeltran** [comment]
Package Info Plus on web relies on the hosted `version.json` file to read the package info, so, if the app is offline it won't be able to obtain the package info. This works as expected.

**Comment by dupuisdavid** [comment]
ok, I understand. By the way, do you know if there are any initiatives for offline operation in the context of a PWA?

**Comment by dupuisdavid** [comment]
Hi. Is there an update on this topic or not?
In the context of PWA app, the `version.json` file could cached...
What do you think @miquelbeltran?
