### ISSUE TITLE
[share_plus] [iOS] Instagram story does not show up in iOS while sharing image file

### ISSUE THREAD

**Issue by raulmabe** [fluttercommunity/plus_plugins#457]
Very similar to #380. Can't share image to instagram stories on iOS, I can only see one Instagram icon and it is for sharing the video as a standard Instagram Post.
On the other hand, in Android sharing a video file shows up all 3 options:

1. Instagram Feed
2. Instagram Direct
3. Instagram Story

**Comment by BLKKKBVSIK** [comment]
Hi, @raulmabe.

Do you still encounter the issue?
I can't reproduce it as well as the #380.


https://user-images.githubusercontent.com/20175372/135515693-f5597891-2f01-4225-bd24-f298b6c48a48.mov

**Comment by raulmabe** [comment]
You are right, I no longer encounter this issue! I honestly don't know what fixed it
