### ISSUE TITLE
 [share_plus] [iOS] Instagram does not show up in provider list for web links

### ISSUE THREAD

**Issue by duzenko** [fluttercommunity/plus_plugins#459]
I need to share links to social platforms, such as Instagram
Tried the following code
```
   action: () => Share.share(event.deepLink),
```
On iOS that shows Twitter, but not Instagram
I had to spend a lot of time researching this until I realized that share_plus does not use NSURL for web links (which I think is the required operation here)
I also created a PR that shows the small code change that actually fixes Instagram sharing
https://github.com/fluttercommunity/plus_plugins/pull/458/files

**Comment by duzenko** [comment]
<img width="375" alt="PNG image 2" src="https://user-images.githubusercontent.com/1481807/133821059-ffe4512e-9cc5-41df-ba3a-b226bc00e0bd.png">
![Uploading PNG image.png…]()

**Comment by champ96k** [comment]
Can I work on this issue @mhadaily 

Thanks :)

**Comment by mhadaily** [comment]
go ahead @champ96k

**Comment by mhadaily** [comment]
release new version 2.1.5

**Comment by champ96k** [comment]
@mhadaily  have you fix this issue, or else I can raise PR?

**Comment by mhadaily** [comment]
@champ96k it seems @duzenko has fixed this issue we had it in our PRs and I just merged it. it's working now. but I'd say you go ahead and test the latest version and if it works, then fine, if not send another PR for edge cases.
