### ISSUE TITLE
[Suggestion] More information on all platforms

### ISSUE THREAD

**Issue by hekhy** [fluttercommunity/plus_plugins#460]
It would be nice to add all the available information about the battery, things like the following:
Battery Capacity, Battery Level, Charging Status, Charge Time Remaining, Current Average, Current Now, Health, Plugged Status, Battery Presence, Scale, Remaining Energy, Technology, Temperature, Voltage

In general everything that can be known, since it limits enough only the battery level because it is the only thing that when I want to know it I look at it in the status bar of the device and I already have it.

**Comment by rktejesh** [comment]
Can I work on this issue @hekhy

**Comment by hekhy** [comment]
Gracias, lo espero con ganas! :)

**Comment by hekhy** [comment]
Thank you, I look forward to it! :)

**Comment by mhadaily** [comment]
@rktejesh please go ahead. that would be awesome.
