### ISSUE TITLE
WeChat share text is invalid

### ISSUE THREAD

**Issue by q172107875** [fluttercommunity/plus_plugins#462]
![WechatIMG72](https://user-images.githubusercontent.com/13548428/133942485-b2c51914-ca20-49cb-822c-ecfee73d8039.jpeg)

Share.share(textContent);

The version in question is 
share_plus: ^2.1.4
flutter version : 2.5.1
dart version : 2.14.2

**Comment by Elias8** [comment]
Hi @q172107875 👋

Thanks for opening an issue!

Could you please describe the issue you are having? 

Thanks!

**Comment by q172107875** [comment]
> Hi @q172107875 👋
> 
> Thanks for opening an issue!
> 
> Could you please describe the issue you are having?
> 
> Thanks!


As shown in the figure, the WeChat sharing text prompt does not support the sharing type. The problem occurs on IOS devices, and Android devices can share normally. As mentioned earlier, this split has not been resolved on other versions, and the same is true for Facebook.

**Comment by linweigao** [comment]
Is there any update for this issue?

**Comment by yenyichau** [comment]
same problem. WeChat share how to solve?

**Comment by liangxiaobo** [comment]
same problem. WeChat share how to solve?
