### ISSUE TITLE
[share_plus] Cannot share file to itself on iOS

### ISSUE THREAD

**Issue by huynguyennovem** [fluttercommunity/plus_plugins#468]
## System info

Issue occurs on: **iOS 14.5 (Iphone 12 Pro Emulator)**
Plugin name: **share_plus**
Plugin version: **2.1.4**
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.1)
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] VS Code (version 1.60.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

## Steps to Reproduce

1. Pick a file from the phone (image for eg)
2. Share the picked file. Then only see an enter text dialog appear then disappear instantly.

- Demo:

https://user-images.githubusercontent.com/29337364/134331550-cc420311-d338-480e-b207-3ddde5558278.mp4

- Note: 
    - The text can share successfully. This bug occurs for files only.
    - This bug relates to [receive_sharing_intent](https://github.com/KasemJaffer/receive_sharing_intent) too.

- The test [source code](https://github.com/huynguyennovem/receive_sharing_intent/tree/demo-share-to-itself)

**Comment by champ96k** [comment]
Hi @huynguyennovem   👋
Thanks for opening an issue!

@mhadaily can you please assign me this issue, I would love to take it.
Thanks!

**Comment by mhadaily** [comment]
done and thanks @champ96k

**Comment by jonbhanson** [comment]
Any ETA on this bug?  It is causing crashes in our app.  Many thanks!
