### ISSUE TITLE
[all] Migrate from deprecated pedantic to flutter_lints

### ISSUE THREAD

**Issue by juliansteenbakker** [fluttercommunity/plus_plugins#471]
## Proposal
Right now, all packages use pedantic. Pedantic however is discontinued. The Google team recommends using https://pub.dev/packages/flutter_lints for flutter packages. We should migrate all packages to this linter.

**Comment by adityathakurxd** [comment]
Can I work on this issue @mhadaily? 
I am new to `flutter_lints` but look into it and migrate all packages to this linter.

**Comment by mhadaily** [comment]
It's all yours. @adityathakurxd

**Comment by thisisamank** [comment]
Hi @adityathakurxd are you currently working on this issue? I would like to assist :)

**Comment by adityathakurxd** [comment]
Hey @thisisamank, Yes I am working on the issue.
I yesterday setup the local environment. And, was looking into `flutter_lints` documentation. I'll make the PR soon.
