### ISSUE TITLE
Connection to mobile wifi router returns ConnectivityResult.none on windows

### ISSUE THREAD

**Issue by gutisalex** [fluttercommunity/plus_plugins#474]
### System info
Issue occurs on: Windows 10
Plugin name: connectivity_plus
Plugin version: 1.1.0

The connectivity plugin with a connection to an alcatel mobile wifi router returns ConnectivityResult.none on windows. Android and IOS working. The wifi connection on Windows also says that there is no internet, eventhough the router is connected to the internet just doesn't have datavolume available. But can this be a reason? I am still connected to the wifi network of the device...

Just tested this with a common router called Speedport in my home network. I just disconnected from internet but the wifi device was still up and running. It's the same problem. The connectivity plugin says ConnectivityResult.none!

**Comment by ShrutiJ-01** [comment]
@mhadaily May I work on this issue? I am new to such issues but I'd like to try it!

**Comment by mhadaily** [comment]
give it try @ShrutiJ-01

**Comment by gutisalex** [comment]
I can confirm that it has to do with the internet connection. I just topped the datavolume on the sim card in the device and all of the sudden it shows Connectivity.wifi...

**Comment by gutisalex** [comment]
any news on this?
