### ISSUE TITLE
Who is merging open PR's?

### ISSUE THREAD

**Issue by juliansteenbakker** [fluttercommunity/plus_plugins#475]
Right now there are 12 open PR's, with some blocking others. For instance, my pr about deprecation #442 is blocked #466. The last merged PR was on 24 of August. Is anyone looking into this?

**Comment by mhadaily** [comment]
@juliansteenbakker  please be patient. with each PR we are communicating to resolve the issues. Most of the PRs were not ready for merging. 

I'll get to all of them one by one within the next few days. 

But I appreciate your feedback. we must be faster we are working to be better.

**Comment by juliansteenbakker** [comment]
Ofcourse, it's good to hear people are working on it! If you guys need any help i'd be happy to.

**Comment by mhadaily** [comment]
Thanks, 
You send PRs and review other PRs. it's always great to have more eyes on a PR.
