### ISSUE TITLE
[all] Migrate to Null Safety

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#50]
Migrate all the plugins to null safety.

Some considerations:
- e2e package is discontinued and replaced by integration_test.
- integration_test package does not support null safety yet.
- migrate only the plugin, and not the example or the e2e test yet.

TODO
- [x] Enable Beta on CI #106 
- [x] battery_plus @miquelbeltran 
- [x] connectivity_plus @mzdm
- [x] device_info_plus @Schwusch 
- [x] network_info_plus @jpnurmi
- [x] package_info_plus @jpnurmi 
- [x] sensors_plus @jpnurmi  
- [x] share_plus @miquelbeltran 
- [x] android_alarm_manager_plus @miquelbeltran 
- [x] android_intent_plus @miquelbeltran 
- [x] Migrate examples & opt out integration test files (https://github.com/fluttercommunity/plus_plugins/issues/50#issuecomment-782154014) @jpnurmi

Tag yourself on each package if you start working on them!

**Comment by miquelbeltran** [comment]
Currently `battery_plus`, `connectivity_plus` and `network_info_plus` are blocked due the dependency on `dbus`.

Ticket: https://github.com/canonical/dbus.dart/issues/119

**Comment by miquelbeltran** [comment]
the dbus team has migrated the codebase to null safety and is ready for a release, once the release is done we can continue the null safety migration work.

**Comment by mhadaily** [comment]
@miquelbeltran, so we technically need to migrate device_info_plus, package_info_plus,  sensors_plus, the rest were migrated?

**Comment by miquelbeltran** [comment]
The following need to be migrated and are still pending:
battery_plu
 connectivity_plus
 device_info_plus
 package_info_plus
 sensors_plus

Any help is appreciated!

**Comment by mhadaily** [comment]
Sure,  you are doing battery plus right?

then I'll take package_info_plus + sensors_plus for now.

**Comment by mzdm** [comment]
I would like to help and give an attempt to migrate `connectivity_plus` plugin to null safety.

**Comment by mhadaily** [comment]
@mzdm it's all yours, please let us know how it goes. 

Thank you for your contribution.

**Comment by jpnurmi** [comment]
@mzdm I think `connectivity_plus` is still waiting for [dbus](https://github.com/canonical/dbus.dart/pull/130), but you could temporarily use it straight from the Git repo for migration purposes.

**Comment by jlubeck** [comment]
Will all the packages be updated at once? Or how can we keep track of each release? Thank you!

**Comment by miquelbeltran** [comment]
Each package should be released individually. If they have a :ballot_box_with_check: then they should be released with a `-nullability` annotated pre-release

**Comment by miquelbeltran** [comment]
Anyone else faced this issue?

```
The current Dart SDK version is 2.12.0-259.12.beta.

Because no versions of dbus match >0.2.0 <0.3.0 and dbus 0.2.0 depends on xml ^5.0.0, dbus ^0.2.0 requires xml ^5.0.0.
Because xml 5.0.0 requires SDK version >=2.12.0-259.14.beta <3.0.0 and no versions of xml match >5.0.0 <6.0.0, xml ^5.0.0 is forbidden.
Thus, dbus ^0.2.0 is forbidden.
So, because battery_plus_linux depends on dbus ^0.2.0, version solving failed.
pub get failed (1; So, because battery_plus_linux depends on dbus ^0.2.0, version solving failed.
```

**Comment by stuartmorgan** [comment]
> * integration_test package does not support null safety yet.
> * migrate only the plugin, and not the example or the e2e test yet.

FYI you can migrate the examples, and just opt the integration test files out explicitly (`// @dart = 2.9`), so you can run examples in strong mode and make sure there are no obvious issues with the null safety migration that are covered by the example but not the unit tests.

flutter/plugins was originally doing what you've described here, and there's been at least one case of a plugin where a serious nullability issue (null values coming from the native code, but being assumed to be non-null in the Dart code) was missed as a result.

**Comment by jpnurmi** [comment]
We are having problems getting that far...

Dart SDK constraints of the indirect `xml` & `petitparser` dependencies were fixed, but the remaining `args` dependency of `dbus` is tricky because it conflicts with `flutter_driver` on the beta channel.

```
Running "flutter pub get" in example...                         
Because every version of connectivity_plus from path depends on connectivity_plus_linux from path which depends on dbus ^0.2.0, every version of connectivity_plus from path requires dbus ^0.2.0.
And because dbus >=0.2.0 depends on args ^2.0.0 and every version of flutter_driver from sdk depends on args 1.6.0, connectivity_plus from path is incompatible with flutter_driver from sdk.
So, because connectivity_plus_example depends on both flutter_driver any from sdk and connectivity_plus from path, version solving failed.
pub get failed (1; So, because connectivity_plus_example depends on both flutter_driver any from sdk and connectivity_plus from path, version solving failed.)
```

I don't know how to get past this without eliminating the whole integration test.

**Comment by stuartmorgan** [comment]
If `flutter_driver` doesn't use any of the deprecated `args` APIs that were removed in 2.0.0 you could potentially use a dependency override.

Worst case though, that's specific to that plugin; the general policy could be to migrate examples even if there are cases where you can't in the short term.

**Comment by jpnurmi** [comment]
All done! :tada:

**Comment by mhadaily** [comment]
well done @jpnurmi
