### ISSUE TITLE
[all] Upgrade to latest gradle versions

### ISSUE THREAD

**Issue by juliansteenbakker** [fluttercommunity/plus_plugins#505]
Right now most of the packages use old versions of Gradle like 3.5.0.

The latest version of the Gradle plugin is 7.0.2 however this requires Java 11 instead of 8.
This will require the CI street to also upgrade to Java 11 [and can be done with the following action](https://github.com/actions/setup-java#setup-java).

**Comment by vbuberen** [comment]
I am already updating some of packages along with dependencies.

As to Java 11 - it is available by default on runners:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#java
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java

**Comment by juliansteenbakker** [comment]
I have made a PR for every package that upgrades to the latest version of gradle, android and updated other dependencies if present. Besides that i also applied some code improvements if possible.

**Comment by miquelbeltran** [comment]
Thanks you both for these contributions. I am reviewing the changes and will release the updated packages at once soon. Please let me know when this issue can be closed.

**Comment by juliansteenbakker** [comment]
@miquelbeltran thanks for reviewing! Is there any reason as why #442 isn't merged?

**Comment by miquelbeltran** [comment]
no particular reason, we are just a bit overwhelmed at the moment, but I am trying to get as much PRs merged as possible
