### ISSUE TITLE
CI doesn't check if plugins build properly

### ISSUE THREAD

**Issue by vbuberen** [fluttercommunity/plus_plugins#506]
It seems that job `build_examples_dart` is configured in a wrong way, so build fails on individual platforms aren't breaking builds and show step as successful in any case. For example, due to this configuration issue it is not detected that #495 broke examples on Android (see the attached screenshot).

<img width="1645" alt="Screenshot 2021-10-05 at 14 53 53" src="https://user-images.githubusercontent.com/13467769/136018119-93453d49-67fc-4fe8-9d80-3067a1b19562.png">

I believe that failing on one of platforms should fail the whole job.

**Comment by mhadaily** [comment]
That's a good catch, are you up for a PR to fix it? or should I do that?

**Comment by vbuberen** [comment]
I will give it a try and write back in case I have issues fixing it.

**Comment by vbuberen** [comment]
Please note that I am already working on updating this workflow
