### ISSUE TITLE
[share_plus] Instagram caption blank

### ISSUE THREAD

**Issue by jasonJamEther** [fluttercommunity/plus_plugins#532]
I am using this plugin to post an image and text to social media platforms. There are a few limitation I am encountering on a few Social platforms:

share_plus: ^3.0.2

`Share.shareFiles(
        [file.path],
        mimeTypes: ['image/png'],
        text: shareText,
      );`

Instagram (iOS and Android) - Image posts but caption is empty. Does not populate with text value.
Facebook (iOS and Android) - Image posts but caption is empty. If shareText contains a hashtag it will post ONE hastag.
Twitter (iOS ad Android) - Image and caption works

not really important but Slack works well with Android, on iOS only the text populates but not the image.

Allowing instagram to populate the caption with at least a hashtag is my biggest priority.

**Comment by aGubhaju** [comment]
any update on this issue?

**Comment by pdax-king** [comment]
I have the same problem, copy on iOS also doesn't copy the image. 

[Related Issue](https://github.com/fluttercommunity/plus_plugins/issues/385)

**Comment by k-ane** [comment]
I'm having the same issue as well

**Comment by ZhiaDev** [comment]
Does this problem have a solution or is it a limitation of the applications themselves?
