### ISSUE TITLE
 Multiple targets match implicit dependency for linker flags '-framework Reachability'.

### ISSUE THREAD

**Issue by archercod** [fluttercommunity/plus_plugins#542]
Hello,
When I add network_info_plus and connectivity_plus I got this this error when I try to archive app, do You have some ideas how to solve this?

: Multiple targets match implicit dependency for linker flags '-framework Reachability'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'Flutter Assemble' from project 'Runner')
    note: Target 'Reachability' (in project 'Pods')
    note: Target 'ReachabilitySwift' (in project 'Pods')

**Comment by archercod** [comment]
@alexbatalov is there any chance to push this pr with fix?

**Comment by kyle-seongwoo-jun** [comment]
same problem here

**Comment by archercod** [comment]
After this changes, connectivity always return wifi connection on, even when turned off
