### ISSUE TITLE
In Flutter 2.0, package_info_plus conflicts with Flutter_keyboard_visibility

### ISSUE THREAD

**Issue by jjvu-xiao** [fluttercommunity/plus_plugins#551]
Because flutter_keyboard_visibility >=5.0.0 depends on flutter_keyboard_visibility_platform_interface ^2.0.0 which depends on plugin_platform_interface ^2.0.0, flutter_keyboard_visibility >=5.0.0 requires plugin_platform_interface ^2.0.0.
And because url_launcher_platform_interface 1.0.9 depends on plugin_platform_interface ^1.0.1 and no versions of url_launcher_platform_interface match >1.0.9 <2.0.0, flutter_keyboard_visibility >=5.0.0 is incompatible with url_launcher_platform_interface ^1.0.9.
And because url_launcher 5.7.10 depends on url_launcher_platform_interface ^1.0.9 and no versions of url_launcher match >5.7.10 <6.0.0, flutter_keyboard_visibility >=5.0.0 is incompatible with url_launcher ^5.7.10.
So, because water_app depends on both url_launcher ^5.7.10 and flutter_keyboard_visibility 5.0.0, version solving failed.

pub get failed (1; So, because water_app depends on both url_launcher ^5.7.10 and flutter_keyboard_visibility 5.0.0, version solving failed.)

When Flutter was migrated to 2.0, Package_info_plus collided with the plugin dependent on Flutter_keyboard_visibility

**Comment by Boehrsi** [comment]
@jjva-xiao Thanks for your report. For me this error message looks like a problem between url_launcher and flutter_keyboard_visibility. I don't see any mention of package_info_plus in the error message.
The error message itself should be easily solvable by updating url_launcher to the latest version (6.0.12) as this version uses `plugin_platform_interface: ^2.0.0` which actually leads to the conflict.

**Comment by fabiancrx** [comment]
The issue still persists @jjvu-xiao ?
