### ISSUE TITLE
extend package_info_plus plugin to return installer info

### ISSUE THREAD

**Issue by ekuleshov** [fluttercommunity/plus_plugins#570]
## Use case

In some cases an app or plugin need to know where the package was installed from, e.g. to use correct services for given marketplace (in-app purchases, maps, push, etc). For example Google Play vs Amazon vs Samsung vs Huawei for Android, or Appstore vs TestFlight for iOS and Macos, local vs Microsoft appstore for Windows, etc.

## Proposal

The package_info plugin already returns a lot of info about package, but not the installer's info.

For Android this info can be retrieved from `PackageManager.getInstallerPackageName`:

```
PackageManager pm = applicationContext.getPackageManager();
String installerPackage = pm.getInstallerPackageName(applicationContext.getPackageName());
map.put("installer", installerPackage);
```

For iOS it is either Apple store or TestFlight, e.g.:

```
NSString *appStoreReceipt = [[[NSBundle mainBundle] appStoreReceiptURL] path];
...
@"installer" : [appStoreReceipt containsString:@"CoreSimulator"] ? @"com.apple.simulator"
    : [appStoreReceipt containsString:@"sandboxReceipt"] ? @"com.apple.testflight" : @"com.apple"
```

**Comment by ekuleshov-idexx** [comment]
Any chance this functionality will be implemented at some point?
