### ISSUE TITLE
[device_info_plus] machineId returns null on WSL

### ISSUE THREAD

**Issue by cedvdb** [fluttercommunity/plus_plugins#576]
machineId returns null on my linux WSL.  
 
 ```dart
 ced$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

Ultimately flutter apps are not likely to find their way onto WSL though

**Comment by jpnurmi** [comment]
> Ultimately flutter apps are not likely to find their way onto WSL though

It's not that far-fetched. Canonical's WSL setup wizard GUI is Flutter. 😄

**Comment by cedvdb** [comment]
I was on WSL 2 if I recall correctly, just in case. I cannot help with this issue anymore as I'm very busy currently so you can close if you are ultimately waiting for me to give a reproducible

**Comment by jpnurmi** [comment]
Ok, please don't hesitate to drop a comment if you still face the issue in the future.

```
jpnurmi@LAPTOP-CF65N0FK:~/Temp/foo$ uname -a
Linux surface 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
