### ISSUE TITLE
FBSDKShareKit.ShareDialog:4:12: note: 'init()' has been explicitly marked unavailable here

### ISSUE THREAD

**Issue by mdridley** [fluttercommunity/plus_plugins#579]
## System info

Issue occurs on: iOS
Plugin name: share_plus
Plugin version: 3.0.4
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

• No issues found!
```

## Steps to Reproduce

XCode 13 - Getting this on build now

**Comment by persec10000** [comment]
I met a similar issue using the other flutter package : [flutter_share_me](https://pub.dev/packages/flutter_share_me), and fixed it.
Please check the following article.
[](https://stackoverflow.com/questions/69835123/flutter-share-facebook-init-has-been-explicitly-marked-unavailable-here-f/69835261#69835261)

**Comment by hieugia3030** [comment]
I tried that but it lead me to another problem.
This is its console logs:
l```
d: warning: Could not find or use auto-linked framework 'DataDetection'
    Undefined symbols for architecture x86_64:
      "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
          __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork)
      "_OBJC_CLASS_$_SKAdImpression", referenced from:
          objc-class-ref in FBAudienceNetwork(FBAdSKAdNetworkManager.m.o)
      "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
          __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to
    14.1.99. (in target 'AppAuth' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to
    14.1.99. (in target 'GoogleSignIn' from project 'Pods')
```
