### ISSUE TITLE
XCode get error: Module 'device_info' not found

### ISSUE THREAD

**Issue by Slackgate** [fluttercommunity/plus_plugins#581]
When I try to build my app with XCode, get error: Module 'device_info' not found
it's work fine on android
in mac I try commands:
flutter clean & flutter pub get
flutter pub add device_info (show it's already in dependencies)
and flutter pub upgrade device_info
still get same error

**Comment by alexbatalov** [comment]
For plus plugins the name is `device_info_plus`, so you have to:

```console
$ flutter pub add device_info_plus
$ flutter pub get
$ flutter run
```

**Comment by luokunman** [comment]
> ```
> flutter pub add device_info_plus 
> ```

This method doesn't help me solve the same problem.

**Comment by VDHjokker** [comment]
Hi, i have the same problem with
Xcode 14 
Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e3c29ec00c (6 days ago) • 2022-09-14 08:46:55 -0500
Engine • revision a4ff2c53d8
Tools • Dart 2.18.1 • DevTools 2.15.0

And I resovled it by : 
device_info_plus: 3.2.2
