### ISSUE TITLE
Connectivity plus not responding in real time

### ISSUE THREAD

**Issue by VladanRandjelovic** [fluttercommunity/plus_plugins#584]
I have implemented connectivity plus plugin to track connection status on my application, and I found out that it has some kind of latency when checking or even maybe not listening  to changes actively on real devices, any suggestions on how to solve it? Since it causes a lot of problems throughout the app overall performance and user experience...

Here is the part of the code that I use in my main.dart (please tell me if I did something wrong here :) ):
`final Connectivity _connectivity = Connectivity();
  StreamSubscription<ConnectivityResult> _connectivitySubscription;

  @override
  void initState() {
    super.initState();
    WizCar.initSharedPrefs();
    initConnectivity();
    _connectivitySubscription = _connectivity.onConnectivityChanged.listen((ConnectivityResult result) {
      // Got a new connectivity status!
      print('CONNECTIVITY: ' + result.toString());
      _updateConnectionStatus(result);
    });
  }
  @override
  void dispose() {
    super.dispose();
    print('MAIN DISPOSE');
    _connectivitySubscription.cancel();
  }

  Future<void> initConnectivity() async {
    var result = ConnectivityResult.none;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      result = await _connectivity.checkConnectivity();
    } on PlatformException catch (e) {
      print(e.toString());
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) {
      return Future.value(null);
    }

    return _updateConnectionStatus(result);
  }

  Future<void> _updateConnectionStatus(ConnectivityResult result) async {
    switch (result) {
      case ConnectivityResult.wifi:
        setState(() { globals.connectivity = 1; });
        print('CONNECTED WIFI ' + globals.connectivity.toString());
        break;
      case ConnectivityResult.mobile:
        setState(() { globals.connectivity = 1; });
        print('CONNECTED MOBILE');
        break;
      case ConnectivityResult.none:
        setState(() { globals.connectivity = 3; globals.offline = true; });
        print('OFFLINE: ' +globals.offline.toString());
        break;
      default:
        setState(() => globals.connectivity = 1);
        break;
    }
  }`

and here is the flutter doctor if needed: 
`
G:\projects\proj1>flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (12 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at C:\Users\vlada\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • M2103K19G (mobile) • wg9hc6qsnnw4bmq4 • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!
`

Thanks in advance!

**Comment by jigarfumakiya** [comment]
I have the same issue.
Disconnecting and connecting ethernet did not trigger **onConnectivityChanged**  stream.

**Comment by Slexom** [comment]
So I'm not the only with similar issues.
Basically when turn **off** WiFi/mobile data, nothing happen on the **onConnectivityChanged** subscription. But, sometimes, when I turn WiFi **on** again, the **ConnectivityResult** value is _**ConnectivityResult.none**_. After that, turning on/off connection print nothing

**Comment by VladanRandjelovic** [comment]
Any updates on this issue? Anybody got at least temporary solution/workaround?

**Comment by rahul-insight** [comment]
Has anybody found any solution? We are also experiencing this issue.
