### ISSUE TITLE
ConnectivityResult.none when using reverse tethering on mobile devices

### ISSUE THREAD

**Issue by Grrravity** [fluttercommunity/plus_plugins#594]
Issue occurs on: Android mobile / tablet
Plugin name: connectivity_plus
Plugin version:  2.0.2
Flutter doctor output:

``` bash
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale fr_FR.UTF-8)
    • Flutter version 2.5.0 at /xxx/xxx/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (il y a 8 semaines), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /xxx/xxx/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Android Studio (version 2020.3)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • SM T390 (mobile) • 5200a2014f9bc481 • android-arm • Android 9 (API 28)
```
Context :
We have databases and api's in dockers/minios reachable from computer's localhost only (for security purpose).
To make it possible for real devices to reach them for development purpose we need to use [reverse tethering](https://github.com/Genymobile/gnirehtet) so that trafic is coming from computer's network.
Then the mobile can reach api's through their ip adresses (ie: http://my-api.com/api becomes http://172.18.0.10/api).
/!\ I only use computer's network for the ip adresses that I need, the others are handeled by tablet's wifi. /!\

1. Connect the tablet to a wifi
2. Unable reverse tethering for the only IP's required
3. Do a request for connectivity :
```dart
var connectivityResult = await (Connectivity().checkConnectivity());
 if (connectivityResult == ConnectivityResult.mobile ||
              connectivityResult == ConnectivityResult.wifi) { ... }
```
4. the result will be none even is Wifi is anabled and working

**Comment by harriseldon** [comment]
I tried to replicate this with the connectivity_plus plugin from git and I was not able to. I used the gnirehtet tool via gnirehtet run.
The network connection showed up as wireless. I disabled wireless and it continued as wireless. I disabled data and it showed up as wireless. I turned on data. Then I stopped gnirehtet and it correctly switched to showing lte data.

**Comment by Grrravity** [comment]
Maybe by using the same command i'm using :
`gnirehtet autorun -r 172.0.12.12,172.0.12.36 & autoadb scrcpy -s '{}'`

autoadb scrcpy is just here to miror device screen so you can ignore this
You can also replace the ips in the -r parameter by the one you like to test

I'll have a try with the standard run cmd but the autorun was quite conveignent for me :p

**Comment by harriseldon** [comment]
Here is what I noticed. It does not solve your problem, but speaks to, potentially, an underlying bug in the NetworkCapabilites part of core Android.

The actual results are returned from the following located in /packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/connectivity.java:31

``` java
Network network = connectivityManager.getActiveNetwork();
      NetworkCapabilities capabilities = connectivityManager.getNetworkCapabilities(network);
      if (capabilities == null) {
        return CONNECTIVITY_NONE;
      }
```
This returns a NetworkCapabilities object as defined here: https://developer.android.com/reference/android/net/NetworkCapabilities#hasTransport(int)

It subsequently uses the hasTransport method to query if a given transport is available, checking in the following order:
WIFI
Ethernet
Cellular

``` java
//example
if (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)) {
    return CONNECTIVITY_WIFI;
}

```

If you notice when you tether, the key icon appears in the status area. This means that you are connected to a vpn. However, the existence of a vpn connection is not checked.

If someone from the plus_plugins team is willing to work with me, I can look into what it would take to add the vpn connection. For Android, this would need to be the first check.

Here is where I see the potential bug. If a VPN is available, hasTransport still returns true for Wifi. This is why you continued to see the wifi connection mode despite turning off wifi.

For the fix, I am not sure that it would be possible to change how Android handles this, but, if we add vpn, then you would at least get a notification that a vpn network is present.

**Comment by Grrravity** [comment]
Interesting... 
Tho I dont know if this case will be used in any other way but in development mode as noone ever use reverse tethering on production apps
Still, vpn-connection type detection would be a good feature to provide I guess
