### ISSUE TITLE
[connectivity_plus] No such file or directory - /var/run/dbus/system_bus_socket - on docker

### ISSUE THREAD

**Issue by boldt** [fluttercommunity/plus_plugins#602]
## System info

Issue occurs on: Linux (Docker)
Plugin name: connectivity_plus
Plugin version: 2.0.2

## Steps to Reproduce

We're trying to migrate from the depricated **connectivity 3.0.6** to the newest **connectivity_plus 2.0.2**.

### Case 1: Android App

Within the Android app, the plugin works as expected.

### Case 2: "flutter test" on Windows

One of our widgest includes the following:

```dart
Connectivity().onConnectivityChanged.listen((ConnectivityResult result) {
  ...
});
```

Running `flutter test` succeeds.

### Case 3: "flutter test" on Docker-Linux

In our CI/CD pipeline we're using the Linux-based docker image [cirrusci/flutter:2.5.3](https://hub.docker.com/r/cirrusci/flutter) to run `flutter test`, which crashes:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following SocketException was thrown running a test:
Connection failed (OS Error: No such file or directory, errno = 2), address =
/var/run/dbus/system_bus_socket, port = 0

When the exception was thrown, this was the stack:
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:677:35)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:914:12)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1668:26)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
#4      Socket._connect (dart:io-patch/socket_patch.dart:1883:22)
#5      Socket.connect (dart:io/socket.dart:724:21)
#6      DBusClient._openSocket (package:dbus/src/dbus_client.dart:721:28)
#7      DBusClient._connect (package:dbus/src/dbus_client.dart:741:11)
#8      DBusClient.callMethod (package:dbus/src/dbus_client.dart:563:11)
#9      DBusClient.getNameOwner (package:dbus/src/dbus_client.dart:401:22)
#10     DBusClient._findUniqueName (package:dbus/src/dbus_client.dart:580:28)
#11     DBusSignalStream._onListen (package:dbus/src/dbus_client.dart:132:15)
#18     DBusSignalStream.listen (package:dbus/src/dbus_client.dart:126:31)
#22     NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2216:48)
#23     ConnectivityLinux._startListenConnectivity (package:connectivity_plus_linux/src/connectivity_real.dart:53:20)
```

### Observation

It seems, that the connectivity plugin requires dbus under Linux, which seems not to be available within docker.

## Workaround

Ignore during `flutter test`:

```dart
if(!Platform.environment.containsKey('FLUTTER_TEST')) {
  Connectivity().onConnectivityChanged.listen((ConnectivityResult result) {
    ...
  });
}
```

**Comment by woprandi** [comment]
@boldt it's a regression from the old plugin ?

**Comment by jpnurmi** [comment]
I'm afraid `connectivity_plus_linux` cannot work without D-Bus because the package is based on the NetworkManager D-Bus API (via nm.dart).

**Comment by jpnurmi** [comment]
> @boldt it's a regression from the old plugin ?

The old plugin didn't have a Linux platform plugin.

**Comment by girishnair12345** [comment]
Is there any update on this issue? Any package to be installed along with docker so that this doesn't come up.  tried `apt-get install dbus` but it doesn't fix it

**Comment by jpnurmi** [comment]
What's the error?

**Comment by jpnurmi** [comment]
If it's an integration test, I'd start with something like
```
sudo apt-get install -y dbus network-manager xvfb
xvfb-run -a flutter test -d linux test/foo_test.dart
```

**Comment by girishnair12345** [comment]
> If it's an integration test, I'd start with something like
> 
> ```
> sudo apt-get install -y dbus network-manager xvfb
> xvfb-run -a flutter test -d linux test/foo_test.dart
> ```
Getting this
```
root@c5f5179ecb2d:/# apt-get install -y dbus network-manager xvfb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package network-manager
E: Unable to locate package xvfb
root@c5f5179ecb2d:/# xvfb-run -a 
```

**Comment by girishnair12345** [comment]
> What's the error?

<img width="812" alt="image" src="https://user-images.githubusercontent.com/1866371/156892731-2fc65cab-8fe2-43a2-9823-11e595d12ac3.png">

**Comment by jpnurmi** [comment]
Could it be that `apt update` is missing?

https://github.com/fluttercommunity/plus_plugins/blob/6a1d4bcc79251a6077c4e4c5aadc5fd575a081df/.github/workflows/all_plugins.yaml#L129-L133

**Comment by Alvarocda** [comment]
I got the same problem

The problem only happens when running gitlab ci/cd pipeline

```
The following SocketException was thrown running a test:
Connection failed (OS Error: No such file or directory, errno = 2), address =
/var/run/dbus/system_bus_socket, port = 0
When the exception was thrown, this was the stack:
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:948:12)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1805:26)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
#4      DBusClient._openSocket (package:dbus/src/dbus_client.dart:787:31)
#5      DBusClient._connect (package:dbus/src/dbus_client.dart:807:11)
#6      DBusClient.callMethod (package:dbus/src/dbus_client.dart:627:11)
#7      DBusClient.getNameOwner (package:dbus/src/dbus_client.dart:4[59](https://git.pjc.mt.gov.br/gdsa/externo/tco-avancado/tco-avancado-app/-/jobs/9356#L59):22)
#8      DBusClient._findUniqueName (package:dbus/src/dbus_client.dart:[64](https://git.pjc.mt.gov.br/gdsa/externo/tco-avancado/tco-avancado-app/-/jobs/9356#L64)4:28)
#9      DBusSignalStream._onListen (package:dbus/src/dbus_client.dart:132:15)
#14     DBusSignalStream.listen (package:dbus/src/dbus_client.dart:125:31)
#18     NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2303:48)
#19     ConnectivityLinux.checkConnectivity (package:connectivity_plus_linux/src/connectivity.dart:24:18)
#20     Connectivity.checkConnectivity (package:connectivity_plus/connectivity_plus.dart:50:22)
```

**Comment by jpnurmi** [comment]
Leaving aside setting up CI with NM and D-Bus, the best you can do is to replace all networking, sockets, or any other form of I/O, with mocks, fakes, stubs, or anything that results in 100% deterministic behavior.

https://github.com/jpnurmi/connectivity_plus_test
- [x] CI
- [x] widget tests
- [x] integration tests

**Comment by jpnurmi** [comment]
I'd encourage using your favorite DI pattern to inject a `Connectivity` instance and replacing it with a mock in widget tests. If you're feeling lazy, you can also use the `ConnectivityPlatform` interface to replace the underlying platform plugin. That way, you don't necessarily need to change the app at all. The example linked above demonstrates both techniques even though the latter is only used for integration tests. Last but not least, there's a CI example with a full-blown D-Bus + NetworkManager system test.  I hope this helps.
