### ISSUE TITLE
Announcing Hacktoberfest contributors and winners

### ISSUE THREAD

**Issue by mhadaily** [fluttercommunity/plus_plugins#606]
We have so many great contributors with lots of improvements coming as PRs and closing Issues. 
I will ping all GitHub usernames in this issue and send them all swags and stickers + to the top contributed a Dash! 

## We had 65 PRs by 20 amazing contributors. 59 PRs were merged, and six were closed. ##

# Amazing contributors 

1- @marcossevilla 
- https://github.com/fluttercommunity/plus_plugins/pull/593 (merged)
 
2- @vbuberen
- https://github.com/fluttercommunity/plus_plugins/pull/590 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/583 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/580 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/552 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/547 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/538 (closed)
- https://github.com/fluttercommunity/plus_plugins/pull/518 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/517 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/509 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/502 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/496 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/494 (merged) 

3- @alexbatalov
- https://github.com/fluttercommunity/plus_plugins/pull/588 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/587 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/586 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/571 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/543 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/536 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/535 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/473 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/472 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/470 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/466 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/463 (merged)

4- @navczydev 
- https://github.com/fluttercommunity/plus_plugins/pull/585 (merged)

5- @thecoderkd 
- https://github.com/fluttercommunity/plus_plugins/pull/578 (merged)

6- @pr-Mais 
- https://github.com/fluttercommunity/plus_plugins/pull/574 (merged)

7- @miquelbeltran 
- https://github.com/fluttercommunity/plus_plugins/pull/561 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/520 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/500 (merged)

8- @ChristianEdwardPadilla 
- https://github.com/fluttercommunity/plus_plugins/pull/559 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/444 (merged)

9- @Sameerkash 
- https://github.com/fluttercommunity/plus_plugins/pull/554 (merged)

10- @kyle-seongwoo-jun 
- https://github.com/fluttercommunity/plus_plugins/pull/550 (merged)

11- @Boehrsi 
- https://github.com/fluttercommunity/plus_plugins/pull/546 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/530 (merged)

12- @adityathakurxd 
- https://github.com/fluttercommunity/plus_plugins/pull/537 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/519 (merged)
- [- ](https://github.com/fluttercommunity/plus_plugins/pull/478) (closed)

13- @radvansky-tomas 
- https://github.com/fluttercommunity/plus_plugins/pull/533 (merged)

14- @juliansteenbakker 
- https://github.com/fluttercommunity/plus_plugins/pull/529 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/527 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/522 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/521 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/513 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/512  (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/511 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/510 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/508 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/507 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/491 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/476 (closed)
- https://github.com/fluttercommunity/plus_plugins/pull/442 (merged)

15- @mhadaily 
- https://github.com/fluttercommunity/plus_plugins/pull/515 (merged) 
- https://github.com/fluttercommunity/plus_plugins/pull/490 (closed)
- https://github.com/fluttercommunity/plus_plugins/pull/489 (merged)

16- @nohli 
- https://github.com/fluttercommunity/plus_plugins/pull/495 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/461 (merged)
- https://github.com/fluttercommunity/plus_plugins/pull/482 (closed) 
- https://github.com/fluttercommunity/plus_plugins/pull/481 (closed) 

17- @JigneshPatel23 
- https://github.com/fluttercommunity/plus_plugins/pull/492 (merged) 

18- @ThexXTURBOXx 
- https://github.com/fluttercommunity/plus_plugins/pull/486 (merged)

19- @duzenko  
- https://github.com/fluttercommunity/plus_plugins/pull/458 (merged)

20 - @phan-dev 
- https://github.com/fluttercommunity/plus_plugins/pull/451 (merged) 

Thank you, everyone; even though October is over, you can still help us have a great set of plugins for the communities. Keep rocking.

**Comment by mhadaily** [comment]
Congrats to all of you for doing a fantastic job for the community. Keep rocking. 

All of our contributors above (20 in total) will receive swags, and I decided to send a Dash to @juliansteenbakker @alexbatalov and @vbuberen  because of the fantastic efforts that they have made. All you need to do is create a PRIVATE repo under your Github account and share it with me to find your address and phone, and full name. Once I copied that, you can delete the repo. In this case, I can easily verify your username too. 

I also invite all of you to join our Plus_Plugins team if you want to; what you need to do is to DM/email me and tell me you are interested. We would love to have you on our team.

**Comment by juliansteenbakker** [comment]
Thanks for the rewards ! It was fun helping the plus community and improving the packages 😄. I hope I can also help maintain these packages in the future and make the community even better.

**Comment by mhadaily** [comment]
> Thanks for the rewards ! It was fun helping the plus community and improving the packages 😄. I hope I can also help maintain these packages in the future and make the community even better.

Fantastic, If you'd like to can join our team. DM me on Twitter or send me an email to discuss more.

**Comment by navczydev** [comment]
Hi Majid, Can you update once you have the information so we can delete
this repo.

Thanks

**Comment by vbuberen** [comment]
@mhadaily Joining the question above ☝🏻 😄

**Comment by mhadaily** [comment]
Hi, Yes, please delete them, the packages are in the queue to be shipped already, they must arrive to you in Feb after FlutterVikings.

**Comment by phan-dev** [comment]
@mhadaily 
Thank you!

**Comment by thecoderkd** [comment]
@mhadaily I totally missed this thread. Is it still possible to send you over my details? Please
