### ISSUE TITLE
Connectivity plus not working with Linux

### ISSUE THREAD

**Issue by Silfalion** [fluttercommunity/plus_plugins#626]
## System info

Issue occurs on: Linux
Plugin name: connectivity_plus
Plugin version: 2.0.3
Flutter doctor output: 

all good

## Steps to Reproduce

1. create a flutter app with the connectivity_plus plugin
2. run the app

## Logs

Unhandled Exception: MissingPluginException(No implementation found for method check on channel dev.fluttercommunity.plus/connectivity)

All the errors are about unused imports, using prints, overriding fields(of my own classes) and constants

 all good

**Comment by harriseldon** [comment]
Can you provide more details? For example, what distribution and desktop environment are you using? Are you using NetworkManager to manage your network? If you do not know the answer to this last question, the answer to the first might help.
I just created a simple app at https://gitlab.com/dgreengas/flutter_connectivity_test_linux
It just listens to the stream of network changes and shows it on the main screen. I tested it on the following:
Operating System: Manjaro Linux
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.14.18-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-6200U CPU @ 2.30GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 520

Flutter version:
Flutter (Channel dev, 2.6.0-11.0.pre, on Manjaro Linux 5.14.18-1-MANJARO, locale en_US.UTF-8)

**Comment by Silfalion** [comment]
Sure. I'm using Ubuntu mint so mint desktop and the error happens at this exact line:

```
        connectivityResult = await (Connectivity().checkConnectivity());
```

Flutter version is 2.5.3.

Will test the app you provided very soon and report back.

**Comment by Silfalion** [comment]
upgraded to flutter 2.8 and tested with the connectivity plus linux 1.1.1 version. Everything works great now. Thank you!

**Comment by jpnurmi** [comment]
Thanks for the update!
