### ISSUE TITLE
Update and align Dart SDK & Flutter version constraints

### ISSUE THREAD

**Issue by jpnurmi** [fluttercommunity/plus_plugins#63]
@slightfoot proposed updating every `pubspec.yaml` to:
```
environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.4 <2.0.0"
```

**Comment by mhadaily** [comment]
@pr-Mais  @Schwusch  @bruno-garcia  @miquelbeltran what do you think about this

**Comment by jpnurmi** [comment]
I don't remember how Simon concluded those exact versions, but I think the current engaging recommendation (`pub publish`) is to not have the `<2.0.0` upper boundary... :wink:

**Comment by miquelbeltran** [comment]
Yes, adding the upperbound will raise a warning with the pub publish check. The rest should be fine and I'd be happy to have a unified version requirement!

**Comment by pr-Mais** [comment]
I'm not yet so familiar with how the upper bound would affect the packages, but every chance of unifying things between packages would be nice to consider

**Comment by mhadaily** [comment]
Hey, 
it's an old issue, but today I'd like to propose a new proposal

```
environment:
  sdk: ">=2.13.0-0 <3.0.0"
  flutter: ">=2.2.0 <3.0.0"
```

I don't see any advantages of having an older version of SDKs as we also don't support it anyway. 

What do you think?

**Comment by miquelbeltran** [comment]
I am not sure if the issue is still there, but having an upper bound (<3.0.0) will raise a warning by the pub publish check job.
