### ISSUE TITLE
[connectivity_plus] can't check wifi connection without internet access

### ISSUE THREAD

**Issue by X0Rz1st** [fluttercommunity/plus_plugins#632]
Thank you for providing this plugin!

# System info

Issue occurs on: iOS
Plugin name: connectivity_plus
Plugin version: 2.0.3
Flutter doctor output:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale de-DE)
    • Flutter version 2.5.3 at /Users/smmprojekt/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/smmprojekt/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • iPad (mobile) • 26e4XXX • ios • iOS 15.1 19B74

! Doctor found issues in 1 category.
```

## Steps to Reproduce
I need to figure out whether the device is connected to a wifi access point (that has no internet connection) or not.

1. subscribe to onConnectivityChanged
2. Establish connection to wifi access point _without_ internet connection via system settings
3. Return to app
4. No onConnectivityChanged event occurs

If I connect to a wifi with internet connection it works fine.
Also on Android it works as expected.
Can't find anything in the documentation about this behaviour.

**Comment by matthias-steinkamp** [comment]
thanks for the ticket. in our project, we are struggling with this issue, too. would be great, if this would be fixed, soon.

**Comment by vbuberen** [comment]
@X0Rz1st Did I understand it correctly that the problem is in having no events fired when Android device connects to some wi-fi access point without internet?

**Comment by kostov** [comment]
On iOS Connectivity().checkConnectivity() always returns ConnectivityResult.none when we connected to wifi without Internet access.

**Comment by Johandrex** [comment]
Having the same issue as @X0Rz1st, ConnectivityResult().checkConnectivity() never changes to .none on iOS.

**Comment by kuhnroyal** [comment]
Yea same here, additionally there is no event when having mobile data disabled and switching between

Wifi (no internet)
Wifi disabled

Can switch as often as I want, there is no event.

**Comment by kuhnroyal** [comment]
Wonder if this can be solved with `NWPathMonitor` which is iOS 12+

**Comment by Johandrex** [comment]
> Wonder if this can be solved with `NWPathMonitor` which is iOS 12+

Very grateful that you've (hopefully) fixed the issue, thanks! Do you have any idea when the plugin will release a new version with the fix included?
