### ISSUE TITLE
[Proposal] Apps filtering and custom UI (share_plus)

### ISSUE THREAD

**Issue by ggdream** [fluttercommunity/plus_plugins#635]
Mainly for mobile:

## Problem
1. In many cases, it is just for sharing to a part of the application. It’s inconvenient for users to find out if all are displayed directly.
2. When sharing, existing native applications often include functions such as copying links. But the package calls the system's native dialog, which makes the flutter layer unable to implement this function.

## Solution
1. Added API to get all package names on this machine
2. Add an API similar to the existing `share`, but with a new package name list parameter
2. New API, providing package name parameters to determine the application to be called

**Comment by NickTheDev** [comment]
Has there been any progress on filtering apps for the share intent?
