### ISSUE TITLE
[share_plus] Huge shadow in background when opening share sheet on iPad

### ISSUE THREAD

**Issue by saibotma** [fluttercommunity/plus_plugins#637]
Had to take a photo as the screenshot processing would minify the shadow.
The photo is self-explanatory. Sharing with Telegram in this example:

![IMG_20211201_211641__01](https://user-images.githubusercontent.com/26022902/144307846-972d9c3e-4b62-4243-b50d-5b47aa920625.jpg)

## System info

Issue occurs on: iOS 14.8.1 (iPad; did not test other OS versions)
Plugin name: share_plus
Plugin version: 3.0.4
Flutter doctor output:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-DE)
    • Flutter version 2.5.3 at /Users/tobias/Documents/Dev/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
```

Everything else is also green ✅

**Comment by saibotma** [comment]
This is not stale.

**Comment by miquelbeltran** [comment]
- Can you provide a code sample? I cannot reproduce the issue using the example in share_plus.
- Is it only happening with Telegram, or also happens with other apps?
- Is this issue present on iPhone as well?

**Comment by saibotma** [comment]
Not stale, will provide a code sample soon.

**Comment by saibotma** [comment]
Tested it again using version 9.0.0 and iPadOS 17.5 and the issue is gone.
