### ISSUE TITLE
Unable to create ipa for iOS app + Reachability issue

### ISSUE THREAD

**Issue by dheerajHipster** [fluttercommunity/plus_plugins#638]
I'm able to run project in Simulators and real device but not able to create ipa for productions

## System info

Issue occurs on: iOS
Plugin name: connectivity_plus
Plugin version: 2.1.0
Flutter doctor output: 

hipster@Hipsters-MacBook-Air barePack_flutter % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
![Screenshot 2021-12-03 at 5 47 03 PM](https://user-images.githubusercontent.com/68731433/144601311-ee05ed3d-6f00-428c-bd04-47f870de4204.png)

I'm using below plugins in my projects

cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  page_indicator: ^0.4.1
  flutter_local_notifications: ^6.0.0
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^10.0.1
  firebase_auth: ^1.1.3
  google_sign_in: ^5.0.2
  apple_sign_in: ^0.1.0
  url_launcher: ^6.0.3
  cloud_functions: ^3.2.0
  flutter_webview_plugin: ^0.4.0
  dotted_border: ^2.0.0
  qr_code_scanner: ^0.5.1
  flutter_facebook_login: ^3.0.0
  location: ^4.3.0
  firebase_dynamic_links: ^2.0.5
  flutter_appavailability: ^0.0.21
  google_maps_flutter: ^2.0.6
  cached_network_image: ^3.0.0
  toast: ^0.1.5
  geolocator: ^7.2.0+1
  stripe_payment: ^1.1.4
  http: ^0.13.3
  country_picker : ^2.0.6
  sliding_up_panel: ^2.0.0+1
  flutter_keyboard_visibility: ^5.1.0
  device_info: ^2.0.2
  package_info: ^2.0.2
  external_app_launcher: ^2.0.2
  pin_code_fields: ^7.3.0
  rename: ^1.3.1
  new_version: ^0.2.2
  permission_handler: ^8.1.4+2
  mixpanel_flutter: ^1.2.1
  firebase_in_app_messaging: ^0.5.0+9
  connectivity_plus: ^2.1.0

 
## Logs
![Screenshot 2021-12-03 at 5 50 51 PM](https://user-images.githubusercontent.com/68731433/144601682-29c00806-1e3d-49c5-9dfc-95d6e51a4e5f.png)

PLEASE HELP

**Comment by ritheshSalyan** [comment]
@dheerajHipster Did you solve this issue?

**Comment by joyincomp** [comment]
same problem here

**Comment by rpekarek-tc** [comment]
Same problem after updating to Flutter 2.10.4, anyone find a work around?

**Comment by original-one** [comment]
I get "Header 'Reachability-Swift.h' not found" issue too

**Comment by hcaz** [comment]
I found this comment elsewhere which suggests this is a conflict between Apples reachability class - https://github.com/pusher/pusher-websocket-swift/issues/235#issuecomment-545833987
