### ISSUE TITLE
[connectivity_plus] Connectivity changes to mobile even when connected to wifi

### ISSUE THREAD

**Issue by shailu95** [fluttercommunity/plus_plugins#641]
Connectivity listener changes the connection to mobile when wifi signal strength changes on iOS not tested on Android.

**Comment by dan1229** [comment]
+1 this - I get mobile on web (running on my desktop) even if wifi is off.

**Comment by dan1229** [comment]
Is there any progress on this? It makes this plugin more or less useless on web.

**Comment by miquelbeltran** [comment]
Should be fixed by #904
