### ISSUE TITLE
[share_plus] Android 11 not working

### ISSUE THREAD

**Issue by Noviko777** [fluttercommunity/plus_plugins#643]
Hi!
I can not share the file on Android 11, I suspect that it does not work due to Scoped storage. Please fix it as soon as possible.

**Comment by Noviko777** [comment]
E/ActivityThread: Failed to find provider info for {applicationId}.flutter.share_provider

**Comment by vbuberen** [comment]
Hello. Thanks for you report.

Could you provide proper tech info as requested by the issue template? Without it we couldn't provide good support to resolve the possible issue. 

> Please fix it as soon as possible.

This is an open source project where people work in their free time. If it is something that is of priority you are more than welcomed to contribute.

**Comment by Noviko777** [comment]
It was necessary to enable MIUI optimization

**Comment by vbuberen** [comment]
@Noviko777 You closed the issue because the problem was in something else?

**Comment by szuwest** [comment]
> E/ActivityThread: Failed to find provider info for {applicationId}.flutter.share_provider

android 11 need file provider. anybody can fix it?
