### ISSUE TITLE
[share_plus] Save to Files on iOS results in an error

### ISSUE THREAD

**Issue by uchidacode** [fluttercommunity/plus_plugins#645]
## System info

Issue occurs on: iOS
Plugin name: share_plus
Plugin version: 3.0.4
Flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.0)

## Problem
When I click Save to Files on iOS, I get the following error. Also, AirDrop will immediately fail after selecting the destination.

```
[NSExtension] Extension request contains input items but the extension point does not specify a set of allowed payload classes. The extension point's NSExtensionContext subclass must implement `+_allowedItemPayloadClasses`. This must return the set of allowed NSExtensionItem payload classes. In future, this request will fail with an error. Extension: <EXConcreteExtension: 0x2804933c0> {id = com.apple.DocumentManagerUICore.SaveToFiles} Items: (

    "<NSExtensionItem: 0x2833c0690> - userInfo: {\n    NSExtensionItemAttachmentsKey =     (\n        \"<NSItemProvider: 0x281a98e70> {types = (\\n    \\\"public.zip-archive\\\",\\n    \\\"public.file-url\\\"\\n)}\"\n    );\n    \"com.apple.UIKit.NSExtensionItemUserInfoIsContentManagedKey\" = 0;\n}"
)

[ShareSheet] cancelled request - error: invalid argument

```

is there any solution for that?

**Comment by flogy** [comment]
What was the solution to this?

**Comment by lecicdjuro** [comment]
Why this issue is closed? It's still present. Any explanation? @uchidacode

**Comment by EnduringBeta** [comment]
Not sure about the AirDrop problem, but over [here](https://github.com/fluttercommunity/plus_plugins/issues/730#issuecomment-1182643141) there seems to be a big difference between error logs in debug mode versus release mode.

**Comment by uchidacode** [comment]
I had accidentally Closed it by mistake. I still haven't resolved the issue, so I need you to investigate.

**Comment by abindrip** [comment]
Has anyone got a solution so far?

**Comment by simplenotezy** [comment]
This would be a really great bug to get fixed! Can confirm I have the same issue.
