### ISSUE TITLE
[android_alarm_manager_plus] crash 

### ISSUE THREAD

**Issue by adrianvintu** [fluttercommunity/plus_plugins#649]
Hello, I have installed `android_alarm_manager_plus: ^2.0.3` and a lot of crashed come in.

Please let me know if there is something else I can add to make it easier for you to debug.

```
 Caused by java.lang.NullPointerException
Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath (FlutterLoader.java:2)
io.flutter.view.FlutterMain.findAppBundlePath (FlutterMain.java:8)
dev.fluttercommunity.plus.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate (FlutterBackgroundExecutor.java:17)
dev.fluttercommunity.plus.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate (FlutterBackgroundExecutor.java:21)
dev.fluttercommunity.plus.androidalarmmanager.AlarmService.onCreate (AlarmService.java:20) 
```
![2021-12-12 15_37_21-Window](https://user-images.githubusercontent.com/33379688/145714625-2d2147e6-be2f-4cf9-9ca9-0140777a80fe.png)
![2021-12-12 15_37_54-Window](https://user-images.githubusercontent.com/33379688/145714630-a2317fc8-c46d-4c51-8074-efdf86f9e99d.png)

**Comment by valentintintin** [comment]
Hi @adrianvintu,

I just found this lib today and I had the same error.
Here is the fix : add to your android/app/main/AndroidManifest.xml : `<application android:name="io.flutter.app.FlutterApplication"`

Related : 
- https://github.com/fluttercommunity/plus_plugins/issues/144
- https://github.com/transistorsoft/flutter_background_fetch/issues/160

**Comment by adrianvintu** [comment]
Thank you very much @valentintintin

**Comment by vbuberen** [comment]
@adrianvintu The suggested solution worked for you?

**Comment by adrianvintu** [comment]
@vbuberen i did not deploy the change because i feared it may not work. in other words: i don't know, i did not test it.

**Comment by vbuberen** [comment]
Please let me know if it fixed the issue when you try it. Would like to update docs if the suggested solution works.

**Comment by adrianvintu** [comment]
Ok @vbuberen, but I will not deploy this soon. Maybe someone else will do it and announce it here.

**Comment by vbuberen** [comment]
I looked a little bit deeper in the code of alarm_manager_plus plugin and believe that we can provide a fix from our side which won't require adding anything into a manifest file. 

I will provide more info after testing a possible fix.

**Comment by adrianvintu** [comment]
@vbuberen I have added the fix provided by @valentintintin, deployed to users and haven't seen a single crash.
https://github.com/fluttercommunity/plus_plugins/issues/649#issuecomment-996058714
I think it's pretty safe to add it to the documentation.
Thank you for your wonderful work!

**Comment by vbuberen** [comment]
For me it seems that current implementation of `android_alarm_manager_plus` has a very old implementation and wasn't properly migrated from v1 embedding to v2. I would love to try and tackle it somewhere in the nearest time as I found more issues like this one: https://github.com/fluttercommunity/plus_plugins/issues/266
