### ISSUE TITLE
[share_plus] iOS - The share window does not appear.

### ISSUE THREAD

**Issue by mikrul85** [fluttercommunity/plus_plugins#658]
When calling the plugin on the iOS simulator and on a real iPad device, the share window does not appear!
Plugin version: 3.0.4

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale ru-RU)
    • Flutter version 2.5.3 at /Users/mihail/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mihail/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2, Build version 13C90
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Users/mihail/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
```

**Comment by viniciusddrft** [comment]
Hi I'm not one of the plugin developers but I just came to let you know if you haven't seen that the plugin is currently only for android.

**Comment by mikrul85** [comment]
> Hi I'm not one of the plugin developers but I just came to let you know if you haven't seen that the plugin is currently only for android.

https://pub.dev/packages/share_plus - it says here that the plugin supports iOS
https://github.com/flutter/flutter/issues/95292 - and then I was informed that the share plugin is no longer supported and offered to switch to share_plus

**Comment by Sachinsowri** [comment]
Flutter 2.8.1 and Share_plus :3.0.4 device ipad(IOS 15)  
when i tirgger share file this error come

 " Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x283611770 V:[_UIActivityContentNavigationBar:0x15423c320]-(0)-[UIFocusContainerGuide:0x282a75a40'UINavigationControllerContentFocusContainerGuide']   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-01-19 13:06:47.837857+0530 Runner[6119:2049283] [default] LaunchServices: store (null) or url (null) was nil: Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=264, _LSFunction=-[_LSDReadClient getServerStoreWithCompletionHandler:]}
2022-01-19 13:06:47.839074+0530 Runner[6119:2049283] [default] Attempt to map database failed: permission was denied. This attempt will not be retried.
2022-01-19 13:06:47.839194+0530 Runner[6119:2049283] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=264, _LSFunction=-[_LSDReadClient getServerStoreWithCompletionHandler:]}
2022-01-19 13:06:47.974794+0530 Runner[6119:2049283] [LayoutConstraints] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x283619090 H:|-(0)-[_UIActivityContentTitleView:0x154207f40]   (active, names: '|':_UINavigationBarContentView:0x15423c770'Share From Output Books' )>",
    "<NSLayoutConstraint:0x283619180 _UIActivityContentTitleView:0x154207f40.trailing == _UINavigationBarContentView:0x15423c770'Share From Output Books'.trailing   (active)>",
    "<NSLayoutConstraint:0x283619860 LPLinkView:0x154208470.leading == UILayoutGuide:0x282c65dc0'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x2836196d0 H:[LPLinkView:0x154208470]-(27)-|   (active, names: '|':_UIActivityContentTitleView:0x154207f40 )>",
    "<NSLayoutConstraint:0x283620550 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x15423c770'Share From Output Books'.width == 0   (active)>",
    "<NSLayoutConstraint:0x283619770 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x282c65dc0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIActivityContentTitleView:0x154207f40 )>"
)
" and share window not opend . it works fine in Android

**Comment by zambetpentru** [comment]
The good news is that there is a simple fix:

  Share.share(
      'https://www.google.ie', sharePositionOrigin: Rect.fromLTWH(0, 0, 300, 300));

https://github.com/flutter/flutter/issues/47220

@ben-xD FYI
