### ISSUE TITLE
share_plus: ^3.0.4  While sharing multiple images with text on Whatsapp the text is copied with all the images.

### ISSUE THREAD

**Issue by RiyaJaggi28** [fluttercommunity/plus_plugins#679]
## System info
**Device**
Realme 8S

**Plugin name**: share_plus
**Plugin version**: ^3.0.4

**Flutter doctor output:**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (4 available)

**Bug Description**
Sharing multiple images with text on whatsapp, the added text is shared along with each image added.

**To Reproduce**
 Share.shareFiles(imagesToShare,
      text: "Sending images to whatsapp"); // imagesToShare is list of images to be shared.

**Expected Behaviour**
It should share all images as it is doing right now but the attached text should get linked only with one image.

**Actual Behaviour**
Pass 7 images with text then the text will also be sent seven times along with each image.

**Screenshots**
![Screenshot 2022-01-03 at 4 18 26 PM](https://user-images.githubusercontent.com/89966518/147922351-4eb8b06b-7679-4872-83ab-bd7053fca7dc.png)

![Screenshot 2022-01-03 at 4 18 44 PM](https://user-images.githubusercontent.com/89966518/147922387-2db3dcce-1a31-4711-b6e0-5b3606a441e1.png)

@brianegan @jpnurmi @alexbatalov @KirillArtemenko @slightfoot

**Comment by abingeorgev** [comment]
Are there any updates or fixes in the pipeline for this? Same issue is happening with us.
