### ISSUE TITLE
[share_plus] Share subject does not appear in email

### ISSUE THREAD

**Issue by appinteractive** [fluttercommunity/plus_plugins#691]
## Description

When I try to share a link or a message vie mail, using the Share_Plus plugin on iOS (maybe both), the subject is empty, but it should contain it.

## System info

Issue occurs on: iOS (maybe both)
Plugin name: Share_Plus
Plugin version: 3.0.4
Flutter doctor output: 

```
❯ flutter doctor
Doctor summary (to see all details, run flutter
doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm,
    locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!
```

## Steps to Reproduce

1. `Share.share('http://example.org', subject: 'my subject in case of email');`
2. choose mail from sharing dialog
3. see that the subject is empty in all email apps

**Comment by Coronon** [comment]
> @Coronon @miquelbeltran could someone if you talented guys take a look? 🙂

I'm a little busy until the weekend but will try to look into it :)

**Comment by Coronon** [comment]
I was able to reproduce the issue: It seems that Apple handles pure URL shares differently (loads the website icon and title) and therefore ignores our way of setting the subject. I have however found a way to override this behavior and still force a user chosen subject.

Will submit a PR soon :)

**Comment by Coronon** [comment]
You can try these changes with this repo: [share_plus_example](https://github.com/Coronon/share_plus_example)

**Comment by miquelbeltran** [comment]
> @ Coronon @ miquelbeltran could someone if you talented guys take a look? slightly_smiling_face

Please do not direct quote repo members asking for updates.

**Comment by appinteractive** [comment]
@Coronon Thanks man! It works like a charm (on iOS) Android I can't get hold of a working mail client atm. 

@miquelbeltran sorry, I did not want to bind any resources it that was the case or skip any priorities, my intention was only to get awareness. ✌️ Was not aware of any problems in that regard 😬
