### ISSUE TITLE
[share_plus] Share image in Flutter Web doesn't work

### ISSUE THREAD

**Issue by joshipucher** [fluttercommunity/plus_plugins#692]
In Flutter Web this doesn't open anything, even though the image url exists:
Share.shareFiles(['https://mywebsite.com/image.jpg']);

With text only it works (it will open my email software with the entered text).

Also, it would be nice if it would be possible to share an image from a Uint8List in Flutter Web

**Comment by jithware** [comment]
Appears to be the same for 

``` Share.share('check out my website https://example.com', subject: 'Look what I made!');``` 

Opens a a new about:blank tab with no contents on Chrome Version 97.0.4692.71 (Official Build) (64-bit)

```<html><head></head><body></body></html>```

**Comment by miquelbeltran** [comment]
Your bug doesn't follow the bug reporting template: https://github.com/fluttercommunity/plus_plugins/blob/main/.github/ISSUE_TEMPLATE/BUG.md

Please use the template or we will have to close this issue.
