### ISSUE TITLE
"AndroidAlarmManager.periodic" Not working. only work for first time but not interval also not showing any error.

### ISSUE THREAD

**Issue by ABmamunHoneybee** [fluttercommunity/plus_plugins#709]
``void printHello() {
  final DateTime now = DateTime.now();
  final int isolateId = Isolate.current.hashCode;
  print("[$now] Hello, world! isolate=$isolateId");
  NotificationService().showScheduledNotification();
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await AndroidAlarmManager.cancel(0);
  await AndroidAlarmManager.initialize();
  runApp(const MyApp());
  await AndroidAlarmManager.periodic(const Duration(minutes: 1), 0, printHello);
}

**Comment by vbuberen** [comment]
Please provide info according to suggested issue template. Without full information and description we can't help.

**Comment by hedihadi** [comment]
i have the same problem, reported here https://github.com/fluttercommunity/plus_plugins/issues/686
