### ISSUE TITLE
Adding device_info_plus to the project completely breaks the build process without an error

### ISSUE THREAD

**Issue by arisAlexis** [fluttercommunity/plus_plugins#710]
Flutter project working normally. Adding in packages.yaml device_info_plus: ^3.2.1 makes the Run process stuck at: Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'..

Commenting out this package runs the project correctly. No other error message. All AVDs. 

Latest Intellij, latest Dart/Flutter plugins.

**Comment by miquelbeltran** [comment]
Your bug doesn't follow the bug reporting template: https://github.com/fluttercommunity/plus_plugins/blob/main/.github/ISSUE_TEMPLATE/BUG.md

Please use the template or we will have to close this issue.
