### ISSUE TITLE
On iOS we can share only text or image, not both on same time.

### ISSUE THREAD

**Issue by boparaiamrit** [fluttercommunity/plus_plugins#712]
## System info
iOS 15.x
Flutter 2.8

Platform the Issue occurs on:
Plugin name: Share Plus
Plugin version: 3.0.4

## Steps to Reproduce
Try to share both text and image files at the same time.

### Workaround
![image](https://user-images.githubusercontent.com/1220153/151317553-997380c3-500b-41de-9e6d-9edfd4593ed8.png)

**Comment by miquelbeltran** [comment]
Your bug doesn't follow the bug reporting template: https://github.com/fluttercommunity/plus_plugins/blob/main/.github/ISSUE_TEMPLATE/BUG.md

Please use the template or we will have to close this issue.

**Comment by debasmitasarkar** [comment]
Same issue is here. Any progress on this ? @miquelbeltran

**Comment by miquelbeltran** [comment]
No, there's no progress on this because it is a limitation on the apps receiving the share intent.

Also, don't ask for progress on open source projects.
