### ISSUE TITLE
ShareFiles does not work only text sharing works

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [fluttercommunity/plus_plugins#718]
First I have used `Share.share()` to share the text. It works great but when I use `Share.sharefiles(`) it does not work. 
Here is my code for sharing image:
`Future<void> shareProduct(
    {required String refferal
, required String imageUrl}) 
async {
  log("imageUrl in share product = $imageUrl");
  final url = Uri.parse(imageUrl);
  final responce = await http.get(url);
  final bytes = responce.bodyBytes;
  final temp = await getTemporaryDirectory();
  final path = "${temp.path}/image.jpg ";
  File(path).writeAsBytes(bytes);
  log("refferalurl = $refferal");
  log("shareProduct fired");
  Share.shareFiles([path], text: refferal,);
}`

**Comment by miquelbeltran** [comment]
This issue has been discussed in many other tickets like https://github.com/fluttercommunity/plus_plugins/issues/711

In short: Some apps don't accept Text + Image when sharing.

**Comment by UmairSaqibBhutta** [comment]
@miquelbeltran issue has been discussed earlier but not yet solved...

**Comment by vbuberen** [comment]
> @miquelbeltran issue has been discussed earlier but not yet solved...

So instead of adding a new info to the original issue if you have any, you believe it is better to spam with opening duplicate issues?
