### ISSUE TITLE
[connectivity_plus] Mobile connectivity is reported when WIFI signal strength is low/medium and WIFI Assist is enabled on iOS

### ISSUE THREAD

**Issue by ghermana** [fluttercommunity/plus_plugins#721]
On iOS with [WIFI Assist](https://support.apple.com/en-us/HT205296) enabled, the connectivity_plus plugin reports Mobile connectivity instead of WIFI when the WIFI signal strength is at medium or low (1/3 or 2/3 in top bar of the iPhone).

To clarify: WIFI connectivity is still possible, Chrome connects on WIFI, and the WIFI network interfaces are all available. \
But the plugin reports mobile. This seems to be due to the underlying Reachability check that reports mobile on the default route.

This problem seems similar to [issues/641](https://github.com/fluttercommunity/plus_plugins/issues/641).

**Comment by dan1229** [comment]
+1 - experiencing this as well. really frustrating as it makes this package kind of useless in the meantime.

**Comment by dan1229** [comment]
Is there any progress on this? It makes this plugin more or less useless on web.
