### ISSUE TITLE
[connectivity_plus] Flutter 2.10 requires connectivity_plus to use embedding v2

### ISSUE THREAD

**Issue by lukaskirner** [fluttercommunity/plus_plugins#723]
The plugin connectivity_plus uses embedding v1 which is deprecated. Flutter 2.10.0, which was released yesterday, enforces the use of embedding v2. The log output is misunderstanding. It suggests the developer to migrate the app to use embedding v2 but instead of the app the plugin does not use embedding v2.

## System info

Platform the Issue occurs on: Android
Plugin name: connectivity_plus
Plugin version: 2.2.0

## Steps to Reproduce
1. use flutter in version 2.10.0

<details>
<summary>Logs</summary>

```dart
Running "flutter pub get" in test...              1,756ms
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `connectivity_plus` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this
command.
```

</details>

<details>
<summary>Flutter doctor output</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-DE)
```

</details>

**Comment by Chinmay-KB** [comment]
As you can see in the logs, the issue is with the app using v1 embedding and not the plugin. `connectivity_plugin` already uses v2 embedding. I am currently using this plugin in production for various projects which have v2 and it works fine on Flutter 2.10.

**Comment by purgeyao** [comment]
@Chinmay-KB May I ask when do you plan to release the plug-in with V2, because we have also encountered this problem

**Comment by Chinmay-KB** [comment]
@lukaskirner said the logs are misleading because it says the app to be migrated to v2. But I am not able to replicate this issue on my project with this plugin. Also when I go through the code, it seems to me the plugin is already using v2 if i'm not wrong

**Comment by vbuberen** [comment]
`Connectivity_plus` already migrated to embedding V2. Please check logs of your project carefully.

Here is an example of logs from the project I needed to update just yesterday:

```
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  /Users/vb/StudioProjects/app/android/app/src/main/AndroidManifest.xml uses `android:name="io.flutter.app.FutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Running "flutter pub get" in app...
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `connectivity_plus` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
```

As you can see `connectivity_plus` requires the app to be migrated, not the plugin isn't migrated.

**Comment by Mashood97** [comment]
This issue started coming again when i am using 5.0.1
Can you please look into this?
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `connectivity_plus` requires your app to be migrated to the Android embedding v2. Follow the steps on the migration doc above and re-run this command.
