### ISSUE TITLE
Provide details how to configure development IDE for working with plus_plugins monorepo

### ISSUE THREAD

**Issue by ekuleshov** [fluttercommunity/plus_plugins#724]
## Use case

The section "5.1 Getting started" of the `CONTRIBUTING.md` simply says "git fetch, git checkuput, hack away".
That is not enough details to get the project's code into an IDE, especially when the contributor's intent to look only at individual plugins and some subset of platforms (e.g. mobile ones).

Unlike may other open-source plugins and packages, I can't see an obvious way to get parts of the code imported into the IDE to allow the "hack away" part on this large monorepo.

For example, this is how one of the projects opens in AS after running the prescribed `melos bootstrap`:

![image](https://user-images.githubusercontent.com/440954/152699344-dad3a3ef-e655-495d-acd3-972fde66f88e.png)

## Proposal

Please provide details how to get to code into IDE, be able to compile it there and run the tests from the common Flutter IDEs, e.g. VS Code and Android Studio.

**Comment by Chinmay-KB** [comment]
Could you explain what you exactly mean by "get code into IDE"?

**Comment by ekuleshov** [comment]
> Could you explain what you exactly mean by "get code into IDE"?

See screenshot illustrating it in the issue description. You don't expect contributors to "hack away" in a Notepad, or do you?

**Comment by Chinmay-KB** [comment]
I use VS code for flutter. To check on Android Studio I opened this folder, it worked fine there. I have not installed anything other than Flutter plugin. It's something to do with the IDE, this isn't how its supposed to look out of the box.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/13520364/152861358-ddf14f61-e34e-4847-8bae-04c76523090d.png">

**Comment by ekuleshov** [comment]
That is what I'd have expected to see but it doesn't look like that here. Either some steps are missing or you "opened this folder" in AS somewhat differently.

**Comment by Chinmay-KB** [comment]
After running melos bootstrap in the terminal, I selected "Open project", then navigated to packages-> package_info_plus -> package_info_plus and that's it.
