### ISSUE TITLE
android_alarm_manager_plus Crashing App

### ISSUE THREAD

**Issue by hammadpervez** [fluttercommunity/plus_plugins#725]
I am using latest version of flutter 2.8.1 and also latest version of `android_alarm_manager_plus: ^2.0.4`  It's crashing my application .

![image](https://user-images.githubusercontent.com/33895363/152700965-e1717235-80e6-4d79-b06c-0a227160e33d.png)

![image](https://user-images.githubusercontent.com/33895363/152700983-d4a7b08a-3524-49db-bc00-1b03761cc1a3.png)

It throws an error ClassNotFoundException Component

**Comment by vbuberen** [comment]
Please provide information according to provided bug template.
