### ISSUE TITLE
[network_info_plus] Warning: Deprecated methods

### ISSUE THREAD

**Issue by aklehm** [fluttercommunity/plus_plugins#727]
I'm getting a warning while building my flutter app with network_info_plus version 2.1.2:

`C:\flutter\.pub-cache\hosted\pub.dartlang.org\network_info_plus-2.1.2\android\src\main\java\dev\fluttercommunity\plus\network_info\NetworkInfo.java:46: warning: [deprecation] getConnectionInfo() in WifiManager has been deprecated
    if (wifiManager != null) wifiInfo = wifiManager.getConnectionInfo();
                                                   ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\network_info_plus-2.1.2\android\src\main\java\dev\fluttercommunity\plus\network_info\NetworkInfo.java:49: warning: [deprecation] getIpAddress() in WifiInfo has been deprecated
    if (wifiInfo != null) i_ip = wifiInfo.getIpAddress();
                                         ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\network_info_plus-2.1.2\android\src\main\java\dev\fluttercommunity\plus\network_info\NetworkInfo.java:108: warning: [deprecation] getDhcpInfo() in WifiManager has been deprecated
    DhcpInfo dhcpInfo = this.wifiManager.getDhcpInfo();
                                        ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\network_info_plus-2.1.2\android\src\main\java\dev\fluttercommunity\plus\network_info\NetworkInfo.java:122: warning: [deprecation] getConnectionInfo() in WifiManager has been deprecated
    return wifiManager == null ? null : wifiManager.getConnectionInfo();
                                                   ^
4 warnings`

flutter docotr -v:
`[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19042.1466], locale de-DE)
    • Flutter version 2.10.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (8 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Android_SDK
    • Platform android-31, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = C:\Android_SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.64.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`
Do you have any suggestions, to fix it?

**Comment by vbuberen** [comment]
Hi. It is not a bug, but just warnings. 
Network info plus supports lots of Android versions, including very old ones and to get network information on old device the plugin also uses APIs which are already deprecated in newer Android versions.
These warnings that you get during the builds aren't something that will fail the build or cause any issues, so you shouldn't worry about it.
