### ISSUE TITLE
identifierForVendor change when reset on iphone

### ISSUE THREAD

**Issue by hoangde2811** [fluttercommunity/plus_plugins#729]
## System info

Platform the Issue occurs on:
Plugin name:
Plugin version:

## Steps to Reproduce

1. ...
2. ...
3. ...

<details>
<summary>Logs</summary>

```dart
```

</details>

<details>
<summary>Flutter doctor output</summary>

```
```

</details>

**Comment by vbuberen** [comment]
Issue has no required info.
