### ISSUE TITLE
Error while sharing a file got by http.get (bytes)

### ISSUE THREAD

**Issue by mauricioluz** [fluttercommunity/plus_plugins#735]
I'm getting a file through http.get (in bytes), writing it in local storage as a PDF file and after I'm trying to share this file using Share.shareFiles. But I'm not able to share it. Any option that I'm using (as sharing on whatsapp, open in a pdf reader, printing, save in smartphone files) it is showing an error (could not share, could not copy this file). The same thing is happening when trying to share a PNG file.
I'm testing in debug mode.

There is something that I need to do addittionaly?
Someone can help me please?

I'm using Flutter 2.8.1.

**Comment by cutzmf** [comment]
have same problem, cant share downloaded jpeg & pdf files

console log on share jpeg
`[default] LaunchServices: store (null) or url (null) was nil: Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=264, _LSFunction=-[_LSDReadClient getServerStoreWithCompletionHandler:]}
[default] Attempt to map database failed: permission was denied. This attempt will not be retried.
[db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=264, _LSFunction=-[_LSDReadClient getServerStoreWithCompletionHandler:]}
[default] -imageForImageDescriptor: can do IO please adopt -imageForDescriptor: for IO free drawing or -prepareImageForDescriptor: if IO is allowed. (This will become a fault soon.)
[LayoutConstraints] Changing the translatesAutoresizingMaskIntoConstraints property of a UICollectionReusableView that is managed by a UICollectionView is not supported, and will result in incorrect self-sizing. View: <_UIActivityContentFooterView: 0x12af7a1c0; baseClass = UICollectionReusableView; frame = (16 526.5; 343 52); layer = <CALayer: 0x2811cc380>>
[NSExtension] Extension request contains input items but the extension point does not specify a set of allowed payload classes. The extension point's NSExtensionContext subclass must implement `+_allowedItemPayloadClasses`. This must return the set of allowed NSExtensionItem payload classes. In future, this request will fail with an error.
[assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
[lifecycle] [u 91968774-196A-4B1B-85E5-DE76649D4F5D:m (null)] [ph.telegra.Telegraph.Share(8.5.1)] Connection to plugin interrupted while in use.
[lifecycle] [u 91968774-196A-4B1B-85E5-DE76649D4F5D:m (null)] [ph.telegra.Telegraph.Share(8.5.1)] Connection to plugin invalidated while in use.
[core] SLRemoteComposeViewController: (this may be harmless) viewServiceDidTerminateWithError: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "(null)" UserInfo={Message=Service Connection Interrupted}
viewServiceDidTerminateWithError:: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "(null)" UserInfo={Message=Service Connection Interrupted}`

**Comment by simplenotezy** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/645

**Comment by simplenotezy** [comment]
https://github.com/fluttercommunity/plus_plugins/issues/730
