### ISSUE TITLE
 error: Target of URI doesn't exist: 'snake.dart'

### ISSUE THREAD

**Issue by 41linea45** [fluttercommunity/plus_plugins#742]
Hello

I use sensors_plus example https://pub.dev/packages/sensors_plus but i see error ` error: Target of URI doesn't exist: 'snake.dart'` i added snake library https://pub.dev/packages/snake  but exaple gives error.

How can i solve this issue?

**Comment by vbuberen** [comment]
Issue doesn't follow any of provided templates.

`example` app works fine both on iOS and Android at the moment.
