### ISSUE TITLE
[sensors_plus] Actually cleanup in onDetachedFromEngine

### ISSUE THREAD

**Issue by Rexios80** [fluttercommunity/plus_plugins#752]
## System info

Platform the Issue occurs on: Android
Plugin name: sensors_plus
Plugin version: 1.2.2

## Steps to Reproduce

1. Collect data
2. Kill app from recents
3. You'll get a ton of these: `W[/FlutterJNI]()(13631): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send.`

**Comment by vbuberen** [comment]
Please provide more detailed set of steps to reproduce. `Collect data` is the most confusing part. I would like to test both the issue and the fix you provided.

**Comment by Rexios80** [comment]
Listen to any of the streams from this plugin: https://pub.dev/packages/sensors_plus#example

Don't cancel them before killing the app

**Comment by vbuberen** [comment]
Streams are already listened in that example app. I can't reproduce the issue you mentioned on a physical device.

**Comment by Rexios80** [comment]
Without the PR code:

https://user-images.githubusercontent.com/7896519/154822861-15d288ed-9be2-476c-82a0-797bb1ba55e4.mov

With the PR code:

https://user-images.githubusercontent.com/7896519/154822978-bf8f033d-2aae-4ce9-aa0d-b49190368352.mov

Weird I can't reproduce it in a minimal sample by removing the app from recents, but I can reproduce it by hitting the back button to kill the activity.
