### ISSUE TITLE
connectivity_plus is incompatible with flutter_local_notifications.

### ISSUE THREAD

**Issue by dpedrinha** [fluttercommunity/plus_plugins#754]
## System info

Platform the Issue occurs on: Both
Plugin name: connectivity_plus
Plugin version: 2.2.1

## Steps to Reproduce

Add connectivity_plus 2.2.1 and flutter_local_notifications 9.0.2 to any project and try pub get

<details>
<summary>

Because connectivity_plus >=2.2.1 depends on connectivity_plus_linux ^1.3.0 which depends on nm ^0.5.0, connectivity_plus >=2.2.1 requires nm ^0.5.0.
(1) So, because nm >=0.5.0 depends on dbus ^0.7.0, connectivity_plus >=2.2.1 requires dbus ^0.7.0.

    Because flutter_local_notifications >=9.2.0 <10.0.0-dev.1 depends on flutter_local_notifications_linux ^0.4.1 and flutter_local_notifications >=9.1.5 <9.2.0 depends on flutter_local_notifications_linux ^0.4.0, flutter_local_notifications >=9.1.5 <10.0.0-dev.1 requires flutter_local_notifications_linux ^0.4.0.
    And because flutter_local_notifications >=9.0.0 <9.1.5 depends on flutter_local_notifications_linux ^0.3.0, flutter_local_notifications >=9.0.0 <10.0.0-dev.1 requires flutter_local_notifications_linux ^0.3.0 or ^0.4.0.
    And because flutter_local_notifications_linux <0.4.0 depends on dbus ^0.5.0 and flutter_local_notifications_linux >=0.4.0 depends on dbus ^0.6.0, flutter_local_notifications >=9.0.0 <10.0.0-dev.1 requires dbus ^0.5.0 or ^0.6.0.
    And because connectivity_plus >=2.2.1 requires dbus ^0.7.0 (1), connectivity_plus >=2.2.1 is incompatible with flutter_local_notifications >=9.0.0 <10.0.0-dev.1.
    So, because 'myappname' depends on both flutter_local_notifications ^9.0.2 and connectivity_plus ^2.2.1, version solving failed.
pub get failed (1;     So, because 'myappname' depends on both flutter_local_notifications ^9.0.2 and connectivity_plus ^2.2.1, version solving failed.)
</summary>

</details>

<details>
<summary>Flutter doctor output</summary>

```
flutter doctor -v
[√] Flutter (Channel master, 2.11.0-0.0.pre.604, on Microsoft Windows [versÃ£o 10.0.19043.1466], locale pt-BR)
    • Flutter version 2.11.0-0.0.pre.604 at D:\DEV\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 28e1dea69c (2 hours ago), 2022-02-17 16:24:16 -0500
    • Engine revision 01ac6cf661
    • Dart version 2.17.0 (build 2.17.0-117.0.dev)
    • DevTools version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at C:\Users\myuser\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19043.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by vbuberen** [comment]
Connectivity plus 2.2.1 was updated to use latest `nm` dependency to be compatible with other plugins #728 

Currently, looking at your logs it is flutter_local_notification isn't compatible with Connectivity plus, since uses older version of `nm`.
