### ISSUE TITLE
[share_plus]  Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by JAICHANGPARK** [fluttercommunity/plus_plugins#758]
## System info

Platform the Issue occurs on:  build error 
Plugin name: share plus
Plugin version: 3.1.0
flutter sdk : 2.11.0 - master channel

<details>
<summary>Logs</summary>

```
/share_plus-3.1.0/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt: (34, 24): Type mismatch: inferred type is String? but String was expected
```

</details>

<details>
<summary>Flutter doctor output</summary>

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.633, on macOS 12.2.1 21D62
    darwin-arm, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by tgucio** [comment]
+1 here

**Comment by TheJulianJES** [comment]
Seems to have been caused by a combination of using the Flutter master branch and https://github.com/fluttercommunity/plus_plugins/pull/667.

``share_plus: 3.0.5`` still works fine on the Flutter master branch.

**Comment by TheJulianJES** [comment]
This probably isn't a great solution, but I've changed
https://github.com/fluttercommunity/plus_plugins/blob/b817c032ccf2492c2eff8fef5e6c2864ea03aef2/packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt#L34
to
```kotlin
result.error(e.message ?: "Error message is null", null, null)
```
and it seems to compile just fine now.

@vbuberen Since you did the original migration, do you mind having a look at this when you have some time?

**Comment by vbuberen** [comment]
Yes, I will do it when have more time.

**Comment by selvam920** [comment]
any update

**Comment by mikewolfd** [comment]
still seeing this

**Comment by selvam920** [comment]
flutter beta branch also coming this error

**Comment by UlyssesAlves** [comment]
Just edit your flutter project pubspec.yaml file to use share_plus version 5.0.0. There's no need to edit kotling_version.
