### ISSUE TITLE
UserAccelerometerEvent

### ISSUE THREAD

**Issue by SwiftyFlow** [fluttercommunity/plus_plugins#768]
Do we agree that UserAccelerometerEvent will NOT give me the user current speed if in a car? It gives the speed at which the device travels to if I throw it... Thing I might do soon hahaha

Am I right thinking I need Geolocator instead with position.speed? But I'm too dumb to get the stream to work properly...

**Comment by saravanans55** [comment]
@SwiftyFlow Yes, you are 200% right. It will not give speed of vehicle. It's just return the value of mobile's physical acceleration speed.  You can't use this package for finding vehicle or any moving things speed.
