### ISSUE TITLE
flutter_alarm_manager_plus `periodic()` not working when app is killed

### ISSUE THREAD

**Issue by erisanolasheni** [fluttercommunity/plus_plugins#778]
## System info

Platform the Issue occurs on: Infinix X652 Android 9 (API Level 28)
Plugin name: android_alarm_manager_plus
Plugin version: ^2.0.3

## Steps to Reproduce

The `AndroidAlarmManager.periodic()` method is not working when the app is killed. Tried to play a sound every 1 minute at intervals, this work when my app is still active (on debug mode), but immediately the app is killed and onDetachedFromActivity, it stops playing the music:
```dart
import 'dart:isolate';

import 'package:android_alarm_manager_plus/android_alarm_manager_plus.dart';
import 'package:audioplayers/audioplayers.dart';

int alarmManageID = Isolate.current.hashCode;
AndroidAlarmManager.periodic(
    const Duration(minutes: 1),
    alarmManageID,
    () {
    final AudioPlayer audioPlay = AudioPlayer();
    audioPlay.play("https://www.royaltyfreemusicclips.com/files/composer_mp3_1028944.mp3");
    },
    allowWhileIdle: true,
    /*exact: true,*/ rescheduleOnReboot: true,
    wakeup: true,
  );

```

This works when currently debugging the app and app is active but would not when app is killed or closed.

I had added the dependencies to my Android manifest.
```xml
...
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<!-- For apps with targetSDK=31 (Android 12) -->
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>
...
<application>
...
<service
    android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmService"
    android:permission="android.permission.BIND_JOB_SERVICE"
    android:exported="false"/>
<receiver
    android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmBroadcastReceiver"
    android:exported="false"/>
<receiver
    android:name="dev.fluttercommunity.plus.androidalarmmanager.RebootBroadcastReceiver"
    android:enabled="false"
    android:exported="false">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
    </intent-filter>
</receiver>
...
</application>
...
```

<details>
<summary>Flutter doctor output</summary>
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 2.10.2 at F:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\D\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 32-bit edition (version 1.64.2)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (1 available)
    • Infinix X652 (mobile) • 100.107.219.116:5555 • android-arm64 • Android 9 (API 28)

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
```

</details>

**Comment by erisanolasheni** [comment]
Hello, no comments here yet.

**Comment by erisanolasheni** [comment]
Hi, can anyone help see this out? @jpnurmi @radvansky-tomas @miquelbeltran @mhadaily @KirillArtemenko @narumishi @Rexios80 @vbuberen @navczydev @yash1200 @JigneshPatel23 @Amitbhave @alexbatalov @jdebou

**Comment by radvansky-tomas** [comment]
What happens when you run app (without debugger, just from the phone) and then kill it ? 

But as I can see from your code...its not correct...you need to define top level function, so it runs in separate isolate

https://plus.fluttercommunity.dev/docs/android_alarm_manager_plus/usage

**Comment by erisanolasheni** [comment]
Hello, thanks @radvansky-tomas , my code is just the life from the larger codes. Now answering your questions:
1. Yes, I have tried to release to run in release, but it still has the same problem.
2. Even though I don't think defining a function body in the `.peroidic` method should be a reason why it won't work, I have also tried on several occasions to use top-level functions and it's still the same results.

**Comment by erisanolasheni** [comment]
Yes, I see at the period which I am still debugging, but not when debugging is closed.

**Comment by radvansky-tomas** [comment]
ok lets simplify, just replace your periodic body with this topLevel functionvoid 
```
printHello() {
  final DateTime now = DateTime.now();
  final int isolateId = Isolate.current.hashCode;
  print("[$now] Hello, world! isolate=${isolateId} function='$printHello'");
}`
```

And then run app, WITHOUT debugger and open logcat ...do you see hello world printed there ?

**Comment by erisanolasheni** [comment]
Any idea on how to make `logcat` minimal? This repeatly show lots of logs and not easy to filter.

**Comment by radvansky-tomas** [comment]
There is a way to select process Id and also to search in

**Comment by erisanolasheni** [comment]
Thanks @radvansky-tomas , I used your exact function as top-level. Using release version, no debugger in on, only using adb logcat to track the logs, on Samsung A32 Android version 11, it could not run unless the app is on, when I killed the app, it stops logging.

**Comment by radvansky-tomas** [comment]
Not sure then ;) you can try running https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_alarm_manager_plus/example

If still not, there might be a bug, but I am not the one built it :P

**Comment by miquelbeltran** [comment]
Please, @erisanolasheni do not `@` people. This is a formal warning.

Secondly, this is how Alarms on Android work: https://stackoverflow.com/questions/11658129/android-alarms-cancelled-when-application-is-killed
