### ISSUE TITLE
[device_info_plus] Module 'device_info_plus' not found

### ISSUE THREAD

**Issue by erperejildo** [fluttercommunity/plus_plugins#780]
I'm getting this error while trying to publish a new iOS version. I cleaned project, updated/installed pods... but nothing seemed to work

device_info_plus: ^3.2.2

doctor:
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.2 20G314 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by ryuujo1573** [comment]
Hi. Did you mean executing `flutter pub get` in the end by "updated/installed pods"?
I can't help you so far. Any information else?

**Comment by someshubham** [comment]
Facing similar issue

**Comment by felipeparente** [comment]
I got a same error.

**Comment by erperejildo** [comment]
> Hi. Did you mean executing `flutter pub get` in the end by "updated/installed pods"? I can't help you so far. Any information else?

futter pub get
pod install
flutter clean
pod cache clean
etc

I don't it's related to some commands I forgot, specially when more people are facing this

**Comment by JoshRice1** [comment]
I am getting the same error.  

Parse Issue (Xcode): Module 'device_info_plus' not found
<pathToProject>/ios/Runner/GeneratedPluginRegistrant.m:23:8

**Comment by felipeparente** [comment]
I've tried several things I've seen on the internet, nothing works.
When I remove the problem lib, the same problem occurs in another one.

**Comment by JoshRice1** [comment]
So eventually I resolved this by opening Xcode and updating the iOS version I was targetting from 9 to 11.  I did almost everything else I could find as well but it was that that made the build work.

**Comment by felipeparente** [comment]
@JoshRice1 My friend, thank you very much.
This solved my problem, I had been struggling with this for a few days now.
And I didn't even think of that solution.

**Comment by jiangxiaoqiang** [comment]
> So eventually I resolved this by opening Xcode and updating the iOS version I was targetting from 9 to 11. I did almost everything else I could find as well but it was that that made the build work.

I changed the target to 11 but did not fixed this problem.

**Comment by Hoai-Phong** [comment]
@PesaCoder  can you help me, now i do all the problems but still can't solve.

I gave target to 11
device_info_plus: ^3.2.2

![image](https://user-images.githubusercontent.com/83800555/183271702-f14df696-31dc-4965-aab5-3438ec4a25c0.png)
![image](https://user-images.githubusercontent.com/83800555/183271802-367f0c4f-9a21-404c-af53-6227b1fa91e9.png)

**Comment by bigbang489** [comment]
I got the same error, ios target is 11.
Parse Issue (Xcode): Module 'device_info_plus' not found

**Comment by Aaron009** [comment]
![image](https://user-images.githubusercontent.com/3838050/186070842-4cc51b95-5699-4668-bf36-ec80919c2b12.png)
I referenced this picture and succeeded.

**Comment by fedejuret** [comment]
> I've tried several things I've seen on the internet, nothing works. When I remove the problem lib, the same problem occurs in another one.

And can you solved it? I have the same problem

**Comment by gikwegbu** [comment]
@Aaron009 method worked for me too, just changed the iOS Deployment Target to 11.0, and I was able to archive successfully.

**Comment by evindunn** [comment]
> 1. Delete pod directory and podfile.lock
> 
>     2. flutter clean
> 
>     3. flutter pub get
> 
>     4. cd ios
> 
>     5. pod install --repo-update
> 
>     6. run the application in Xcode

This did it for me, thanks @usamaaelgendy

**Comment by ibrahimsm83** [comment]
Just changed the iOS Deployment Target to 11.0, and I was able to archive successfully.

**Comment by ulrickpsp** [comment]
> 1. Delete pod directory and podfile.lock
> 2. flutter clean
> 3. flutter pub get
> 4. cd ios
> 5. pod install --repo-update
> 6. run the application in Xcode

Worked for me, thanks.

**Comment by ClubAce** [comment]
So far non of the suggested approaches have worked for me. 

When opening the Runner.xcodeproj file in Xcode and building the project to a real iPhone device, the "Build Failed" message is displayed and the GeneratedPluginRegistrant error "Module 'device_info_plus' not found" is pressent in the left side panel.

![xcode_build_faild_screenshot](https://github.com/fluttercommunity/plus_plugins/assets/12293417/2ae1f494-febf-4269-8a6c-ac2206b8b46d)

**Comment by federico-b-visia** [comment]
> So far non of the suggested approaches have worked for me.
> 
> When opening the Runner.xcodeproj file in Xcode and building the project to a real iPhone device, the "Build Failed" message is displayed and the GeneratedPluginRegistrant error "Module 'device_info_plus' not found" is pressent in the left side panel.
> 
> ![xcode_build_faild_screenshot](https://user-images.githubusercontent.com/12293417/265933201-2ae1f494-febf-4269-8a6c-ac2206b8b46d.jpg)

I'am in the same situation, already tried all previous suggestions

**Comment by ineffablesam** [comment]
For me the issue is my project is having a invalid project name which is something like

`flick-analytics`

when i changed it to 

`flickanalytics`

it built sucessfully

**Comment by arnovanliere** [comment]
Just for anyone else who might stumble upon this: if `flutter build ios` works, but running the emulator fails with this error, you might have opened XCode with the wrong extension. Make sure you open the file with the .xcworkspace extension instead of the one with .xcodeproj and then build again. If you opened the project with the wrong extension, the emulator fails with `Module '...'  not found` and uses the first module name in the error, so the error might not be in the actual module.

**Comment by novas1r1** [comment]
I'm still getting this error. It works on simulator (17.4) and it works on my physical iPhone 11 (17.4.) but it does not work for "Any iOS Device (arm64)" for archiving a release version.

Flutter 3.19.5
device_info_plus: 10.1.0

![image](https://github.com/fluttercommunity/plus_plugins/assets/2575205/7d9b5a0e-4b7f-4618-a99e-2f7cbbd06fc0)

Anyone else facing this issue?

**Comment by annguyenairstage** [comment]
Open source code in Xcode with workspace will fix this issues, don't open with xproj.

**Comment by novas1r1** [comment]
@annguyenairstage I always open the workspace, not the project and it still doesn't work for me :(!

**Comment by ebensakyi** [comment]
Any solution in 2024?

**Comment by hiakdeniz** [comment]
same problem. any fixed here pls.

**Comment by rajatsingh0406** [comment]
same problem, any fixed here plz help
![Uploading Screenshot 2024-07-03 at 10.29.50 AM.png…]()

**Comment by Blasanka** [comment]
Im wondering why this issue is closed without any solution. Im in Flutter 3.19.6 and Gradle 8 with source compatibility with Java 8.

**Comment by Blasanka** [comment]
Ops.. It is more than 2 years without any feedback from the maintainers.

```
Failed to build iOS app
Parse Issue (Xcode): Module 'device_info_plus' not found
/Users/asankaliyanage/Developer/flutter_projects/cortex-cashierapp/ios/Runner/GeneratedPluginRegistrant.m:11:8


Encountered error while building for device.

```

**Comment by Blasanka** [comment]
Ops.. It is more than 2 years without any feedback from the maintainers.

```
Failed to build iOS app
Parse Issue (Xcode): Module 'device_info_plus' not found
/Users/aaaa/Developer/projects/cccc_app/ios/Runner/GeneratedPluginRegistrant.m:11:8


Encountered error while building for device.

```

**Comment by miquelbeltran** [comment]
@Blasanka open a "compilation" ticket here and provide all the necessary information: https://github.com/fluttercommunity/plus_plugins/issues/new?assignees=&labels=compile%2Ctriage&projects=&template=COMPILATION.yaml&title=%5BCompile%5D%3A+

Meanwhile, I am locking this ticket. If you still have a compilation issue, follow the instructions in the "Compilation" ticket template.
