### ISSUE TITLE
Magnetometer values are off

### ISSUE THREAD

**Issue by filippkowalski** [fluttercommunity/plus_plugins#781]
## System info

Platform the Issue occurs on: iOS
Plugin name: sensors_plus
Plugin version: 1.3.0

## Steps to Reproduce

It seems that Flutter's implementation of the Magnetometer is off when compared to iOS devices. 
I don't know yet if it's due to some additional flags that are set on the iOS side to calibrate the magnetometer ( https://stackoverflow.com/questions/28365121/how-to-get-magnetometer-data-using-swift ), but results for Flutter are way higher than for iOS devices. And actually sometimes when the Flutter app detects metals the values go down instead of going up.

You can easily test it out by downloading those 3 apps below and seeing the results by yourself.

iOS implementation
https://apps.apple.com/us/app/stud-finder-wall-detector/id1530653768
https://apps.apple.com/us/app/teslameter/id976926346

Flutter implementation
https://apps.apple.com/us/app/stud-finder/id1613688190

iOS
<p align="center">
  <img width="320" src="https://user-images.githubusercontent.com/10477861/157858540-561a7f00-a25e-4a78-bac3-8b6e2a39f341.PNG">
  <img width="320" src="https://user-images.githubusercontent.com/10477861/157858553-bdfc93f1-7286-4130-b1a4-19523bc0760e.PNG">
</p>

Flutter
<p align="center">
  <img width="320" src="https://user-images.githubusercontent.com/10477861/157858551-aa4f2a8c-6e9b-4949-9b8a-d466499358d3.PNG">
</p>

You can see on the screenshots that iOS values are lower than those on Flutter. All of those screenshots were made in the same phone position, with the phone lying flat.

One note here: Look at the X, Y, Z values here, because the Flutter app has the main displayed wrong.

cc: @Zabadam because I've seen that you were implementing this feature

**Comment by Zabadam** [comment]
I have an extremely limited knowledge of iOS and as such the testing for that platform was less than thorough. 

If I take another look, it may be as simple as calling values from sensor manager incorrectly.

It seems Android has moved things around over the years, and iOS may be similar; whereby I could have been referencing irrelevant docs.

**Comment by filippkowalski** [comment]
Possibly, I'll also take a look at what could be wrong here

**Comment by Zabadam** [comment]
I have finally sat down to look into this.

It seems like it may be a simple fix. We are after [this value](https://developer.apple.com/documentation/coremotion/cmdevicemotion/1616140-magneticfield), the *calibrated* `magneticField` property of a [`CMDeviceMotion`](https://developer.apple.com/documentation/coremotion/cmdevicemotion) object that "unlike the [`magneticField`](https://developer.apple.com/documentation/coremotion/cmmagnetometerdata/1616084-magneticfield) property of the `CMMagnetometerData` class . . . reflect the earth’s magnetic field plus surrounding fields, minus device bias."

**Comment by Zabadam** [comment]
https://github.com/Zabadam/plus_plugins/commit/0b72713a476d18b1bd49c99be319038f448095b8

**Comment by filippkowalski** [comment]
Awesome!
I'll check it out later. @Zabadam 

Just FYI, in the meantime, I've used this library: https://pub.dev/packages/motion_sensors and it seems to have a proper implementation.

**Comment by Zabadam** [comment]
> Just FYI, in the meantime, I've used this library: https://pub.dev/packages/motion_sensors and it seems to have a proper implementation.

I remember when I was building a sensors based package I had to make the decision between that package and `sensors_plus`.

You can see now the decision that I ultimately made was to *add* the magnetometer support I needed to this official package instead of using `motion_sensors` as per its lack of web support.

**Comment by Zabadam** [comment]
Barring a check for availability of sensors and providing a means to alter temporal accuracy, this implementation should accomplish the same expected functionality as from `motion_sensors`:

```objective-c

**Comment by Zabadam** [comment]
I wish I had an iOS device to verify this fix. Could be checked by someone else if they have the time:

```yaml
dependencies
  # Testing calibrated magnetometer on iOS
  sensors_plus:
    git:
      url: https://github.com/Zabadam/plus_plugins.git
      path: packages/sensors_plus/sensors_plus
```

**Comment by filippkowalski** [comment]
@Zabadam Thanks for your effort! 

I just used this dependency and it seems that it's still showing higher values than the other apps or the `motion_plus` package.

**Comment by Zabadam** [comment]
> @Zabadam Thanks for your effort!
> 
> I just used this dependency and it seems that it's still showing higher values than the other apps or the `motion_plus` package.

Because the shared section of code is nearly identical (albeit Swift instead of ObjC) to `motion_sensors`, it seems the magnetometer implementation here may not be the source of issue after all.

**Comment by Zabadam** [comment]
The PR that implements this fix will likely soon be merged. As the code is technically correct, especially when compared to your other linked package that implements iOS magnetometer support, I'm unsure the status on this Issue. 

I would love an update on the status of this fix.

**Comment by filippkowalski** [comment]
Sorry, didn't notice your previous message. 
It's hard to test those things since we don't really know what's the correct result. The implementation looks good to me, I say: merge it.

**Comment by Zabadam** [comment]
Wow, I learned a lot just by reading [this excellent comment on StackOverflow](https://stackoverflow.com/a/15470571/14140759). 

Snipped below: 

> I have put a [Magnet-O-Meter demo app on gitHub](https://github.com/foundry/MagnetoMeter) which displays some of these differences. It's quite revealing to wave a magnet around your device when the app is running and watching how the various APIs react:

my original solution

> `CMMagnetometer` doesn't react much to anything unless you pull a rare earth magnet up close. The onboard magnetic fields seem far more significant than local external fields or the earth's magnetic field. On my iPhone 4S it consistently points to the bottom left of the device; on the iPad mini it points usually to the top right.

my proposed solution

> `CMCalibratedMagneticField` is the most steady in the face of varying external fields, but otherwise tracks it's Core Location counterpart CLHeading.[x|y|z] pretty closely.

...but it seems that

> `CLHeading.[x|y|z]` is the most vulnerable (responsive) to local external fields, whether moving or static relative to the device.

And this is the surprising bit. It would seem, according to these tests, that the Core Location `CLHeading` provides geomagnetic data that both filters out the device hard iron and also is more responsive to external elements (such as is desired for a stud finder) than is the Core Motion `CMDeviceMotion`'s `CMCalibratedMagneticField`.


Their final note:
> `CLHeading.magneticHeading` - Apple's recommendation for magnetic compass reading - is far more stable than any of these. It is using data from the other sensors to stabilise the magnetometer data. But you don't get a raw breakdown of x,y,z

Still, how these values compare to Android implementation is mystery to me. It is almost funny to me that by now I have learned far more about how iOS and Apple handle sensors and this sort of data than the platform I actually use. That just means I have more to learn!

**Comment by miquelbeltran** [comment]
The PR with the magnet sensor changes has been merged and release. Let me know if this ticket can be closed.

**Comment by Silverviql** [comment]
@Zabadam have you checked further to see if it gives the correct values?
i checked today and magnetometerEventStream still returns incorrect values ​​that are much higher
