### ISSUE TITLE
[device_info_plus] Add specifications when property becomes null

### ISSUE THREAD

**Issue by ryuujo1573** [fluttercommunity/plus_plugins#784]
Hi, I was confused of the property 
```dart
// android_device_info.dart
...
final String? androidId;
```
which appears as a nullable.

Is there any cases that this is **null**? 
In my case, I need a stable and polite way to distinct each among similar devices with same model and so on.

Thank you for your time. 😍

**Comment by ryuujo1573** [comment]
Also, when would the followings be false? Is there any system permission issue about this?

- `iosInfo.identifierForVendor`
- `linuxInfo.machineId`
- ...

Thank you.

**Comment by moodstubos** [comment]
I have the same question. 

In my case I need androidInfo.version.sdkInt which comes directly from Build.VERSION.SDK_INT (see [MethodCallHandlerImpl.java](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java))

How can this value be null?

This does not make sense for me.

**Comment by Scienticious** [comment]
Hi, @mhadaily  would you please mention is this a valid Issue? So I Can try to fix this issue and raise a PR.
Thanks

**Comment by mhadaily** [comment]
@Scienticious go for it

**Comment by ryuujo1573** [comment]
Any progress? Thanks ;>

**Comment by nohli** [comment]
FYI `androidId` was removed from the plugin `device_info_plus`, so there is a new separate plugin for getting the Android ID 🙂
https://pub.dev/packages/android_id
