### ISSUE TITLE
share_plus Android minSdk bump drops support for a lot of devices

### ISSUE THREAD

**Issue by ekuleshov** [fluttercommunity/plus_plugins#789]
## System info

Platform the Issue occurs on: Android
Plugin name: share_plus
Plugin version: 4.0.1

## Steps to Reproduce

The latest `share_pus` plugin update bumped minSdk Android API from 16 to 23 (from Android 4.1 to Android 6). With Flutter itself supporting API 16 that is a large drop of supported Android devices.

My app is primarily used on Android tablets, and there is a lot of them running older Android versions. For example, older generation Amazon Fire 7 tablets (Fire OS 5 is API level 22) and some of 3..4 year old Samsung's Tab As are also running Android 5 or older.

**Comment by vbuberen** [comment]
I am not a big fan of what happened with minSDK in Share plus, but I missed this PR due to events in Ukraine. I think that there was no need to bump that high. 

Don't see it as a critical issue, though, considering that you can still use older versions.

As to `share_plus` I will create a PR, which will change the minSDK to lower version as it is possible as it seems to me.

P.S. I also believe that it would be good for all plugins to slowly go to 21 as their minSDK, but it is a different topic.

**Comment by ekuleshov** [comment]
Thank you

> it would be good for all plugins to slowly go to 21 as their minSDK, but it is a different topic

I respectfully disagree. All the `*_plus` plugins in their roots are basically the core platform plugins, which the Flutter core team don't have capacity or is unwilling to maintain. With that, all the `*_plus` should match the [Flutter's core platform support](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms#supported-platforms), even if some functionality is not supported on certain platform versions (i.e. can't be supported on a lower Android API versions), unless it is absolutely not possible to support plugin's core features (which doesn't seem to be the case with the `share_plus` plugin).

As for using older plugin versions. My past experience shows that it quickly turns in a dependency hell, due to plugin's cross dependency and dependency on external plugins. Up to now we could at least rely on the core plugins (which used to be the `pre-*_plus` ones) being the latest and on par with the Flutter core and platform. Not to mention changes in the Flutter core and the Dart itself.

**Comment by vbuberen** [comment]
> I respectfully disagree. All the `*_plus` plugins in their roots are basically the core platform plugins, which the Flutter core team don't have capacity or is unwilling to maintain. With that, all the `*_plus` should match the [Flutter's core platform support](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms#supported-platforms), even if some functionality is not supported on certain platform versions (i.e. can't be supported on a lower Android API versions), unless it is absolutely not possible to support plugin's core features (which doesn't seem to be the case with the `share_plus` plugin).

I agree with your concerns, but even in the link you attached it is SDK 19, not 16 that is currently minimally supported by `plus_plugins`. And I believe that we will see a bump to 21 in Flutter itself before 2022 ends. Because 21 brought some better APIs, which made lots of things easier and because it is from 2014, which is very very old. I wouldn't like to continue this topic here as we will stay with our opinions anyway.

As to `share_plus` I see a possibility to lower only to 22 as before 22 there were no way to add `sender` param into Intent to get a callback. If it is still something that you consider critical I would suggest to go and share your concerns in #386.

**Comment by Coronon** [comment]
https://github.com/fluttercommunity/plus_plugins/pull/797#issuecomment-1073345787

**Comment by ekuleshov** [comment]
> #797 (comment)

@Coronon thank you for looking into this. All seem to work as before. Yay!

As @vbuberen noted before, on Android it reports `ShareResultStatus.success` after you select some activity from the list and then immediately cancel it, so nothing really shared. The method doc doesn't seem to say it that way.

On a side note, the `_resultUnavailable` uses somewhat odd value. Could `raw` field be a nullable `String?` instead? The `raw` value doesn't have any special meaning for an `unavailable` and `dismissed` statuses anyways.

```
const _resultUnavailable = ShareResult(
  'dev.fluttercommunity.plus/share/unavailable',
  ShareResultStatus.unavailable,
);
```

**Comment by Coronon** [comment]
```
/// While on IOS the selected action can inform its caller that it was completed
/// or dismissed midway (_actions are free to return whatever they want_),
/// Android and macOS only record if the user selected an action or outright
/// dismissed the share-sheet.
```
I don't know how to make this any clearer, it says "**Android and macOS only record if the user selected an action or outright dismissed the share-sheet**", that's exactly how it is!

We use null for no return (without result), `''` for dismissed share and `{VALUE}` for successful share. The `dev.fluttercommunity.plus/share/unavailable` is another value where we can be pretty certain that no other application will use it.

**Comment by vbuberen** [comment]
Was automaticall closed due to my PR description. Opening again till the new PR is ready.

**Comment by m-ochyra** [comment]
Hi, I love this plugin and I'm sad, becouse for me minSdk 22 is not acceptable. My project uses minSdk 21 and update is not possible, becouse a lot of users still use Android 5.

What do you think about disabling results for Android 5 and lower OS versions? I think share_plus shoud have lower minSdk, becouse other plugins like webview_flutter or firebase plugins have it lower.

**Comment by vbuberen** [comment]
> I don't know how to make this any clearer, it says "**Android and macOS only record if the user selected an action or outright dismissed the share-sheet**", that's exactly how it behaves!

Let me provide a PR with docs updates and I will provide that comment update as well.

> What do you think about disabling results for Android 5 and lower OS versions? I think share_plus shoud have lower minSdk, becouse other plugins like webview_flutter or firebase plugins have it lower.

There is a person already working on it, so no worries here.

**Comment by Coronon** [comment]
> Let me provide a PR with docs updates and I will provide that comment update as well.

I have improved the docs in my PR, have a look if that makes it clearer :)

**Comment by Coronon** [comment]
My PR should be ready
