### ISSUE TITLE
[connectivity_plus] Opening the application causes onConnectivityChanged to emit two events

### ISSUE THREAD

**Issue by cal-g** [fluttercommunity/plus_plugins#790]
## System info

Platform the Issue occurs on: iOS
Plugin name: connectivity_plus
Plugin version: 2.2.1

## Steps to Reproduce

Demo code increments counter when connection is changed to Wifi.
Link to [gist](https://gist.github.com/cal-g/4523a9161e2b826bc739013e0f347bd8)
1. Run the gist code on a simulator or real device

When the app is opened the `onConnectivityChanged`  emits two events instead of just one. On Android it correctly emits just one event. I'm guessing this can be a bug on the iOS.
The video attached is the release build of the demo gist on a iPhone 8

Since, there are 2 events emitted the counter increments 2 times if WiFi is turned on and 2 is displayed when the app is opened. There are 2 events emitted even if Wifi and Data is turned off.

Expected: Only one event should be emitted.

https://user-images.githubusercontent.com/98470469/158479544-e5a1fa9a-45b5-47db-8bf0-578ad3ab67fd.mp4

<details>
Running in debug mode on iOS Simulator. 
"Got a new connectivity status!  ::wifi" is printed twice.
<summary>Logs</summary>

```dart
Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3.5s
Xcode build done.                                            9.6s
flutter: initState
flutter: Got a new connectivity status!  ::wifi
flutter: Got a new connectivity status!  ::wifi
Syncing files to device iPhone SE (3rd generation)...              214ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪
```

</details>

<details>
<summary>Flutter doctor output</summary>

```
✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale en-CA)
    • Flutter version 2.10.3 at /Users/calvin.gonsalves/Desktop/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (13 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/calvin.gonsalves/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by kuhnroyal** [comment]
I stumbled on this issue by chance and tested it with https://github.com/fluttercommunity/plus_plugins/pull/791
Same result, first event is `ConnectivityResult.none` and second is `ConnectivityResult.wifi`.

**Comment by miquelbeltran** [comment]
closing, if the issue reappears please say so here and I will reopen the issue

**Comment by luis901101** [comment]
I have tested the recently published version [v2.3.0](https://pub.dev/packages/connectivity_plus/versions/2.3.0) and I also tested [PR 791](https://github.com/fluttercommunity/plus_plugins/pull/791) and I'm still facing the same issue.
The commit I specifically tested from PR 791 was:
```yaml
connectivity_plus: #^2.3.0
    git:
      url: https://github.com/kuhnroyal/plus_plugins
      path: packages/connectivity_plus/connectivity_plus
      ref: d7b83c425f63a049d5195df99848c33a9eb1e894
```

**Comment by kuhnroyal** [comment]
@luis901101 On which iOS version did you test?
The line which can potentially cause double emit is still there: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus/ios/Classes/SwiftConnectivityPlusPlugin.swift#L67

I remember this also being a timing issue. In my test app on iOS 15 I only had one event.
Removing the line cause sometimes no initial event to be fired.

Will try to testing this again.

**Comment by kuhnroyal** [comment]
Also this may play a role here: https://github.com/fluttercommunity/plus_plugins/pull/791#issuecomment-1069385002

**Comment by luis901101** [comment]
Tested in iOS 15.3.1 and 15.4.1

**Comment by miquelbeltran** [comment]
Reopened. Just to be sure, is this a big issue if you receive two events? How is that affecting your code? (just want to understand better the scope of this problem)

**Comment by kuhnroyal** [comment]
@838 Which iOS version and did the same happen before the 2.3.0 release?

**Comment by 838** [comment]
@miquelbeltran  In my case, I'm checking the connectivity state on every `AppLifecycleState.resumed` and for a very short time the app will show a offline page if I don't skip the first emit.

@kuhnroyal The iOS version is 15.4.1. I have tested on 2.2.2 and 2.2.1 I have the same issue, but if I'm connected to WIFI then `onConnectivityChanged` emits `ConnectivityResult.wifi` twice. In 2.3.0 the first emit is always `ConnectivityResult.none`.

**Comment by kuhnroyal** [comment]
@838 This is likely due to https://github.com/fluttercommunity/plus_plugins/pull/791#issuecomment-1069385002
My suggestion in that comment would probably fix this.
What I do to circumvent this is an `await checkConnection()` and start the stream afterwards, discarding the first event.

**Comment by ycherniavskyi** [comment]
@kuhnroyal calling `await checkConnection()` before start the stream doesn't change anything with double emit 😟 for iOS.

Also check on Android and there `onConnectivityChanged` emits one event as expected.

**Comment by ycherniavskyi** [comment]
Just fallback to old `ReachabilityConnectivityProvider` by commented `PathMonitorConnectivityProvider` within plugin source code and event emit one time as expected.

Also create stub SwiftUI app with next initial block:
```swift
        let monitor = NWPathMonitor()
        monitor.pathUpdateHandler = { path in
            print(path)
        }
        let queue = DispatchQueue.global(qos: .background)
        monitor.start(queue: queue)
```
and also get double handle calls with identical `path` objects (at last from its public fields view).

My current iOS version is 15.4.1.

🤷🏻‍♂️

**Comment by leanhro2812** [comment]
Same issue. [2.3.5]

**Comment by kuhnroyal** [comment]
So it seems the `NWPathMonitor .pathUpdaterHandler` can be called multiple times with the same path. According to discussions on the apple community board, your app needs to be resilient against multiple invocations.
This can happen on app start or even while the app is running and you lose connectivity.

There may still be ways to reduce the chance of this happening on app start but I don't think it can be prevent completely.

**Comment by ycherniavskyi** [comment]
What's a fantastic Apple API. Does this board explain what the reason for these multiple invocations is? Does it indicate something valuable (some interface updated, but I can't see any property changes when debugging it)?

In any case, what do you think about adding multiple invocations handling in `connectivity_plus` plugin and putting only different `ConnectivityResult` in `onConnectivityChanged`?

**Comment by kuhnroyal** [comment]
> In any case, what do you think about adding multiple invocations handling in `connectivity_plus` plugin and putting only different `ConnectivityResult` in `onConnectivityChanged`?

I thought about this but that is rather hard to do correct. Like changing from one wifi to another wifi network will result in 2 wifi events.

Maybe it can be done with a very limited timeframe check but it will not completely guard you from those events. You need to handle the meaning of this on your side, especially if you want to do more than just a connectivity check.

**Comment by kuhnroyal** [comment]
> Does it indicate something valuable (some interface updated, but I can't see any property changes when debugging it)?

Yes I have noticed the same thing, but the objects are not comparable so that I can for them out. Could probably try to compare it on a field by fiel basis. Maybe someone else knows more about swift ^^

**Comment by ycherniavskyi** [comment]
> I thought about this but that is rather hard to do correct. Like changing from one wifi to another wifi network will result in 2 wifi events.

Have you checked that the wifi network switch emits two `wifi` results without `none` between them?

**Comment by freeman29** [comment]
This is how I fixed this issue using RxDart's debounceTime.

``` 
late StreamSubscription connectivitySubs;
PublishSubject<ConnectivityResult> onConnectionChange =
      PublishSubject<ConnectivityResult>();
      
      onConnectionChange
        .debounceTime(const Duration(
      seconds: 1,
    ))
        .listen((event) {
      log.d('connectionOnChange $event');
      if (event == ConnectivityResult.none) {
        Get.dialog(
          const NoInternetModal(),
          barrierDismissible: false,
        );
      }
    });
    
    connectivitySubs = Connectivity()
            .onConnectivityChanged
            .listen((ConnectivityResult result) {
          connectionOnChange.add(result);
        });
        
    // don't forget to dispose connectivitySubs
    connectivitySubs.cancel();
        
 ```
 
 I know it's redundant to use 2 listeners, but it works for me.

**Comment by NijatTagizada** [comment]
Same issue happened to me
