### ISSUE TITLE
[network_info_plus][iOS] Do not receive address

### ISSUE THREAD

**Issue by SteMMo33** [fluttercommunity/plus_plugins#792]
## System info

Platform the Issue occurs on: iOS 15
Plugin name: network_info_plus
Plugin version: 2.1.3

When I run the debug application on the mobile I do not receive addresses.

In the console I see the message (twice a time):
`[] NEHotspotNetwork nehelper sent invalid result code [1] for Wi-Fi information request`

I added the 'Access WiFi information' capabilities by the Xcode.
I also added the 'Privacy - Location..' items in the Property List.

Any idea to solve, please?
Thanks

**Comment by flore-costa** [comment]
I can confirm the same issue.

Platform the Issue occurs on: iOS 15
Plugin name: network_info_plus
Plugin version: 2.1.3

**Comment by zzz2016** [comment]
Add the 'access wifi information' to xcode may solve the problem.

**Comment by kekko7072** [comment]
+ 1

**Comment by kekko7072** [comment]
Still issue
