### ISSUE TITLE
[share_plus] On macOS, the native share menu appears at a strange place. Is this expected behavior?

### ISSUE THREAD

**Issue by GroovinChip** [fluttercommunity/plus_plugins#793]
As you can see from the recording below, the native share menu appears at the top left corner of the application window. Is this the expected behavior, or should it be appearing in a different location?

https://user-images.githubusercontent.com/4250470/158654603-bb31b772-0e51-4cc5-b86b-42d1d96be95d.mov

**Comment by Coronon** [comment]
Yes, this is the intended behaviour as you probably did not specify `sharePositionOrigin`, which is internally mapped to `NSMakeRect(x, y, width, height)` when calling your share method. It defaults to `NSMakeRect(0, 0, 0, 0)` -> upper left corner.

I must admit, the documentation says this is only relevant for iPads... You can read more on how these values are used in the official documentation for [NSSharingServicePicker](https://developer.apple.com/documentation/appkit/nssharingservicepicker/1402706-show).

**Comment by GroovinChip** [comment]
Ah yes, that does the trick. I was not aware of that parameter. Thank you!
