### ISSUE TITLE
Other Flutter Plugin with android alarm manager

### ISSUE THREAD

**Issue by ManavBrothers** [fluttercommunity/plus_plugins#798]
I want to use shared Preferences with my android alarm manager so that I can perform several tasks in background like resetting a counter but when I implemented it it is giving me an error.
E/flutter (25092): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

I checked the reference but no one have specified how to use other plugins with android alarm manager plus.
Help me its urgent.

**Comment by azeem-io** [comment]
Hi, did you ever find a solution?
