### ISSUE TITLE
Plugin connectivity_plus not working on the iphone 13 pro with mobile data changes when hotspot is enabled

### ISSUE THREAD

**Issue by carlos-enzo** [fluttercommunity/plus_plugins#799]
## System info

Platform the Issue occurs on: iPhone 13 pro
Plugin name: connectivity_plus
Plugin version: 1.0.0+1

## Steps to Reproduce

1. run the official example in a physical iPhone 13, with hotspot enabled
2. turn on/off the mobile data
3. app crashes

<details>
<summary>Logs</summary>

```Lost connection to device.
```

</details>
App just crashes with message "Lost connection to device." I haven't checked in other iPhones.
<details>
<summary></summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by rakesh0689** [comment]
Any solution for the problem. My app is crashing when I turn off mobile data (hotspot or wifi not enabled). But when I turn off the wifi app is not crashing. I am testing on iPhone 12 mini (physical device).
