### ISSUE TITLE
Android Alarm Manager Plus appears abandoned, a warning should be placed in documentation

### ISSUE THREAD

**Issue by RobertNelsonMSUDenver** [fluttercommunity/plus_plugins#801]
Referencing... every single ticket concerning this specific plugin in the past few months, it appears the plugin is fatally broken in several places with no interest from the maintainer to fix it, with the standing recommendation of the maintainer himself it appears to be to [not use his plugin](https://github.com/fluttercommunity/plus_plugins/discussions/281).

Right now, as this plugin covers a huge number of vital use cases and is abandoned, its kinda a pit trap until you figure out for yourself it doesn't work right now. Further, its state makes the wider plus_plugins project look like abandonware.

Perhaps its time for a small warning banner on the documentation here and on pub.dev until a new maintainer has interest in fixing it?

**Comment by CoderWeiLee** [comment]
have error like this : Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

**Comment by globalwebforce** [comment]
The Author might be a Ukranian

**Comment by hedihadi** [comment]
yeah unfortunately, i've posted a major bug 3 months ago and it's not even been responded to.

**Comment by armouti** [comment]
:(
