### ISSUE TITLE
Share bottomsheet comes from the side instead of from bottom

### ISSUE THREAD

**Issue by ExpertKiD** [fluttercommunity/plus_plugins#802]
Hello, I am trying to share a file. The bottom sheet comes from the bottom as usual, however, if I keep pushing it, it comes from the right. How can I set it to come from the bottom always?

Demo Repo: https://github.com/ExpertKiD/flutter_share_demo

**Comment by werainkhatri** [comment]
could you provide the steps to reproduce this issue? can't seem to reproduce it on android or ios.

**Comment by ExpertKiD** [comment]
I am unable to reproduce the issue either on a newly setup project. Unfortunately, I cannot share the project code with you.

The issue I am facing is as follows:

I have a file at `/storage/emulated/0/Download/txn-159231.pdf`.  I am calling the `Share.shareFiles(['/storage/emulated/0/Download/txn-159231.pdf'])`.

I have started debugging the app. And, in deed the path sent is seen correctly. Everything is working fine on flutter side. However, `channel.invokeMethod('shareFiles', params)` after it returns gives the below error.

`E/MethodChannel#plugins.flutter.io/share( 9447): java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.example.someapp/cache/share/txn-159231.pdf`

**Comment by rodrigoschaefer** [comment]
Also facing this issue

**Comment by Kiirous** [comment]
Same issue here...
