### ISSUE TITLE
Error: UnimplementedError: shareFiles() has not been implemented on Web.

### ISSUE THREAD

**Issue by jtmuller5** [fluttercommunity/plus_plugins#804]
## Use case

Hi, I'm trying to use the share_plus plugin to share an image from a Flutter web app. When I try to share an image using the shareFiles() syntax I get the following message:

"Error: UnimplementedError: shareFiles() has not been implemented on Web."

From the [docs](https://pub.dev/documentation/share_plus_web/latest/share_plus_web/SharePlusPlugin/shareFiles.html) it looks like this just hasn't been implemented yet.

## Proposal

Add file sharing support for Flutter web. FYI, here is [a related issue](https://github.com/flutter/flutter/issues/55330) from the old share plugin.

**Comment by Chinmay-KB** [comment]
Correct me if I am wrong, but if we're sharing a image file, it will have a null path on flutter web. The plugin will have to make an exception and maybe pass a Uint8list of the file bytes to make it work.

**Comment by Odinachi** [comment]
@mhadaily  I'll like to work on this

**Comment by miquelbeltran** [comment]
This should have been fixed for a while. "Share files" is supported on web (on those browsers that are supported, of couse)
