### ISSUE TITLE
How to give name to the file?

### ISSUE THREAD

**Issue by tsomone** [fluttercommunity/plus_plugins#808]
When i run this code on ios app, it shows action sheet, then i picked 'Save to Files' to saving file, but saved file doesn't have the filename, is there any way to give name to the saved file?

`Directory appDocDir = await getTemporaryDirectory();
            
Share.shareFilesWithResult(['${appDocDir.absolute.path}/$filename']); 
// filename is: my_image.jpg, my_doc.pdf etc`

Result:
![IMG_2165](https://user-images.githubusercontent.com/7868707/160412101-7dc9d1fd-03ae-4366-b297-58e41f54332a.PNG)

**Comment by Coronon** [comment]
Thanks for this question, that seems to be an iOS specific issue. If you are ok with moving this discussion into #821, please close this issue. :)
