### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by sowravroyjoy** [fluttercommunity/plus_plugins#809]
## System info

Platform the Issue occurs on: Android
Plugin name: AndroidAlarmManagerPlus
Plugin version:2.0.5

## Steps to Reproduce

1. ... I want to use the android alarm manager plus plugin to get some data using the shared preference plugin in the background every few minutes but I can not use the shared preference plugin in that as well as any other. Please provide me with any solution regarding that
2. ... It says, I need to register the plugin before using it but in the readme, there is no explanation for that how anyone does that.
3. ...

<details>
<summary>Logs</summary>

![image](https://user-images.githubusercontent.com/83823385/160455555-9499c4c1-6d3d-4d53-bfb4-b461829c3490.png)

```dart
```

</details>

<details>
<summary>Flutter doctor output</summary>

![image](https://user-images.githubusercontent.com/83823385/160455703-86789b97-5b0f-435c-8c31-84cd3c577b6e.png)

```
```

</details>

**Comment by j787701730** [comment]
[Windows] package_info_plus: ^1.4.0
```
Syncing files to device Windows...
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:377:43)
<asynchronous suspension>
#2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
<asynchronous suspension>
#3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:36:26)
<asynchronous suspension>
#4      main (package:task_reminder_flutter/main.dart:28:31)
<asynchronous suspension>
```
```
 Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586], locale zh-CN)
    • Flutter version 2.10.4 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (8 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
```

**Comment by Andrew-Bekhiet** [comment]
I think it is a problem with flutter itself, since in my case I have the same error with Hive and I believe it is the case for any plugin used on the background thread of AndroidAlarmManagerPlus

**Comment by Andrew-Bekhiet** [comment]
> I think it is a problem with flutter itself, since in my case I have the same error with Hive and I believe it is the case for any plugin used on the background thread of AndroidAlarmManagerPlus

Now I am sure
I upgraded to flutter 2.12.0-4.2.pre (latest beta version) and it works fine

**Comment by VladislavRUS** [comment]
On Windows project upgrading to 2.11.0-0.1.pre did not solve the problem

**Comment by VladislavRUS** [comment]
On Windows upgrading to 2.12.0-4.2.pre did not solve the problem

**Comment by fabiancrx** [comment]
@sowravroyjoy it seems to be an error of `shared_preferences` not `AndroidAlarmManagerPlus`, are you sure you call
