### ISSUE TITLE
[share_plus] Need shareSheet open and dismiss callbacks or Content shared successfully 

### ISSUE THREAD

**Issue by dhanrajVerma** [fluttercommunity/plus_plugins#811]
## Use case
We want to give application access to users when they share the Application to three people.  
We are using [share_plus](https://pub.dev/packages/share_plus) plugin for this purpose.
But this package did not give any kind of success callback(whether content is shared successfully or not).
So we do not know whether he shared the application or not.

## Proposal
These are my Suggestions
1. Success Callback telling the whether the content is shared successfully or not.
                                **OR**
2. Provide shareSheet opened and dismiss callbacks. (We will calculate elapsed time between these two callbacks and consider it a successful share if elapsed time is no less than **m** seconds )

**Comment by muhammadidrees** [comment]
Thank you for opening an issue.

Have you tried `shareWithResult` or `shareFilesWithResult`. It gives you the share status of whether the file was shared successfully or not.

You can read about it in the [docs](https://plus.fluttercommunity.dev/docs/share_plus/usage).

**Comment by dhanrajVerma** [comment]
> Thank you for opening an issue.
> 
> Have you tried `shareWithResult` or `shareFilesWithResult`. It gives you the share status of whether the file was shared successfully or not.
> 
> You can read about it in the [docs](https://plus.fluttercommunity.dev/docs/share_plus/usage).

@muhammadidrees thanks for the information as these methods updated recently that's why I missed them.
Thanks again.

**Comment by dhanrajVerma** [comment]
Since the issue is resolved, I am closing the issue.
