### ISSUE TITLE
Share not working on iPAD

### ISSUE THREAD

**Issue by pratikbaid3** [fluttercommunity/plus_plugins#822]
Share is working on iphone but not on ipad. I don't see a specific configuration that needs to be added to the iPad build so does the plugin not support ipad?

**Comment by xpolter** [comment]
Hi my friend!

It must be positioned via the "sharePositionOrigin" parameter.

Example:
`sharePositionOrigin: Rect.fromLTWH(10, 10, 10, 10),`

[example/lib/main.dart#L123](https://github.com/fluttercommunity/plus_plugins/blob/5f15844aa4531a9de13c1659883f247938833f19/packages/share_plus/share_plus/example/lib/main.dart#L123)

**Comment by balaji101010** [comment]
```
  static shareLink(BuildContext context, String url,
      {String? message, String? subject}) async {
    final RenderBox? box = context.findRenderObject() as RenderBox?;

    await Share.share(message!,
        sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size);
  }
```

Me too ! I have this code and it is not working in iPad

**Comment by xpolter** [comment]
> Наконец-то я это исправил
> 
> ```
>   static shareLink(BuildContext context, {String? message}) async {
>     Size size = MediaQuery.of(context).size;
>     Share.share(
>       message!,
>       sharePositionOrigin: Rect.fromLTWH(0, 0, size.width, size.height / 2),
>     );
>   }
> ```
> 
> Из этой ссылки для ipad выпуск [flutter/flutter#47220 (комментарий)](https://github.com/flutter/flutter/issues/47220#issuecomment-608453383)

Right
It worked for me when explicitly specifying the location of the element.

![Screenshot_1649160864](https://user-images.githubusercontent.com/65862130/161752991-d1a2a05b-866f-4a01-8ac4-536f699ffead.png)

**Comment by miquelbeltran** [comment]
documentation has been updated: https://github.com/fluttercommunity/plus_plugins/pull/898

**Comment by eyale** [comment]
I'm faced same issue with layout - Xcode console, says that this is Constraints bug, so I've fixed it with this code

```
sharePositionOrigin: Rect.fromLTWH(
          box.size.width.toDouble(),
          box.size.height.toDouble() / 1.6,
          10,
          10,
        ),
```
