### ISSUE TITLE
Could we exclude Settings.Secure.ANDROID_ID

### ISSUE THREAD

**Issue by johanlantz** [fluttercommunity/plus_plugins#824]
I recently submitted an app to Google Play Store and it seems that from June onwards you have to declare if you use tracking id's.

The error message from Google Play is not easy to understand, I was confused for quite some time before I found the usage of ANDROID_ID[ inside device_info_plus](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java#L109).

Since our app does not need ANDROID_ID, I prefer not to declare that our app uses tracking identifiers since I think this will show as a badge in the Google Play store which is unnecessary if the app does not need it.

For now I have just forked device_info_plus and removed it and Google is happy but given that this plugin is widely used, perhaps it is worth looking for a solution for this to not force apps not using tracking identifiers to declare that they do?

**Comment by lanistor** [comment]
Yeah, we need it too, int our law, you cannot request device id before your users allow it.

**Comment by vbuberen** [comment]
@johanlantz Could you provide some logs or messages from Google Play you mentioned? Because I currently work on a projects which uses `device_info_plus` as well and publishes updates every week. 
So far I haven't seen any warnings except for the other dependency I had, which was fixed this week.

**Comment by johanlantz** [comment]
I got emails from Google like the one below. Finally, I declared that we use unique identifiers in the Google Play Console even though we really do not have to. I think the consequence is that a badge will show in Google Play when a user downloads the app, saying that this app collects unique identifiers. As long as you declare that, it should not be an issue but on the other hand, many apps trying to collect as little data as possible probably do not want to show this to the user.

Maybe ANDROID_ID and friends just have to live in a plugin of their own at some point.
-------------------------
We found an issue in the following area(s):

SPLIT_BUNDLE 549: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)
About the Data safety section in Google Play User Data Policy Policy
Starting in late April 2022, approved Data safety sections will start appearing to users; make any changes needed by then. Starting July 20, 2022, your app must be in compliance with this policy or app updates will be rejected. If your app continues to be non-compliant beyond July 20, 2022 your app may face additional enforcement actions in the future.

Please make changes to align your app's Data safety section with the app's behavior. This can be done by either:

Updating your form in Play Console to declare collection of Data Types noted below; or
Removing unwanted functionality and attributable code that collects this user data from your app or libraries used in your app, and when applicable to deactivate all non-compliant APKs.
To deactivate non-compliant APKS, you can create a new release and upload a compliant APK to each track containing the non-compliant APKs.
Be sure to increment the APK version code. If using staged rollout, be sure to set the release to 100% rollout.
Learn more about how to [Provide app privacy and security information for Google Play's Data safety section](https://notifications.google.com/g/p/AD-FnEzSoaAynZ6VHS3lw6lG53xS9bdyw3H_4NNpa-50rt-oglLgRatQCQUW5QrsocmPojSN_2WJW5uYTOWW8bxwQGs4cE0BkqlCx80R5OhRBSDUr4a1ASMGXZK0hWEbEKhyQPsMfrNktn4C).

**Comment by feinstein** [comment]
@vbuberen I think this breaking change was rushed.

First of all there are many apps that need an Android ID (like financial apps) and don't want to be stuck with an old version of the library forever.

Second, although you made a breaking change and correctly incremented the library's major version, you didn't remove the androidId getter at the Flutter level, but just at the Android level, which means if someone didn't realize what's going on and just updated, things would compile just fine, he would release his app in production and later would see his backend not being able to process Android identifications.

So here are my recommendations:

1 - Make the Android ID getter configurable if possible.
2 - If you really want to remove it, remove it from the Flutter API as well.

**Comment by johanlantz** [comment]
The least complex option might just be creating a separate plugin called device_id_plus doing the inverse of this PR. Removing everything but the device_id.

**Comment by utkudenis** [comment]
Hello there,
We are selling an affordable package for new members within the app. We were controlling this with the device id so that new accounts would not be opened and taken from the same device. We can't do this right now, do you have any suggestions?

We explained that we got the device id information in the play store and why we got it, and it was accepted.

**Comment by johanlantz** [comment]
It is not about the app being accepted. I do not think Google would reject anyone for collecting this. The point is that most apps probably do not need AndroidId but they would still:
1. Be forced to declare this in Google Play for something they do not use.
2. On the App page on Google Play Store it will say under the Data Safety section that this app is collecting Device or other Id's and while this might not be an issue for most, an app that tries to stay as clean as possible, does not want this. 

Finally, as a previous poster mentioned, there might be legislative concerns in some countries around accessing these unique Id's before getting explicit user consent.

I still think the easiest solution is to add a new package in this multirepo with the sole purpose of getting the AndroidId and then the apps that need it, just use this new package.

**Comment by vbuberen** [comment]
> We can't do this right now, do you have any suggestions?

It is not true - you can continue using older version of the package and still have AndroidID as you want.

Would like to write to all people saying that update broke something for them - yes, it broke, but only for those, who did an update to a new version, which specifically had major version bumped to highlight that change is breaking. The reason for that is already explained. If you still need AndroidId - use older version of the package or create a different package for that. I don't think or support the idea that the `device_info_plus` package has to force people, who don't use AndroidId, to declare it in Play Console and create potential risks of not getting some users, who are concerned about which data some app collects.

Considering mentioned Google changes I strongly believe that `AndroidId` should be part of a different new package. If somebody is interested to create such - feel free so as I currently don't have much capacity. We (Plus plugins maintainers) can even help and host such new package here in `fluttercommunity`. For others, who want to have AndroidId, don't update `device_info_plus` to 4.0.0.

**Comment by feinstein** [comment]
As I said before I am going to say again: I strongly disagree with this position, being forced to an older version means never getting any updates from the package as any platform evolves.

There are other ways of solving this, as I said before, I think we can leave for the app to declare the Android id key into the App's Manifest, and make a machanism where it will come as null in dart if the app didn't declare it. This way no one is forced to collect the Android id, only those who actually need it.

I believe there are mechanism for making this optional and configurable, we don't need to exclude anyone.

**Comment by vbuberen** [comment]
> I think we can leave for the app to declare the Android id key into the App's Manifest, and make a mechanism where it will come as null in dart if the app didn't declare it.

You are more than welcome to implement it and open a PR for `device_info_plus`, helping other people like you. 
There is an option to create a package solely for `AndroidId`, which will be implemented soon depending on when somebody gets to it. You can be this person and greatly help the community by doing so. 

Demanding something the way you do from an open source project, which doesn't charge you anything and where people work in their free time, not as part of their job, isn't a nice way of collaboration.

I don't think you are going to implement anything, so would only suggest to use old version of plugin till a new package for AndroidId will be released.

**Comment by nohli** [comment]
FYI @feinstein @utkudenis 
The new plugin for getting the Android ID can be found [here](https://pub.dev/packages/android_id), so you can use the latest version of `device_info_plus` 🙂
