### ISSUE TITLE
[package_info_plus][windows] - Incorrect version returned

### ISSUE THREAD

**Issue by chirag729** [fluttercommunity/plus_plugins#835]
## System info

Platform the Issue occurs on:
Plugin name: package_info_plus
Plugin version: 1.4.2
Platform: Windows

## Steps to Reproduce

```
var packageInfo = await PackageInfo.fromPlatform();
print('${packageInfo.version})
```

Always outputs 1.0.0 instead of actual version as defined in pubspec.yaml.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/fluttercommunity/plus_plugins/issues/343; see my comment there.
