### ISSUE TITLE
Can't share image and text simultaneously on instagram, facebook.

### ISSUE THREAD

**Issue by Abhishek8115** [fluttercommunity/plus_plugins#839]
Everything works fine except this lib can't share text on Instagram and Facebook simultaneously. 
Neither the subject nor the title text appears in the message.

**Comment by acamue** [comment]
Same here

**Comment by miquelbeltran** [comment]
Duplicated

![image](https://user-images.githubusercontent.com/2494376/171183395-d4a40931-5646-4638-a096-e45e12e8a807.png)
