### ISSUE TITLE
[device_info_plus] Serial number for Android

### ISSUE THREAD

**Issue by woprandi** [fluttercommunity/plus_plugins#840]
## Use case
 
Read `Build.getSerial()` / `Build.SERIAL` for Android device.

And warn user about required permission
## Proposal

Add `serial` property to `AndroidDeviceInfo`

**Comment by Chinmay-KB** [comment]
Starting Android 10, [3rd party apps cannot ask for this info](https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids).

**Comment by woprandi** [comment]
@Chinmay-KB if the app is device owner you can still ask for it.

**Comment by Chinmay-KB** [comment]
App is device owner? I didn't get you.

**Comment by IlyaZadyabin** [comment]
Attempting `Build.getSerial()` is not compiling with an error: `Missing permissions required by Build.getSerial: android.permission.READ_PRIVILEGED_PHONE_STATE`.
And this permission can only be requested by system apps.

**Comment by woprandi** [comment]
@Chinmay-KB 
> App is device owner? I didn't get you.

It's written in your posted link : 

> Note: If your app is the [device or profile owner app](https://developers.google.com/android/work/overview#android_devices_enterprise_use_cases), you need only the [READ_PHONE_STATE](https://developer.android.com/reference/android/Manifest.permission#READ_PHONE_STATE) permission to access non-resettable device identifiers, even if your app targets Android 10 or higher. Also, if your app has [special carrier permissions](https://source.android.com/devices/tech/config/uicc), you don't need any permissions to access the identifiers.

**Comment by Chinmay-KB** [comment]
> @Chinmay-KB
> 
> > App is device owner? I didn't get you.
> 
> It's written in your posted link :
> 
> > Note: If your app is the [device or profile owner app](https://developers.google.com/android/work/overview#android_devices_enterprise_use_cases), you need only the [READ_PHONE_STATE](https://developer.android.com/reference/android/Manifest.permission#READ_PHONE_STATE) permission to access non-resettable device identifiers, even if your app targets Android 10 or higher. Also, if your app has [special carrier permissions](https://source.android.com/devices/tech/config/uicc), you don't need any permissions to access the identifiers.

From what I understood, if the device I have is a work device provided by enterprise (completely or partially), then the enterprise apps can access the non resettable identifiers, right?

**Comment by woprandi** [comment]
I only tested with a device-owner app and I can access to the serial number (otherwise it's `unknown`). It's probably same with other identifiers

**Comment by woprandi** [comment]
I did the implementation. It's quite simple. I'm open to discussion on this.

**Comment by vbuberen** [comment]
Can be closed as #840 is merged and will be released soon.

**Comment by naveenr-egov** [comment]
> I did the implementation. It's quite simple. I'm open to discussion on this.



> I did the implementation. It's quite simple. I'm open to discussion on this.

Can i get the implementation?   

Added this <uses-permission android:name="android.permission.READ_PRIVILEGED_PHONE_STATE" />
And granted the permission. Getting unknown when fetching serial number.

**Comment by woprandi** [comment]
`android.permission.READ_PRIVILEGED_PHONE_STATE ` is a special permission for preloaded app only. You need `android.permission.READ_PHONE_STATE` permission AND elevated privileges for the app (device owner for example).
