### ISSUE TITLE
[android_alarm_manager_plus] MissingPluginException for path_provider

### ISSUE THREAD

**Issue by TheCarpetMerchant** [fluttercommunity/plus_plugins#841]
## System info

Platform the Issue occurs on: Android
Plugin name: android_alarm_manager_plus
Plugin version: 2.0.5

## Steps to Reproduce

I could not reproduce the issue. It appears seemingly at random. It has not appeared in debug, I only got it twice through a print statement while debugging _another app_.
`MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel [plugins.flutter.io/path_provider](http://plugins.flutter.io/path_provider))`

How can I _manually_ register plugins, in order to avoid this no matter what ?

**Comment by chirag-chopra** [comment]
I also faced same issue...

**Comment by ldobreira** [comment]
Same!

**Comment by mdpe-ir** [comment]
i found a solution for it . 
due to  https://github.com/flutter/flutter/issues/99155#issuecomment-1052023743 .

Add dependencies on [path_provider_android](https://pub.dev/packages/path_provider_android) and [path_provider_ios](https://pub.dev/packages/path_provider_ios).

and your callback method should be like this : 

```
  // The callback for our alarm
  static Future<void> callback() async {

    if (Platform.isAndroid) PathProviderAndroid.registerWith();
    if (Platform.isIOS) PathProviderIOS.registerWith();

    ObjectBox objectbox = await ObjectBox.create();

    log("WORKS");


  }
```

**Comment by TheCarpetMerchant** [comment]
Yep, that's what I did, only difference being I'm using workmanager instead of android_alarm_manager_plus.
