### ISSUE TITLE
lateinit property sensorEventListener has not been initialized

### ISSUE THREAD

**Issue by Wackymax** [fluttercommunity/plus_plugins#843]
## System info

Platform the Issue occurs on: Android
Plugin name: sensors_plus
Plugin version: 1.3.1

## Steps to Reproduce

1. Not sure, only seeing the logs in Crashlytics

```
Caused by x8.r: lateinit property sensorEventListener has not been initialized
       at dev.fluttercommunity.plus.sensors.StreamHandlerImpl.onCancel(StreamHandlerImpl.java:12)
       at dev.fluttercommunity.plus.sensors.SensorsPlugin.teardownEventChannels(SensorsPlugin.java:40)
       at dev.fluttercommunity.plus.sensors.SensorsPlugin.onDetachedFromEngine(SensorsPlugin.java:5)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:143)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:16)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:11)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:10)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:31)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:90)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:18)
       at android.app.Activity.performDestroy(Activity.java:8225)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5441)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5493)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by darwin-morocho** [comment]
> ## System info
> Platform the Issue occurs on: Android Plugin name: sensors_plus Plugin version: 1.3.1
> 
> ## Steps to Reproduce
> 1. Not sure, only seeing the logs in Crashlytics
> 
> ```
> Caused by x8.r: lateinit property sensorEventListener has not been initialized
>        at dev.fluttercommunity.plus.sensors.StreamHandlerImpl.onCancel(StreamHandlerImpl.java:12)
>        at dev.fluttercommunity.plus.sensors.SensorsPlugin.teardownEventChannels(SensorsPlugin.java:40)
>        at dev.fluttercommunity.plus.sensors.SensorsPlugin.onDetachedFromEngine(SensorsPlugin.java:5)
>        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:143)
>        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:16)
>        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:11)
>        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:10)
>        at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:31)
>        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:90)
>        at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:18)
>        at android.app.Activity.performDestroy(Activity.java:8225)
>        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
>        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5441)
>        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5493)
>        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
>        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
>        at android.os.Handler.dispatchMessage(Handler.java:107)
>        at android.os.Looper.loop(Looper.java:237)
>        at android.app.ActivityThread.main(ActivityThread.java:8167)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
> ```

same error on Samsung devices

**Comment by fabiancrx** [comment]
Do you have any 'Steps to Reproduce' @darwin-morocho ? I can test with a samsung s8, would that device be representative of the issue?

**Comment by Wackymax** [comment]
Open a flutter app but don't open any of the sensor streams. Press the back button to close the app.

**Comment by darwin-morocho** [comment]
> Do you have any 'Steps to Reproduce' @darwin-morocho ? I can test with a samsung s8, would that device be representative of the issue?


Galaxy S21+ 5G and Galaxy S8+. I my case I just close the app and then In my firebase console I have the next error report

```
dev.fluttercommunity.plus.sensors.StreamHandlerImpl.onCancel (StreamHandlerImpl.java:12)
dev.fluttercommunity.plus.sensors.SensorsPlugin.teardownEventChannels (SensorsPlugin.java:40)
dev.fluttercommunity.plus.sensors.SensorsPlugin.onDetachedFromEngine (SensorsPlugin.java:5)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove (FlutterEngineConnectionRegistry.java:143)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove (FlutterEngineConnectionRegistry.java:16)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll (FlutterEngineConnectionRegistry.java:11)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy (FlutterEngineConnectionRegistry.java:10)
io.flutter.embedding.engine.FlutterEngine.destroy (FlutterEngine.java:31)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:90)
io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:18)
android.app.Activity.performDestroy (Activity.java:8468)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1344)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5622)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5682)
android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2317)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8595)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

**Comment by fabiancrx** [comment]
Thanks @darwin-morocho and @Wackymax, I'll take a look at this issue

**Comment by fabiancrx** [comment]
Actually it seems this issue should be solved after #838 is merged

**Comment by Wackymax** [comment]
Any update on this? I see there is an open PR, when will it be merged and released?

**Comment by PlutoHDDev** [comment]
My app also has this issue, so it would be great if the PR was merged as soon as possible.

**Comment by offline-first** [comment]
Please fix this bug

**Comment by fabiancrx** [comment]
For anyone who is in a hurry or blocked by this PR not being merged you could just override the dependency with the code from the PR in your pubspec.yaml 

```yaml
dependencies:
  sensors_plus:
    git:
      url: https://github.com/Rexios80/plus_plugins
      ref: c6ddf49f6c2a3ea553c86033ef5427893dc07707
      path: packages/sensors_plus/sensors_plus
```

cc: @offline-first

**Comment by AndreCarreiraGoncalves** [comment]
How do i still have this issue even tho I uninstalled the package, cleared pub cache, deleted lock, did flutter clean...

**Comment by SirusCodes** [comment]
We can close this as #838 is merged👀
