### ISSUE TITLE
[android_intent_plus] canResolveActivity() returns false in targetSdkVersion>=30

### ISSUE THREAD

**Issue by saulrmzlpz** [fluttercommunity/plus_plugins#850]
## System info

Platform the Issue occurs on: Android
Plugin name: android_intent_plus
Plugin version: 3.1.1

## Steps to Reproduce

1. Create flutter project
2. Add plugin to dependencies
3. Create intent object with action: 'android.intent.action.MAIN' or another for one app
4. The method canResolveActivity() always return false

<details>
<summary>Logs</summary>

```dart
```

</details>

<details>
<summary>Flutter doctor output</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale
    es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by saulrmzlpz** [comment]
Doing some research I found the following link:

Add the following to my app's manifest and it seems to work.
`        <queries>
          <intent>
              <action android:name="android.intent.action.MAIN" />
          </intent>
          <intent>
              <action android:name="android.action.start.flutter.activity" />
          </intent>
      </queries>`

Will we have to add each action in our manifest to fix it?

**Comment by saulrmzlpz** [comment]
Any update?...

**Comment by charafau** [comment]
Looks like there's nothing we can do but add documentation for that function with links to Android docs
