### ISSUE TITLE
No implementation found for method listen on channel 

### ISSUE THREAD

**Issue by VNAPNIC** [fluttercommunity/plus_plugins#860]
```dart
startNetworkChecking() {
  Connectivity().onConnectivityChanged.listen((ConnectivityResult result) {
    Log.info('$Connectivity', 'ConnectivityResult -> $result');
    _streamController.sink.add(result);
  });
}

checkInternetConnection() async {
  var result = await (Connectivity().checkConnectivity());
  _streamController.sink.add(result);
}

```

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel dev.fluttercommunity.plus/connectivity_status:
MissingPluginException(No implementation found for method listen on channel dev.fluttercommunity.plus/connectivity_status)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:516:9)
<asynchronous suspension>
====================================================================================================
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ 💡 Application: setting is  unsubscribe<…>
flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method check on channel dev.fluttercommunity.plus/connectivity)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      checkInternetConnection (package:configuration/network/network.dart:17:16)
<asynchronous suspension>
flutter: WalletManager 286996137 current wallet state WalletState.noWallet

**Comment by turtlepile** [comment]
we are having the same issue. Any solution?

**Comment by AdamBridges** [comment]
I know this may be obvious but did you try stopping and running the app after adding the package?

**Comment by braginsm** [comment]
I'm having the same issue, but only when I try to generate golden tests

**Comment by zzorba** [comment]
Seeing the same exact thing, when trying to use this with `graphql_flutter` package

**Comment by miloops** [comment]
Anyone found a way to fix this?

**Comment by sarankumar-ns** [comment]
+1

**Comment by miquelbeltran** [comment]
In general, shouldn't call into a platform plugin from tests, instead, the package should be mocked or wrapped with a service class that can be replaced via dependency injection.
