### ISSUE TITLE
[share_plus] Error: PlatformException(Share failed, assets/images/app-logo.png: The source file doesn't exist., null, null)

### ISSUE THREAD

**Issue by federico2390** [fluttercommunity/plus_plugins#861]
Hello I don't know why my iOS real device display image but not android real device.
I receive the error on the title and I'm using this myself method. What's is wrong?

```
Future<void> share(
    {BuildContext context, String asset, String text, String subject}) async {
  try {
    await Share.shareFiles([
      AssetImage(asset).assetName,
    ],
        text: text,
        subject: subject,
        sharePositionOrigin: Rect.fromCenter(
            center: Offset(
                MediaQuery.of(context).size.width / 2,
                (MediaQuery.of(context).size.height / 2) +
                    MediaQuery.of(context).size.height / 2),
            width: 100,
            height: 100));
  } catch (e) {
    print('Error: $e');
  }
}
```

and call this method as it:

 ```
share(
  context: context,
  asset: 'assets/images/app-logo.png',
  text: 'Title', 
  subject: 'Subject',
);
```

Thanx

**Comment by federico2390** [comment]
Solved:

```
Future<void> share(
    {BuildContext context, String asset, String text, String subject}) async {
  try {
    ByteData imagebyte = await rootBundle.load(asset);
    final temp = await getTemporaryDirectory();
    final path = '${temp.path}/imagename.png';
    File(path).writeAsBytesSync(imagebyte.buffer.asUint8List());

    await Share.shareFiles([
      path,
    ],
        text: text,
        subject: subject,
        sharePositionOrigin: Rect.fromCenter(
            center: Offset(
                MediaQuery.of(context).size.width / 2,
                (MediaQuery.of(context).size.height / 2) +
                    MediaQuery.of(context).size.height / 2),
            width: 100,
            height: 100));
  } catch (e) {
    print('Error: $e');
  }
}
```

**Comment by mase7569** [comment]
> Solved:
> 
> ```
> Future<void> share(
>     {BuildContext context, String asset, String text, String subject}) async {
>   try {
>     ByteData imagebyte = await rootBundle.load(asset);
>     final temp = await getTemporaryDirectory();
>     final path = '${temp.path}/imagename.png';
>     File(path).writeAsBytesSync(imagebyte.buffer.asUint8List());
> 
>     await Share.shareFiles([
>       path,
>     ],
>         text: text,
>         subject: subject,
>         sharePositionOrigin: Rect.fromCenter(
>             center: Offset(
>                 MediaQuery.of(context).size.width / 2,
>                 (MediaQuery.of(context).size.height / 2) +
>                     MediaQuery.of(context).size.height / 2),
>             width: 100,
>             height: 100));
>   } catch (e) {
>     print('Error: $e');
>   }
> }
> ```

This should be documented!
