### ISSUE TITLE
[connectivity_plus] not compatible with flutter_svg

### ISSUE THREAD

**Issue by zakblacki** [fluttercommunity/plus_plugins#868]
> Because flutter_svg >=1.1.0 depends on xml ^6.0.1 and dbus >=0.2.0 depends on xml ^5.0.0, flutter_svg >=1.1.0 is incompatible with dbus >=0.2.0.
> And because nm 0.5.0 depends on dbus ^0.7.0 and no versions of nm match >0.5.0 <0.6.0, flutter_svg >=1.1.0 is incompatible with nm ^0.5.0.
> And because connectivity_plus_linux 1.3.0 depends on nm ^0.5.0 and no versions of connectivity_plus_linux match >1.3.0 <2.0.0, flutter_svg >=1.1.0 is incompatible with connectivity_plus_linux ^1.3.0.
> And because connectivity_plus 2.3.0 depends on connectivity_plus_linux ^1.3.0 and no versions of connectivity_plus match >2.3.0 <3.0.0, flutter_svg >=1.1.0 is incompatible with connectivity_plus ^2.3.0.
> So, because project depends on both connectivity_plus ^2.3.0 and flutter_svg ^1.1.0, version solving failed.

**Comment by m-theis** [comment]
Hey @zakblacki 

I just wrote how to deal with this in https://github.com/fluttercommunity/plus_plugins/issues/869
Since you are using flutter_svg 1.1.0 just change the xml override to version 6.0.1

**Comment by miquelbeltran** [comment]
Please use the Bug template to fill a bug report and include all the information in it

**Comment by jpnurmi** [comment]
Perhaps just a matter of running `flutter pub upgrade`?

```
jpnurmi@xps-15-9520:~/Temp$ flutter create --platforms linux connectivity_svg
Creating project connectivity_svg...
Running "flutter pub get" in connectivity_svg...                   864ms
Wrote 18 files.

All done!
In order to run your application, type:

  $ cd connectivity_svg
  $ flutter run

Your application code is in connectivity_svg/lib/main.dart.

jpnurmi@xps-15-9520:~/Temp$ cd connectivity_svg/
jpnurmi@xps-15-9520:~/Temp/connectivity_svg$ flutter pub add connectivity_plus flutter_svg
Resolving dependencies...
+ args 2.3.1
  async 2.8.2 (2.9.0 available)
  characters 1.2.0 (1.2.1 available)
  clock 1.1.0 (1.1.1 available)
+ connectivity_plus 2.3.5
+ connectivity_plus_linux 1.3.1
+ connectivity_plus_macos 1.2.4
+ connectivity_plus_platform_interface 1.2.1
+ connectivity_plus_web 1.2.2
+ connectivity_plus_windows 1.2.2
+ dbus 0.7.6
  fake_async 1.3.0 (1.3.1 available)
+ ffi 2.0.1
+ flutter_svg 1.1.0
+ flutter_web_plugins 0.0.0 from sdk flutter
+ js 0.6.4
  matcher 0.12.11 (0.12.12 available)
  material_color_utilities 0.1.4 (0.1.5 available)
  meta 1.7.0 (1.8.0 available)
+ nm 0.5.0
  path 1.8.1 (1.8.2 available)
+ path_drawing 1.0.0
+ path_parsing 1.0.0
+ petitparser 5.0.0
+ plugin_platform_interface 2.1.2
  source_span 1.8.2 (1.9.0 available)
  string_scanner 1.1.0 (1.1.1 available)
  term_glyph 1.2.0 (1.2.1 available)
  test_api 0.4.9 (0.4.11 available)
+ xml 6.1.0
Downloading connectivity_plus 2.3.5...
Changed 18 dependencies!
jpnurmi@xps-15-9520:~/Temp/connectivity_svg$ flutter pub get
Running "flutter pub get" in connectivity_svg...                   266ms
jpnurmi@xps-15-9520:~/Temp/connectivity_svg$ echo $?
0
```
