### ISSUE TITLE
[connectivity_plus] not compatible with image

### ISSUE THREAD

**Issue by a-v-ebrahimi** [fluttercommunity/plus_plugins#869]
Because image >=3.2.0 depends on xml ^6.0.0 and dbus >=0.2.0 depends on xml ^5.0.0, image >=3.2.0 is incompatible with dbus >=0.2.0.
And because nm 0.5.0 depends on dbus ^0.7.0 and no versions of nm match >0.5.0 <0.6.0, image >=3.2.0 is incompatible with nm ^0.5.0.
And because connectivity_plus_linux 1.3.0 depends on nm ^0.5.0 and no versions of connectivity_plus_linux match >1.3.0 <2.0.0, image >=3.2.0 is incompatible with connectivity_plus_linux ^1.3.0.
And because connectivity_plus 2.3.0 depends on connectivity_plus_linux ^1.3.0 and no versions of connectivity_plus match >2.3.0 <3.0.0, image >=3.2.0 is incompatible with connectivity_plus ^2.3.0.
...
pub get failed (1; So, because APP depends on both connectivity_plus ^2.3.0 and image ^3.2.0, version solving failed.)

**Comment by miquelbeltran** [comment]
Please use the Bug template to fill a bug report and include all the information in it
