### ISSUE TITLE
android_alarm_manager_plus 2.0.5 not working periodically with 1 day interval

### ISSUE THREAD

**Issue by SaikiranReddy412** [fluttercommunity/plus_plugins#871]
we are getting issues with android_alarm_manager_plus 2.0.5 not working periodically with 1 day interval and not firing every 24 hr

**Comment by miquelbeltran** [comment]
Please use the Bug template to fill a bug report and include all the information in it

**Comment by vbuberen** [comment]
Even with missing information I feel it is related to https://github.com/fluttercommunity/plus_plugins/pull/810

**Comment by charafau** [comment]
instead of depending on alarm manager, it would be probably better to use [Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager) as it's preffered way of scheduling tasks on Android right now

**Comment by miquelbeltran** [comment]
I mean, no. AlarmManager has a place (wanting to run a task at a precise time, e.g. an actual alarm) and WorkManager is more to schedule work in the background without worrying too much on when it is going to be done.

Now, on Flutter and given how flaky the plugin is, I would simply avoid using either if possible.

**Comment by Rackor** [comment]
AlarmManager has definitely its place since its the only possibility to fight [Doze Mode](https://developer.android.com/training/monitoring-device-state/doze-standby) without internet connection (then Push Notificiations can be used). WorkManager is for general background scheduling, and cannot wake the device up when in doze mode!

**Comment by charafau** [comment]
You're right, I misread the docs. I was pretty sure that the work manager had a special API for alarm manager like tasks. Thanks 👍
