### ISSUE TITLE
[share_plus] On iPad, it is not possible to dismiss the Share dialog

### ISSUE THREAD

**Issue by albemala** [fluttercommunity/plus_plugins#875]
## System info

Platform the Issue occurs on: iPadOS 14.x
Plugin name: share_plus
Plugin version: 4.0.4

## Steps to Reproduce

On the iPhone (iOS), when showing the Share dialog, it is possible to dismiss it by tapping on the black area above it (red circle in the screenshot below), or with the Close button (arrow in the screenshot below).

On the iPad (iPad OS 14.x), neither of these options are available. When tapping outside the Share dialog, touch events are passed to the Flutter app and it's still possible to interact with it. The Close button is not present. Therefore it's not possible to dismiss/close the Share dialog.

Sorry I don't have an iPad from where I can take a screenshot. This has been reported by some users. 

I also don't know if this happens only on iPadOS 14 or also on iPadOS 15. It was tested on iPadOS 14 only.

Thanks!

![IMG_C1D4D9A9A583-1](https://user-images.githubusercontent.com/2332860/170943881-b0813cb2-ff1f-4b5b-bc22-bc64bf0a7950.jpeg)

**Comment by miquelbeltran** [comment]
I believe this would have to do with the `sharePositionOrigin` param.

From the docs:

```
  /// The optional [sharePositionOrigin] parameter can be used to specify a global
  /// origin rect for the share sheet to popover from on iPads. It has no effect
  /// on non-iPads.
```

You will need an iPad (maybe a simulator) to implement that correctly.

**Comment by albemala** [comment]
I'm already setting the `sharePositionOrigin` parameter, so I believe the problem is not related to that.

**Comment by miquelbeltran** [comment]
Documentation has been updated: https://github.com/fluttercommunity/plus_plugins/pull/898

Please provide a code example on this ticket, since I could not reproduce the issue on an iPad simulator with the share_plus example

**Comment by miquelbeltran** [comment]
thanks for the feedback!

**Comment by JetA2** [comment]
This issue seems to appear when sharing is initiated from a dialog.
There is a narrow band at the top of the screen where a tap still dismisses the share sheet.
On the rest of the screen area, taps interact with the Flutter UI.
When the dialog is popped, the share sheet remains.
The share sheet can then be dismissed by tapping outside of it, except when tapping on UI elements that capture taps like buttons etc.
