### ISSUE TITLE
[sensors_plus][android] Compilation fails - Redeclaration: StreamHandlerImpl

### ISSUE THREAD

**Issue by lahdekorpi** [fluttercommunity/plus_plugins#878]
```
e: ~/.pub-cache/hosted/pub.dartlang.org/sensors_plus-1.3.2/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/StreamHandlerImpl.kt: (10, 16): Redeclaration: StreamHandlerImpl

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sensors_plus:compileDebugKotlin'.
> Compilation error. See log for more details
```

1.3.1 works.  
1.3.2 does not.

**Comment by miquelbeltran** [comment]
Please use the Bug template to fill a bug report and include all the information in it

**Comment by lavinov-mercury** [comment]
@androidyue `flutter clean` didn't work for me, but defining a dependency override for sensors_plus to 1.3.1 did. And i even has no sensors_plus in my deps, it's a transitive dependency
```
dependency_overrides:
  sensors_plus: 1.3.1
```

**Comment by samuelchanx** [comment]
In my case, using flutter clean fixes the issue, while using overriden version of 1.3.2 for sensors_plus. Hope it helps @lavinov-mercury 
```
dependency_overrides: 
  sensors_plus: 1.3.2
```

**Comment by ShahzaibAyyub** [comment]
> In my case, using flutter clean fixes the issue, while using overriden version of 1.3.2 for sensors_plus. Hope it helps @lavinov-mercury
> 
> ```
> dependency_overrides: 
>   sensors_plus: 1.3.2
> ```

This fixed my issue. Thanks!
