### ISSUE TITLE
how to check if internet connection is available?

### ISSUE THREAD

**Issue by eggysudianto** [fluttercommunity/plus_plugins#882]
### What is your question?

I tried connect to other second  phone using mobile tethering, but internet connection in second phone is turn off, only turn on tethering, but the result code detect my phone connect using wifi even though internet is not available.

how to check if internet connection is available?

**Comment by miquelbeltran** [comment]
Looks like your question is more suited for StackOverflow, but have you tried the connectivity_plus plugin?

**Comment by niteshsh4rma** [comment]
> yes I have, but without internet connection this plugin still return true because connect wifi
@eggysudianto 

You can ping google.com and check responses to conclude network connectivity. https://dev.to/ashishrawat2911/handling-network-calls-and-exceptions-in-flutter-54me

**Comment by miquelbeltran** [comment]
I'll close the issue, as this is not related to plus_plugins. I'd recommend checking on StackOverflow as said.
