### ISSUE TITLE
CI build script needs updated

### ISSUE THREAD

**Issue by Sunbreak** [fluttercommunity/plus_plugins#89]
As shown at https://github.com/fluttercommunity/plus_plugins/blob/a7038c25613d16c85b82a8f1228abec0220852ff/.github/workflows/all_plugins.yaml#L86

We use `flutter build aot` in build script, which is deprecated https://github.com/flutter/flutter/issues/49562

**Comment by miquelbeltran** [comment]
Is this replaced with `flutter assemble` ?

**Comment by Sunbreak** [comment]
Sorry I've no idea

**Comment by miquelbeltran** [comment]
Fixed
