### ISSUE TITLE
[Question]:Unused variable 'pathExtension' Warning

### ISSUE THREAD

**Issue by BetulComak** [fluttercommunity/plus_plugins#900]
### What is your question?

I am using share_plus package(v:4.0.7) in flutter application. But when I get build for ios via Xcode, it gives a "Unused variable 'pathExtension'" warning. How can I solve this?

**Comment by Chever-John** [comment]
Can you tell us about the flutter version?

**Comment by Chever-John** [comment]
It is advisable to attach, the command that will accurately reproduce this problem.

**Comment by BetulComak** [comment]
@Chever-John  Hi, I am using flutter version 3.0.0 and only I just press build on Xcode

**Comment by Chever-John** [comment]
@BetulComak Got it, let me try this command on my end.

**Comment by Chever-John** [comment]
@BetulComak Hi, I have just tried to reproduce the problem. 

**The result is that everything is fine here**.

The problem reproduction process is as follows. Please reply to me directly if you have a different opinion.


## Configuration

My machine & env configuration:
```bash
macOS: 12.4 (M1)
flutter version: 3.0.1 (Maybe I should try 3.0.0)
Android Studio: Android Studio Bumblebee | 2021.1.1 Patch 2
Xcode: Version 13.4.1 (13F100)
```

## Problem reproduction process

My pubspec.yaml
```bash
dependencies:
  flutter:
    sdk: flutter
  share_plus: ^4.0.7
```

Codes from this [repository](https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus/example)
