### ISSUE TITLE
[Bug]: Module 'battery_plus' not found in iOS

### ISSUE THREAD

**Issue by SaikiranReddy412** [fluttercommunity/plus_plugins#908]
### Platform

iOS 15.5

### Plugin

battery_plus'

### Version

2.1.4

### Flutter SDK

2.10.5

### Steps to reproduce

![Screenshot 2022-06-14 at 11 35 54 AM](https://user-images.githubusercontent.com/27664178/173505156-5cdf2b78-7769-49c9-baf9-25cab1b00bcd.png)

### Code Sample

```dart
var battery = Battery();
    batteryLevel = (await battery.batteryLevel).toDouble();
    print("Battery ${await battery.batteryLevel}");
```

### Logs

```shell
MetadataProvider: Loaded debug metadata for module: packages/battery_plus_web/battery_plus_web.dart
[   +8 ms] MetadataProvider: Loaded debug metadata for module: packages/battery_plus_platform_interface/method_channel_battery_plus.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/battery_plus_platform_interface/src/enums.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/battery_plus_platform_interface/src/utils.dart

Found plugin battery_plus_macos at /Users/dcasf/BddddgazeDevelopment
/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/battery_plus_macos-1.1.1/
[   +7 ms] Found plugin battery_plus_web at /Users/ddd/BddddeDevelopment
/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/battery_plus_web-1.1.0/
[  +13 ms] Found plugin battery_plus_windows at /Users/bidddzgddaze/BdddeDevelopment
/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/battery_plus_windows-1.1.2/
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by penhorwood** [comment]
I am seeing this same bug on my iOS build.

**Comment by miquelbeltran** [comment]
As I understand, this is a compilation issue, right?

I cannot reproduce this by compiling the example in the battery_plus package folder. Can you try that? build and run the example in `packages/battery_plus/battery_plus/example`

**Comment by charafau** [comment]
Checked this on new project:

```
$ flutter create battery_test
$ cd battery_test
$ flutter pub add battery_plus
```

copied example from.. example folder

plugin compiled and works.

my flutter doctor output:
```
➜  battery_test flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-GB)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
```

guess we can close this ?

**Comment by DenisMrGnusa** [comment]
same issue here, 

flutter version
Flutter 3.3.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6928314d50 (7 days ago) • 2022-10-25 16:34:41 -0400
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0

flutter doctor
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-x64, locale en-ID)                                                                                                                                                                                                                                     Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

my device
Iphone XR (iOS 15.5)

**Comment by miquelbeltran** [comment]
I cannot reproduce the issue with a newly created project. You probably need to clean your project and maybe delete the Podfile.lock and Pods folder, so it is recreated correctly again.

**Comment by miguelmobilat** [comment]
same problem

**Comment by Fugipe** [comment]
same problem
