### ISSUE TITLE
[Bug]: For IOS connectivity checking it not supporting perfectly

### ISSUE THREAD

**Issue by shashanka777** [fluttercommunity/plus_plugins#927]
### Platform

IOS

### Plugin

Connectivity plus

### Version

1.0.0

### Flutter SDK

 ">=2.17.0 <3.0.0"

### Steps to reproduce

1.In IOS emulator it showing previous connected status , If wifi connected  it will show previous "disconnected  status". 
2.After wifi is disconnected it will show previous connected status is "connected wifi"

### Logs

```shell
NA
```

### Flutter Doctor

```shell
NA
```

**Comment by ehusmann** [comment]
Seems to be a known issue that is affecting iOS simulators and has not much to do with the package:
https://github.com/fluttercommunity/plus_plugins/issues/479

**Comment by Chever-John** [comment]
@ehusmann Agree!
Maybe it seems to the issue #479

**Comment by marcglasberg** [comment]
We are having problems in real iPhones. So it's not only in the Simulator.

**Comment by miquelbeltran** [comment]
@minhdangoz the plus_plugins is an open source project maintained by volunteers, so solving issues depends on their time, knowledge, and motivation to do so. Asking for updates doesn't help anyone. Instead, you can help by providing more information about the issue, researching possible solutions, and even submitting a PR with a fix.
