### ISSUE TITLE
[Bug]: Unable to share subject text to whatsapp

### ISSUE THREAD

**Issue by dafanabil** [fluttercommunity/plus_plugins#938]
### Platform

Android 12

### Plugin

share_plus

### Version

4.0.10

### Flutter SDK

3.0.1

### Steps to reproduce

I found issue in this plugin only in Android device
If i share this in whatsapp then only image and text is showing but not coming subject 
And if i share in Skype then only image is coming

### Code Sample

```dart
shareResult = await Share.shareFilesWithResult(
                                    [path],
                                    text: '''
                                  $text
                                  https://www.google.com/maps/search/?api=1&query=$latitude,$longitude''',
                                    subject: 'test',
                                    sharePositionOrigin:
                                        box!.localToGlobal(Offset.zero) &
                                            box.size);
```

### Logs

```shell
V/FA      ( 4364): Connecting to remote service
V/FA      ( 4364): Connection attempt already in progress
V/FA      ( 4364): Activity paused, time: 3896159443
D/FA      ( 4364): Connected to remote service
V/FA      ( 4364): Processing queued up service tasks: 2
E/        ( 4364): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale en-SA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by Coronon** [comment]
Hi there, it is expected behaviour, that the `subject` will not show up when sharing to WA.
Where would you put it? You can share files (an image it seems in this case) and add text, which will use the `text` argument.

The subject would be used if you for example shared via email which allows a subject and main body.

Hope this explains your issue :)

**Comment by dafanabil** [comment]
Hi,

Thanks for the reply.
I even try to share on "Skype" and only image is showing not text or subject argument.
Only it's working perfectly on sharing to "GMail".

This is the code tried to share on "Skype" but only displaying image
`await Share.shareFilesWithResult(
                                    [path],
                                    text: 'test',
                                    sharePositionOrigin:
                                        box!.localToGlobal(Offset.zero) &
                                            box.size);`

**Comment by Coronon** [comment]
I don’t know about Skype, maybe they implemented sharing differently and don’t accept a text and image together? Do you know of another App that supports both text and image sharing to skype?

**Comment by dafanabil** [comment]
Skype don't accept image and text together, only working perfectly in gmail. I don't know which app supports both sharing to skype.

**Comment by Coronon** [comment]
That sounds like a limitation of third party applications, which would not be a bug of `share_plus`. Please close this issue if you don't have further questions or can show that other apps can share like that :)

**Comment by sajjad-n** [comment]
For WhatsApp, you can't share image and text at the same time. 
@masood5400
