### ISSUE TITLE
[device_info_plus] browse name is incorrect for Edge

### ISSUE THREAD

**Issue by zengkid** [fluttercommunity/plus_plugins#94]
## System info

Issue occurs on: windows Egde web
Plugin name: device_info
Plugin version: 0.6.0

my code:
```dart
'browserName': describeEnum(data.browserName),
'userAgent': data.userAgent,
```
the output is Chrome
```
browserName: chrome

userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
```

**Comment by miquelbeltran** [comment]
Microsoft Edge is based in Chromium :thinking:

**Comment by mhadaily** [comment]
@zengkid  Thanks for reporting this should fix it now https://github.com/fluttercommunity/plus_plugins/pull/95/files

we will release it once it's merged.
