### ISSUE TITLE
[Question]: Bumping [package_info_plus_windows] ffi dependency version

### ISSUE THREAD

**Issue by adigladi** [fluttercommunity/plus_plugins#941]
### What is your question?

Hi! Currently in our project (iOS/Android) we are encountering issues when using `ffi` version 2 since `package_info_plus_windows` depends on an older version of `ffi (1.0.0)`. Is it possible to bump this dependency version? We can override that dependency for now, but might be a good upgrade for the plugin if possible.

**Comment by guyluz11** [comment]
I think we need to update the `ffi` version.

`device_info_plus` dependence got an update and now the ffi version gets conflicted.

```
Because no versions of package_info_plus match >1.4.2 <2.0.0 and package_info_plus 1.4.2 depends on package_info_plus_windows ^1.0.5, package_info_plus ^1.4.2 requires package_info_plus_windows ^1.0.5.
And because no versions of package_info_plus_windows match >1.0.5 <2.0.0 and package_info_plus_windows 1.0.5 depends on ffi ^1.0.0, package_info_plus ^1.4.2 requires ffi ^1.0.0.
And because device_info_plus >=4.0.1 depends on device_info_plus_windows ^3.0.1 which depends on ffi ^2.0.1, package_info_plus ^1.4.2 is incompatible with device_info_plus >=4.0.1.
So, because cybear_jinni depends on both device_info_plus ^4.0.1 and package_info_plus ^1.4.2, version solving failed.
pub get failed (1; So, because cybear_jinni depends on both device_info_plus ^4.0.1 and package_info_plus ^1.4.2, version solving failed.)
```

**Comment by guyluz11** [comment]
Found pull request that should fix that
#941

**Comment by guyluz11** [comment]
Hi @adigladi

My pull request got merged, you can close the issue now.

**Comment by adigladi** [comment]
Thank you @guyluz11!
