### ISSUE TITLE
[Request]: getSerial()

### ISSUE THREAD

**Issue by lalLAL95828** [fluttercommunity/plus_plugins#948]
### Plugin

device_info_plus

### Use case

hope get Serial

### Proposal

Serial

**Comment by VoidCupboard** [comment]
Can I work on this issue?

**Comment by VoidCupboard** [comment]
Hi! Can I work on this issue?

**Comment by suryaa62** [comment]
can I work on this issue?

**Comment by vbuberen** [comment]
On iOS Apple forbids to get unique device identifiers like serial number. Google goes the same way, so it makes no sense in adding this functionality, even if it is planned to be used on old versions of iOS or Android.
