### ISSUE TITLE
Image + Text Url is not shared in IOS at the same time

### ISSUE THREAD

**Issue by expertdev-designer** [fluttercommunity/plus_plugins#962]
### What is your question?

I have to share Image + Text url  at the same time as normal message. In Android  image and Text both share perfectly but in IOS only image is shared and text is excluded

**Comment by ndesamuelmbah** [comment]
I have the same problem.
@expertdev-designer  did you find any solution yet?

**Comment by expertdev-designer** [comment]
@ndesamuelmbah No Yet.

**Comment by expertdev-designer** [comment]
@ndesamuelmbah No Yet.

**Comment by sajjad-n** [comment]
For WhatsApp, you can't share image and text at the same time. 
@masood5400

**Comment by weijie050301** [comment]
faced same issues

**Comment by parulgarg004** [comment]
Facing same issue

**Comment by 01000001x01001110x01010011x01001000** [comment]
Facing same issue but with android and ios both any suggestion ?
