### ISSUE TITLE
[Question]: How To Get Context Inside Callback

### ISSUE THREAD

**Issue by TomerPacific** [fluttercommunity/plus_plugins#964]
### What is your question?

When using the Flutter AlarmManagerPlus package and any one of its exposed methods, the callback we can pass is either of type Function or Function(int).

`assert(callback is Function() || callback is Function(int));`

Furthermore, we are instructed to mark our callback functions as **_static_**.

Due to all of these restrictions, I am wondering how I can access/get a context in one of the callbacks so that I can (for example) show an alert dialog when the callback is being triggered.

```
 static void _periodicTaskCallback() {
    // How to get context here?
  }

 void _schedulePeriodicAlarm() async {
    Duration duration = await _chooseDuration();
    await AndroidAlarmManager.periodic(duration, _periodicTaskId, _periodicTaskCallback);
  }
```

Just as a note, I have a basic one class stateful widget and I have tried accessing the state using a GlobalKey or using the OneContext package, but both don't appear to work.

You can see the code [here](https://github.com/TomerPacific/MediumArticles/blob/master/alarm_manager_example/lib/main.dart).

Any guidance will be appreciated.

**Comment by wurikiji** [comment]
In addition, if what you want to do is to show a graphical alert when the alarm is on, then consider https://pub.dev/packages/flutter_local_notifications package.
