### ISSUE TITLE
[Bug]: Build and deploy website CI job failing

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#969]
### Steps to reproduce

See failed job: https://github.com/fluttercommunity/plus_plugins/runs/7388153075?check_suite_focus=true

**Comment by vbuberen** [comment]
Yes, saw such issue when was playing around with some dependencies updates for our website. Changing some of dependencies version helps. The only problem was that we don't have preview enabled on Firebase where the website, so didn't want to push potentially breaking website changes without being sure that website still works fine.
