### ISSUE TITLE
[Bug]: Battery save mode not available.

### ISSUE THREAD

**Issue by water-user** [fluttercommunity/plus_plugins#988]
### Platform

10

### Plugin

battery_plus

### Version

^2.1.4

### Flutter SDK

2.8.1

### Steps to reproduce

[](url)Run the application.
This crash occurs only on my Xiaomi Mi 9T Pro
![Screen Shot 2022-07-31 at 11 28 50](https://user-images.githubusercontent.com/95235346/182018070-7155c93b-4cc1-4bb7-851f-a471f4df290b.png)

![1659257037034](https://user-images.githubusercontent.com/95235346/182018200-e6886a05-276d-46ec-bc47-93e4ca1a7f85.jpg)

### Code Sample

```dart
Battery().isInBatterySaveMode.then((isInSaveMode) {
      if (Platform.isIOS || !isInSaveMode || Prefs.isBatterySaverDetected) {
        return;
      } else {
        Future.delayed(Duration.zero, () => showBatterySaverDetectionDialog());
      }
    }).catchError((e) {
      print(e);
    });
```

### Logs

```shell
No data.
```

### Flutter Doctor

```shell
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (8 months ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

**Comment by miquelbeltran** [comment]
Well, if save mode is not available on the device, there's not much we can do :)

`inInBatterySaveMode` returns a `bool`, so we cannot return a different state (like `unavailable`).

Probably improving documentation and explaining that the method will throw is good enough.

Still, is good practice to catch all errors that can come from native platform calls just in case.

**Comment by JulianBissekkou** [comment]
Can you please reopen the issue?
This happens on a Huawei P30 Lite which has a battery save mode, so this shouldn't throw an exception.
