### ISSUE TITLE
I can't get the Wifi name

### ISSUE THREAD

**Issue by ousvat** [fluttercommunity/plus_plugins#99]
## System info

Issue occurs on:  Android 10
Plugin name: connectivity_plus
Plugin version: ^0.7.1
Flutter doctor output:

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.22.6 at D:\Flutter\flutter_windows_1.17.3-stable\flutter
    • Framework revision 9b2d32b605 (6 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ovidiu.usvat\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\ovidiu.usvat\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\ovidiu.usvat\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • SM G970F (mobile) • RF8MA07GHKP • android-arm64 • Android 10 (API 29)
```

## Steps to Reproduce

1. My code looks like here:
```
onPressed: () async {
                var wifiIP = await WifiInfo().getWifiIP();
                var wifiName = await WifiInfo().getWifiName();
                print('$wifiIP -> $wifiName');
              },
```
2. Each time I press the button i get null on Wifi name. The IP works well. I run the app on `Samsung Galaxy S10e`.

## Logs

Every thing is fine when I run `flutter run --verbose`

**Comment by mhadaily** [comment]
Hello, 

thanks for the report we have made a new package for this purpose `networt_Info_plus`. we will release it very soon. @jpnurmi can you let us know when we will release the new package?

**Comment by jpnurmi** [comment]
I'm afraid `network_info_plus` won't fix the issue, because the Android implementation hasn't changed, just moved from `connectivity_plus` to `network_info_plus`.

It will be released soon, though. Over the weekend if not already tonight. :)

**Comment by bestkid1234** [comment]
> I'm afraid `network_info_plus` won't fix the issue, because the Android implementation hasn't changed, just moved from `connectivity_plus` to `network_info_plus`.
> 
> It will be released soon, though. Over the weekend if not already tonight. :)

The implementation will be release on `connectivity_plus` or on `network_info_plus` ?

**Comment by mhadaily** [comment]
Our intention is to resolve in `network_info_plus` as `connectivity_plus` will be different in the next release. we are working on it now. We will keep you posted in this thread once that's done.

**Comment by bestkid1234** [comment]
> Our intention is to resolve in `network_info_plus` as `connectivity_plus` will be different in the next release. we are working on it now. We will keep you posted in this thread once that's done.

Ok. Thank you very much!

**Comment by viveky259259** [comment]
From android 8.0 onwards we won't be getting SSID of the connected network unless Location(GPS) is turned on.
So, Provide Location permission to the app.

**Comment by mhadaily** [comment]
@miquelbeltran @jpnurmi @bestkid1234 for this issue @viveky259259 has a point. what do you think we should do best, 

1- add location permission error when a user asked for SSID
2- add location permission in the package?

**Comment by bestkid1234** [comment]
> @miquelbeltran @jpnurmi @bestkid1234 for this issue @viveky259259 has a point. what do you think we should do best,
> 
> 1- add location permission error when a user asked for SSID
> 2- add location permission in the package?

I think that the best option is to add the permision in the package.

**Comment by miquelbeltran** [comment]
I guess we would have to add the permission to the package, yes.

fyi, there's now the wifi_info_flutter package: https://github.com/flutter/plugins/tree/master/packages/wifi_info_flutter from the Flutter team which extracted this functionality into a different package than the connectivity one.

I am not really aware of the whole situation with connectivity, network_info and now wifi_info, but looks very messy :)

If anything, I would be OK to do a "hard reset" and start again this these packages based on the current state in the flutter/plugins repo.

**Comment by mhadaily** [comment]
@miquelbeltran they started wifi_info but we renamed it to network_info because we may introduce new features that they don't want to perhaps like ethernet. 
I believe network_info is pretty much the same as wifi_info as @jpnurmi did and connectivity will be rebased to the current version soon as @jpnurmi is working on it 

correct @jpnurmi ?

**Comment by jpnurmi** [comment]
Indeed, network_info is the same as wifi_info, but with a more appropriate name considering that desktop systems don't necessarily have wifi at all and we want to extend the API with ethernet.

**Comment by miquelbeltran** [comment]
OK, so my understanding is:

`flutter/connectivity` --> `fluttercommunity/connectivity_plus`
`flutter/wifi_info_flutter` --> `fluttercommunity/network_info_plus`

https://pub.dev/packages/wifi_info_flutter indeed has the ACCESS_FINE_LOCATION permission requests.

**Comment by viveky259259** [comment]
I'll raise a PR on this in the next few days

**Comment by bestkid1234** [comment]
> I'll raise a PR on this in the next few days

Great! Thank you!

**Comment by FredVB1** [comment]
@jpnurmi shouldn't we remove the reference on how to get wifi related information from the `README` if the functionality was migrated to `network_info_plus`?

**Comment by jpnurmi** [comment]
@FredVB1 I thought I did, but something has clearly gone wrong.

**Comment by FredVB1** [comment]
@jpnurmi Ok. And are there any plans on adding a stream, which we can listen to and "detect" changes based on it?

**Comment by viveky259259** [comment]
Sorry guys for the delay. I'm waiting for my machine to be repaired

**Comment by miquelbeltran** [comment]
Hey everyone, today we received the following PR: https://github.com/fluttercommunity/plus_plugins/pull/218#event-4628744623 attempting to solve this issue.

I'd like to clarify that we should not add the permission ACCESS_FINE_LOCATION to the plugin, but instead, users should add it to their app. Just like the wifi_info_flutter does: https://github.com/flutter/plugins/blob/master/packages/wifi_info_flutter/wifi_info_flutter/example/android/app/src/main/AndroidManifest.xml#L4

This should be added to the network_info_plus README.md if it is not already present.
