### ISSUE TITLE
[Question]: "Exception caught by services library" when trying to use sensors_plus

### ISSUE THREAD

**Issue by jckpn** [fluttercommunity/plus_plugins#991]
### What is your question?

When trying to get gyroscope data from sensors_plus as shown in the plugin's example page, I get the following exception error:

```
════════ Exception caught by services library ══════════════════════════════════
PlatformException(error, <get-sensor>(...) must not be null, null, null)
════════════════════════════════════════════════════════════════════════════════
```

Values from the sensors are null. I've not found anyone else with this issue online. What am I doing wrong?

**Comment by KimAloy** [comment]
Same here, even running the GitHub Snake example that's on this site without changing a single line of code, only Accelerometer returns values, but UserAccelerometer, Gyroscope and Magnetometer are all null.

**Comment by chapsan2001** [comment]
Same here, stack trace is awesome btw
```
 at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
 at MethodChannel._invokeMethod(platform_channel.dart:296)
 at EventChannel.receiveBroadcastStream.<fn>(platform_channel.dart:637)
```
