### ISSUE TITLE
[Question]: Can WhatsApp on iOS share image and text together?

### ISSUE THREAD

**Issue by amir14a** [fluttercommunity/plus_plugins#994]
### What is your question?

Hi, I use share plus plugin for sharing files on iOS.
I write this code:
`Share.shareFiles([imagePath], text: myText);`
It works perfectly on android, also for WhatsApp, but on iOS, sharing to other platforms like Telegram works well but WhatsApp only share the text and ignore the image.
Is there any alternative way for WhatsApp?

**Comment by sajjad-n** [comment]
Hi, you can find the answer [here](https://github.com/fluttercommunity/plus_plugins/issues/962#issuecomment-1195378462).

**Comment by devkishor8007** [comment]
@amir14a hello there!
try to use these packages for your need according.
- whatsapp_share2: https://pub.dev/packages/whatsapp_share2
- whatsapp_share: https://pub.dev/packages/whatsapp_share
- share_plus: https://pub.dev/packages/share_plus
- akvelon_flutter_share_plugin: https://pub.dev/packages/akvelon_flutter_share_plugin
- flutter_share: https://pub.dev/packages/flutter_share

hope it can solve your issue.
