### ISSUE TITLE
[Request]: Add support for the Windows Share Dialog

### ISSUE THREAD

**Issue by morning4coffe-dev** [fluttercommunity/plus_plugins#999]
### Plugin

share_plus

### Use case

I am currently working on a multiplatform app and I wanted to implement a share function for them and I run into a missing feature.

### Proposal

Add support for the ability to share files/text via the Windows Share Dialog.

![image](https://user-images.githubusercontent.com/78549750/183244957-fc9cbf67-5472-4c3f-8f27-64b75ef819f7.png)

https://docs.microsoft.com/en-us/windows/apps/get-started/make-apps-great-for-windows#share-dialog

**Comment by UtkarshDeoli** [comment]
hey, i am a biggner and i would love to work on this but could you first tell me if i just need to implement a plugin (that i can do)but if intermediate or higher knowledge is required please guide me.

**Comment by alexmercerind** [comment]
I made an implementation, uses same UWP API through Com/WRL. See: #1158

https://user-images.githubusercontent.com/28951144/193889028-b15f6c3c-9fc1-442c-b472-39b848fcf0ae.mp4
